### ISSUE TITLE
Engineers should have a lower selectable priority

### ISSUE THREAD

**Issue by r34ch** [OpenRA/OpenRA#10113]
When mixed with a group and attack moved, engineers just run straight at the target.

An argument could be made for mechs / medics too but when they attack move with a group they usually stop to heal friendlies so generally move with the group. I don't think it is as much of an issue.

Thoughts?

**Comment by anjew175** [comment]
The most annoying part is when you order your units to attack enemy units and the engineer runs up next to them. Maybe this would be alright for RA since the engineer doesn't capture instantly. This might be annoying for TD if you want some engineers in your army to capture husks and enemy buildings.  I like the current system because using control groups is adequate to control them in my opinion but it is annoying when they sprint up to the enemy

**Comment by abcdefg30** [comment]
Fixed in #10519.

**Comment by djlists** [comment]
I don't think this is the correct fix. It's confusing that some troops aren't selectable. Numerous selection attempts are needed to move troops into a transport. The proper solution (and I think the original RA did this) is to not have the engineers move when given an attack order. You have a group huddled together and you give an attack order. Those that can attack go running after the target. Those that can't remain idle.

**Comment by pchote** [comment]
This was already reverted everywhere except in the RA mod.
