### ISSUE TITLE
Grenadier self destruction damage a way too high...

### ISSUE THREAD

**Issue by vipches** [OpenRA/OpenRA#10114]
So, I found a really big problem about the grenadier, on both red alert and dune 2000, because those grenadier self destruction damage a way too high, which it will kill almost every friendly infantry nearby, most the time the grenadier is with other infantry on combat, and they are going way too front, make them get killed on the frist place, and even worst, if many of them stay together, it will cause chain reaction, make them blow up almost half you infantry group, is way too high on the damage, and most the time they will get killed without even reach the thorwing range or before throwing the grenade, because those problem, the grenadier is become almost useless, almost useless on the crazy ivan on the red alert 2.
##

**Comment by vipches** [comment]
Well, I was later check the new version playtest 20151114, and look like the grenadier self destruction on dune 2000 was already balanced, but red alert is still the same, hope some one make it soon.

**Comment by MustaphaTR** [comment]
Reason of RA Grenadiers' high damage is that they lack of Weapon: under Explodes: and uses default UnitExplode weapon, while their EmptyWeapon: is UnitExplodeSmall.

**Comment by pchote** [comment]
This is a silly oversight with an easy fix, so adding to the next release milestone.

**Comment by MustaphaTR** [comment]
That would effect the balancing tho.

Pinging @SoScared

**Comment by SoScared** [comment]
OP calling the current grenadier "almost useless" is incorrect - as of 2015 (same year as this issue was posted) Grenadiers has become integrated with Soviets early game. As far as I'm concerned the RA Grenadier is balanced. Holding off quick waves of solid blobs of grenadiers sounds like a nightmare to me. Besides, watching exploding blobs of grenadiers is immensely satisfying.

If there's a proper way to emulate the 'bugged' behavior with proper code I'd recommend doing so.

**Comment by pchote** [comment]
If we want to keep the current behaviour then we should remove the useless and misleading `Weapon: UnitExplodeSmall` to make it explicit that `UnitExplode` is intentional.

**Comment by ltem** [comment]
So to gets this correct:
- Change `Weapon: UnitExplodeSmall` to `Weapon: UnitExplode` (Explodes-Trait requires a weapon).
- We won't add a `EmptyWeapon: UnitExplode` because this is already the default.
- This means that if the grenadier gets killed while his weapon is loaded, he will trigger now a bigger explosion?!

Before: 
 ```yaml
	Explodes:
		Weapon: UnitExplodeSmall
		Chance: 50
```
After:
```yaml
	Explodes:
		Weapon: UnitExplode
		Chance: 50
```

If this is okay I would make a PR for it.

**Comment by pchote** [comment]
Closing as per #12728.
