### ISSUE TITLE
Desync on playtest-20151129 related to Turreted

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#10155]
[Here are the sync logs](https://gist.github.com/abcdefg30/17c1084886ef0d6a558e/revisions).

**Comment by kyrreso** [comment]
Replay from zypres: http://s000.tinyupload.com/index.php?file_id=97251790162190813014

**Comment by obrakmann** [comment]
Well, the good news is that the crash can be reproduced using the replay. The bad news is that I couldn't find a cause while single-stepping through the last four frames  (9288 - 9292). The impacted 1tnk is the only 1tnk on the map at the time of the crash, but you can't see it doing anything at that point. In frame 9290 `AttackBase.IsAttacking` changes to true, so that will probably be related. When `IsAttacking` is true, the only location that could change `TurretFacing` is `FaceTarget`, which only gets called from `AttackTurreted.CanAttack()`. It needs a target at that point, though, and I havn't had a chance to check if it had one yet.

**Comment by RoosterDragon** [comment]
The replay also desyncs on my machine (I get a report matching abcdefg30).

The target is the camo pillbox. `AttackTurreted.CanAttack` returns false for me as `AttackBase.CanAttack` returns false on the [CanTargetActor check](https://github.com/OpenRA/OpenRA/blob/eddda3ecca82807a25a341a9a9a267f31619730e/OpenRA.Mods.Common/Traits/Attack/AttackBase.cs#L93)

If I ignore this failure in the debugger and allow it to run `FaceTarget` anyway, the turret begins to turn for two ticks and I remain in sync (the replay then ends normally).

This could be visibility related? (A GPS was active at the time, if that counts for anything)

**Comment by pchote** [comment]
Replacing `atek.World.RenderPlayer` with `Owner` at https://github.com/OpenRA/OpenRA/blob/74db6f337d6038cf0c387c14c5081c8abf83ef65/OpenRA.Mods.RA/Traits/SupportPowers/GpsPower.cs#L66 may help.

**Comment by RoosterDragon** [comment]
We should make that change anyway, but It doesn't appear to fix this specific desync.

**Comment by RoosterDragon** [comment]
@obrakmann noticed in IRC that if you watch the replay from Zypres's point of view, it *won't* desync. It will desync if you observe from another players' perspective.

This would suggest that the root cause is something checking against the current render player when updating the simulation state.

The only obvious misuse of `World.RenderPlayer` is the above noted code - which does need fixing - but this doesn't help for this specific desync.

**Comment by RoosterDragon** [comment]
Found the cause of this.

The GPS was relying on whether the frozen actor for the pillbox had been rendered or not. Anything checking visibility, such as targeting, was checking the GPS in case that revealed the unit. In this case, the tank has acquired the pillbox as a target according to Zypres's view and had turned to attack it. From abcdefg30's view, the tank did not have sight on the pillbox and hence the turret had not moved.

The rendering for the frozen actor need not match up with the world state (if you can't see it, we don't bother rendering it). Since the GPS was accidentally relying on this render state, the GPS could be different depending on which player you were observing in a replay (or which player you are during the game!)

This manifested as the tank acquiring and turning to target the pillbox in one version of events, and not having sight and thus ignoring the pillbox in another version.
