### ISSUE TITLE
New "cloak" effect is too ambiguous. [PLAYTEST 1129]

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#10179]
Its difficult to tell if things are cloaked or not, especially under certain condition. 

I built a phase tank and was like "What the hell is the cloaking broken?" and I thought Camo Pillboxe's were broken too.

**Comment by Phrohdoh** [comment]
What about it is difficult? Could your provide a screenshot of a situation you were unsure of?

**Comment by penev92** [comment]
To be fair it's hard to notice in both RA and D2k. In pretty much all cases.

**Comment by jaZzKCS** [comment]
The effect differs greatly (RA/D2k) from the one used in TD. I agree that it's sometimes difficult to make out what's cloaked and what's not, depending on the terrain and the number of units deployed. On first glimpse that is, obviously theres a distinct difference between cloaked and uncloaked units, albeit with a higher number of units and a bigger base, this can get a tad unclear.

With higher numbers of units on screen, the TD stealth effect does a way better job in differentiating between cloaked and uncloaked units at first glimpse due to its "shining-cloak" effect.

**Comment by pchote** [comment]
The new cloak effect has been shipped for several months now, and we haven't received any more negative feedback on it.  I don't think this is likely to be reverted, so closing.
