### ISSUE TITLE
Playtest replays not working ("unknown map") after same (custom) map played on bleed

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#10192]
Playtest 20151129, Windows 8.1 

If you create and play a custom map on current playtest and later play the same map on bleed the playtest replay doesn't work anymore (loses map ~association), error: "Unknown map". 

How to re-create: 
On current playtest: 
1. Create a new custom map (it can be a simple empty map), name it & save it (default location "^maps/ra") 
2. Play the map (skirmish, you can surrender) 
3. (optional) Verify that the replay is working 

On bleed: 
4. Play the same map (skirmish, surrender) 
5. (optional) Verify that the new replay works also 

Back on playtest 
5. Ty to load the replay of the previous (first) game 
It should report "Unknown map" and there is no thumbnail for the replay. 

To fix it: 
Open the map in the playtest's editor (it normally shows in browser) and just save it unchanged (overwrite). Again the default location here is "^maps/ra" for me. 

This only happens if you play the playtest's map with bleed (and come back to playtest) and not with current release (which is older than the current playtest) 

It also doesn't happen with official maps - just custom ones.
##

**Comment by abcdefg30** [comment]
> 22:03:40 (abcdefg30) pi99y it is expected that maps change from playtest -> bleed
22:03:54 (abcdefg30) so it's likely that they don't work in the playtest (again)
22:04:00 (abcdefg30) that's unfortunate though
22:04:15 (pi99y) abcdefg30, but it doesnt happen with official maps
22:04:34 (abcdefg30) because the official maps are stored seperate for every openra version
22:05:46 (abcdefg30) we should somewhen fix that probably (i.e. by different version folders for custom maps)
22:07:06 (abcdefg30) or sth like that

**Comment by pchote** [comment]
This was fixed a long time ago.
