### ISSUE TITLE
Only one nuke should not destroy the construction yard

### ISSUE THREAD

**Issue by netolopes27** [OpenRA/OpenRA#10198]
Mainly in Tiberium Dawn for fun and game balancing a nuke should not be sufficient for the destruction of 100% health construction yard. GDI don't have a similar super weapon as in Red Alert.
##

**Comment by anjew175** [comment]
Maybe if it let the MCV specifically on 1hp. But imo the nuke the is fine in terms of balance. In RA the nuke is much stronger, even damaging units at very large distance. GDI has the ion cannon which is 2 minutes faster to acquire, can be shot instantly

**Comment by AoAGeneral** [comment]
Nuke is fine in my opinion. While it is rather strong in TD the ion charges faster as Anjew mentions. Besides when you hear the nuke go off just move your MCV. Nuke wasted.

**Comment by Mailaender** [comment]
I assume https://github.com/OpenRA/OpenRA/pull/10552 fixed it.

> Construction yard HP increase to 2000 from 1400.

**Comment by AoAGeneral** [comment]
Still one shots it.

**Comment by psydev** [comment]
I think the one-shot makes sense. Now that the conyard is more expensive, we'll see. 

If we were to re-think this, it should be in the context of the fact that conyards cannot be killed with Ion + Airstrike anymore.

**Comment by AoAGeneral** [comment]
While the ion + airstrike does not one shot a CY anyone. It is also to note that CYs can be moved. Pack back up and relocated which can result in a wasted nuke.

Otherwise the other option is to increase the timers of the support powers and slight increase their damage and spread. However, various players disagree with the timer change and will be difficult to make a change on this unless a very good reason comes up.

**Comment by pchote** [comment]
The game balance has changed a lot since this was filed, so closing as no longer valid.
