### ISSUE TITLE
YAML merging issues

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#10207]
Since #9710, yaml rules that used to be fine in our missions and mini-games don't work anymore (see [irc logs](http://logs.openra.net/?year=2015&month=12&day=12#16:10:29), for example).

**Comment by abcdefg30** [comment]
See also https://github.com/OpenRA/OpenRA/pull/10206#issuecomment-164196266 or [this irc log](http://logs.openra.net/?year=2015&month=12&day=08#16:22:33).

**Comment by pchote** [comment]
So much for unit tests catching future breaking :)

Can we get a testcase showing this working before #9710 and not working now?  I'll then look into what went wrong.

**Comment by pchote** [comment]
I expect this is happening because of the split between resolving merges/removals (which happens in the lowest level miniyaml code) and resolving inheritance (which happens in the actor loading code).  Before #9710 we resolved all removals before considering inheritance, which meant that you couldn't remove nodes from inherited parents.  After #9710 we resolve all removals at the end, which I expect means that it *also* removes from children, as well as parents (which is equally bogus).  The fix for this will be to change the actor inheritance to use head recursion and fully resolve the removals at each step on the way out.

**Comment by pchote** [comment]
Calling `MiniYaml.ApplyRemovals` inside `MergeWithParents` may be sufficient, but we need some testcases to verify this first.

**Comment by RoosterDragon** [comment]
Try adding these to `ActorInfoTest.cs`

```c#
class MockStringInfo : MockTraitInfo { public string AString = null; }
```

```c#
		[TestCase(TestName = "Trait can be removed and later overridden")]
		public void TraitCanBeRemovedAndLaterOverridden()
		{
			var baseYaml = @"
^BaseA:
	MockStringInfo:
		Foo: ""Base""
Actor:
	Inherits: ^BaseA
	-MockStringInfo:
";
			var overrideYaml = @"
Actor:
	MockStringInfo:
		Foo: ""Override""
";

			var actorInfo = CreateActorInfoFromYaml("Actor", null, baseYaml, overrideYaml);
			Assert.IsTrue(actorInfo.HasTraitInfo<MockStringInfo>(), "Actor should have the MockStringInfo trait, but does not.");
			Assert.IsTrue(actorInfo.TraitInfo<MockStringInfo>().AString == "Override",
				"MockStringInfo trait has not been set with the correct override value for AString.");
		}
```

I didn't test this pre-#9710, but it fails on the current bleed with:
```
Result Message:	
Actor should have the MockStringInfo trait, but does not.
  Expected: True
  But was:  False
```
