### ISSUE TITLE
Unit jumps a few pixels (when target is lost)

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#10224]
Tested on current bleed (2015/12/14) but also present in release-20150919, skirmish mode

You can see the V2 jump a few pixels to the left before moving away. Also seen in replay (attached).

https://media.giphy.com/media/l0OWiWL8hGC75A40w/giphy.gif

This happens (see for reproduce steps) along issue #10223 when the second behaviour ("ignore the attack command and switch to "move there") happens.

Replay + map (happens at around 90% time mark): http://www.megafileupload.com/mrKG/jumping.zip
##

**Comment by abcdefg30** [comment]
Could that be related to #9404?

**Comment by pi99y** [comment]
@abcdefg30 IDK, could be

Requested by @penev92 - Reproduced on bleed with grid enabled:
https://media.giphy.com/media/3o8doPCnvmnAHMB5wQ/giphy.gif

**Comment by reaperrr** [comment]
Looks like if the current action is stopped or replaced with a different action before the actor enters the next cell, the position is reset to the current cell's center.

**Comment by pchote** [comment]
This and the common "attack order turns into a move order" complaints are caused by https://github.com/OpenRA/OpenRA/blob/5f54e46eae98632e3f38d5fc13287789a32e3735/OpenRA.Mods.Common/Activities/Move/MoveAdjacentTo.cs#L86-L95

When the target is lost under fog this code will swap out the move order without letting it finish.  The unit then starts the next move order from the location that it was *supposed* to, but never got the chance to, reach.
