### ISSUE TITLE
ATTACK order immediately ignored or changed to MOVE order when VISION of target LOST

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#10223]
Tested on **current bleed (2015/12/14)** 
EDIT: this was tested on skirmish mode

When a unit is given a direct attack command but the vision of the target is immediately lost (fog of war) it will either: 
- **ignore the command** (red target line is shown but disappears a bit later than usual, unit does not respond) 
  see clip here: https://imgur.com/MBiKzkH 
  or gif: https://media.giphy.com/media/3o8doTBgODOGKM2SmA/giphy.gif 
- **ignore the attack command and switch to "move there"** (red target line shown, switches to green, unit begins to move in that direction) 
  see clip here: https://imgur.com/HIgkFIc 
  or gif: https://media.giphy.com/media/d2Zd4S2ZBfy5LBaE/giphy.gif 

You could argue that units should **not chase actors that disappear under the fog of war,** but I say there should be a at least certain (or longer) time window before giving up. Current behaviour feels (player's perspective) like it's broken.

**This might also be a source of reported "attack does not work" issues,** since it feels that way if you don't notice the brief vision loss. 

PS: This has been a real pain to record (with the attack, move lines) and convert to web-friendly format. Any good screen capturing recommendations (60fps) without image compression? 
##

**Comment by penev92** [comment]
I'm pretty sure this is intentional. We do want actors to drop targets when they become hidden.
Was the bridge or whatever blocked in your first gif, so the V2 couldn't move to the target location?

**Comment by pi99y** [comment]
At the very least the behaviour should be always the same. Not two kinds.
Ignoring the command in the same second might be technically correct but feels wrong during play.

Gifs were recorded close together, the obstruction of the bridge does not seem to be the reason for switching behaviour.

**Comment by klaas1** [comment]
I think the title of this issue is confusing, because I think the bug shown in the second animation needs attention, while the subject of the issue title is intentional and not a problem.

**Comment by pi99y** [comment]
Might be intended, but it's an annoyance (from player's perspective). Suggest a new title please.

**Comment by klaas1** [comment]
Maybe "attack command changed to move upon lost vision of target"?

I think the need of vision (and the occasional move instead of attack) is not that annoying actually, it was much more annoying when you didn't need vision, and arties just fired away in the fog. Just building arties and basewalking was way too easy and effective.

**Comment by pi99y** [comment]
The annoying part is when you loose and regain vision in a "second" but your units stopped or are doing something other than your order. It happens fast and you can easily miss it, so it feels unresponsive or broken.

**Comment by klaas1** [comment]
I can see this behavior may confuse some, however "fixing" by creating an exception in the game mechanics is not a good idea, because it will probably lead to new bugs. Maybe an attack order could default to an attack-move order, so the unit will just move until it regains vision on the target, or attack something else? (I don't think I would prefer this over just canceling the order BTW)

However, an attack order should never become a move order, IMO a bug that needs fixing.

**Comment by pi99y** [comment]
Attack order (when target is lost) becoming attack-move order seems like a good compromise to me.

**Comment by r34ch** [comment]
@klaas1 +1

Direct attack falling back to attack move on loss of vision seems like a much more intuitive result than falling back to a simple move command.

**Comment by pi99y** [comment]
Devs - do you think that @klaas1's solution cauld be placed in the Next milestone? Seems harmless enough and it might just solve the issue...
Thanks!

**Comment by pi99y** [comment]
I think this is the bug @SoScared mentions in a recent video here: https://www.twitch.tv/soscared/v/68153313?t=03h35m45s and callin it "terrible", "biggest bug". Please look into it :)

**Comment by Szunti** [comment]
That kills my v2-s. Really annoying. I think the right replacement is force attacking the position cause that's what I mean when I clicked on the target. And that's what I currently do if I don't want my v2 to do silly things.

**Comment by GraionDilach** [comment]
I have seen a lot of cases where this happens in Warcraft 3 (asin, attack becomes simple move) so I don't see what's wrong with this.

**Comment by pi99y** [comment]
It depends on a unit. For V2 "don't move" would be better than "move there" since it's a ranged unit that's vulnerable when it's close to enemy. That's why "attack move" is a better solution I think.

**Comment by Szunti** [comment]
Move is the worst thing, but attack move is not ideal either, beacuse if you lose vision due to the yak, v2 will go closer and closer every time the yak moves away until it reaches the unit with its own vision, which is too close. If there is a group there and you aim at the arty for example, it will start moving closer, yak comes with vision, v2 will shoot the closest enemy - instead of arty, but it's less annoying then the suicide walk -, vision goes away, v2 goes closer and get killed by the group.

 Force attack has the problem that the v2 won't change target.

Maybe a thing like if the target is lost, keep moving until the spot is in your attack range but stop instead of shooting. So when the vision comes back v2 will shoot but won't ever move closer than you intended.

**Comment by pchote** [comment]
Related to #10224 (see the explanation about `MoveAdjacentTo`).

**Comment by pchote** [comment]
I have a hunch that this is fixable using our new activity system.

When investigating #16010 I noticed that `HeliAttack` and `MoveAdjacentTo` have special case handling, introduced in #8084, to make the unit move to the targets last known position if it disappears under the fog. If we queue these moves as child activities then we can continue to check the status of the target, and recover if it becomes visible again.  If the unit reaches the original target location without seeing it again, then we can give finally give up and move on.

**Comment by pchote** [comment]
I tried to raise some discussion on the discord channel about this, but didn't really get far:
![screenshot 2019-01-09 at 19 41 19](https://user-images.githubusercontent.com/167819/50924182-c2cd2000-1446-11e9-8e53-ccf2238b748b.png)
![screenshot 2019-01-09 at 19 42 03](https://user-images.githubusercontent.com/167819/50924204-d1b3d280-1446-11e9-9f87-5ec290fd59ee.png)

Artillery style units are a problem: they can't move to reveal the target themselves, so that means introducing an artificial delay that forces them to sit idle and wait for the target to perhaps be revealed again.  This seems like a really bad idea in the middle of a battle, and seems unlikely to be accepted as  a fix.

I will be filing an issue that makes units chase their target to its last known position and reacquire the original target if it (or something else) reveals it. I believe this adequately fixes the issue here for everything but artillery, so will mark that PR to close this.

If there really is a desire to introduce attack-idling for artillery-like units then a new, more focused issue can be created to discuss that.

**Comment by matjaeck** [comment]
Wouldn't this solution in the last comment cause an exploitable conflict with mobile gap generators?
