### ISSUE TITLE
A Few Noticed Issues

### ISSUE THREAD

**Issue by L00K3** [OpenRA/OpenRA#10259]
Firstly I have noticed an issue with the mouse flickering at the top of the screen (about top 80%) when using the Ubuntu Build.

Secondly I also noticed that the commando is GDI only, they use multi engineer,  the missions are done using only 4 tech levels and you only have 6 missions for each side, I think the way missions are run for NOD and GDI will interfere with later missions then have been implemented and would like to see the ability to choose the next mission from the map like in the original.

Thirdly I would like to see a third side, the Scrin in the classic Command And Conquer Tiberium Dawn.

**Comment by penev92** [comment]
Firstly, I am going to go ahead and blame your video driver (window manager would be funnier though), since this isn't happening on other OS-es.

Secondly mission choosing will come eventually, when we support campaign progression. I don't understand what issues you see with the commando, engineers, tech levels or future missions (current mission scripting?).

Thirdly a third faction will not happen in the "classic" (although rebalanced) TD mod. But worry not, there would be plenty of Scrin in upcoming (thirdparty) TS-based mods.

**Comment by Mailaender** [comment]
Thanks for your feedback. Closing here as this is primarily our task tracker for development.
