### ISSUE TITLE
Deviator tanks don't seem to work on release-20151224

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#10278]
I played several games against Ordos, with a constant stream of Deviators coming my way, but I didn't see a single one of my units have it's owner changed.
I suspect the (somewhat) recently added inaccuracy doesn't play well with their small damage spread, and the targets don't get affected at all by the gas.

**Comment by Mailaender** [comment]
It seems to work fine against stationary targets on current bleed. Indeed this is probably the bogus original balancing which had less splash damage making this appear broken as you see a large gas cloud, but need direct hits nonetheless.

**Comment by penev92** [comment]
It just does not work. You can fire at a target 5 times and do nothing. That is broken.

**Comment by reaperrr** [comment]
This might be due to the improved missile 'shouldExplode' check.

The `Missile.CloseEnough` default (298) is larger than the `ChangeOwner` warhead's range, so I suspect that the missile nearly always explodes more than 256 WDist away from target.

In addition, the warhead's Range ignores `HitShapes` and measures distance to target center, so it almost never explodes close enough.

Reducing Inaccuracy to 384 and increasing COWH Range from 256 to 512 fixed it for me.
