### ISSUE TITLE
Balance : Nerfing Tesla Tank ? 

### ISSUE THREAD

**Issue by ShadowA** [OpenRA/OpenRA#10426]
Hello :)

Yesterday I've been testing the new Tesla Tank 
(http://s000.tinyupload.com/index.php?file_id=67625660725952331414)
- watching SoScared stream 
  (http://www.twitch.tv/soscared/v/33626018 ,  usage 51st min)

While Tesla tanks being now really fun and a good hit'n'run unit, it might have become a bit too strong in the this new release, because it has all the advantages : 
- High speed
- Good range
- High damage
- Quite good armor 
  (against tanks for instance, although 1 full Yak / Hind can destroy it
  EDIT : after second try, it's super fragile against all gun types ... but still)
- Crushing ability
- Turreted attack

It's almost like a "highspeed-hybrid-long-range-tank-unit" :) which could cause some balance issues.

Only disadvantages IMO :
- Anti-air vulnerability (but mixing with anti-air units (flaks especially) reduces this disadvantage)
- Fragile against gun-type (air, pillboxes, ...)
- Price / construction time maybe ? Not so high though.

Maybe one of these traits could be nerfed ? Not sure which one though 
(Speed ? As it is a tank. But that would reduce the hit'n'run ability, which is a nice trait of this unit.
Long range ? Why should they have bigger range than other tanks ?
Armor ?)

Thoughts ? :)
##

**Comment by Townes27** [comment]
You forgot one thing. They can be curtained. If shockies were OP, then this is über-UP.

**Comment by r34ch** [comment]
:+1: I agree they need a nerf. I would propose they get a substantial health nerf and to loose their crushing ability. They are far too tanky right now and the crushing ability is silly considering their speed and the IC support power. 

That would keep them as light support units and allow air and infantry to be far more effective against them.

**Comment by klaas1** [comment]
I think we should watch out calling higher tier units overpowered. I mean, they should be better or more versatile than the heavy tank/ medium tank, because otherwise they are obsolete and nobody will ever build them.

That said, it is a bit easy to crush infantry ATM with testla tanks, and even more so with chrono tanks, balance wise this could be an issue.

**Comment by ShadowA** [comment]
Yes you're right @klaas1 
They're powerful but still counterable and got their weak points, so I'd not say OP

But maybe a slight tweak somehow of one the traits could be considered

**Comment by MurtoTheRay** [comment]
I dont think tesla tanks require a nerf. As has already been said the meta hasn't settled yet and it is difficult to tell if tesla tanks are OP. Rushing them means you are vulnerable for a long time which can be exploited and getting them later on simply means that you have held of your opponent long enough to get them. Well deserved. I think it just creates an end game for the soviets instead of relying on low tech units such as flaks.

**Comment by HenrytheSlav** [comment]
I would maybe consider their armor type (either make them fast but vlnerable like now, maybe a bit health nerf) or make them slower, but a bit more robust. But soviets have enough slow heavy tanks so this would be a bad idea imho.

**Comment by Smittytron** [comment]
This issue is dated. Tesla tanks were even given an HP buff in #13790 to encourage more use. The bulk of complaints I hear now about teslas concern the shock trooper.
