### ISSUE TITLE
Integer Overflow when using actors with AttackGarrisoned Trait.

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#10549]
I can't really say much about what caused this bug, the mod has a defence structure and a vehicle that use AttackGarrisoned, obviously one of both must have been used when the crash happened, I didn't had the luck to see it. @penev92 has some ideas of what might have caused it.
The Spanish text says, the negation of the minimal value of two complementary numbers is not valid.
```
Shattered Paradise Mod at Version {DEV_VERSION}
on map a2e47ffc10af1ce0b256aafa4b12f372543bf406 (A River Runs Near It by Westwood Studios).
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.OverflowException`: La negación del valor mínimo de dos números complementarios no es válido.
   en System.Math.AbsHelper(Int32 value)
   en System.Math.Abs(Int32 value)
   en OpenRA.WAngle.ArcTan(Int32 y, Int32 x, Int32 stride) en c:\Users\Alfred\Desktop\SP2016-01-18\OpenRA.Game\WAngle.cs:línea 83
   en OpenRA.WAngle.ArcTan(Int32 y, Int32 x) en c:\Users\Alfred\Desktop\SP2016-01-18\OpenRA.Game\WAngle.cs:línea 66
   en OpenRA.WVec.get_Yaw() en c:\Users\Alfred\Desktop\SP2016-01-18\OpenRA.Game\WVec.cs:línea 69
   en OpenRA.Mods.Common.Traits.AttackGarrisoned.DoAttack(Actor self, Target target, IEnumerable`1 armaments)
   en OpenRA.Mods.Common.Traits.AttackFollow.Tick(Actor self)
   en OpenRA.Mods.Common.Traits.AttackGarrisoned.Tick(Actor self)
   en OpenRA.World.<Tick>b__7(TraitPair`1 x) en c:\Users\Alfred\Desktop\SP2016-01-18\OpenRA.Game\World.cs:línea 303
   en OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text) en c:\Users\Alfred\Desktop\SP2016-01-18\OpenRA.Game\WorldUtils.cs:línea 53
   en OpenRA.World.Tick() en c:\Users\Alfred\Desktop\SP2016-01-18\OpenRA.Game\World.cs:línea 0
   en OpenRA.Game.InnerLogicTick(OrderManager orderManager) en c:\Users\Alfred\Desktop\SP2016-01-18\OpenRA.Game\Game.cs:línea 557
   en OpenRA.Game.LogicTick() en c:\Users\Alfred\Desktop\SP2016-01-18\OpenRA.Game\Game.cs:línea 582
   en OpenRA.Game.Loop() en c:\Users\Alfred\Desktop\SP2016-01-18\OpenRA.Game\Game.cs:línea 709
   en OpenRA.Game.Run() en c:\Users\Alfred\Desktop\SP2016-01-18\OpenRA.Game\Game.cs:línea 749
   en OpenRA.Program.Run(String[] args) en c:\Users\Alfred\Desktop\SP2016-01-18\OpenRA.Game\Support\Program.cs:línea 117
   en OpenRA.Program.Main(String[] args) en c:\Users\Alfred\Desktop\SP2016-01-18\OpenRA.Game\Support\Program.cs:línea 39
```

**Comment by GraionDilach** [comment]
Must be something involved with the `Port*` tags.

**Comment by ABrandau** [comment]
No idea, maybe it was my mistake since the ports had some empty spaces after the inputed data. I cleaned those spaces after the crash, but I haven't played enough to know if that's the problem.

**Comment by penev92** [comment]
This is suspiciously tied to the recent changes from #10521.
The error in the stack trace (after reading up on some MSDN) turns out to be that `Math.Abs()` recieved `int.MinValue`, which it is [designed to throw that specific exception](https://msdn.microsoft.com/en-us/library/dk4666yx%28v=vs.110%29.aspx) on.

*Some educated and partially-supported-by-facts guesses coming up:*
This happened because (from what I hear) the Forgotten Commando has a range of 12 cells. That lead to [this here `WVec`](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Attack/AttackGarrisoned.cs#L142) being `(12c0, 0)` or close to that. Which (fast forward a bit), led to a `Math.Abs(int.MinValue)` [here](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/WAngle.cs#L83), supposedly when `i == 255`.

**Comment by pchote** [comment]
This sounds like expected behavior for `abs(tan(π/2))`.  The bug is that is in whatever code is trying to evaluate that.
