### ISSUE TITLE
Ability to save/store your favourite colors

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#10591]
A suitable way for the pick-from-boxes crowd, it would be nice if there would be a bunch of empty boxes the player could save their favourite colors to and then instead of going through the UI to reset the shade they want, they would just switch slots.

It's already cumbersome to pick the "perfect" shade so this would probably cheer a bunch of people up in the playerbase.
##

**Comment by jaZzKCS** [comment]
So instead of - lets say - switching to a box-selection of different shades - rather add Favourite Slots that User fill themselves, therefore keeping the current color selection as well?

There seems to be an increasing number of ppl upset because it feels like - in some cases - that "half" the colours aren't choosable anyways, so they say.

Instead of changing the colour selection to a box selection mode, this would that add a colour fav. submenu that can be filled by the users themselves? DIUTC [did I understand that correctly?]

**Comment by cjshmyr** [comment]
Could even default those empty boxes to the original games' colors

**Comment by pchote** [comment]
This was part of the original plan for the color chooser: a tab with the existing palette, and then a tab with N fixed colors and N user-selected colors.

> There seems to be an increasing number of ppl upset because it feels like - in some cases - that "half" the colours aren't choosable anyways, so they say.

This is more than just a feeling &rarr; #10217.

**Comment by GraionDilach** [comment]
Fixed by #14853.
