### ISSUE TITLE
Weird attack-move behavior

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#10625]
The attack-move command has now a weird behavior.
Is it focusing on buildings or vehicles ?
On this screenshot you can see the behavior of the mammoth tanks when I ordered them to attack-move to my cursor while placing it above the construction yard.
I added the red lines on MS Paint to show the behavior because they are hard to get. I almost spammed "angry" attack-move orders (10+) but the mammoth tanks still wanted to attack the turret instead of the guy.
![weird_attack_move](https://cloud.githubusercontent.com/assets/8930382/12626933/8b5f5fc8-c53b-11e5-96a9-52c5de8a7fad.png)
I saw way more strange attack-move behaviors, like having a bunch of mammoth tanks attacking a service depot 2 or 3 cells away from them instead of attacking the 15 bazookas right in front of them. Almost 10 attack-move orders sent, target lines straight to the service depot. All the mammoth tanks died, obviously.
They really act like buildings or vehicles are the most important thing to target, or like the first target seen must be destroyed at any cost (this happened with the service depot : they started to attack it and the bazookas finally came close to them but with tons of new attack-move orders they only wanted to attack the service depot)
If you send (fast) attack-move orders while retreating, at one time the closest enemy will be the only one they can see so they will finally attack him.
##

**Comment by obrakmann** [comment]
Please upload the replay of that game somewhere provide the following information so that we can take a proper look at it:

* which map the game was played on (if not a shipped one, please link to the map's page on the resource site.)
* when and whereabouts during the replay the behaviour can be observed.

Thanks.

Also, just as a side note, spamming orders won't do you any good, it just slows your units down.

**Comment by StexoO** [comment]
I spam orders because I want the tanks to target the nearest unit, even if they don't move, but they don't.
For example you can see in the replay http://s000.tinyupload.com/index.php?file_id=24004888062909314376 @ 09 min 04 s in the middle of the map (Snow Town http://resource.openra.net/maps/8227/) that my mammoth tanks don't attack the brown guys in front of them but they target the (far) turret shooting at them, despite the attack-move orders (the mammoth tanks' behavior show the multiple attack-move orders).
In the replay http://s000.tinyupload.com/index.php?file_id=19237426262566664874 you can also see @ 18:50 on the left of the map (Hellfire Hills http://resource.openra.net/maps/7646/) that my mammoth tanks want to destroy the oil derrick and not the blue guys in front, "ignoring" the new attak-move orders (again, their behavior show the multiple attack-move orders).
I don't know if it's specific to mammoth tanks because I only build mammoth tanks but you can try it ingame and feel this "why don't you attack the nearest enemy ?" behavior easily.

**Comment by pchote** [comment]
AutoTarget / AttackMove does not prioritize targets based on distance (except at the very coarse "in attack range" / "not in attack range" level)

**Comment by StexoO** [comment]
Did this changed in the latest release ? I never had this "issue" before : one new attack-move order and the tanks attack the guys in front of them.

**Comment by RoosterDragon** [comment]
AutoTarget *did* change in this release. It will prioritizes targets based on preferred armament and then distance. i.e. Closest target that can be hit by the main weapon, if none then closest that can be hit be the secondary, etc.

However, once it has a target it won't change unless that first target becomes invalid again (dead, out of range, etc).

**Comment by StexoO** [comment]
Still present in the 20160403 playtest.

The mammoth tank (I don't know if it happens with other vehicles) really (really) wants to attack buildings first and because of that change low tech units and buildings are actually way stronger than mammoth tanks.

Don't forget the cost of a mammoth tank :
If you want to have __one__ mammoth tank on the battlefield you have to spend at least 3 power plants + 1 refinery + 1 war factory + 1 radar + 1 service depot + 1 tech center + the mammoth tank for a total cost of 3 * 300 + 1400 + 2000 + 1800 + 1200 + 1500 + 2000 = __$ 10 800__ and you have to "wait" for 3 * 8 + 34 + 48 + 44 + 29 + 36 + 40 = __4 min 15 s__.
And all of that in order to kill... two bazookas ? :sob:

On the following GIFs I __only__ send __one__ attack-move order above the turret.
This configuration is not a particular case because almost all the players have units around their defenses in order to defend or attack. Mammoth tanks are just focusing on the wrong targets.

| __release-20150919__ | __playtest-20160403__ |
| --- | --- |
| ![openra-20150919-realmamm](https://cloud.githubusercontent.com/assets/8930382/14508952/4aad845c-01ca-11e6-98b5-63ff59df2e5d.gif) | ![openra-20160403-cardboardmamm](https://cloud.githubusercontent.com/assets/8930382/14508994/73b9cc0c-01ca-11e6-9053-71d782e8c1ac.gif) |

IMO restoring the previous attack priorities (or setting it as an option) could lead to long, heavy and high tech games again ! :tada:

**Comment by GraionDilach** [comment]
Looking at this - I'd assume the culprit lies in #9734 - more exactly along the lines of https://github.com/OpenRA/OpenRA/pull/9734/commits/7fbbaa2221c0fe04024fcd4523fcc48a57addcd1#diff-3907b06bf0efdd105dc1a0bcc8af7d2bR174

**Comment by RoosterDragon** [comment]
The actual behaviour change was #8768, #9734 was only an optimization pass.

**Comment by Elizadmin** [comment]
I spotted this behavior in release-20170421.
It's easy to trick and destroy mammoth tanks with few bazookas and a simple light tank behind them.
The mammoth targets the tank (not the bazookas) so you just have to move the tank to the back cell by cell. The mammoth follows the light tank and the bazookas destroy the mammoth tank.
With correct timings your bazookas and your light tank don't take any shot from the mammoth tank, so actually a light tank and 2-3 bazookas are stronger than a mammoth tank. 😋 
If you own the mammoth tank it can survive if you target the bazookas one by one...
