### ISSUE TITLE
Paratroopers are not affected by the nuke

### ISSUE THREAD

**Issue by hacikenks** [OpenRA/OpenRA#10658]
The title says it all
##

**Comment by jaZzKCS** [comment]
...whilst still dropping/in air. Confirmed on current playtest.

**Comment by pchote** [comment]
This was a deliberate balance choice when the paradrop code was reworked, because there was no interest in re-balancing it to offset the nerf from having them be killable.  Adding appropriate target types to the RA yaml should be sufficient to address this at the technical level, but that opens a can of worms for balance.

**Comment by MustaphaTR** [comment]
In original game Paratroopers was targetable but not destroyable wich makes some high ROF units waste their shots on them. Not sure how does that work on OpenRA. I think they are neighter target or destroyable.
