### ISSUE TITLE
Drop Windows XP and .NET 4.0 support.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#10661]
Maintaining Windows XP support means that we are stuck with .NET 4.0, which is holding us back in a number of ways (which I expect to grow as time goes on):

1.  We can't fix our broken UPNP support because OpenNAT has only ever supported .NET >= 4.5 (#7140).  This then leads to confusion from people who don't know why we have a port forwarding option that can't obviously be enabled.
2.  The GeoIP library has recently dropped support for .NET < 4.5, so we are now stuck on an older version that won't receive bugfixes and makes life more difficult for linux packagers (#10280).
3.  The Roslyn compiler will give us access to much more powerful analysis tools for linting and documentation generation, but can only target the .NET >= 4.5 runtimes.
4.  Xamarin now only maintain partial support the 4.0 runtime by shipping pre-compiled assemblies (it is no longer possible to compile them from source, AFAIK).   Linux distros such as Fedora and Debian testing will not distribute these, so we can't support OpenRA on these platforms unless the player compiles/installs their own version of mono.
5. Microsoft have dropped all support for .NET 4.0 (https://support.microsoft.com/en-gb/lifecycle?C2=548), and Windows > XP support 4.5.2 or greater.

Depends on #10662.  Pulling the rug out from anyone who does use XP isn't very polite, so we need to know how big of an effect this will have.

**Comment by AoAGeneral** [comment]
According to https://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0 it is showing that 52% is under Windows 7.

According to http://store.steampowered.com/hwsurvey within the first month of January 32% show using Windows 7.

Going by http://www.w3schools.com/browsers/browsers_os.asp It shows a more detailed usage of the OS in category and in type.

News feed from softpedia at http://news.softpedia.com/news/windows-10-becomes-the-third-most-used-desktop-os-in-the-world-496203.shtml states that Windows 7 of novemeber last year is the most used OS. Windows 10 being the third most used.

Back when Vista made its release no one wished to make the switch due to how buggy the system was. Particularly in the time that 64 bit was still a new technology and running 4gb of ram on windows XP was still enough.

It started to get to a point where people wanted more then 4gb due to advancements of video editing and other software designs which released windows XP 64 editions. However, Windows 7 was close on the rise so there were people who waited. (Estimated number whom waited I am unsure of)

Once windows 7 released the switch to 64 bit was clear as XP 32 was unable to utilize more then 4gb of ram. (Sometimes even 4gb itself and had to be 3.5gb) Which is why Windows 7 became so popular. Let alone for easy software usage.

Personal opinion: I think it is safe to make the switch to drop Windows XP. While it sucks all the same that Microsoft decided to do such as small companies still use XP. However, A lot of games coming out now and otherwise do not support XP. They instead support either Vista and above or Windows 7 and above. (Even some games no longer support Vista.)

**Comment by dan9550** [comment]
I feel this is acceptable, the original games are fairly compatible with XP anyway more so than Vista and up. Its not like we are leaving people without a choice.

**Comment by rapgro** [comment]
Guys, this is a real blocker for Fedora packages.

**Comment by GraionDilach** [comment]
@rapgro Don't get me wrong... but what isn't a blocker for Fedora? To me it seems, Fedora is just damned picky about everything.

It really should be checked beforehand how much the userbase will be affected by such a change of dropping XP, considering that XP is popular among the casuals, compared to Fedora.

**Comment by rapgro** [comment]
http://www.mono-project.com/docs/about-mono/compatibility/

**Comment by Mailaender** [comment]
![image](https://cloud.githubusercontent.com/assets/756669/15272850/7a2a7ab2-1a86-11e6-83cd-894ecaa0fad3.png)

0,48% of our users playing the latest released version are running Windows XP.
