### ISSUE TITLE
Tab completion isn't working for dev commands

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#10683]
##

**Comment by obrakmann** [comment]
Er, wtf? I just bisected this. It seems it was introduced by #10648. I have no idea where those things even touch.

**Comment by pchote** [comment]
There's probably an undeclared TraitInfo order dependency somewhere in the commands code that breaks now that the yaml merging works properly (which may cause some traits to be initialized in a different order).

**Comment by obrakmann** [comment]
Order dependency was right, but not for the TraitInfos.

So all the `*Commands` do their thing in `WorldLoaded`. `IngameChatLogic` gathers all the commands in its constructor.

As it turns out, the widgets themselves are created during `LoadWidgetAtGameStart`'s `WorldLoaded` method, which, as `LoadWidgetAtGameStart` is declared as one of the first traits in `world.yaml`, runs before the `WorldLoaded` method of the `*Commands` traits.

**Comment by obrakmann** [comment]
OK, https://github.com/OpenRA/OpenRA/compare/bleed...obrakmann:fix10683_broken-dev-commands fixes it. Not sure if that's the solution we want to go with, though.

**Comment by abcdefg30** [comment]
I'd like to keep this issue open though, as reminder that something in the logic is bogus (https://github.com/OpenRA/OpenRA/issues/10683#issuecomment-179478285).

**Comment by PunkPun** [comment]
> I'd like to keep this issue open though, as reminder that something in the logic is bogus ([#10683 (comment)](https://github.com/OpenRA/OpenRA/issues/10683#issuecomment-179478285)).

Do we still wanna keep this open?

**Comment by abcdefg30** [comment]
Yes, we shouldn't need to rely on ordering in yaml. (Unless this was fixed since?)

**Comment by abcdefg30** [comment]
Closed by #20147.
