### ISSUE TITLE
[RA] The official map pool. Out with the old...

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#10708]
As requested here's a list of maps I believe think should be wiped off the official map pool. We need to take advantage of newer and better maps from the resource center and make sure we regularly replace the outdated and old. This will also encourage people to make more and better maps for the future.

This list I think presents the worst ones and imo are beyond salvage. The list progress in the same order as in the official map tab in-game.

[Burlesca](http://resource.openra.net/maps/7126/) (2 players)
[Styrian Mountains](http://resource.openra.net/maps/7284/) (2 players)
[Contact](http://resource.openra.net/maps/7537/) (4 players)
[Island Hoppers](http://resource.openra.net/maps/6925/) (4 players)
[Pearly Wastelands](http://resource.openra.net/maps/7292/) (4 players)
[Breaking Point](http://resource.openra.net/maps/7544/) (8 players)
[Central Conflict](http://resource.openra.net/maps/7541/) (8 players)
[Raraku](http://resource.openra.net/maps/7179/) (8 players) (swap with Caffeinated, see #10710)
[Ring of Fire](http://resource.openra.net/maps/7273/) (8 players)
[High & Low Extended](http://resource.openra.net/maps/7357/) (10 players)

**Comment by psydev** [comment]
I would just like to add, it would be really useful if we collected statistics from servers on which maps were the most/least used. That would give us an idea of what players enjoy playing.

**Comment by pchote** [comment]
We have those stats, and they can be queried from the master server.  e.g. compare [Tainted Peak](http://master.openra.net/map_stats.php?hash=9570bd1af6cb7e78b22a7179902cd8a926fac45a) (2 plays recorded) against SoScared's [Sidestep](http://master.openra.net/map_stats.php?hash=2fca722987df9e740d65544ad30b2b0be060e701) (352 plays).

**Comment by kyrylo** [comment]
@pchote due to rehashing of the maps the counters are not accurate. [Tainted Peak](http://master.openra.net/map_stats?hash=2e84e0251cd969ec191ab90b97c9943eb3d7589c) has more plays.

**Comment by pchote** [comment]
Here's a list of the stats for release-20121224:
```
mods/ra/maps/doubles.oramap	2105
mods/ra/maps/singles.oramap	1630
mods/ra/maps/tournament-island.oramap	1504
mods/ra/maps/vegetation.oramap	1113
mods/ra/maps/haos-ridges.oramap	1043
mods/ra/maps/bombardment-islands.oramap	669
mods/ra/maps/regeneration-basin.oramap	662
mods/ra/maps/ore-lord.oramap	590
mods/ra/maps/chaos-canyon.oramap	507
mods/ra/maps/synergy.oramap	440
mods/ra/maps/keep-off-the-grass-2.oramap	405
mods/ra/maps/barracuda.oramap	394
mods/ra/maps/puddles-redux.oramap	394
mods/ra/maps/sidestep.oramap	352
mods/ra/maps/mad-science.oramap	342
mods/ra/maps/temperal.oramap	310
mods/ra/maps/Sahara.oramap	308
mods/ra/maps/mass-confliction.oramap	299
mods/ra/maps/snowyridge.oramap	290
mods/ra/maps/first-come-first-served.oramap	287
mods/ra/maps/engagement.oramap	285
mods/ra/maps/east-vs-west.oramap	260
mods/ra/maps/pressure.oramap	258
mods/ra/maps/all-connected.oramap	256
mods/ra/maps/ring-of-fire.oramap	244
mods/ra/maps/alaska-anarchy-redux.oramap	240
mods/ra/maps/marooned-2.oramap	230
mods/ra/maps/bloody-delta.oramap	227
mods/ra/maps/doughnut.oramap	223
mods/ra/maps/tainted-peak.oramap	223
mods/ra/maps/man-to-man.oramap	218
mods/ra/maps/cold-front.oramap	209
mods/ra/maps/ghost-town.oramap	208
mods/ra/maps/a-path-beyond.oramap	191
mods/ra/maps/calm-before-storm.oramap	179
mods/ra/maps/forest-path.oramap	178
mods/ra/maps/island-hoppers.oramap	161
mods/ra/maps/raraku.oramap	160
mods/ra/maps/bad-neighbors.oramap	152
mods/ra/maps/caffeinated.oramap	144
mods/ra/maps/snowy-island.oramap	139
mods/ra/maps/suffrage.oramap	137
mods/ra/maps/central-conflict.oramap	135
mods/ra/maps/high-and-low-extended.oramap	135
mods/ra/maps/tabula-rasa.oramap	128
mods/ra/maps/asymmetric-battle.oramap	116
mods/ra/maps/styrian-mountains.oramap	110
mods/ra/maps/blitzkrieg.oramap	98
mods/ra/maps/breaking-point.oramap	97
mods/ra/maps/coastal-influence.oramap	94
mods/ra/maps/high-and-low.oramap	94
mods/ra/maps/chokepoint.oramap	92
mods/ra/maps/equal-opportunity.oramap	91
mods/ra/maps/seaside-2.oramap	83
mods/ra/maps/encounter.oramap	79
mods/ra/maps/north-by-northwest.oramap	79
mods/ra/maps/arctic-triangle-affair.oramap	50
mods/ra/maps/contact.oramap	47
mods/ra/maps/pearly-wastelands.oramap	47
```

**Comment by Micr0Bit** [comment]
best would be to ask the contributers of the maps directly ... imho

@chrisforbes about Snowy Ridge , which is a nice 1v1v1 map , and we dont have lots of 1v1v1 maps

@NukemBro made Contact and Tainted Peak ... good maps , i like them 

too bad buddha isnt on github ,  cause "pearly wastelands" is a nice classic 2v2 ... we even used to play them in the old first tournaments 

i dont care that much on the westwood crap , and sw1 and Reflex arent on github ... so lets say im indifferent about removing those maps

**Comment by SoScared** [comment]
@Micr0Bit Snowy ridge has the bottom player at a terrible eco disadvantage. IMO it needs to change or go. Contact is a duplicant to other 2v2 maps and to be honest, isn't pretty.

Shouldn't map creators be treated the same way as any other contributor? If there's an improvement in code, do you ask the original author if you may replace it?

**Comment by kyrylo** [comment]
I agree with @SoScared about everything he said in this thread. I also think it's nice to refresh the map pool from time to time. For example, @SoScared's Sidestep drastically changed the way people play this game (at least on that particular map; it stands out). We definitely should try out new maps that introduce new ideas. It's simply not fun to play for years on the same maps like Singles.

**Comment by chrisforbes** [comment]
@Micr0Bit just remove Snowy Ridge. It's terrible. I'm sorry I inflicted it on the world.

**Comment by SoScared** [comment]
@chrisforbes I'll make a re-work list for other maps. There's a lot of maps that can be salvaged, Snowy Ridge included.

**Comment by Micr0Bit** [comment]
im not convinced about removing Snowy Ridge ... @pchote posted stats just above me , and there it says "mods/ra/maps/snowyridge.oramap  290"

so people play this map , that might be not any of the 5-8 tourny players we have  ... that might be the casual / noobs who dont care about map balancing ... and for that reason + because its on of the few 1v1v1 maps we have i give a :-1: for snowy ridge

**Comment by chrisforbes** [comment]
High number of plays for a bad map doesn't justify keeping it. It just means a lot of people have had a lousy experience.

**Comment by r34ch** [comment]
I don't understand why casuals have to play old maps? Why can't newer players play newer/redone maps with you know, proper balance and _trees_ and tech buildings. They don't care for nostalgia of maps they haven't played before. And if they care for nostalgia, they would surely play the original games.


I agree with @SoScared that people contributing maps to the game should have their work freely editable as everyone who contributes to the code base. I also think maps going into the official pool should undergo 'map review' before going into the game just like code does.

I'm pretty sure some of these old maps are the way they are due to lack of tools and early performance reasons. The tools and codebase have caught up, but the most visual impact newer players will get - the maps - haven't. I think these maps being in the official pool will draw an unfair comparison to the rest of the game (the codebase, balance etc).

**Comment by Micr0Bit** [comment]
i didnt say that casuals have to play old maps ... and nobody is against new maps ... i just refuse to let go of some "openra-classics" (not westwood classics)

**Comment by SoScared** [comment]
Ok so I started working on a new job list of maps that should be reworked. There's lot's of time to be saved by upping the quality of the existing maps, including Snowy Ridge and Pearly Wastelands. Some maps need balancing but many of them needs an aesthetic overhaul (e.g. actors, ridge formations).

@Micr0Bit : I agree, we should try to keep the classics but imo that requires some of them to be altered. I think holding on to bad maps in favor of better ones (created by equally hard working people, if not harder) is gonna hurt the enthusiasm for making maps.

**Comment by Micr0Bit** [comment]
@SoScared : sounds good to me

**Comment by cjshmyr** [comment]
:+1:

**Comment by obrakmann** [comment]
FWIW, I'd like to nominate the following:

* [Blitzkrieg](http://resource.openra.net/maps/8258/)
* [Breaking Point](http://resource.openra.net/maps/7544/)
* [Encounter](http://resource.openra.net/maps/7290/)
* [High & Low](http://resource.openra.net/maps/7999/) (+ [Extended](http://resource.openra.net/maps/7357/))
* [Mass Confliction](http://resource.openra.net/maps/7427/)

Those make my eyes bleed.

**Comment by SoScared** [comment]
@obrakmann : I'm hoping Encounter, High & Low and Mass Confliction can be reworked. #10718

**Comment by SoScared** [comment]
@obrakmann Have a look at Encounter, High & Low and Mass Confliction in #10718 

Blitzkrieg looks like a popular map among casual players. Besides being a bit "square-y" it doesn't look too horrific IMO. Breaking Point, agreed. 4 vs 4 player on a very small, very choke-y map. Never had a good game on it.

**Comment by SoScared** [comment]
Adding [Raraku](http://resource.openra.net/maps/7179/) as a suggestion for removal. [Caffeinated](http://resource.openra.net/maps/7369/) is a similar map in style (except more choked) and in number of players, but has better player positioning (easier team setup) and IMO will appeal more to casual players.

Counter to #10712

**Comment by MurtoTheRay** [comment]
@Micr0Bit I agree that that there are a few maps that should be kept as OpenRA Classics. Why not implement a third "Classic" tab which includes these maps?

**Comment by Micr0Bit** [comment]
@MurtoTheRay : why not implement a tab just for SoScareds maps ? what i mean by that is , everyone has their own perception of  "map balance" and about the importance of it ... 
i dont like when one person points at stuff and then a handfull of devotees blindly agree to everything they hear on a stream ...
we have a lot of good (old) players in openra , and SS + 5Aces are by no means experts on OpenRA-related stuff , even though they talk about it on their streams ... 

ive experienced just on github , theres always people "come and go" ... changing things and then disappear the next day because they loose interest  ... and i want to avoid being exposed to ideas from single contributers which then (maybe) turn out to be "bad ideas" ... but the "causer" of the (maybe) dislikes or problems dont care anymore or simply disappeared

**Comment by SoScared** [comment]
@Micr0Bit Jeez Microbit. Couldn't you type this (condescending) rant in the forum or something? It's a total derail.

**Comment by Micr0Bit** [comment]
@SoScared : oh , im sorry , i didnt mean to be condescending ... i like you , and i like the work you are putting into the community ...  i was just pointing out the reason why im "against" it in the first place ... causing contoversy can lead to more people getting involved and say their oppinion

im willing to give this a try for a playtest ... so i change my thumb 

:+1:

**Comment by SoScared** [comment]
There's still related discussions going on in the forums so I'm guessing there's no rush to declare consensus until we're closer to a new release.

**Comment by dtluna** [comment]
@Micr0Bit 
>first of all. causing contoversy can lead to more people getting involved and say their oppinion
Oh, wait a second, getting more people to voice their opinion and have a discussion is considered bad all of a sudden.
And by the way, if an issue is controversial it is a yet one more reason to discuss it, not less reasons.

>everyone has their own perception of "map balance"
And everyone has their own perception of red color. But still it is not something subjective.
Stop using those postmodernistic "arguments", Microbit. Map balance is not just a subjective thing. It can be assessed and evaluated.

>and i want to avoid being exposed to ideas from single contributers which then (maybe) turn out to be "bad ideas"
That's why we are having a discussion right here!  To present arguments to understand whose idea is the best one.

>i dont like when one person points at stuff and then a handfull of devotees blindly agree to everything they watch on the public stream of those person ...
Oh, thanks, now I am shoved into a category of "SoScared's blind devotees".
I do not just blindly accept his opinion. I agree with him, because he presented reasons and arguments to me. And my reasons, thoughts and feelings are somewhat the same as his on this issue.

>i think its important in open-source projects to show agreement as well as resistance on contributions ...
After having a reasonable discussion, which you are trying to shut down.

>we have a lot of good (old) players in openra , and SS + 5Aces are by no means experts on OpenRA-related stuff , even though they talk about it on their streams ...
Being old or good does not give you more expertise in this issue. Stop using ad hominem.

**Comment by dtluna** [comment]
@Micr0Bit 

> first of all. causing contoversy can lead to more people getting involved and say their oppinion

Oh, wait a second, getting more people to voice their opinion and have a discussion is considered bad all of a sudden.
And by the way, if an issue is controversial it is a yet one more reason to discuss it, not less reasons.

>everyone has their own perception of "map balance"

And everyone has their own perception of red color. But still it is not something subjective.
Stop using those postmodernistic "arguments", Microbit. Map balance is not just a subjective thing. It can be assessed and evaluated.

> and i want to avoid being exposed to ideas from single contributers which then (maybe) turn out to be "bad ideas"

That's why we are having a discussion right here!  To present arguments to understand whose idea is the best one.

> i dont like when one person points at stuff and then a handfull of devotees blindly agree to everything they watch on the public stream of those person ...

Oh, thanks, now I am shoved into a category of "SoScared's blind devotees".
I do not just blindly accept his opinion. I agree with him, because he presented reasons and arguments to me. And my reasons, thoughts and feelings are somewhat the same as his on this issue.

> i think its important in open-source projects to show agreement as well as resistance on contributions ...

After having a reasonable discussion, which you are trying to shut down.

> we have a lot of good (old) players in openra , and SS + 5Aces are by no means experts on OpenRA-related stuff , even though they talk about it on their streams ...

Being old or good does not give you more expertise in this issue. Stop using ad hominem.

**Comment by Micr0Bit** [comment]
as much as i would like to answer this ... we should stay on topic

**Comment by jaZzKCS** [comment]
Please DO have a lively discussion about the balancing, as it is desired, albeit NOT HERE.
Use the Balance Thread in the forums to continue discussing, this place is reserved for the RESULTS

**Comment by SoScared** [comment]
Latest changes, added:

**Breaking Point**: 8 players fighting through 2 narrow chokes. Also it's one of the 'capture the middle or die' kind of maps, but doesn't make it obvious to new or casual players. There's no interest in altering the map either since it would alter the map's original purpose.

**Raraku**: Fugly version of map Caffeinated. See main post on Caffeinated in #10710.

**High & Low Extended**: I altered High & Low (8 players) but I won't for this one. Personally I can remember plenty of good fun games on H&L (played big team games quite a lot some years ago) but can't remember one single good game on H&L Extended. These maps extends games that are already decided without any interesting after-play, meaning once one side has an insurmountable lead it becomes tiresome killing off opponents doing the good old 'last man standing'. There's probably other reasons but I think 'Extended' just pulls it a bit too far.
