### ISSUE TITLE
Add switch to sequences for first facing = south

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#10735]
Unit art in C&C/Dune games always uses north/up facing as first facing.

However, there are games like MechCommander where the first facing in sprites is south/down, so they currently require some annoying work-arounds (using either `Frames:` or `Combine:` to re-order the frames).

It would be easier to have a simple boolean switch to handle this in a way that doesn't require manually ordering (which is both time-consuming and makes the sequence yamls larger).

**Comment by pchote** [comment]
This is only true for our current `ISpriteSequenceLoader` implementations.  My original intention from splitting out the sequence loaders is that mods that have significantly different requirements/assumption would implement their own loaders, instead of overloading our default ones with more and more flags.

**Comment by pchote** [comment]
My suggestion above seems like the best "official" approach, so closing in favor of letting downstream mods use our plumbing for what it was designed for :smile:
