### ISSUE TITLE
More control abilities for upgrades

### ISSUE THREAD

**Issue by DoGyAUT** [OpenRA/OpenRA#10810]
The upgrades seems to be quite limited once you have to work with multiple ones affecting the same unit.

As example I have an artillery unit.

Its base weapon is enabled by default. There are 3 possible upgrades for it, which the player can pick two out of three (in this example I only added 2 upgrades so far).

Each upgrade does change the weapon and disables the default one. But I also want to achieve that once you have chosen two upgrades the first lvl 1 upgrade gets disabled too - leaving only the lvl 2 weapon active.

Now the problem is this that there seems no possibility to disable the lvl 1 weapon, the unit ends up with two weapons instead.

http://pastebin.com/QXcPSNJa

**Comment by GraionDilach** [comment]
This is why I want the TickTank PR merged, you can then use a set of upgrades to upgrade the Attack* trait instead of the Armaments trait.

On the other hand, there is a workaround already to your problem, use proper planning and layers. If there's three upgrades possible for that unit, then set that one upgrade grants it one level, the next two and the next one four. then set it up like a table

0 1 - first upgrade enabled
2 3 - second upgrade mixed with first
4 5 - third upgrade enabled mixed with first
6 7 - all three upgrades can be enabled.

**Comment by atlimit8** [comment]
Condition/variable expressions allow: `!technology && !propaganda!`, `technology && !propaganda!`, `!technology && propaganda!`, `technology && propaganda!`. Unless I am missing something, this is already covered.
