### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by konqoro** [OpenRA/OpenRA#10849]
After I select a game from mod chooser (I tried both cnc and ra), the loading screen appears and then the game crashes. The exception log is here: http://pastebin.com/Wjwx5m9P. If I give write permissions to my user for file /usr/lib/openra/lua/scriptwrapper.lua, the game runs normally but it crashes in the settings screen. My OS is Manjaro linux. To get openra I used the PKGBUILD from aur and switched branch to bleed.

**Comment by pchote** [comment]
This looks like a permissions issue on your end.  Try cloning or downloading the zip with the latest bleed source and then compiling and running from inside your home directory (https://github.com/OpenRA/OpenRA/blob/bleed/INSTALL.md).

**Comment by konqoro** [comment]
Done, crashes when clicking Settings http://pastebin.com/8421WwZq

**Comment by konqoro** [comment]
Master works both locally and globally installed. Permissions for scriptwrapper.lua are what the ought to be (644). This could be a regression for linux.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/tree/bleed/lua remained unchanged in the last two years and our https://github.com/OpenRA/OpenRA/blob/bleed/Makefile#L401 is just doing a regular copy, so I don't think it is a regression on our end.

Looking at https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=openra-git it should really `make version`, because it is checking out `master` which is our stable branch, but claims to be an outdated playtest.2015.09.19.git version.

You should stick with https://www.archlinux.org/packages/community/any/openra/
