### ISSUE TITLE
[TS] Units can't get out from factories if there are obstacles

### ISSUE THREAD

**Issue by Fincer** [OpenRA/OpenRA#10843]
For example, infantry can't get out if I build it right behind a ConYard:

![cantbuild-cropped](https://cloud.githubusercontent.com/assets/3705231/13371918/7e0dc852-dd3a-11e5-9b50-7559f9598cdc.gif)

Someone could say this is not a bug but it clearly affects annoyingly the gameplay and thus should be considered as one. I've not tested how the original TS handled kind of situation but at least the original RA2 could do it well.

Same as https://github.com/OpenRA/ra2/issues/137

**Comment by GraionDilach** [comment]
The orig games were more lenient.

In orig TS and RA2, exit cells were defined, and the unit spawned and got nudged there, the actual exit offset wasn't that strict compared to OpenRA. On the other hand if you walled around your sole barracks in TS/RA2, the unit you trained just paid back it's price when training finished (which was bugged in RA2, because walling off barracks and having a Cloning Vats still meant the Vats produce the infantry => free infantry).

**Comment by Phrohdoh** [comment]
This isn't at all a bug, you are blocking the defined `Exit`.
Perhaps we should have an interface method ` IEnumerable<CVec> IExtendsFootprint.GetUnblockableCells()` so traits (such as `Exit) can define cells that it wants to be free and we can then append those cells to the `x` (in yaml) cells.

**Comment by weinerschnitzel** [comment]
In the original game if the exit was blocked it would spawn the infantry on an adjacent cell to the barracks without terrain or buildings or stuck vehicles in the way.

**Comment by LipkeGu** [comment]
Units was also paid back when units gots trained too fast

**Comment by forcecore** [comment]
Happens in RA1 ai when it builds KENN at a bad spot. As a result, it can not build any infantry!
