### ISSUE TITLE
[RA] Official Map Pool: Alter Keep Off The Grass 2 (2 players) - balance, aesthetics

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#10954]
[**Keep Off The Grass 2, current**](http://resource.openra.net/maps/7242/), (2 players)

Changes:
Moved the first ore patch for both spawns to balance ore access.
Changed ridges and debris to balance fields around the players.  #10347
Tweaked the players spawn's first ore field after discussion below.

[**Keep Off The Grass 2, altered**](http://resource.openra.net/maps/9542/), Playtested (revision 4), altered to revision 5 after discussion below.

![keep off the grass 2 compare revision](https://cloud.githubusercontent.com/assets/2715583/14116632/fe7edd3c-f5e0-11e5-829e-0733d9072fbd.png)

![keep off the grass 2 rew](https://cloud.githubusercontent.com/assets/2715583/14116636/05f65b58-f5e1-11e5-8683-7f8252d4523f.png)

**Comment by Aaron-Lloyd** [comment]
Hey, SoScared, I was just looking through all your fixed up maps. They all look great so far, but this one has me ever so slightly worried, I'm worried that the way you have the spawn point ore patches set up it slightly favours the northern player.

Because of the refinery orientation and preferring to keep the bulk of the ore south of the refinery the southern player would be encouraged to build their refinery in the northern half of the ore patch where it'd be more vulnerable and the southern player would more likely put their's in the northern half of their's too where it'd be better protected. It's a minor issue but I still think it could be a balance problem.

**Comment by SoScared** [comment]
Hadn't considered that. You're right it might be a minor issue but I think it's worth tweaking. Especially now that these map issues are hot. 

Looks like a simple fix to me, skewing the ore point south for each player. I'll have it done by the week-end. Thanks for the heads-up!

**Comment by SoScared** [comment]
Figured it better be done sooner rather than later. New revision proposed:
https://github.com/OpenRA/OpenRA/pull/10986#issuecomment-202984455

**Comment by SoScared** [comment]
Updated the main post links and images and link in the master ticket #10718 for map Keep of the grass 2 after this issue reopened.
