### ISSUE TITLE
Primary building selector is nearly invisible against an arctic map

### ISSUE THREAD

**Issue by scshunt** [OpenRA/OpenRA#10996]
The word "primary" is drawn in white on the white terrain and consequently is almost invisible.

**Comment by HenrytheSlav** [comment]
Noone uploaded a screenshot so I will.

![prim](https://cloud.githubusercontent.com/assets/12610736/14228302/057194e4-f911-11e5-9046-5a4ab5dd38bb.png)
Is this relly so bad? I can read it okay.

**Comment by scshunt** [comment]
Oops, my bad. I mis-filed this under RA rather than RA2.

**Comment by GraionDilach** [comment]
This should be a problem on TS arctic though.

There are two factors here.
A) Primary isn't a glyph in the nonD2k mods.
B) Primary is placed in the top middle of the selection box. Since TS and RA2 uses isometric POV, the building has a lot less chance to be under the text.

The combination of A and B should apply to TS and honestly, the RA barracks is already on the edge with it.

**Comment by scshunt** [comment]
There is the black shadow to make them legible, though.
