### ISSUE TITLE
"Stop" is invalid for defensive structures

### ISSUE THREAD

**Issue by steadyfield** [OpenRA/OpenRA#11027]
Cannot stop any defensive structure from force attacking. I tried pressing "S", but it didn't work. It only works for infantries and vehicles.

**Comment by pchote** [comment]
Confirmed that this is a regression between release-20151224 and bleed.

**Comment by pchote** [comment]
Introduced by #10750:

```
dc6d31cec8a18c45a93c4c6c080ac54731a79646 is the first bad commit
commit dc6d31cec8a18c45a93c4c6c080ac54731a79646
Author: teees <>
Date:   Wed Nov 4 09:19:58 2015 +0100

    Fix turreted immovable actors not dropping targets that are out of range

```

**Comment by pchote** [comment]
In the case for immobile turreted actors (i.e. all base defenses) `AttackFollow.AttackActivity` runs continuously instead of sequencing other activities.  When the stop order is issues the `AttackFollow` changes its target to invalid, but the activity doesn't detect this because it keeps its own internal copy that isn't updated.
