### ISSUE TITLE
Fix shocktroopers shooting through walls

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#11050]
> Coils shouldn't change, and IMO an argument could be made for letting ttnk fire over walls too. Shock troopers definitely shouldn't, though.

**Comment by pi99y** [comment]
Although @pchote  confirmed this as a bug, I think that:

* **thesla coils SHOULD be able to shoot over walls** since they are **significantly taller** than walls and other defense structures.
* Walls **blocking fire from shock troopers and tesla tanks seems fine to me.**

I think that the argument "Allies don't have a similar defensive structure" is not to be considered since we probably want diversity to make the game more interesting.

**Comment by pchote** [comment]
IMO an argument could be made for letting ttnk fire over walls too.  Shock troopers definitely shouldn't, though.

**Comment by Micr0Bit** [comment]
**yo# u want diversity in terms of basewalking  like "one side had advantage over the other side" ? **

**Comment by StexoO** [comment]
This is how an expensive, high, slow (cooldown) and weak (hitpoints) Tesla coil works :
https://www.youtube.com/watch?v=VmstSYWBPIU
https://www.youtube.com/watch?v=jSHbYFD4LBI
:yum:

**Comment by Micr0Bit** [comment]
http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=20007
