### ISSUE TITLE
Light Tank Vehicle Husk

### ISSUE THREAD

**Issue by DeclanMurphyCit** [OpenRA/OpenRA#11054]
Since nobody uses mechanics to reuse light tank husks, and the only use of a husk of a light tank is to block an ore refinery / war factory. Is there any chance that they could be removed from the game?

**Comment by kingtiger01** [comment]
I dont see why this is a issue? removing a element because some people dont use it? 

why not have husk creation be periodical, that way it can be used more stregically than as a blockade.

**Comment by DeclanMurphyCit** [comment]
Ok to look at it from another perspective: soviet vehicles don't leave husks until you build a repair bay. So if takes longer to execute the blocking strategy. 

I find it unfair in 1v1 games, that Allies can do this strategy straight away.

Or how about vehicles exiting war factories and harvastors entering refineries don't get blocked?

**Comment by StexoO** [comment]
Light tanks can be used to crush infantry, to scout and husks can be destroyed. :open_mouth: 

Light tanks leave husks but they can only crush infantry and can't destroy or kill anything (subjective feeling about early games). You just need few bazookas or one turret to remove any light tank and its husk.
You can build your war factory near your refinery and build a turret between the two. When the light tank is destroyed, force fire on the husk with your turret (or your bazookas) to remove the husk and you'll never (never) be blocked a long time in any game, even if the light tank comes with its maximum health.
So if you are prepared, this light tank blocking your refinery is not a good move against you but a money loss for your opponent. In early games it can hurt. :yum: 
Soviets can use APCs to block buildings. APCs leave no husk when they are destroyed but they are faster, have a better sight range and are deadly against infantry. If Soviets are blocked by a husk they can also destroy it with few bazookas or any defense.

APCs and light tanks also have a huge impact on micro and macro management, and early games are a bit like a poker game because APCs and light tanks exist :
- Will your opponent attack/scout you with an early APC/light tank, so will you place your buildings in order to easily defend them or will you place them in order to optimize paths, map control, mining and so on ?
- Will you place defenses or bazookas immediately on the field or will you keep them in your build queues to get your cash back if your opponent doesn't attack or block you ?
- Will you even build something against/for this or will you use your time and money to get buildings, technology, units and vehicles instead ?
- If you try to attack or block him, will you focus on delaying the ore trucks or the vehicles production or will you focus on forcing him to build defenses and units all around his base ?
- What if... two APCs / light tanks ? Three ?
- ...
- And what is your opponent thinking about all of this ?

IMO APCs and light tanks are somehow balanced and useful, and if you remove the light tank Soviets will have an advantage and early games will be less exciting. :sob:

**Comment by HenrytheSlav** [comment]
@DeclanMurphyCit since the last release allows you destruction of husks even on refinery, this could be closed, unless there is something else that you wish to comment.

**Comment by Micr0Bit** [comment]
i agree , and i dont see them getting removed ... now that we got a refinery-patch-fix
"this could be closed"
