### ISSUE TITLE
Supply trucks destroyed right before entering a building causes the game to crash

### ISSUE THREAD

**Issue by Aaron-Lloyd** [OpenRA/OpenRA#11218]
Was messing around in debug mode and got a crash when the AI destroyed a supply truck which was just about to enter a building.

Here's the exception.log:

> Red Alert Mod at Version release-20151224
> on map 44c32eea46646e757b38779d772407908e32e6f6 (Crater Lake by Raymundo).
> Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
> Runtime Version: .NET CLR 4.0.30319.34209
> Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (truk 309 (not in world))
>    at OpenRA.TraitDictionary.CheckDestroyed(Actor actor)
>    at OpenRA.TraitDictionary.GetOrDefault[T](Actor actor)
>    at OpenRA.Actor.TraitOrDefault[T]()
>    at OpenRA.Mods.RA.Traits.SpawnActorOnDeath.<Killed>c__AnonStorey0.<>m__0(World w)
>    at OpenRA.World.Tick()
>    at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
>    at OpenRA.Game.LogicTick()
>    at OpenRA.Game.Loop()
>    at OpenRA.Game.Run()
>    at OpenRA.Program.Run(String[] args)
>    at OpenRA.Program.Main(String[] args)
>

**Comment by obrakmann** [comment]
I think these would be the events leading up to that crash:

1. Truk enters the building

2. `Enter.FindAndTransitionToNextState()` is running, and since `DonateSupplies` uses `EnterBehaviour.Dispose`, `Actor.Dispose()` runs for the actor, queueing a FrameEndTask.

3. Truk is then killed by the enemy:

* `Health.InflictDamage` first calls `SpawnActorOnDeath.Killed()`, which queues a FrameEndTask, during which some trait lookups happen.
* `Health.InflightDamage` then calls `Actor.Dispose()` as well, queueing another FrameEndTask (which will never run, the game crashes before).

4. After the tick, the first FrameEndTask disposes of the actor. The second FrameEndTask would spawn the crate from the truk, but the trait lookups then fail and throw an exception.


The fix would be to check `Actor.Disposed` in `SpawnActorOnDeath`'s FrameEndTask. The truk has already delivered the money, so a crate shouldn't be spawned anyway.

**Comment by abcdefg30** [comment]
Wasn't this fixed in #11234 now (see https://github.com/OpenRA/OpenRA/pull/11234#issuecomment-217642412)?
