### ISSUE TITLE
Can't queue harvester commands

### ISSUE THREAD

**Issue by AMHOL** [OpenRA/OpenRA#11264]
Tried with both left and right click orders, commands are issued instantly rather than queued, this bug was present before the release too

**Comment by obrakmann** [comment]
Well, it's not strictly a bug. There are several orders that are un-queued by default (unloading passengers or sending units to a repair pad would be other examples). It would be nice to fix all of those, which would be especially helpful for scripting. Definitely a long-term goal, though, since it's a huge task.

**Comment by matjaeck** [comment]
This behavior for harvesters is unchanged in playtest-20190106.

**Comment by AMHOL** [comment]
Also seems that if a harvester is told to harvest ore more than x(5ish) tiles away, it ignores the order and moves to the nearest ore field and starts harvesting there, even if it was queued behind a move command. Has lost me many harvesters when being attacked and they decide to do their own thing.
