### ISSUE TITLE
Black Desktop and no Choice

### ISSUE THREAD

**Issue by HakuDeathgoof** [OpenRA/OpenRA#11314]
- Hey,
  
  i installed the OpenRA yesterday and directly installed Dune 2000. At first all works fantastic! 
  But toay i want to continue and after starting the OpenRA, i cant choice which game i want to play, and the Desktop get black. 

I can see the cursor like in Dune, and hear the electercy sounds from the Sandworm, but i cant see or do anything.
I uninstall and download the OpenRa completly new, but nothing changes .....
i use Windows 8.1 #

**Comment by GraionDilach** [comment]
Could you rename `/username/My Documents/OpenRA/settings.yaml` and recheck if the problem exists? (This sets everything back to default.)

Might be some display settings went off.

**Comment by HakuDeathgoof** [comment]
Uhm... there isnt any "setting.yaml" or anything with "settings", so i cant rename it ><

**Comment by GraionDilach** [comment]
Sorry, it should be `Users/username/Documents/OpenRA/settings.yaml`.

If you have one, could you please check/add the following into it:
```
Graphics:
	Mode: Windowed
```

This should launch OpenRA in windowed mode.

**Comment by HakuDeathgoof** [comment]
Did it.... started the game, no Windowed mode, after opening the grahic thing again, the new saved settings are lost.

i give up

**Comment by philmexico** [comment]
I seem to have a very similar issue. I run openRa on a laptop w/ win8.1(64) with an nvidia 820m.

the first time i ran it, i got to the mod selection and from there to the games without any issues.

Since then, whenever I run it in fullscreen, all I see is the cursor of the mod selection, or whichever mod I run; only black screen other than the cursor, though. Sound seems to be fine, as do buttons to interact.

I was able to run the game fine in fullscreen mode once or twice, I believe after I updated the nvidia driver. Unable to reproduce, unfortunately.

Window mode runs without issue.

Issue not affected by wether I run the game using the nvidia card, or only cpu.

Nothing useful in logs.

No new settings.yaml is created when I remove mine; I guess I simply don't advance far enough in the game to the point where one is created though.

Kinda reminds me this issue: https://github.com/OpenRA/OpenRA/issues/13034 - just with nothing visible at all except cursor and black screen, instead of the glitches.

**Comment by philmexico** [comment]
setting the mode to windowed and the window size to screen size in settings.yaml worked! I can now play openRA in full screen mode :)

Graphics:
	Mode: Windowed
	WindowedSize: 1600,900

(Btw, simply changing to fullscreen from the windowed game had produced the same error)

**Comment by abcdefg30** [comment]
Closing due to lack of information/inactivity. Please leave a comment when you want this reopened.
