### ISSUE TITLE
Sprites render from the wrong texture.

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#11341]
Can't reproduce it anymore though.
![niced2kloadscreen](https://cloud.githubusercontent.com/assets/7704140/15457031/cd796d80-2081-11e6-951b-01ce8d103c3d.png)

**Comment by pchote** [comment]
This won't be related to d2k specifically.

**Comment by MustaphaTR** [comment]
I can't retest right now,  but yea i saw that once too.

**Comment by ltem** [comment]
hello,

My setup:
- OpenRa-Version: release-20161015 (plus the last 3 releases (playtest + stable))
- OS: Debian 8
- GPU: Amd
- GPU-Driver: fglrx
- Chromium-Version: 53 (from debian repo)

I have this error as well and I can reproduce it.

If I start OpenRa while Chromium (HWA active) is already running, render and graphic glitches can/will appear (see examples below). If I close Chromium and restart OpenRa the glitches are gone (Chromium is not running at this time).

A quick test showed that with Chromium HWA deactivated non of these errors appear for me.

In my opinion Chromium somehow corrupts the rendering of OpenRa (no idea how this is possible but I would like to know :) ). 
So it could be due to a strange connection between Openra + Linux Amd Hardware + Driver + Chromium Hardware Acceleration. 

It is not a real issue for me but maybe this report helps you somehow. 

PS: If I remember correctly I read  that Chromium has some problems with AMD GPUs + Linux Drivers somewhere :/

HWA ... Hardware Acceleration

Examples:
![screenshot1](https://cloud.githubusercontent.com/assets/20945684/19420610/12166f16-93ef-11e6-87da-886d64552ffd.png)
![screenshot2](https://cloud.githubusercontent.com/assets/20945684/19420647/1100de1c-93f0-11e6-939c-e2eb7d639682.png)

**Comment by Mailaender** [comment]
My guess is these are hardware driver issues that may not even be related to the game. Try reporting the problem to your graphics card vendor.

**Comment by pchote** [comment]
We're seeing enough reports of these issues across enough different configurations / OSes that this must be an OpenRA bug.

**Comment by Micr0Bit** [comment]
![what](https://cloud.githubusercontent.com/assets/9139965/22087083/3f9934be-dddc-11e6-9293-6c67617a63b7.png)

**Comment by pchote** [comment]
The minimap issues, at least, were introduced by #11098 (bonus points to anyone who can work out why before I file a PR with the fix) and are easily reproducable by installing enough custom maps to require a second preview sheet.  It is less clear how it could have caused the other issues here, but the timing is right for it to be that too.
