### ISSUE TITLE
[TS] GDI Component Tower bug.

### ISSUE THREAD

**Issue by Marnador** [OpenRA/OpenRA#11349]
When GDI component tower is placed and being fired upon during Make Animation, it skips the make animation and locks up. You can't sell it, you can't have a turret on it, in other words it becomes a useless drain of power until destroyed.
I noticed it's related to WithWallSpriteBody: trait and as long as it's present the problem persists.

**Comment by GraionDilach** [comment]
I was quite certain @DoGyAUT reported this already, but I can't find the report...

**Comment by GraionDilach** [comment]
Ah, #10438 was in my mind which isn't exactly the same.

**Comment by Marnador** [comment]
@GraionDilach ah sounds very similar indeed, although in this case I can't replicate the issue with just any turreted building.

**Comment by pchote** [comment]
It sounds like something is overwriting the default animation without checking the building lock first.

**Comment by pchote** [comment]
This is different to #10438 and actually has nothing to do with responding to damage.

The issue is with https://github.com/OpenRA/OpenRA/blob/e038b8674224ebb251773a5ab82bbc05042e5ace/OpenRA.Mods.Common/Traits/Render/WithWallSpriteBody.cs#L107-L110

which unconditionally overwrites the make animation when the tower is damaged, transitioning to the `Light` damage state.

**Comment by reaperrr** [comment]
The only reason D2k towers don't use their make anim is this very bug, though.

**Comment by pchote** [comment]
This can now be fixed by following the example of #17817.
