### ISSUE TITLE
Diplomacy out?

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#11418]
That was the most idiotic thing to do! and yes i am talking to the idiot that did this! nice idea Dude! yea! lets de-evolve the game! nice going!! oh yea i am a developer so i will do whatever the fuck i whana do!  what was your problem man?????? if you din't like then don't use it! but remove it! BRAVOOO.and yea i am mad right now! and yea i am out of the line! and yea what you did was idiotic! and yea am going to regret this but its worth it for me at least!

**Comment by Ripsn** [comment]
KOYK. 
Please chose a better way to communicate your feelings in future. 
the only De-Evolving i can see.. is this thread. 
*Waits for admin to remove*

**Comment by obrakmann** [comment]
Yes, fragile diplomacy was removed, because it was broken. You can read all about it in the PR that removed it: #10650.

FWIW, I'm fine with adding it back if someone figures out a way to implement it in a way that actually works. We did the same thing with left-click orders, for example.

But I'm not going to let a ticket that starts off like that be a precedent. It's fine that you want that feature back, but I'm sure you can communicate that in a civil way.
