### ISSUE TITLE
Grouped units move back and forth after reaching their destination

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#11440]
See the group of flak trucks in the bottom left https://youtu.be/xc6q2C2CtRg?t=1m47s As the destination cell is blocked by friendly units they seem to retry all the time.

**Comment by obrakmann** [comment]
I think that's just another thing wrong with `AttackMove`. Each of the units you gave the order to tries to reach the `TargetPosition`, with the `nearEnough` parameter set to 1. First of all, we could increase that to two, but I don't think that would actually help. Due to the brain-dead nature of `AttackMove`, which restarts itself every time the actor goes idle, a new `Move` activity is generated at the same time, which then probably causes it to move even when it already is close enough.

(Have I mentioned yet that `TickIdle` is a horrible kludge that needs to die a violent death?)

**Comment by pchote** [comment]
Regular moves use a `nearEnough` parameter of 8, which causes bad behavior when units are ordered across bridges or other choke points.  `nearEnough` really needs to be ripped out and replaced with a smarter check for whether the unit has reached something close enough to its destination.  It would be worth checking how the original games handled this.

**Comment by Mailaender** [comment]
It seems original games:

* did move to the nearest accessible terrain #2309 no matter what, which we currently don't do when the domain index is unreachable
* in TS when a group pathed they don't get all path to the same location, but every unit gets their own destination spot based on the current formation at least that is indicated by the target lines

**Comment by Mailaender** [comment]
The `nearEnough = 8` also causes unsatisfying results on clear terrain when groups move and block paths as wells as destination cells:

![image](https://cloud.githubusercontent.com/assets/756669/16947343/dc187e6c-4dae-11e6-917d-3cd5986a74b4.png)

**Comment by PunkPun** [comment]
Is this still relevant?

**Comment by Mailaender** [comment]
I think I haven't seen this in a while.
