### ISSUE TITLE
RA - Replace Fake CYard with Fake MCV for France

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#11444]
I use fake MCVs in my YR mod, not fake CYard.
http://www.moddb.com/mods/red-alert-2-yuris-revenge-cncd2k-mod/images/fake-mcvs#imagebox

It makes sense because if enemy has visibility over your base he can understand Fake CYard is fake because you build it via real CYard, not a MCV. This can fix it. Fake MCV shouldn't require Service Depot as Fake buildings doesn't require anything too.

**Comment by SoScared** [comment]
I've seen player Hi make use of the fake Con.Yard consistently by placing it right before he moves the real one off to move/expand. Otherwise it's use is somewhat limited but I think that's mostly because France's fake structures currently is underused.

**Comment by r34ch** [comment]
I think @MustaphaTR has a point though about a base that has already been scouted. If you play against France and get a second scout off where you see a CY that has moved a few cells it's almost certainly a fake. Plus some expansions are cramped so placing the fake MCV anywhere except where the original MCV was looks wrong to most experienced players due to the build radius.

If it was possible to place a fake CY on-top of a real one (like the TS upgrade modules) and have the real one undeploy into an MCV and move out of the fake CY's cells, that could be one way to solve the issue.

**Comment by MustaphaTR** [comment]
I think fakes should be able to built around other fakes, which is not possible yet without a GivesBuildableArea: enchantment, so we can build a complete fake base. After we got fake Service Depot and PPs we now have almost all fakes.

**Comment by SoScared** [comment]
@MustaphaTR That's a fantastic Idea!

**Comment by abcdefg30** [comment]
Seems like there is no interest in this, and fakes can build off other fakes since #15091.
