### ISSUE TITLE
[RA] Official Map Pool: Alter Bombardment Islands (6 players) - aesthetics

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#11530]
[**Bombardment Islands, current**](http://resource.openra.net/maps/12868/), (6 players)

Changes:
Minor aesthetics - roads, debris, trees and ridge/shoreline fixes.

[**Bombardment Islands, altered**](http://resource.openra.net/maps/14749/), playtested multiplayer.

![bombardment islands compare](https://cloud.githubusercontent.com/assets/2715583/16358638/a80ae22e-3b19-11e6-8876-ac211368eff3.png)

![bombardment islands compare](https://cloud.githubusercontent.com/assets/2715583/16358639/addf309c-3b19-11e6-96e0-8f1e36f918c1.png)

**Comment by FrenzyTime** [comment]
Nice beginning there :) 
I think this map can be very interesting (the Heavy Bomb. version is much better in terms of eco btw !).

However, the original map is still highly unbalanced, in favor of southern island. 
Several major issues on this map : 
- the central mountain on North island prevents from building there. It should be totally removed
- also, southern shores seem to be more accessible (compare C and D spots)
- oil derricks : southern oil derricks are on 1 spot, so more easily defendable by a group of infantry
- finally, maybe expanding the limits of the map (is this possible with current Map Editor ?), so that naval maneuvers become easier, instead of having to deal with narrow water corridors ...

**Comment by SoScared** [comment]
The main issue about these map alterations is the balance between making the map more player balanced and retaining the maps' original properties. Until we have maps that outright replaces the current maps in the map pool I'm hesitent to alter the originals much beyond what the original creator made them to be. Sooner or later a map will come a long to push this map off its place but until that happens I'd like to have this map present certain standards of which map makers can size themselves against.

**Comment by FrenzyTime** [comment]
Fair enough :) I see your point of view, even though I belong to the other philosophy school, that doesn't see much of a problem in altering and modifying existing maps to make them better. As it says in its name, "OpenRA" is about open content, so why not playing with it ^_^

Just for the record, I used to hate this map, until the Heavy version showed up, making it possible to have a decent economy, and a pleasant game. Therefore, I think improving existing maps over and over is IMO a good thing, in order to keep them appealing, and alive :) 

But like I said I totally understand your stance, and yeah maybe it's even better to create new maps that are inspired from the originals, and adding new ideas to them. The Map Design Contest is a good way to do this, kudos to that :)

**Comment by SoScared** [comment]
I wouldn't stand against having maps in that produce better and more fun games. 

official:
http://resource.openra.net/maps/8257/
Istanbul Bombardment
http://resource.openra.net/maps/6804/
Heavy bombardment
http://resource.openra.net/maps/8020/

I'm unfamiliar with the different map versions of Bombardment Island but Istanbul/Heavy (virtually same map) looks to have been very popular over a long period opf time.
