### ISSUE TITLE
Debug menu: some option checkboxes blink during enabling/disabling.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#11585]
Must be a recent regression. Tested on the CNC mod.

Unaffected settings: Show A\* Cost, Show Actor Tags, and all the four options in the bottom right (Show \* Geometry and Custom Terrain). The top checkboxes and Show Unit Paths are affected.

**Comment by pchote** [comment]
I bet you tested this on a dedicated or MP server.  This happens because all the settings except the ones you mention operate via an order.  The checkbox is "checked" from the mouse-down state, then goes unchecked while the order is in flight, then rechecks once it is finally parsed.

This can be fixed by predicting the final state, like we do for pausing.

**Comment by GraionDilach** [comment]
I was testing this on skirmish. Might be I was on the fastest gamespeed though.

**Comment by PunkPun** [comment]
related #20102

**Comment by PunkPun** [comment]
This is no longer an issue
