### ISSUE TITLE
Ore truck with inaccessible destination just stops

### ISSUE THREAD

**Issue by collimation** [OpenRA/OpenRA#11615]
If an ore truck has an inaccessible destination it will stop rather than pick up other nearby ore.

**Comment by pchote** [comment]
This is intentional.  The automatic harvesting behaviour is disabled when you explicitly move or stop a harvester because players don't like it when the harvester ignores their explicit orders.  Having the move order fail is a bit of an edge case, but IMO this is still the correct behaviour.

The automatic behaviour is restored when you issue a harvest/deliver order.

**Comment by DeclanMurphyCit** [comment]
Would it be possible to get the ore truck to move towards the nearest refinery and just wait outside until it becomes available?

**Comment by WolfGaming** [comment]
Couldn't we change the move order so it moves to the closest accessible point on the map?

**Comment by reaperrr** [comment]
IIRC this was fixed in the last release, can anyone confirm @OpenRA/engine-hackers ?

**Comment by abcdefg30** [comment]
Harvesters still stop. But I would agree with @pchote here that this is expected behaviour.

**Comment by tovl** [comment]
#2309 is the real bug here. The harvester behaviour is just a consequence of that.

**Comment by tovl** [comment]
Closing as a duplicate of #2309.
