### ISSUE TITLE
Subtraction of two CPos values returns error

### ISSUE THREAD

**Issue by lovalmidas** [OpenRA/OpenRA#11667]
Attempting to perform a subtraction of two CPos values does not give a CVec as expected.
It appears that the engine thinks it should treat it as **CPos - CVec**, which, unsurprisingly, returns an error.

Error found by performing the following calculation
`local vec = someactor.Location - someactor2.Location`

Error message (first line)
 ===============
C:\Program Files (x86)\OpenRA\/lua/sandbox.lua:150: [string "BindingSupport.lua"]:30: Uncaught CLR exception at Lua->CLR boundary: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Eluant.LuaException: [string "BindingSupport.lua"]:30: **Attempted to call CPos.Subtract(CPos, CVec) with invalid arguments (CPos, CPos)**

**Comment by GraionDilach** [comment]
I don't understand Lua well, but shouldn't that operation look something like `CVec.New(A.X-B.X, A.Y-B.Y)` with A and B being CPoses?

**Comment by pchote** [comment]
We support math operations on those types, we just overlooked that specific case in the Lua bridge.  It works fine on the C# side.

**Comment by Phrohdoh** [comment]
From a scripter standpoint this should be invoking [-(CPos, CPos)](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/CPos.cs#L31) but instead [-(CPos, CVec)](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/CPos.cs#L30) is being called.

Due to [the Subtract method](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/CPos.cs#L83) explicitly doing `CPos - CVec` the arguments must be that also.

So you'll have to use what @GraionDilach suggested, unfortunately.

**Comment by pchote** [comment]
@Phrohdoh as a temporary workaround, sure.  We should fix this properly on our end.

**Comment by lovalmidas** [comment]
You can perform individual operations on .X and .Y, as what Graion suggested, that works (I tried that about an hour after posting this error, but thanks on the heads-up). Knowing this requires one to read the declarations on CPos.cs to know the variables to use (.X and .Y are not on wiki).
