### ISSUE TITLE
Lint warning to detect unused actors in a map rule definition

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#11695]
Cleanup for cases like https://github.com/OpenRA/OpenRA/pull/11316#discussion_r71973766.

**Comment by pchote** [comment]
I doubt this is worth the non-trivial effort to implement and maintain.  You'd need to compare the default vs map rules to identify the newly defined actors (this is the easy bit), and then make sure that these new actors can't ever be built or otherwise created by the game world (harder, but doable) or lua scripts (not currently possible).

**Comment by Mailaender** [comment]
Oh, yes this is probably overkill.
