### ISSUE TITLE
Forcing Concrete - option

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#11718]
![concreteslab](https://cloud.githubusercontent.com/assets/9139965/17137100/9add4d2a-5339-11e6-85c1-ea20362de197.jpg)

Concrete is a very important element of the dune-games ... as it (along with the deserts and building-islands) makes a huge portion of the difference between other rts-games like Tiberian Dawn and Red Alert ...  

while i was playing the new dune2-mod that's in development for OpenRA ... i realized that building concrete is putting you in disadvantage to a enemy that is not building concrete at all ... you can notice that when playing against the AI

part of me also thinks that this is a very aesthetic feature ... and i "hate" being forced to avoid using it in competitive games

so what the players are allowed , is to completely avoid a main-feature of dune-games ... and get an advantage out of it , by getting a boost for the economy and production in return ... which ultimately will lead to victory over a player that is carefully placing one concrete after another 

so my idea is ... that we add an option ... (off on default) ... to force people to build concrete .. otherwise they cant place buildings on the ground

this would put all players on the same starting-conditions without having them avoid a "main-aspect" of the dune-games ... and further more this could actually help defusing the early (and fast) trike/raider rushes ... as everyone should be able (in theory) to have the same amount of time  to produce counter - units

i discussed that already with @x-a-n-a-x and @MustaphaTR ... here : http://logs.openra.net/?year=2016&month=07&day=25#08:55:38

i would be actually interested especially on the opinion of @Nyerguds on this issue 

also @SoScared and @TheRaffy should add their mustard on this matter , as this option would effect both d2k and d2

**Comment by GraionDilach** [comment]
This would be an example case of #9422.

**Comment by MustaphaTR** [comment]
I think we should have 3 cases(dropdown menu?) here. Instead of on-off. Normal, Forced and Disabled. Some people may want it play without concrete but no damage, like before we added them to ORA. Just saying my opinion, i'm not one ıf them.

**Comment by Micr0Bit** [comment]
i also think that this option could help making d2k more attractive for tournaments

**Comment by Nyerguds** [comment]
I've always faithfully built my concrete in Dune II, but that was also due to the fact repairs on buildings cost insanely more than the concrete under them. Not to mention, structures without concrete decayed faster in Dune II.

Though not using concrete probably gives advantages even there. I heard of Dune II players who simply played that way; never repairing anything beyond 50% (since decay only goes down to half), and never bothering with power, radar or concrete beyond their use as tech tree requirements. Apparently, it wasn't all that more difficult.

Of course, that's all single play. I'm not really much of a multiplayer guy. but I know if I'd play Dune II in multiplay I'd probably still build my concrete, so an option forcing that to remove the advantage of people not using it seems like a nice thing.

**Comment by CH4Code** [comment]
I had an Idea about this some time ago: 
In Dune2k make **all buildings scale their efficiency with their health**, not only powerplants. This way you soft-force concrete but allow skips for special strategies.
This would be a suggestion:
- production: barracks, lt.factory,heavy factory,High-tech-factory, conyard: lower production speed.
- outpost: make radar flicker in a damage dependent interval.
- refineries: slower unloading of harvesters.
- ixlab: ???
- starport: lower production speed/limit units brought in/increase timer.
- palace: increase special powers cooldown.
- repair pad: repair slower.

**Comment by pchote** [comment]
Wanting to force concrete is just an excuse for not wanting to balance the game, IMO.

Concrete effectively doubles the health of structures.  If this really has no impact on real games, then it means that either the meta is immature (players don't take advantage of this weakness), or that balance is completely broken (and forcing concrete won't fix this).

**Comment by Micr0Bit** [comment]
pchote : its more then just about balance ... as i already said ... its also an aesthetic thing , because placed buildings with their bibs hanging down from the slabs ... or just completely without slabs under it look fucking ugly as shit 

it would be actually pretty stupid to let "slabs" influence the unit-balance ... my idea here is just to give everyone an equal start "as option" without any shenanigans

**Comment by AoAGeneral** [comment]
Nyerguds is right actually with the exception of power.

In multiplayer games building without concrete is an advantage thing right now with the exception of building concrete just for power plants only. Building them for the power gives you 100% full power rather then the 50% due to half damage.

**Comment by Micr0Bit** [comment]
@AoAGeneral : there was all kinds of interesting bugs ... for example "units facing south deal more damage" is also pretty interesting ... 
https://forum.dune2k.com/topic/26868-dune-ii-micro-is-balanced/

**Comment by Nyerguds** [comment]
@AoAGeneral  That was actually the same guy on both of these. He never bothered with keeping the power up either, since it just meant constantly having to repair power plants. Do remember, Dune II has a minimap even without building a comm center, and the comm center does not serve as prerequisite for anything. So simply not building it means you got the limited buildings-only minimap.

**Comment by StexoO** [comment]
Tournament players don't build concrete (except under power plants) because it costs time.
Thus you could have a production queue dedicated to concrete slabs :
- No build time difference between a "concrete player" and a "no concrete player".
- The concrete player has a "better defense" but the no concrete one has more units (no money loss due to concrete slabs).

**Comment by AoAGeneral** [comment]
@Nyerguds His units would be building extremely slow with low power and you would have to build extra power plants just to keep up with power. Which costs a lot of time. Using concrete slabs for power increases max power and don't need as many power plants which saves a lot of time and keeps your units building faster without low power penaltys. 

Everything else as StexoO is quite true and I do this myself. Example of a tournament video: https://www.youtube.com/watch?v=mnBV1ylgBGo

**Comment by SoScared** [comment]
@Stexo0 @Micr0Bit Placing slabs (and defensive structures) into a seperate tab was the basis of Marn's custom D2K mod and has been tested extensively. If you're looking for a way to get slabs more involved, this would be a great way to go. These slabs would also allow units to move faster.

**Comment by MustaphaTR** [comment]
> These slabs would also allow units to move faster.
:+1: 

About moving them to own tab. This indeed speeds stuff up but i'm not sure if i really wanna see them in own tab.

**Comment by Nyerguds** [comment]
@AoAGeneral I said I was talking about Dune II... where power affects nothing except radar. Probably not even decay speed. Not that that even matters in the case I mentioned, since decay only goes down to 50%.

**Comment by Micr0Bit** [comment]
isnt that already in ? a speedbonus on slabs ? i think even dune 2 had a speedbonus on slabs ... 
anyway , this is a double-edged sword though ... as it makes your enemys units also faster ... on your own slabs

im not sure about a 2nd tab "just?" for the concrete slabs ... still think my idea of adding a mode where concrete is a requirement in order to place buildings is better ... as it would force sort of like a civilized setup therefor could lead to more quality-games

**Comment by Nyerguds** [comment]
@Micr0Bit  It certainly is in Dune II.

[Rock]
Moving speed: Foot      = 112/256 (43%)
Moving speed: Tracked   = 160/256 (62%)
Moving speed: Harvester = 160/256 (62%)
Moving speed: Wheeled   = 112/256 (43%)

[Concrete]
Moving speed: Foot      = 255/256 (99%)
Moving speed: Tracked   = 255/256 (99%)
Moving speed: Harvester = 255/256 (99%)
Moving speed: Wheeled   = 255/256 (99%)

(from http://nyerguds.arsaneus-design.com/dune/dune2rules/rules-1.07-HS.ini )

**Comment by Micr0Bit** [comment]
@Nyerguds : so its actually not a bonus that you get on concrete (because on concrete . units use their (almost)full speed-capability but not more) ... its rather more a speed-penalty that you get , for not using concrete ...

**Comment by Nyerguds** [comment]
@Micr0Bit Well, all modifiers in C&C work like that, and not just movement speed. Armour on weapons is exactly the same. Bare value is 100%, actual damage per armour type is a fraction of that.

As for the rules... thank Olaf, he originally requested that my Dune II editor be able to dump them. The rule dumps of the other Dune II versions are [in the same folder](http://nyerguds.arsaneus-design.com/dune/dune2rules/).

**Comment by TheRaffy** [comment]
Don't forget the weight of one slab has to be 1,469 kg according to the manual.

**Comment by SoScared** [comment]
@Micr0Bit Not just a slabs tab. The slabs go into a defensive tab which also alleviates the current monolithic build tab.

That setup created options in-game and allowed players to stretch for different strategies - e.g. agressive players would slab their power plants, defensive players would slab the majority of their base structures, have some slab pathways and have time to ready up defensive structures.

**Comment by Micr0Bit** [comment]
@SoScared : i can see that this could help some balance-issues ... and it actually sounds pretty good having the slabs in the defense tab ... but theres still the aesthetic that gets lost in dune-games ... when people just ignore slabs ...

and still ... buildings slabs does cost money ... and it does cost time (even in the defense tab)

**Comment by AoAGeneral** [comment]
Is it possible to have buildings produce units and vehicles 1 second faster? You can do this to have them on slabs. Production factories/barracks on slabs build units 1 second faster. For technology buildings researches take less time on slabs.

**Comment by CH4Code** [comment]
@soscared: I'm not sure a defense tab would be beneficial.

 why? It would be just like in RA or TD, have defenses ready to pop up in front of attacking troops. The game dynamics would assimilate towards RA and TD. No one needs a second TD or RA. D2k needs its own identity. One way would be keeping defenses in the main tab, so that you need to palce defenses beforehand. This adds to the "big bustling base" feel of D2k.

**Comment by Micr0Bit** [comment]
i agree with @CH4Code ... and we will keep sure it stays that way in dune2 

it actually slows down the pace of base-building having support-structures and structures/production-buildings in one tab ... and this indeed adds to "being different" from other mods 

place defense-structures "before" the enemy arrives is also a good thing ...

**Comment by Nyerguds** [comment]
@Micr0Bit What I'd really like to see is for OpenRA to be able to read the original mission scripts, but as far as I've seen there's no motivation whatsoever in the OpenRA team to implement such a thing..

**Comment by TheRaffy** [comment]
Hey, I thought about it, and agree the opinions of Ch4Code and Pchote. A concrete option is no sollution to the true problem.  **There need to bee a significant benefit of building concrete besides the aesthetic one.** 

The concrete game mechanic adds alot variation to the build orders. "easy to learn hard to master" sounds kinda silly here. But concrete slabs are increasing the complexity of buildorders extremly.
And a hell breaks loose when I place them accidently on the wrong cell. (missclick, canceling all pre orderd stuff) And then there are these shitty d2k structure shapes (refinery and hightech factory). That have that 1 annoying cell on the north side. I rly hate this structure shape and see them as one game design mistakes in d2k... anoying!

Ok, now try to view concrete like a techlevel setting. You know, like: playing RA without nukes or with infantry only. Such settings are cool and are adding variation, but they are rarely used. 
A concrete option, is like cutting the techtree from the bottom side. It's a nice to have, that might end up beeing used as rarely as techlevel settings. 

But a "concrete slab tech" option would lower the entrance barrier.
It would be like: "starting with a small base" , or "a small unit force". Trying to cut away the boring starting game parts. But here again, the default settings piced by players are close to always to "no extra starting units". That's not just because its the default. It's due to giving rushes more potential. 
So, in other words cutting the concrete slab tech would also cut away some game play variance, especially in the early game stages. 

Concrete slabs are unique to the dune feeling and should be the default in my opinion. 

But, I totally understand that concrete slabs are super annoying, need extra time & clicks and are odd to the used game flow of other mods. That's why I'd like to suggest an also mostly known middle way.

Imagine concrete slabs that spawns automatically some cells arround the constuction yards.
If you are running out of tha automatically build concrete space, you will have to eighter expand manually, or build another yard. This whole mechanic, could also be a technology that you could be researched at the conyard, like bigger c. slabs.
It's close to Zerg creap and also could get used by the AI.

Btw. it's also a feature of "dune2 the golden path", that i enjoyed alot.

**Comment by Nyerguds** [comment]
@TheRaffy Very good point on the irregular shapes... that's a problem Dune II never really had. All its buildings are square, at least.

**Comment by MurtoTheRay** [comment]
Did anyone else play Marn's version of D2K? He put slabs into the defence tab and they were instantly more popular.

**Comment by MustaphaTR** [comment]
I'm not sure if it is really better to move concrete. In my YR mod, there are Concretes in D2K tileset maps(doesn't really do anything but i still build) and it takes too much to go defence-build concrete-back to buildings-build building. Maybe just because i'm not using keyboard shortcuts not sure.

**Comment by GraionDilach** [comment]
@Nyerguds Don't get me wrong, but reading the original mission/map formats would be quite hackish IMO (due to the different structure). A Lua code generator could be a solution but that's quite complex itself as well.

**Comment by pchote** [comment]
A related but I guess opposite idea that would now be very easy to implement (see #14363) is a lobby option to automatically place concrete under all structures, not just MCVs.

**Comment by Micr0Bit** [comment]
>A related but I guess opposite idea that would now be very easy to implement (see #14363) is a lobby option to automatically place concrete under all structures, not just MCVs.

for free ? does that mean the actually buildtime of the buildtime of the building would be raised ?

**Comment by abcdefg30** [comment]
> A related but I guess opposite idea that would now be very easy to implement (see #14363) is a lobby option to automatically place concrete under all structures, not just MCVs.

This was done in #18562. I don't think it makes sense to keep this issue open now. (Since not having concrete can now easily be nerfed even more, making an option to force concrete obsolete.)
