### ISSUE TITLE
[RA] Add features to the Engineer.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#11749]
It feels like there's more potential to the Engineer. As of now the unit is more or less discarded after the first minutes of a game. This could also serve as an extended olive branch to players wanting to have the unit used as a production queue killer as it gives the unit a purpose after it has finished capturing oil derrics: http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&p=297153#297153

Allow the Engineer to detect, walk over and disassemble mines: So what if you could a-move the Engineer, triggering it to disassemble mines along its' path, perhaps with a detection range of say, 3?

Allow the Engineer to gradually repair structures: CTRL+Right Click a structure, start repairing. Slowly.

**Comment by r34ch** [comment]
+1 for the engie mine detection and disable.

I like the gradual (free) repair of structures idea but it would make more sense for the in-game logic to match the medic/mechanic in that any building in a nearby radius is repaired rather than modifying an existing core repair mechanic (i.e. forget to Ctrl, loose the engi completely..)

**Comment by GraionDilach** [comment]
Medic and mechanic both uses a weapon to fix nearby damaged actors. (Although providing a healaura is also possible, it's not used in any shipped mods.)

**Comment by pchote** [comment]
C&C3 (and RA3?) let engineers recover husks, and we copied this over to the engineers in our TD. Of course, RA has the mechanic, which messes up this otherwise obvious use for engineers there.

**Comment by whi7ed3vil** [comment]
I'd just love for the ability to stop my units from destroying a building currently being captured by an engie. Only solution now is to move them out of range. Probably shoud split this to a new topic ...

**Comment by Smittytron** [comment]
Allow the engineer to C4 a concrete wall, destroying a 3 or 5 cell radius of wall. Would it be used that often? No. Would it look awesome when someone uses it successfully? Heck yes.

**Comment by SoScared** [comment]
@Smittytron Intriguing! Tho 5 cell radius sounds like a lot,

**Comment by Smittytron** [comment]
I view the engineer as a utility unit as opposed to a support unit. Something that does things across the battlefield but has no role in pitched combat like a medic or mechanic.
Here is my wishlist of engineer abilities:
- Combat Engineer: Engineers can C4 concrete walls and sandbags, destroying a 3x3 radius. (using Tanya’s C4 cursor)
- Wire Cutters: Engineers can instantly remove one cell of adjacent wire fencing. (Play fence being run over sound)
- Salvager: Engineers can salvage husks for 40% (spitballing) of the destroyed vehicle’s value. This uses the dollar-sign sell cursor when placed over a husk while an engineer is selected. The husk disappears after it is salvaged and the player is rewarded the credits. (Perhaps go with a quick capture bar instead of making salvage instant)
- Engineers can detect (3 cells) and disarm landmines from an adjacent cell.

**Comment by 3Lucian** [comment]
if you allow an engineer to C4 walls, Tanya should also be allowed to c4 walls, given she also has C4. 3x3 would be the radius to use.

**Comment by SoScared** [comment]
Seem like the engineer discussion has more or less evaporated, plus with the incoming newly added civilian structures the engineer will have additional roles to fill. If people have a specific ides on adding features to the engineer they could start up a separate issue.
