### ISSUE TITLE
Minelayers can't get a group order

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#11763]
Currently, if you select a group of minelayers, and want them to place the same minefield, only one minelayer will follow the order. 
You have to repeat the order for each minelayer.
![openra-2016-08-03t180618z](https://cloud.githubusercontent.com/assets/20139967/17376442/dd4c2050-59b5-11e6-9a21-8efd36298d77.png)

**Comment by CH4Code** [comment]
Didnt even know you could order a minefield with ctrl+mousebutton! great!

**Comment by WolfGaming** [comment]
We are replacing the OrderManager with a MinefieldOrderGenerator that takes the actor as a parameter, I guess we are replacing the OrderManager for every MineLayer and only the last one is kept since only the one actor, could be fixed by checking if the current OrderManager is a MinefieldOrderGenerator we add the actor to that OrderManager,

Or we do something more elegant but thats the idea that came off the top of my head.

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/0cfb96d35e0f3c3ba661f8edf51b14856d70a7d5...d82b8bd89eccc9165d6db9c551af310149cca29a)
