### ISSUE TITLE
Improve support for features needed by external mods

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#11813]
In the past, certain features and changes were submitted which were needed for 3rd-party mods, but not really necessary for any of the shipping/WIP 1st-party mods, sometimes leading to discussions over whether to accept them or not (due to regression concerns or lack of usefulness for the shipping mods), in some cases leading to their rejection.

While understandable, one of the results has been that currently, a couple of modders - myself included - ship their own modified versions of `Common` traits or activities and effects, and/or rarely submit new features or changes upstream because the reviewing process, upgrade rules, solving of regression concerns and overall code 'perfection' required to get those changes accepted into bleed - in some cases in addition to their lack of value for the official mods - is simply way too time-consuming compared to simply shipping them in their own dll.

This approach sort of works, but it also means that a lot of features and changes that could be useful for more than just 1 or 2 modders never get submitted to upstream.
Additionally, there are cases (in my mods, at least) where even a 3rd-party dll currently doesn't help implementing a wanted feature, because that feature would require direct modifications to `Common` code (because certain pieces of `Common` code currently aren't overridable) and sometimes complex upgrade rules as well, blocking features even in external mods.

A possible solution to improve the situation could look like this:
1. As far as possible, make `Common` features that 3rd-party mods might want to modify overridable if they aren't already, so direct modifications of `Common` become unnecessary most of the time
2. Introduce an additional `Unsupported` mod dll to OpenRA, where features not needed by TS and the shipping mods, but potentially useful for several external mods, can be added more easily

This new `Unsupported` dll would not be used by any of the official mods, with 'unsupported' meaning
- features or default values can be changed, renamed or removed without repercussions or the need for upgrade rules if there's a solid reason (modders that use any of these features should be aware of its 'beta' and DIY nature)
- generally more lenience when accepting new features to this dll (still requiring +2, adherance to StyleCop and no unresolved issues if possible, but not requiring upgrade rules or completely hack-free code)
- could also be used as proving ground for features deemed potentially useful to the shipping mods, but too risky to accept into `Common` as-is
- if a feature has been tested enough and is considered useful and 'safe', it could be moved down to `Common` later

Ultimately, the idea is to 
- lower the hurdle for less experienced external contributors to get their features merged
- increase the pace and probability of new features being merged in general
- increase sharing of work and ideas between makers of external mods, reducing the _"everyone cooking their own soup"_ effect
- avoid regressions in the first-party mods without rejecting/blocking features for or in external mods

**Comment by GraionDilach** [comment]
I'd say consider the possibility to change everything with private access to protected instead. That would allow downstream direct modifications to Common code without actual direct modifications in Common code.

It was just yesterday when I wanted to make a `RefineryRA2` trait to implement the Ore Purifier (without dwelving into the IMO-still messy plans of multiple resources) by simply overriding `Refinery.GiveResource` but turned out that I can't do that without copying the whole trait because `Refinery.currentDisplayValue` is a private variable and I'd lose the refinery ticks if I can't update that one.

I'm not against this but I don't think this is a good solution to the problem either.

**Comment by GraionDilach** [comment]
Another thing to consider, that we are quite low on reviewers already, and this Unsupported dll would just make that issue worse. I mean, I have a PR in the queue since May which I'm constantly updating but it didn't got even a single :+1: by now - and my frustration comes that I did everything to fix my local issue yet I can't fix it for close three months now because there are no reviewers on it.

**Comment by WolfGaming** [comment]
I think this is a great idea, but one of the main points about it is that it would introduce a lot of new PRs which is good because hey more coding but bad since we don't have a lot of reviewers.

Also to the first point @GraionDilach made is that we have to be careful to not expose variables that won't are overrideable, what I mean by this lets say we have a variable called X, we set X in method Y and then the modder used it in method Z, all is good there. However what if the modder overrode method Y, suddenly the variable X doesn't serve its purpose anymore.

**Comment by pchote** [comment]
In the long term, I'd really like to see us discard the "Common" part of Mods.Common, and require all mods to ship *all* of their own mod code.  We would, of course, maintain a set of standard logic (possibly in its own repository, and certainly split into multiple smaller dlls), but all mods (including our default ones) would ship their own versions of that logic.

We could then unbundle our core mods from the engine, and update them independently.  We would still merge changes upstream into the common mod code, but this would only affect other mods when they explicitly choose to pull down the newer mod logic.  This will make testing common-logic changes for regressions much more difficult, but new tooling could make this a bit less painful.

There is one big problem here: .NET doesn't support unloading assemblies.  When a mod imports a dll all those objects are imported into the program space and remain there until the game quits, even if you switch to another mod.  This is why it is so important that mods reference dlls instead of copying them, and why you must rename traits when you copy and modify them in downstream dlls – if you don't they will conflict and cause some really weird bugs that depend on the order that you load and switch between mods.

I remember reading about a plan to include support for unloading assemblies in a future version of .NET Core, but in the best case it would be many years before we could rely on that logic being available everywhere that we support.

The only way we could do this then is to force an engine restart when switching mods.  We would still support direct switching between mods ingame, but the game window would be closed and reopened which can be jarring for players (especially on OSX and other platforms where "fullscreen" windows exist in their own space with animations transitioning to and from them).

**Comment by pchote** [comment]
If we go the separate dlls + engine restart route then we could install different engine versions side by side into the main install dir to provide backwards compatibility for external mods.  The main difficulty would come from needing to freeze our web interfaces so that we didn't break game list / resource center / etc lookups for older versions.

**Comment by GraionDilach** [comment]
It also requres some refactoring in TraitsInterfaces.

**Comment by WolfGaming** [comment]
I give my thumbs up to separate dlls + engine restart, question though can we minimize the restarts by checking if it requires the same version or would that be too much work?

**Comment by reaperrr** [comment]
> It also requres some refactoring in TraitsInterfaces - Game has a lot of Common's.

I believe a good chunk of that could already be moved to `Common` without even having to make any other changes (except for updating some usings, probably).

**Comment by pchote** [comment]
I filed #12188 as a refinement of point 2 above.

**Comment by pchote** [comment]
Superseded by #12188 and #12554.
