### ISSUE TITLE
(Bleed) Screen-grab scrolling (Standard) with Right Mouse Button executes orders when units are selected.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#11849]
Happens every time RMB is released when scrolling.

#11148 #9399

**Comment by Mailaender** [comment]
Isn't that just a misconfiguration on your side?

**Comment by SoScared** [comment]
I wouldn't know about it being a misconfiguration. RMB scrolling has been merged in the bleed has it not? Regardless MMB scrolling is horrible for a wide range of mouses and up until now RMB scrolling has been reserved for TS style scrolling - which is equally horrible imo :)

**Comment by Mailaender** [comment]
I thought right mouse button scrolling was created for use in conjunction with left-click orders.

**Comment by SoScared** [comment]
Oh god I hope that's not the case.

**Comment by pchote** [comment]
It isn't.  The two links you posted in the initial description explain that.

**Comment by Sininini** [comment]
Can confirm, but it only happens if you keep holding down RMB after stopping scrolling with it. Like this: press RMB > move mouse in direction > move mouse  back so camera stops > release RMB.
  I assume most people use RMB scroll like this: press RMB > move mouse in direction > release RMB > repeat. This bug doesn't affect those people.

**Comment by Sininini** [comment]
@SoScared Oh, apologizes, I thought RMB "joystick" scrolling technique like that would be super weird but now it makes sense with clarification.

Standard scrolling with RMB reproduces that bug every time on my end.

**Comment by SoScared** [comment]
No apopgies needed. Issue title was unclear.
