### ISSUE TITLE
Feature request: OpenRA Utility needs a user interface

### ISSUE THREAD

**Issue by Aquilar** [OpenRA/OpenRA#11921]
The utility desperately needs it's own user interface since command line isn't terribly intuitive to most users and can easily screw up with very little feedback as to why it didn't work. 
People that want to create content for OpenRA should not need to go through this.

**Comment by pchote** [comment]
Sorry, but this isn't going to happen.  It is completely infeasible for two reasons:

1.  There are no suitable cross-platform GUI toolkits we could use. Winforms and WPF only work reliably under windows, and we are not going to force everyone to install GTK just so that a few windows users don't have to go outside their comfort zone.

2.  The utility is not a single static program.  It is a thin dynamic frontend that aggregates disjoint command modules implemented in mod code.  Each command would have to implement its own GUI, which would be a prohibative amount of effort even if it were possible.

**Comment by Aquilar** [comment]
Then a better idea to avoid all that effort is to bundle utility and it's modules into a separate program independent of the game and give that a GUI instead? Then you can make it specific to the OS' of your choosing.

**Comment by pchote** [comment]
If the modding community wants to make its own windows-specific GUI for certain utility commands, then it is of course free to do so as an external project.
