### ISSUE TITLE
Add a localization project for OpenRA

### ISSUE THREAD

**Issue by tytannial** [OpenRA/OpenRA#11935]
Why not add a new project that collects localization text for future use. Maybe it is no use for now but once needed it should be very useful.

**Comment by pchote** [comment]
The overall translation project is currently dead in the water because there's no developer interest in finishing the prerequisite engine features.

Collecting translations now would premature because there is no timeline for them being needed, and our strings (particularly in the UI) change fast enough that many of them would be outdated before they would be used.

**Comment by MustaphaTR** [comment]
When we are in it i should say, after prerequistes of translations is added we should open a Crowdin page for OpenRA. It is free for Open Source projects.

https://crowdin.com/

**Comment by tytannial** [comment]
hum...If I have time I will translate it to Chinese. Because ra1,cnc1,cnc2 and dune2000, their engine are not support CJK character.

**Comment by pchote** [comment]
Please note that we won't be able to accept any translated strings until after the tasks in #10475 are completed.

**Comment by tytannial** [comment]
Always glad to help, if needed.

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/issues/10475#issuecomment-249404159
