### ISSUE TITLE
[TS] Allow Gate placing on walls (as like in originals)

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#12088]
In the vanilla TS it was able to place gates on walls which replaced the Wall sections which are covered by gates as like the component tower...

**Comment by fruestueck** [comment]
I would like to try to implement this functionality. Therefore i think, it would be easyer to start implementing GDI Guard Towers (size 1x1) to be build on Walls and later figure out how to handle Gates (size 4x1).

Due to beeing new to openra development i will try to explain my approach and am happy for any advice how to do it right.

- First, i'd add a Trait called e.g. 'ReplacesWall'
  - Add Trait 'ReplacesWall' to 'mods\ts\rules\gdi-support.yaml' in 'GACTWR' (gdi guard tower base)

Next step would be to allow placing of guard tower not only on empty buildable are, but also on are already occupied by a wall. This seems to be handled in 'OpenRA.Mods.Common\Traits\Buildings\BuildingUtils.cs' in 'isCellBuildable' but i do not think it would be right to change modify that script for one special function. Would be better to adapt this function in a specific script.

- Create cs script in 'OpenRA.Mods.Common\Traits\Buildings\ReplacesWall.cs'
or should it be added to / handeld in 
- 'OpenRA.Mods.Common\Traits\Buildings\Buildings.cs'?

Don't know exactly how to approach this in a good way and am happy for advice. I hope i could add this feature, if not at least i'd learn more about the openra structure. Still hopfully it'll work : )

**Comment by GraionDilach** [comment]
I'd take a different approach, which would fix a technicality bug along.

There are terrain layers in OpenRA, with the resource layer being the most well known one (there's also D2k concrete though). What I'd go with is that actors with foundation could also very well define such a terrain layer with a terrain type and then the building placement logic could also take all these layers in effect when placing the building.

This'd even allow reciprocating the Warcraft 3 undead blight logic as well via using a resource.

**Comment by MunWolf** [comment]
@GraionDilach idea along with a sell on placement trait (or something similar) would create this functionality, aka limiting the sell to a terrain layer (though a similar thing could be achieved by defining actors that it can sell)

**Comment by fruestueck** [comment]
@GraionDilach simplyfied, you mean to give walls there own terrain layer?

I won't be able to make that. Simply due to the fact that i am still a beginner with openra dev (at best ; )

**Comment by pchote** [comment]
I suggest familiarizing yourself with how the plug placement code works.  You could generalize or copy this to support actor replacement.
