### ISSUE TITLE
Show Trees on map previews (lobby) like on minimap (radar)

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/OpenRA#12097]
Hey, 
I noticed that map previews doesn't show trees comepared to the minimap.
Imagine missing informations on a map with alot negativ space, like a wooden maze. 

This could be an easy fix, because it's already coded. But not used for the minimap previews.

Thanks!
![screenshot 2016-09-24 18 00 08](https://cloud.githubusercontent.com/assets/5147014/18809622/253a12ca-8281-11e6-8324-177229e31bfc.png)

**Comment by pchote** [comment]
The reason for this is that until recently the map previews were generated dynamically without having access to any of the actors on the map.  We now generate the previews when saving the map from the editor, where we have that data, so this shouldn't be too hard to fix.

**Comment by antoniomdk** [comment]
I'd like to work on this. It's my first task. What classes should I check? Thanks!

**Comment by abc013** [comment]
Hi @antoniomdk,
first of all, the change should be added [here](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Map/Map.cs#L634). You'll need a new Trait for it (which *must* be in `OpenRA.Game`) to check which actors should be drawn as well as which color should be used. One problem is that you have to get the footprint of the actor (in order to draw the size of it on the map, not just a point), which could be solved by moving `Footprint` to `OpenRA.Game`.
Note that this would be my way to draw actors on the map preview and it is probably not entirely correct :).

**Comment by GraionDilach** [comment]
Another option would be to create an interface in the Game namespace implemented by a (strictly-editor?) trait in Mods.Common which would cache the cell content into a layer for rendering.

**Comment by pchote** [comment]
We already have that in a sense for the map editor.  The most sensible option would be to refactor that code to work more generally -- it doesn't necessarily need to live in the Game namespace, and ideally shouldn't.

**Comment by antoniomdk** [comment]
Ok, I'm going to understand how traits and traitinfo really work. Then, I will start to create the trait mentioned by @abc013

**Comment by abcdefg30** [comment]
This is fixed on bleed.
