### ISSUE TITLE
OpenRA-bleed 1993ee25b877992f7a54088fdf37f49d09743711 - Exception of type `System.InvalidOperationException`: Out of sync

### ISSUE THREAD

**Issue by Cilyena** [OpenRA/OpenRA#12091]
SHA 1993ee25b877992f7a54088fdf37f49d09743711 
https://github.com/OpenRA/OpenRA/tree/1993ee25b877992f7a54088fdf37f49d09743711

**Exception of type System.InvalidOperationException: Out of sync** inside exception.log

**Players and host :**
**Slide :** host and player
**RedWolf + bombe + Celebrimbore :** Players

Files (exception + syncreport + replay) :
[bombe.zip](https://github.com/OpenRA/OpenRA/files/490573/bombe.zip)
[Slide.zip](https://github.com/OpenRA/OpenRA/files/490572/Slide.zip)
[Celebrimbore.zip](https://github.com/OpenRA/OpenRA/files/490591/Celebrimbore.zip)
[RedWolf.zip](https://github.com/OpenRA/OpenRA/files/490651/RedWolf.zip)

**Comment by Cilyena** [comment]
Updated.

**Comment by pchote** [comment]
SharedRandom is the only difference between players.

My gut feeling points towards https://github.com/OpenRA/OpenRA/pull/11207/files#diff-288b404a7eb1501ffc0c6919729361a3R145

**Comment by pchote** [comment]
Thanks for the excellent bug report by the way.  I wish all our desync reports could have this much detail!

**Comment by pchote** [comment]
Gut feeling confirmed.  This can be easily reproduced:

1.  Player A makes a crater on the ground.
2.  Player B moves a unit into range to reveal it, and then away so that it is hidden under the fog.
3.  Player A places a building over the crater to clear it.
4.  Player A sells the building.
5.  Player A shoots the same cell again to make a new crater.
