### ISSUE TITLE
Can't single-select aircraft that is on top a blob of ground-units

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#12118]
release-20160508

i also cant force-fire on aircraft that is on top of a blob (with AA for example)

doesnt matter if the units are infantry or vehicles ... you cant cherry-pick the aircraft when its on top of groundunits ...migh work when you hotkey-grouped the aircrafts before , but only that way ... 

![cherry2](https://cloud.githubusercontent.com/assets/9139965/18872581/760b736a-84bb-11e6-9dc9-259ce1ff332f.png)

![cherry](https://cloud.githubusercontent.com/assets/9139965/18872592/801b2e22-84bb-11e6-9bac-ffc8cd93f02e.png)

**Comment by matjaeck** [comment]
This is fixed in playtest-20190106. Force-fire-targeting the helicopter works in these situations, too.
![2](https://user-images.githubusercontent.com/37185497/51631908-48c08f00-1f4e-11e9-8dcc-93c33b9e5998.jpg)
![1](https://user-images.githubusercontent.com/37185497/51631910-48c08f00-1f4e-11e9-90ac-a82aa230be9e.jpg)

(Mouse cursor got hidden from screenshot)
