### ISSUE TITLE
Why not include mono inside the OSX app?

### ISSUE THREAD

**Issue by JoshuaPettus** [OpenRA/OpenRA#12170]
As a mac user and dev, I strongly believe you should take advantage of the OSX app system and include ALL necessary libraries inside your release app bundles, including mono.  Apps like Gnomoria have done it just fine, why not OpenRA as well?   Just looking at Gnomoria the libraries involved are probably only a few extra mb and is far, far better then having to give our whole system mono just for the one app.  Have you guys looked into it?  Is there a reason it must be a separate download?

**Comment by pchote** [comment]
We actually used to do this, many years and mono versions ago.

Back then mono's bundling tools didn't work properly on OSX, so I wrote an abomination that recursively copied and patched the libraries we needed to run OpenRA ([link for the curious](https://github.com/OpenRA/OpenRA/blob/4c8575b1f53d5bff8b2e92e905dfe2f982f8c9f3/packaging/osx/package.sh)).

We threw that away at some point because 1) it was horrible, 2) it was hard to justify an OSX-specific packaging step when we were able to automate the rest of our packaging on a Linux box, and 3) it added ~15 MB to our installer download, which was a big deal back when the entire rest of the game was only 2MB and hosted off a single server with limited bandwidth.

None of these reasons are relevant now of course, but I haven't been in any rush to revisit those experiences :wink:

We eventually moved back to a native-code OSX launcher, which lives in its own repository: http://github.com/OpenRA/OpenRALauncherOSX.  In principle you just need to tweak the Makefile to link against and package a local mono framework.  Would you be interested in taking a shot at this?

**Comment by JoshuaPettus** [comment]
Very interesting, looking at your OpenRALauncher makefile is libgdiplus.dylib all that is required of the whole Mono.framework?  surely that alone can be bundled.  I've used a tool called dylibbundler which would  copy all the linked dylibs to the executable to the app bundle and sort through all the dll he** re linking everything together.

**Comment by pchote** [comment]
The `libgdiplus.dylib` symlink is there to work around missing/incorrect paths defined in the mono standard library.  Life would be much simpler if that was the only dependency, but it isn't.

macdylibbundler appears to cover the native assembly rewriting (the `patch_mono` function in my old script), but we also need to change the references in the managed assembly metadata (the *.config files).

Mono's "official" procedure is to use their Xamarin.Mac framework, which then has a build task that compiles down to a .app bundle.  I haven't tested this, so it's not clear whether this uses a bundling tool that we could repurpose, or, more likely, AOT compiles everything down to native code (which we couldn't repurpose).

Resurrecting my old script is probably going to be the easiest option if we want to do this.

**Comment by pchote** [comment]
If somebody decides to pick this up then we should investigate https://github.com/mono/sysdrawing-coregraphics.  It might let us sidestep the `libgdiplus` dependency and the black-screen font-caching issues that causes.

**Comment by pchote** [comment]
https://github.com/flibitijibibo/MonoKickstart could also be useful here.

**Comment by pchote** [comment]
The `System.Drawing` dependency has been removed, so my comments above are now moot.
