### ISSUE TITLE
Change the name of a couple of units.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#12197]
(RA) Transport Helicopter -> Chinook **MERGED**

Everyone calls it a Chinook. Noone calls it a Transport Helicopter. The SHP icon says 'Chinook'.
Apparently the real Chinook came into service for the US Army 1962. C&C RA supposedly happened in the 50's (http://cnc.wikia.com/wiki/Red_Alert_universe_timeline) but whatever - it's an alternate timeline switching around a lot of stuff.
http://cnc.wikia.com/wiki/Chinook_(Red_Alert)

(TD) Rocket Launcer -> MLRS (disputed)

This was actually changed in favour of the Rocket Launcher sometime in 2014. The SHP file for the unit says Rocket Launcher so I guess thats more consistent... but the name MLRS is better. New SHP file would be needed.
http://cnc.wikia.com/wiki/Multiple_Launch_Rocket_System_(Tiberian_Dawn)

(TD) Mobile S.A.M. -> Mobile SAM

Looks better imo and consistent with other units with abbreviations. New SHP file would be needed.

**EDIT**:

Some honorable mentions:

(RA) Shipyard -> Naval Yard #5992 **MERGED**

(RA) M.A.D. Tank -> MAD Tank (SHP icon)

(RA) Medics -> Field Medics

(RA) HIND -> Cobra

**Comment by pchote** [comment]
Transport Helicopter -> Chinook makes sense because it matches the original game.
Mobile S.A.M. -> Mobile SAM makes sense because it matches the SAM site.

I'm not a fan of the Rocket Launcher change, this seems like a petty thing to change away from the original game.

**Comment by SoScared** [comment]
http://cnc.wikia.com/wiki/Multiple_Launch_Rocket_System_(Tiberian_Dawn)
http://strategywiki.org/wiki/Command_%26_Conquer/GDI_Units

For the most part the unit is referred to the MLRS (also evolved into TS' Hover MLRS). Seems like 'Rocket Launcher' is the name assigned in-game but I can't find references to it online.

**Comment by pchote** [comment]
![screen shot 2016-10-09 at 18 47 36](https://cloud.githubusercontent.com/assets/167819/19222464/f39c970c-8e50-11e6-9057-37ebd1991af1.png)

It is what is used ingame, so there's not really much else to say?

**Comment by SoScared** [comment]
If people in general, past ot present, relate to the unit as the MLRS, why not use it? From my viewpoint the name Rocket Launcher looks like an outdated name the Westwood crew didn't bother to change after the game came out.

**Comment by reaperrr** [comment]
I'm with @pchote on the Rocket Launcher. It's also in line with 'Medium Tank', 'Flame Tank' and so on.

**Comment by pchote** [comment]
I consider this to be a similar situation to "rocket soldiers" vs E3, but I don't think anyone would suggest we renamed those.

**Comment by SoScared** [comment]
@reaperrr: Yeah but everyone calls the units 'Medium Tank' and 'Flame Tank'.

**Comment by Biofreak1987** [comment]
What I find confusing is that the type name for the MLRS is msam and the Mobile Sam uses mlrs.
Been like that in the original td as well.

**Comment by reaperrr** [comment]
@reaperrr: Yeah but everyone calls the units 'Medium Tank' and 'Flame Tank'. They're relateable.

But you can't know for sure everyone calls the Rocket Launcher "MLRS" just because the majority does.

The other two name changes would be uncontroversial, this one wouldn't.

> What I find confusing is that the type name for the MLRS is msam and the Mobile Sam uses mlrs.
> Been like that in the original td as well.

Because that were the roles Westwood had originally intended for the respective unit/sprite (which is probably what the elevated turret of the MSAM sprite is really for). During earlier alpha stages of C&C development, what we use as 'Mobile SAM' was originally supposed to be GDI's artillery unit.

**Comment by AoAGeneral** [comment]
The original did name the unit Rocket Launcher despite what everyone called it. It was a good name to call it and even on the tongue it feels faster to say it.

However a lot of people say it wrong (Including myself) in saying MLRS because it rolls off the tongue when its actually MRLS. MRLS to me is much harder to say. So naming it the Rocket Launcher is easier to say. Perhaps people will start saying RL :dancing_men:

The tooltips are very well done and hadn't been in any need of changing in TD except for maybe two. But that depends on what the community would like. (IE: Silos and refineries)

**Comment by SoScared** [comment]
C&C Manual:
http://vignette2.wikia.nocookie.net/cnc/images/e/e9/CC-Manual.pdf/revision/latest?cb=20120617101752

@AoAGeneral: Looks like you're on the ball. The general C&C community adopted the name MLRS in favor of MRLS more or less after the Tiberian Sun's _Hover MLRS_ came about. http://vignette1.wikia.nocookie.net/cnc/images/b/be/Manual_Tiberian_Sun.pdf/revision/latest?cb=20120708192212 I
In all likelyhood the name MLRS was adopted for the reasons you mentioned plus it's easier to categorize in memory _MLRS_ with _Hover MLRS_. In light of this I think OpenRA would benefit from adopting the name MLRS. Why not move with the current.

**Comment by FrameLimiter** [comment]
Also shouldn't the MAD tank should be renamed "M.A.D. tank" to match the SHP icon. It's an acronym for Mutually Assured Destruction. I'm pretty sure the tooltip in the original read "M.A.D." instead of MAD.

**Comment by SoScared** [comment]
Seems odd why #5992 died on the vine. Naval Yard is both on the common tongue and in the original game.

I guess M.A.D. in the SHP ought to be renamed MAD if we'd follow the rule of consistency per this issue.

**Comment by AoAGeneral** [comment]
The name could adopt MLRS and im sure a lot of people will (Including myself) because of how easy it is. But the name is still incorrect.

MLRS is Multi-Launch Rocket System where as in CNC95 its Mobile Rocket Launcher System. With how the name changed im sure Westwood thought the samething in its name and went with MLRS as easy to say. Either way im sure it will be adopted. Just the names ingame may not change.

**Comment by senneschall** [comment]
I don't really play online, but I have a LAN system where we play openRA on a regular basis. This means that I meet openRA-newbies

**Comment by ChristianDK** [comment]
The hind is a Russian helicopter. Wouldn't it make sense to rename it to the name of an allied helicopter instead? I know it belonged to soviets in the original and I'm fine with it being an allied unit in Openra but renaming it would be good.

**Comment by abc013** [comment]
I found a rename issue:
In the original RA game medics aren't called "medics",
they're called "field medics".

**Comment by SoScared** [comment]
Agreed in general to the renaming of the Hind. Unfortunately there aren't really any good Allied (real life) alternative to the Hind in terms of its looks. The Hind is pretty unique. Perhaps a generic name like Attack Helicopter, Gunship etc.. C&C games are pretty consistent on using generic names for their units anyways.

**Comment by abcdefg30** [comment]
We could borrow "Apache" from TD. (Although there was no Apache back in the 50s.)

**Comment by pchote** [comment]
The "Apache longbow" is already in RA!

**Comment by MustaphaTR** [comment]
Just "Apache"(AH-64) and "Apache Lobgbow"(AH-64D) are not ecatly same helicopter. They are not too much different to use differently in OpenRA either tho.

**Comment by SoScared** [comment]
Historically the Apache (Longbow) was literally a replacement for the Cobra.
https://en.wikipedia.org/wiki/Boeing_AH-64_Apache
https://en.wikipedia.org/wiki/Bell_AH-1_Cobra

In OpenRA, the Longbow "replaces" the Hind as the game progresses in tech.

Renaming the Hind to Cobra could deflate the Hind discussion permanently. Sounds like a good deal to me.

**Comment by SamKeightley** [comment]
That's incorrect, The Apache started off as a replacement for the Cobra in the United States Army's Advanced Attack Helicopter program and did replace cobra's in the army, but the Cobra is still being heavily used and upgraded by the Marine Corps. 

The Cobra is a poor choice to replace the Hind even by name for that reason. And there's no need to deflate the Hind discussion permanently, since this is a valid issue that needs to be fixed. Simply changing the name of the unit is only a half measure. The shp would still be a hind no matter what you call it:p

**Comment by SoScared** [comment]
> The Apache originally started as the Model 77 developed by Hughes Helicopters for the United States Army's Advanced Attack Helicopter program to replace the AH-1 Cobra.

This is more than good enough for me. The lore has limited relevance to reality so personally I don't care about the technicalities beyond that.

Kill the Hind.

**Comment by pchote** [comment]
:+1: for the chubby cobra.  Someone could tweak the artwork to be a bit more appropriate.

**Comment by MustaphaTR** [comment]
I like the name Huey, but i don't know much about either history or helis so i don't think i can say much.

I'm OK with whatever you choose. As long as we get rid of hind in Allies.

**Comment by Micr0Bit** [comment]
this : 
renaming (RA) HIND -> Cobra
and this : 
The .shp and unit animation are pretty low detailed, I don't see a riot coming out of this either.

:+1:

**Comment by SoScared** [comment]
![cobra 0000](https://cloud.githubusercontent.com/assets/2715583/23185001/1c76a8c0-f882-11e6-8766-2d8468c3d93e.png)
![madtank 0000](https://cloud.githubusercontent.com/assets/2715583/23185002/1f39fb20-f882-11e6-906f-daa1f6fc820d.png)

**Comment by SoScared** [comment]
https://upload.wikimedia.org/wikipedia/commons/archive/6/6a/20161229215207%21Bell_209.jpg
https://upload.wikimedia.org/wikipedia/commons/e/e6/Masada_cobra1.jpg

![cobra 0001](https://cloud.githubusercontent.com/assets/2715583/23185630/4fc23ae4-f884-11e6-9745-c12da215ea5e.png)

**Comment by SoScared** [comment]
![cobra 0000](https://cloud.githubusercontent.com/assets/2715583/23188107/ca4d5d44-f88d-11e6-95df-03a0ba730b1e.png)

**Comment by SoScared** [comment]
https://www.dropbox.com/s/oronipgv5uv4khh/hind.shp?dl=0

Hind with its wings cut.

**Comment by SoScared** [comment]
Well, with a new firing sequence (single instead of twin turrets) and perhaps a two-bladed propeller animation, I guess this could count as a candidate.

![cobra 0000](https://cloud.githubusercontent.com/assets/2715583/23191406/abb03964-f89d-11e6-9307-4d6c99224e5a.png)

![hind-to-cobra02](https://cloud.githubusercontent.com/assets/2715583/23191371/8f66ee06-f89d-11e6-8bed-ea2746f1c3bb.gif)

**Comment by SamKeightley** [comment]
> This is more than good enough for me. The WW lore has limited relevance to reality anyway so personally I don't care about the technicalities beyond that. Looking at the mood of the community, neither will anyone else. Well except you I guess.
> 
> The .shp and unit animation are pretty low detailed, I don't see a riot coming out of this either.

WW Lore has correlation with reality but not to the magnitude that it becomes remotely close reality, this is also a massive though experiment into an alternate timeline. When it comes to the units though, you need context. When it comes to aircraft, they're just that bit more identifiable so the extra attention to detail goes a long way.  

I like the cameo alot, especially the canopy. The stub wings are ok. I'll make a cobra shp too once I finish the huey and then that opens more possibilities.

**Comment by anjew175** [comment]
Discussing which helicopter is the best fit for the lore is completely pointless when the events of RA take place between 1946 and 1953 and from what I can find, most helicopters from the the early 50's look a bit like this 
![xh26](https://cloud.githubusercontent.com/assets/14989579/23208757/f3438354-f941-11e6-9950-3cf3085e5697.jpg)

Regarding the Rocket Launcher. Im not fussed if its changed or not because it still wont change how people communicate. (eg. rocket soldiers will always be e3 to some regardless what you call it). However after using discord and hearing how others refer to it, MLRS is the most dominant term used.
Upon further research even the most well known Red Alert Wiki calls it the MLRS
http://cnc.wikia.com/wiki/M270_Multiple_Launch_Rocket_System

**Comment by GraionDilach** [comment]
Don't forget to mention how you have Abrams Tanks in the '50s.

**Comment by SamKeightley** [comment]
> Discussing which helicopter is the best fit for the lore is completely pointless when the events of RA take place between 1946 and 1953 and from what I can find, most helicopters from the the early 50's look a bit like this
> xh26

All of the units would be very close to early post World War 2 equivalent vehicles, so one could argue that all of the vehicles are out of place. Since this is not the case for RA's units, they do however conform well with each other, so by going from that information one can determine appropriate vehicles that would fit well. Clearly did not think about that right?

**Comment by pchote** [comment]
The tone of the discussions around the hind/cobra/huey topic across Github/forums/IRC has been downright disgusting, and at this point it seems clear that merging *any* of these changes will only continue the toxic drama.

The Allied Hind will have to stay until people can approach the solution and eachother with some basic respect.
