### ISSUE TITLE
new full screen mode does not allow switching to other applications

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#12246]
legacy full screen mode allowed you to alt+tab to other applications on Ubuntu.

full screen mode does no longer support this. 

would be good to have a way to minimize the full screen game - somehow be able to switch back to other applications again.

**Comment by pchote** [comment]
The regular (non-legacy) fullscreen mode should support this.

**Comment by anvilvapre** [comment]
just tried again, i do see the icon bar and i can cycle threw all my applications, but once i select an application/release the alt+tab keys .. the openra full screen windows stays active on top.

i don't have any special key bindings for alt+tab, used to work fine.

**Comment by jaZzKCS** [comment]
Legacy enforce the full-mode, whereas regular non-legacy should still let you alt-tab out.

**Comment by pchote** [comment]
Note that we haven't changed anything with the actual functionality of these modes, we just renamed "Fullscreen" to "Fullscreen (Legacy)" and "Pseudofullscreen" to "Fullscreen" to match the modern expectations for the "default-sounding" option to use borderless windows instead of the ancient driver-level modal fullscreen.

**Comment by anvilvapre** [comment]
legacy was selected after install. there alt+tab works. the general full screen has this issue.
as long as legacy fullscript supports keeps existing its fine for me.
