### ISSUE TITLE
game speed is not working

### ISSUE THREAD

**Issue by Siropenra** [OpenRA/OpenRA#12243]
in multiplayer games the game speed would always be at the slowest... no matter what i am taking faster or fastest its just not working on the game

**Comment by Siropenra** [comment]
units are slow as in normal game speed

**Comment by jaZzKCS** [comment]
Apparently this is only true for multiplayer matches against humans. Botmatches do not seem to be affected.

**Comment by jaZzKCS** [comment]
Just tried to reproduce on 64H - RA - I
Cannot reproduce: Nuke build time gets reduced to 0:30 as planned on "Fast"
Also unit movement is faster on higher speeds.

**Comment by airetaM** [comment]
Game speed working well for me ...

**Comment by reaperrr** [comment]
> units are slow as in normal game speed

I can confirm this. Only affects multiplayer, in skirmish and singleplayer speed changes work.

**Comment by jaZzKCS** [comment]
I fiddled around with this with "Sir" this midday.

Curiously enough, if the settings get deleted [and regenerated byt the new version], it always saved the issue.

The question though is: Why would it work when settings are deleted and freshly generate although it does not save the string of gamespeed in the file in the first place?

Something about the fact that the old file is still present and maybe cant be changed due to permissions, yadda yadda, this would all only make sense if the value of gamespeed is actually saved in there, which is not.

**Comment by SoScared** [comment]
That's pretty rough. A lot of big maps-big team games rely on faster game speed.

**Comment by pchote** [comment]
The key point for reproducing this is that you need to change the speed before another player joins.  The `LobbySettingsNotifications` loads the default map settings into a different object (which isn't supposed to affect the running server state), but https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/ServerTraits/LobbyCommands.cs#L824 doesn't care about our silly theoretical rules and overwrites the state anyway.
