### ISSUE TITLE
timer of fast-forwarded replay doesnt match played timer

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#12265]
in the replay-menu ... you can check the "played" time in the preview section (under the map-name) ... 
i noticed that when i fast-forward , the timer doesnt match the actually played time , and the replay ends faster ... 
so for example  , i had a game that took me 10:06 minutes to play ... but when i watch the replay and fastforward all of it ... the replay ends at 9:34

**Comment by pchote** [comment]
I also noticed this while testing #12096, so it is not specifically related to fast-forwarding.  The replay complete percentage typically gets to ~80% before jumping immediately to 100 on game completion.

**Comment by pchote** [comment]
The replay "100%" point is based on the number of net ticks, so this counts all the real time spent after the game is complete (chatting, etc).  When replaying these end-game ticks are simulated all at once, causing the jump from the final percentage (< 100%) up to 100%.

To fix this `World.EndGame` should write the game tick into the replay game info (refer to `World.OnPlayerWinStateChanged` to see how), the replay connection should load and expose this, and then the ingame replay UI should use this and the local tick count instead of `TickCount` and the `NetFrameNumber`.
