### ISSUE TITLE
Extreme game lag when AI has no path

### ISSUE THREAD

**Issue by Zulukas** [OpenRA/OpenRA#12435]
Playing the original C&C game on OpenRA and there is a map that is divided across the middle with a river and 4 bridges.  If you destroy all 4 bridges, when an AI on the other side of the bride is the only remaining AI, the game starts lagging immensely.

I'm not familiar with the code base, but my guess is the AI is trying to figure out what to do and has nothing to wait around for so it's constantly reevaluating

**Comment by godest88** [comment]
I can sadly confirm that i have seen this in both Tiberian Dawn and Red Alert. You dont even need to destroy all ways for the ai to get to you. Even with 3-4 none destroyable bridges and a relativly open map, the ai will go out of wack in about 10 min of playing, basically not finding the simple way to your base and just having its units stay in groups scattered through out the map and collect a huge ammount of slow and laggy gameplay until destroyed. Feels like the devs need to put prio on the ai/pathfinding, would be a shame to have it be this way for years to come :(

**Comment by StexoO** [comment]
Related to #6047 and #10860 (no path available).
As said somewhere in the issues the AI could try to move to the closest reachable cell to the destination or just stop trying to reach that destination.
In this case the AI could also try to repair the bridge(s). #3771

**Comment by godest88** [comment]
@StexoO You dont even need to have islands / bridges or even extremely narrow ways to move around for the ai to fail to find its way. Since i have not gone through the code myself, im not sure how the ai is implemented, but it does not look like a A* algorithm at work here, which begs the question why and the reason behind current implementation is?

**Comment by Phrohdoh** [comment]
The pathfinding implementation is A*.

https://github.com/OpenRA/OpenRA/tree/6150d25105a0cbfe4d1d1469fc0ac273f860eb77/OpenRA.Mods.Common/Pathfinder

**Comment by godest88** [comment]
@Phrohdoh  if thats the case then there is something seriously wrong with it, as iv witnessed first hand the ai failing to even get around cliffs/small ponds when trying to simply go north/south to reach the enemy :/ Only to end up staying there because it failed to reach the enemy. Not trying to point fingers at people, but rather the obvious issue :)

**Comment by StormWingDelta** [comment]
Ya no A* pathing I've used lags this bad when it can't find a path, it simply refuses to scan for new paths if unable to find one.  This is a really good case for AI use of transport units to bypass these areas and engineers to repair bridges.  Also the AI making sure all parts of its base are pathable.

**Comment by penev92** [comment]
Fixed by #19591.

**Comment by Dasha-98** [comment]
Hi,

I created a [map](https://resource.openra.net/maps/48840/) (archipel) where a player can be isolate by destroying the North and South bridges of his starting island.

If I isolate an AI, then the game will start to lag severely - just as described in this issue.

I tried devtest-20221007 and with it, the issue seems solved. When I isolate the AI player, the game is not lagging anymore.

So, I confirm that this issue seems to be fixed.

Thanks to the dev team for this fix !
