### ISSUE TITLE
Spies can't detect enemy disguised spies

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#12443]
Nothing happens when an enemy (disguised) spy come in the radius of own spy (whether own spy is disguised or not / whether there are units alongside own spy or not)

Replay : https://drive.google.com/open?id=0B4bdF_48xIwKUFpsSlhRYkFVcnM

**Comment by FrameLimiter** [comment]
This is a duplicate issue, but has been ignored for too long now. Spies were suppose to detect other spies since Jul 2, 2015: [#8616](https://github.com/OpenRA/OpenRA/pull/8616)
In order to make them work as intended they need the AutoTarget Trait.

To fix them add this:
OpenRA\mods\ra\rules\infantry.yaml
SPY:
+AutoTarget:
++InitialStance: HoldFire
++ScanRadius: 5

Duplicate tickets:
[#12185](https://github.com/OpenRA/OpenRA/issues/12185)
[#9424](https://github.com/OpenRA/OpenRA/issues/9424)

**Comment by Mailaender** [comment]
Closing as it is a duplicate.
