### ISSUE TITLE
MiGs and YAKs return to base when using 'stop' hotkey

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#12487]
They already do this with the 'deploy' hotkey. As with Longbow/Hinds they ought to just stop, or in this case start idling. Perhaps, if possible, also with a predefined clockwise or counterclockwise path for predictability. That would make MiGs/YAKs more viable as spotters when positioned close to enemy AA.

**Comment by pchote** [comment]
Planes returning to base when idle is standard C&C behaviour.

I've found it kind of sad to watch the "helicopterization" of planes in the RA mod over the last couple of years: the original gameplay plan was for helicopters (tanky but slow) lived on the battlefield except when they returned to resupply, while planes (fast but very fragile) stayed on the airfield except when they were on a strike mission.

**Comment by SoScared** [comment]
It's already off standard C&C behaviour so why not link the 'stop' hotkey to what it's actually supposed to do?

**Comment by Snurre86** [comment]
Can't we just do both and work towards both goals?

**Comment by rob-v** [comment]
PR #13242

MIG, YAK in RA and ORCAB, SCRIN in TS are the only planes that return to base on idle and it is definitely wrong. In game you move your planes to point A. When they reach it they fly in circle there. You can return them anytime to base by F key. When they are moving to point A and before they reach it, you press S to stop them sooner and you expect they will stay there. Thanks to this issue I realized that while playing I can't press S, but I have to use Move order on the current plane position so they stay there, however you can stop Helis by S.

The fix is simple - Replaced ReturnOnIdle (in RA only atm) by FlyCirleOnIdle trait (FlyCirle activity) - the same activity used by Move order when they reach destination. ReturnOnIdle seems useless, because planes are ordered explicitly to return on "RetunToBase"(F key) or out of ammo, they don't return based on ReturnOnIdle trait. It was used only on a Cancel order (like Stop) where in fact it is wrong.

**Comment by pchote** [comment]
Aircraft no longer RTB when using the stop key.
