### ISSUE TITLE
have a fatal error.... or is my computer not good enough :(

### ISSUE THREAD

**Issue by ashmccone** [OpenRA/OpenRA#12526]
this was the exception log ive been told to post and ask for help. hope someone knows what has gone wrong.

Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Can't create OpenAL device
   at OpenRA.Platforms.Default.OpenAlSoundEngine..ctor()
   at OpenRA.Platforms.Default.DeviceFactory.CreateSound()
   at OpenRA.Sound.CreateDevice(Assembly platformDll)
   at OpenRA.Sound..ctor(String engineName)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by GraionDilach** [comment]
Fix your sound output. IIRC disabling all sound devices can cause this.

**Comment by obrakmann** [comment]
In the past this also happened when you didn't have any speakers/headphones connected. Please give that a try.

**Comment by CH4Code** [comment]
Just noticed this, too. It still happens when you have no sound devices connected:

`Date: 2017-02-19 12:32:08Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
   bei OpenRA.Game.Initialize(Arguments args)
   bei OpenRA.Program.Run(String[] args)
   bei OpenRA.Program.Main(String[] args)
`
graphics.log 
`System.InvalidOperationException: Can't create OpenAL device
   bei OpenRA.Platforms.Default.OpenAlSoundEngine..ctor(String deviceName)
   bei OpenRA.Platforms.Default.DefaultPlatform.CreateSound(String device)
   bei OpenRA.Sound..ctor(IPlatform platform, SoundSettings soundSettings)
   bei OpenRA.Game.Initialize(Arguments args)
System.InvalidOperationException: Can't create OpenAL device
   bei OpenRA.Platforms.Default.OpenAlSoundEngine..ctor(String deviceName)
   bei OpenRA.Platforms.Default.DefaultPlatform.CreateSound(String device)
   bei OpenRA.Sound..ctor(IPlatform platform, SoundSettings soundSettings)
   bei OpenRA.Game.Initialize(Arguments args)`

**Comment by abcdefg30** [comment]
This has been fixed.
