### ISSUE TITLE
Disabling weapons after deploying

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#12626]
I'm trying to implement RA2 desolator for my mod, as a test for new traits.

I've ran into a trouble since it has a primary weapon and an elite primary weapon.
The trouble is, I can't disable them with upgrade conditions since the upgrade condition is already in use and I can't add deployed condition.

	Armament@primary:
		Weapon: RadBeamWeapon
		UpgradeTypes: eliteweapon, deployed
		UpgradeMaxEnabledLevel: 0
		UpgradeMaxAcceptedLevel: 1
		LocalOffset: 400,40,444
	Armament@elite:
		Weapon: RadBeamWeaponE
		UpgradeTypes: eliteweapon, deployed
		UpgradeMinEnabledLevel: 1
		UpgradeMaxAcceptedLevel: 1
		LocalOffset: 400,40,444

	DeployToUpgrade:
		DeployedUpgrades: deployed
		CanDeployOnRamps: true
		DeployAnimation: deploy

I think UpgradeMaxEnabledLevel should become something like levelS to accept multiple levels from multiple upgrades.

**Comment by GraionDilach** [comment]
Next release will drop the upgrade system in favor of conditions, which will allow you to do this properly (`RequiresCondition: !rank-elite && !deployed` on the standard weapon, `RequiresCondition: rank-elite && !deployed` on the elite weapon and `RequiresCondition: deployed` on the deploy one) but for now, just set so that `DeployedUpgrades` give you 2 `eliteweapon`s besides deployed and set `UpgradeMaxAcceptedLevel` to 3 on all armaments, so level 0 means rookie undeployed, level 1 is elite undeployed, level 2 is rookie deployed and level3 is elite deployed.

Note that while `DeployToUpgrade->DeployedUpgrades` are allowing multiple upgrades to be granted, it's substitute in the next release, `GrantConditionOnDeploy->DeployedCondition` doesn't due to the boolean logic dropping the requirements of such workarounds like the above.

**Comment by pchote** [comment]
This has indeed been fixed with the new conditions setup.  See the [ts tick tank](https://github.com/OpenRA/OpenRA/blob/bleed/mods/ts/rules/nod-vehicles.yaml#L72) for an example of how to set up a deployer with elite weapons.
