### ISSUE TITLE
Idea openRA to windows universal app

### ISSUE THREAD

**Issue by SrAnderson1** [OpenRA/OpenRA#12652]
It's great to have openRA as an application in the windows store so you can play both pc, mobile and xbox one

**Comment by WolfGaming** [comment]
This would take more time then it is worth, UWP is known to be a pain in the ass for games and honestly supporting such a closed off system in an open platform is not in the interest of any open source project.

**Comment by pchote** [comment]
[Clause 5c](https://msdn.microsoft.com/en-us/library/windows/apps/hh694058.aspx) of the Windows App Developer Agreement bans OpenRA from the Windows app store because we have not explicitly licenced the C&C intellectual property from EA.  I imagine that most other open source engine recreations for proprietary games (OpenTTD, OpenRCT2, etc) will be in a similar situation.

So sorry, this simply isn't possible.
