### ISSUE TITLE
Launch the map editor on .oramap files

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#12704]
like we do with replays.

**Comment by pchote** [comment]
Unfortunately this won't be compatible with #12554 because it won't be possible to guess which engine installation should be used to open the map.

This problem actually already exists: maps can be compatible with multiple mods, which means we can't guess which one to use even if they are all on the same engine version.  This is one of the reasons why I didn't implement this along with replays.

**Comment by Mailaender** [comment]
If https://github.com/OpenRA/OpenRA/issues/12554 will be done right, then a mechanism like [update-alternatives](https://linux.die.net/man/8/update-alternatives) from the operating system will be used to determine the default engine/binary which answers all those requests.

**Comment by pchote** [comment]
This is no longer feasible with side-by-side portable installs and SDK-based mods now all sharing `.oramap` on all platforms.
