### ISSUE TITLE
Does not run properly on Wayland

### ISSUE THREAD

**Issue by paulvt** [OpenRA/OpenRA#12777]
SDL has experimental Wayland support since version 2.0.2 according to [Wayland's wiki](https://wiki.archlinux.org/index.php/wayland#SDL). I tried it out, but I only see the lower left corner of the game.  

```
$ SDL_VIDEODRIVER=wayland openra
Platform is Linux
Using SDL 2 with OpenGL renderer
Desktop resolution: 3200x1800
No custom resolution provided, using desktop resolution
Using resolution: 3200x1800
Using window scale 1.00
OpenGL version: 3.0 Mesa 13.0.3
Using default sound device
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
Available mods:
	cnc: Tiberian Dawn (release-20161019)
	d2k: Dune 2000 (release-20161019)
	modchooser: Mod Chooser (release-20161019)
	ra: Red Alert (release-20161019)
Loading mod: cnc
```

See also the attached screenshot.

![screenshot from 2017-02-14 10-43-13](https://cloud.githubusercontent.com/assets/551904/22923642/95c54a5a-f2a2-11e6-845c-92a6d3096f85.png)

**Comment by pchote** [comment]
Try removing `SDL.SDL_WindowFlags.SDL_WINDOW_ALLOW_HIGHDPI` from https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Platforms.Default/Sdl2GraphicsDevice.cs#L65.  I expect that to fix the scaling, but leave you without HiDPI rendering.

**Comment by paulvt** [comment]
Unfortunately, that doesn't change anything.

**Comment by pchote** [comment]
I set up a Fedora VM and dug around a bit, and as far as I can tell something between SDL, GTK, Wayland, and the GPU drivers is completely broken.

* Your specific problem above happens because `SDL_GetCurrentDisplayMode` reports native pixels but `SDL_CreateWindow` expects scaled points.
* We would need to manually divide the native pixels by the scaling ratio (which we don't know) to get a properly sized window, but we can't because `SDL_GetDisplayDPI` doesn't work and `SDL_GL_GetDrawableSize` appears to be returning scaled points instead of native pixels.
* The `SDL_WINDOW_ALLOW_HIGHDPI` flag seem to work, so I guess we need to ping some native API to disable the window scaling and enable HiDPI at all.

Considering that (1) you have to explicitly override the SDL backend to trigger this, and (2) window borders and possibly other things break under wayland, i'm leaning towards a WONTFIX.

**Comment by aleixpol** [comment]
I tested it yesterday on KDE/Plasma and I get the same behaviour as @paulvt.

**Comment by abcdefg30** [comment]
What is the status here?

**Comment by paulvt** [comment]
This seems fixed, either somewhere in the stack or in OpenRA.
Thanks for the follow-up, @abcdefg30!
