### ISSUE TITLE
Release 20161019: Performance issue Red Alert

### ISSUE THREAD

**Issue by xp65** [OpenRA/OpenRA#12843]
When playing single player there was a performance drop in the game. Which isn't unusual on large maps with many AI's, however when all the ships where destroyed and only two small minor AI's were still existing, the game remained as slow.

Only once the second to last player was destroyed (bottom right player), the game was perfectly fast again. (I have a brand new i7, 16GB ram computer new from this January, so on other computers the replay might be very slow)

I submit this as there is a chance it's something specific and this replay might isolate the problem.

MOD: Red Alert
Type: Single player
Release: 20161019

In attachment:
- Perf log
- Debug log
- Replay file
- Map file

Download:
[Perf.zip](https://github.com/OpenRA/OpenRA/files/800087/Perf.zip)

Screenshot from performance offending player (dark blue):
![image](https://cloud.githubusercontent.com/assets/6690499/23315816/25c76aca-fac8-11e6-8880-f90251d4c79f.png)
Lighter blue killed all the ore trucks, etc and halted attacking him for the remaining of the game. Only once I killed dark blue, the slow down was gone.

I'm not sure if it's something that's easily fixed or if it contributes to any new knowledge. 
Feel free to close this issue when the problem is already know.

Thanks for looking into this and keep up the great work!

**Comment by xp65** [comment]
Additionally, see Ore Truck issue for the player in the UK (see screenshot).

The AI places an infantry in the position of the refinery and all ore trucks get stuck there.

![openra-2017-02-24t180915063z](https://cloud.githubusercontent.com/assets/6690499/23315045/bec57d42-fac4-11e6-9a96-8b3b1675a07e.png)

**Comment by xp65** [comment]
Additional information about the performance in screenshots:

Still slow, just before "killing" the second last player (other player is on the left bottom)
The AI player has only a few troops left (all on screen).
![openra-2017-02-24t203527078z](https://cloud.githubusercontent.com/assets/6690499/23320234/2aefdcdc-fada-11e6-94ca-54b354833936.png)

After the AI is defeated, it's fast, very fast. All the time I was thinking the slowdown was due to lots of boats and other units on the map... but it wasn't..
![openra-2017-02-24t203532860z](https://cloud.githubusercontent.com/assets/6690499/23320312/78431e9a-fada-11e6-80a8-e202b519b5c9.png)

And then there finally was a high frame rate to kill the last player (it never went slow again).
![openra-2017-02-24t203543057z](https://cloud.githubusercontent.com/assets/6690499/23320369/baffd32c-fada-11e6-9419-85ab357316ba.png)

**Comment by Mailaender** [comment]
> 2012 ms [93930] Trait: player->HackyAI

Something in the AI code is really costly here.

**Comment by RoosterDragon** [comment]
The AI is spending its time [issuing new attack orders](https://github.com/OpenRA/OpenRA/blob/release-20161019/OpenRA.Mods.Common/AI/States/GroundStates.cs#L145).

[Finding the closest enemy](https://github.com/OpenRA/OpenRA/blob/release-20161019/OpenRA.Mods.Common/AI/HackyAI.cs#L606-L609) is not a cheap operation. This is likely the reason for the large lag spike.

I suspect it is choosing an invalid target, which means it has to try and find a new one again, which it tries to do roughly every second. The [filter](https://github.com/OpenRA/OpenRA/blob/release-20161019/OpenRA.Mods.Common/AI/HackyAI.cs#L312-L315) only specifies a targetable enemy non-husk unit and makes no further attempt to ensure the target is valid for the actors involved.

- The main fix would be to ensure a valid target is chosen. There is a [`CanAttackTarget`](https://github.com/OpenRA/OpenRA/blob/release-20161019/OpenRA.Mods.Common/AI/States/StateBase.cs#L62-L77) method that sounds suited for the job.
- `FindClosestEnemy` has to check every unit for suitability and then find the nearest. In a world with many units this is expensive. A quick fix for that is `Worlds.Actors.OrderBy(distance).Where(isEnemyUnit).FirstOrDefault()`, if sorting turns out to be cheaper than filtering all the units. A fancier fix would be to use the spatial partitions in the actor map to return actors in approximate distance order. This is more work but means if there is a nearby target we can bail out much sooner without having to check every actor.

**Comment by xp65** [comment]
Thanks @Mailaender and @RoosterDragon  for looking into this. 

The odd thing is, in the end my units are near his base, but the AI does not really use his army on the right to defend. If it rechecks every second for `FindClosestEnemy`, shoudn't it find my nearest units? and earlier in the game find the other AI just next to him?

**Comment by PunkPun** [comment]
This should no longer be relevant

**Comment by Mailaender** [comment]
Can you state the code changes that improved this, because I don't see a significant difference.

**Comment by PunkPun** [comment]
This issue quite old (2017) and most mentioned aspects of the game have had per rewrites or changes done to them

**Comment by Mailaender** [comment]
Not really a fan of auto-closing "old" tickets per se. The bots have been refactored only slightly. Please do your research before pinging again.

Closing as many exceptions have been added to the target search:
https://github.com/OpenRA/OpenRA/pull/17835
https://github.com/OpenRA/OpenRA/pull/17986
https://github.com/OpenRA/OpenRA/pull/18900
