### ISSUE TITLE
TD Missing units.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#12899]
#12818 OP did a fantastic job in cleaning up the assets in the missions. :D Very well done sir!

But it has also takened away a few things from the original that you could build. (Im still working on this list. Im sick as a dog at the time of writing this)

GDI mission 2:

When you capture the Nod MCV and build a barracks you can build engineers from the Nod barracks. The refinery is also missing from the Nod MCV. 

GDI Mission 3:

Capturing the Nod MCV/Barracks you can build rocket infantry.

GDI Mission 5a:

This is a small one but I can ignore it. Nod light tank is buildable without a com center.

GDI Mission 5b:

Nod has the option to build chem troopers but requires the temple. (Which at this stage of the mission is not possible.)

Nod Mission 7c: In Orca theft capturing the helipad you are unable to build extra Orcas.

Nod Mission 8a: Medium tanks do not require com center.

Still working on list as much as I can. I know its knit picking for just small details and reaperrr who worked on the changes did an awesome job.

**Comment by reaperrr** [comment]
#12818 didn't take those away, they were already missing ;)

The real underlying problem is that disabling all actors that shouldn't be available for each mission individually is basically just a giant yaml hack around the fact that we don't have any real mission `TechLevel` system. Short-term, fixing the missions individually might be easier, but mid-to-long-term I think we should replace our error-prone current approach with a real singleplayer `TechLevel` system.

**Comment by pchote** [comment]
There's nothing stopping us from doing that in the short term: add a `campaign-techlevel.yaml` that overrides the prerequisites on all the actors to add `campaign-techlevel-N`, and then have the missions grant those with `ProvidesPrerequisite` on the player actor.
