### ISSUE TITLE
Allow selection of Super/Support Powers to trigger launch cursor.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#12937]
Selecting Iron Curtain, Nuke etc. would then allow you to get the 'select target' cursor (when powers are charged). Also enabling players to use control groups for quick and easy customized access.

As of now support power are binded to hotkeys that recognizes the order of support powers top left of the screen.

**Comment by Smittytron** [comment]
Related to #12752

**Comment by pchote** [comment]
I see two problems here:
* Accidentally double clicked your missile silo while selecting it? RIP, you just nuked your base.
* Some buildings (RA airfield, TS upgrade center) can have multiple targetable powers.

A better fix would be to standardize the support power palette ordering so that the hotkeys are consistent – we have an issue for this, but I can't find it.

**Comment by SoScared** [comment]
I was thinking in terms of left click (or hotkey select) structure and right click to execute. Forgot that we use left click to select target.

**Comment by WolfGaming** [comment]
This could also be fixed by having a general command palette for selected units.

**Comment by Smittytron** [comment]
> Accidentally double clicked your missile silo while selecting it? RIP, you just nuked your base.
> Some buildings (RA airfield, TS upgrade center) can have multiple targetable powers.

Closing as wontfix for reasons above.
