### ISSUE TITLE
Performance issue when searching for target whilst trapped

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#12938]
this is easy to reproduce on bleed (and playtest) ... just turn on the performance-graphs ... wall up 50 or more rocket-troopers ... and then target a yak that is out of reach for the troops ... the perf goes nuts

this is essentially a problem when units are walled up ... but also when they are trapped behind mines (with the latest changes in  #12337 )

im making this ticket on behalf of @FrameLimiter who brought the issue up ingame

the "avoid-friendly-mines-mechanic" will cause additional stress on the performance

**Comment by AoAGeneral** [comment]
This is also an issue vs the AI as they tend to wall themselves in.

**Comment by RadicalEdward2** [comment]
I noticed this too. Specifically on the map, Poland Raid (one of the officials).

**Comment by StormWingDelta** [comment]
Oh it gets more interesting, you know how the move command for players kills itself if units can't get to a location rather than following through with the order?  Well the Attack move as well as the AI's Attack Move doesn't have this check so they continue to try and move even when they are unable to get there.  My guess is the AI is spamming Attack Move and the units are spazzing out because while they want to move they can't. Might be some good places to put in checks to see if a structure is in the way it built and to sell the offending structure, or maybe repair destroyed bridges (or destroy them if in the way of naval units).

**Comment by AoAGeneral** [comment]
The AI attack move/move happens when they are attacking units as well. Its why you see things like recon bikes and light tanks just nudging against your own vehicles.

**Comment by PunkPun** [comment]
Fixed by #19591 and subsequent PR'S
