### ISSUE TITLE
Add support for undeploy on move order

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#13039]
All TS deployers need this to match original behavior. Might be wanted for RA/TD/D2k MCVs, too.

**Comment by AoAGeneral** [comment]
I like this idea but could be an issue if you have artillery deployed and want to manually target fire something. If you miss click on the ground this would cause them to move.

**Comment by atlimit8** [comment]
Could require force-move to undeploy.

**Comment by Mailaender** [comment]
Discussion from https://github.com/OpenRA/ra2/issues/131 also suggested force move would be the best.

**Comment by pchote** [comment]
:+1: to putting this on force-move rather than regular move in our default mods.

**Comment by reaperrr** [comment]
👍 , accidentally undeploying arty/juggers because the target was too fast and you misclicked was a pain in the original.

**Comment by pchote** [comment]
This could be implemented by having `Transforms` piggy back off `Mobile` to know when/how it can move, and then pass a new `MoveToInit` to the actor creation that is picked up by `Mobile` on the newly created actor.

**Comment by pchote** [comment]
The problem with force-move is that it conflicts with the load transport order (to enable the nearby-transport search) and possibly other mod-defined activities.

This wasn't a problem in the original game because the logic there only supported (a subset of!) move orders.

**Comment by matjaeck** [comment]
> The problem with force-move is that it conflicts with the load transport order (to enable the nearby-transport search) and possibly other mod-defined orders.

I think it is time to remove the ALT load feature and adapt the mechanic that we now use for carryalls, so that you would select a blob of units and then shift-click on transports to order the units enter any of the clicked transports. I have never used the ALT auto-entering in RA, and shift-loading would be more intuitive at least for me.

I find it hard to tell whether deployed units should only undeploy when using ALT or also without, so it would be cool if changing that would be possible without rewriting too much, in case feedback from playtests requires it.

**Comment by dragunoff** [comment]
> I have never used the ALT auto-entering in RA, and shift-loading would be more intuitive at least for me.

ALT-loading is a very useful but obscure and unintuitive feature. Though once you get the hang of it it's pretty cool and it saves on a lot of micro. Shift-loading is tedious and prone to errors (compared to ALT-loading) but it also has it's use cases (alongside ALT-loading).

> I find it hard to tell whether deployed units should only undeploy when using ALT or also without, so it would be cool if changing that would be possible without rewriting too much, in case feedback from playtests requires it.

I think undeploying force move is better because it avoids accidental undeploy orders due to misclicks. It could be made configurable though.

**Comment by matjaeck** [comment]
> Shift-loading is tedious and prone to errors (compared to ALT-loading)

I never build more than 3 transports, so this would be a difference of 2 clicks for me. Not really tedious, and I doubt it is a common case to have a army of transport units. Any bugs wrt to shift loading should get reported and get fixed, but they should not be the base for a conceptual decision.

> I think undeploying force move is better because it avoids accidental undeploy orders due to misclicks.

Modt other commenters agree. The problem is the conflict with ALT-loading,, hence I suggest removing the quite special ALT loading in favor of proper common and consistent undeploy on force move behavior.
