### ISSUE TITLE
Render Glitch Fullscreen Windows 8

### ISSUE THREAD

**Issue by daviewales** [OpenRA/OpenRA#13034]
Using the latest playtest 20170304, OpenRA is unplayable in fullscreen on Windows due to graphical glitches.

However, in Windowed mode, it works perfectly.

Note that the UI works perfectly in both Fullscreen and Windowed mode. It is only the map that is glitching. Also note that the map glitches the same way in game as seen in the images below of the start screen.

Here are the steps to reproduce the problem:

- Launch OpenRA on Windows 8. (Assumes data files have been installed)
- If OpenRA is in Fullscreen mode, there will be graphical glitches
- If OpenRA is in Legacy Fullscreen mode, there will be graphical glitches
- If OpenRA is in Windowed mode, it will run perfectly

Here are some images. (Sorry for the poor quality. I didn't know how to screenshot them.)

![img_20170330_082503144](https://cloud.githubusercontent.com/assets/2499066/24481518/85d86bd4-1536-11e7-9240-c864c4044952.jpg)

![img_20170330_082525175](https://cloud.githubusercontent.com/assets/2499066/24481560/c5e5098a-1536-11e7-9f5d-3b1dcb55765f.jpg)

**Comment by pchote** [comment]
> If OpenRA is in Fullscreen mode, there will be graphical glitches
>If OpenRA is in Windowed mode, it will run perfectly

From OpenRA's perspective these two cases are identical.  The "Fullscreen" mode is simply a borderless window that is positioned to cover the whole screen.  The "Fullscreen (Legacy)" mode works somewhat differently.

This makes me think that this is a bug in your GPU drivers.  Have you tried updating those to the latest version?

**Comment by daviewales** [comment]
That's very interesting. It's my wife's computer, so I'll have to see if a driver update can be done.

**Comment by philmexico** [comment]
Any news?

I have a similar issue, just with a black screen instead of glitches: https://github.com/OpenRA/OpenRA/issues/11314

the first time i ran it, i got to the mod selection and from there to the games without any issues.

Since then, whenever I run it in fullscreen, all I see is the cursor of the mod selection, or whichever mod I run; only black screen other than the cursor, though. Sound seems to be fine, as do buttons to interact.

Window mode runs without issue.

Issue not affected by wether I run the game using the nvidia card, or only cpu.

**Comment by abcdefg30** [comment]
> Any news?

#13663 seems to have been fixed after a complete reinstall, although no idea why/how that worked.

**Comment by abcdefg30** [comment]
Closing due to lack of information/inactivity. Please leave a comment when you want this reopened.
