### ISSUE TITLE
Enable Ability to Target GPS Icons

### ISSUE THREAD

**Issue by ThisBlunt** [OpenRA/OpenRA#13078]
Have the opposing enemy's GPS Icons targetable by units. This opens up possibly for attacks instead 
of force firing into fog while GPS is enabled. Ideally not a balance breaking feature as the ability to attack is already enabled.

![screen shot 2017-04-07 at 10 45 17 pm](https://cloud.githubusercontent.com/assets/14940856/24825009/f0448076-1be3-11e7-8c25-15038205af51.png)

edit: reticle wont display desired cursor for screen cap: "unable to target" cursor

**Comment by Smittytron** [comment]
A GPS nerf is certainly something on the mind of the competitive community at the moment. One of the suggestions so far is to have GPS only reveal positions to the player and not provide vision to the player's units, so that artillery, Tanya, etc. won't auto fire into the fog of war at dots. 
This coupled with Blunt's idea could be a worthwhile trade-off.

**Comment by pchote** [comment]
GPS auto-targeting has been removed, so closing as obsolete.
