### ISSUE TITLE
mono 5.0.0 engineer capture bug

### ISSUE THREAD

**Issue by ersingencturk** [OpenRA/OpenRA#13135]
if openra run with mono framework 5.0 on a mac, engineers can't capture buildings. infantry also can't target enemy. helicopters , tanya , a few tanks and ships work ok.

looks like something broken with mono 5 or mono 5 has some bugs in it.

don't get mad with the openra code if this happens to you. (it took me a while to realise this)

**Comment by pchote** [comment]
I can confirm this on `Mono JIT compiler version 5.0.0.100 (2017-02/9667aa6 Fri May  5 09:12:57 EDT 2017)`, and have narrowed it down to *something* wrong inside mono's `IEnumerable<T>.OrderByDescending`.

The `AttackOrderTargeter` is dropped from the enumeration at [UnitOrderGenerator.cs#L144](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Orders/UnitOrderGenerator.cs#L144), and so it ends up selecting the next best order generator (move). 

Unfortunately I don't have time to investigate this further or check if there is an open mono bug for this.  Mono 5 is still pre-release, and is obviously still buggy.  Adding to the next release milestone because we may need to work around this on our end if they don't fix it before the final release.

**Comment by chrisforbes** [comment]
@abcdefg30 you've put the linux tag on this. Is mono 5 for linux affected?

**Comment by abcdefg30** [comment]
Ops, seems like I accidentally placed the wrong label. I might be able to test linux on the weekend though.

**Comment by pchote** [comment]
Confirmed on linux too.

**Comment by rob-v** [comment]
On Windows too, bug with OrderBy and OrderByDescending.

**Comment by pchote** [comment]
It looks like this is related specifically to `.SelectMany().OrderByDescending()`.  Inserting a `ToList()` in the middle fixes this issue, but we'll need to audit our other uses of SelectMany and ordering to make sure there aren't other similar issues hiding.

**Comment by rarules** [comment]
Same issue running linux mono 5.0. Is there a work around or wait for a fix? 

Please note: in missions it works fine. Only on skirmish it does not work. Is the code different?

**Comment by rob-v** [comment]
Some users installed back older mono, e.g. 4.8 until it is resolved.
