### ISSUE TITLE
Cannot show all players on replay

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#13228]
http://resource.openra.net/maps/20471/
https://www.gamereplays.org/openra/replays.php?game=92&show=details&id=320019
stats also missing

**Comment by rob-v** [comment]
It is caused by map's Visibility: MissionSelector.

**Comment by kyrreso** [comment]
That should not be possible, if the modder setup things wrong, we should still be able to "view all players" or no shrouds still. Any way to force or fix this? Why should the modder also turn off stats?

**Comment by rob-v** [comment]
I am not sure if map for mission and lobby at the same time makes sense. It is supposed that on mission map, those options are not available. In this case it doesn't look like mission map? There are no objectives... It looks like mistake. In case it is possible Lobby+MissionSelector, it could fixed. Let me know, I can ask about this.

**Comment by pchote** [comment]
This is the expected/defined behaviour for mission maps.  It is to stop (a) players cheating by starting a mission, surrendering/failing, and then viewing the replay to view the enemy positions, and (b) hide any visual glitches caused by the map scripting (e.g. spawning units under the shroud, which would normally be hidden from the player).

**Comment by kyrreso** [comment]
Could we have the replay viewer override this? for videos, etc?
