### ISSUE TITLE
AI doesn't know where to launch its nuclear missile

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#13251]
Release-20170421.

AI seems to be targeting production and technology buildings when it launches its nuclear missiles.
If no one of these buildings is on the map then the AI doesn't know what to target.
On the following screenshot this sub pen is the only one enemy building left on the map.
(The blue squares come from FRAPS and not from OpenRA)

![no_nuke_launch](https://cloud.githubusercontent.com/assets/25843400/25773902/57f517b8-3286-11e7-8f76-d2ea9aaeb186.gif)

**Comment by GSonderling** [comment]
Are you sure AI knows about the sub pen?
By default AI uses nuke against all structures, regardless of their purpose. Any structure with cost higher than 300 should be a valid target. 
```
                               Against: Enemy
				Types: Structure
				Attractiveness: 1
				TargetMetric: Value
				CheckRadius: 5c0
```
Do you have the safe file on hand by any chance?

**Comment by GraionDilach** [comment]
@Elizadmin Provide the replay.

I have a suspicion that this happens because the subpen is on a specific position of the map and the AI CheckRadiuses just miss it.

**Comment by GSonderling** [comment]
That could be it. But without knowing the map and position we can't test it.

**Comment by Elizadmin** [comment]
I don't have this replay anymore but I have a brand new one on release-20170527.
I started a 100 % AI game on the map Buttisland (http://resource.openra.net/maps/12213/) to have chances to see it.
The replay is uploaded here : https://ufile.io/p3et7.
It lasts three hours so you have to be patient before seeing it.

The guilty AI is the salmon one on the right.

You can notice two things :
- At 23:47 it launches its nuke in a completely unexplored area so the AI knows at any time where enemy buildings are, even without exploring.
- At 2:37:23 it has its GPS, its nuke ready and knows that four buildings exist, two that have been seen and two unknown, but it never launches its nuke.

**Comment by GSonderling** [comment]
If you play the current release version (20170527), bleed is about thousand commits ahead of it, so it might be possible that the issue was fixed in the meantime.

That being said we should take a look at it.

Regarding the position argument: If the problem was with the AI CheckRadius method we should see much more aberrant behavior than just this. It relies on:
`WDist.FromCells()`

And that itself is just:
```
public static WDist FromCells(int cells) { return new WDist(1024 * cells); }

public WDist(int r) { Length = r; }
```

And its used A LOT by the AI. If the problem was there it would mess up everything from Aircraft and Carryalls to AI detecting and launching assaults on enemy.

That doesn't mean that you are wrong, it could still be the issue. But if it is it probably influences other issues as well.

**Comment by pchote** [comment]
AI support power targeting was reworked in release-20180218.  Is this still a problem?

**Comment by abcdefg30** [comment]
Apparently not.
