### ISSUE TITLE
Server log: player victorious/lost

### ISSUE THREAD

**Issue by jeeveekaa** [OpenRA/OpenRA#13308]
I'm currently setting up some basics for a matchmaking system, something like Faceit (https://www.faceit.com). It will be an webapplication in PHP and NodeJS.

It would be nice if the server log can returns who is victorious, so I can track who has won and lost (to create my own ranking system).

[2017-05-16T11:15:22] Game started
[2017-05-16T11:16:31] TestingServer has disconnected.
[2017-05-16T11:17:49] TestingServer2 has disconnected.
[2017-05-16T11:17:49] **TestingServer2 is victorious!**
[2017-05-16T11:17:49] No one is playing, shutting down...
[2017-05-16T11:17:49] Starting a new server instance...

Or maybe someone else has a better idea to track this (API?).

Thanks in advance.

**Comment by pchote** [comment]
Tracking player statistics using player name is a bad idea player names are completely arbitrary.  Anyone can use anyone elses name, and players might want to change their name without losing their stats.

#2265 covers the implementation of a player authentication system.  The API and client side code work, but the project is on indefinate hold because we do not have any reliable manpower to build or maintain the web backend.

**Comment by matjaeck** [comment]
Maintenance can definitely be improved, but the main blocker seems to be now in the area of #14686 so voting for closing here.

**Comment by deleted-user-1** [comment]
Potentially outdated.

**Comment by abcdefg30** [comment]
Yes, this can now be achieved using the server-side replay recording.
