### ISSUE TITLE
Server config: lock gamesettings

### ISSUE THREAD

**Issue by jeeveekaa** [OpenRA/OpenRA#13309]
It would be nice to have an option to lock the game settings (server side), so players can't change the map/speed/crates etc.

For example something like this:
**Server.LockSettings="True"**

No idea if this is possible, thanks in advance.

**Comment by leodew** [comment]
I was exactly thinking of this for map locking, for instance to dedicate servers for map-testing 1 or several maps or modded maps. 

That could help a lot for map-testing, balance improving, and overall maps visibility.

**Comment by CH4Code** [comment]
@leodew I like the idea of map-list-locked servers too, but then the players would have to have the maps allready installed, since there is no way to search/download maps from inside OpenRA. (Which would be a good feature)

Also @jeeveekaa I see conflicts with maps locking setting themselves. For example my mission maps have crates forced off and might have shroud locked on. Which would take precedence?

**Comment by rob-v** [comment]
@CH4Code What you mean by "there is no way to search/download maps from inside OpenRA"? In lobby when a map from Resource center is selected which you don't have, you click on 'Install map' button below map to install it.

**Comment by abcdefg30** [comment]
I created https://github.com/OpenRA/OpenRA/wiki/Lock-server-settings offering a way to lock server settings.
