### ISSUE TITLE
Successive orders

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#13390]
As mentioned in this discussion : http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&p=302572#302572 , there seems to be a few bugs related to successive orders given with the Shift key (or work differently accross computers ?). I guessed I'd make 1 single post for it

- "A-move" : doesn't work with me (is it supposed to ?)
- MCV move & deployment : seems to either not work at all, or deploy at the first location of a path
- Repair at Service Depot : works with movement. But at the end of the last order, the unit then goes to the rally point of the SD. Can cause unintended behaviour

**Comment by FrameLimiter** [comment]
Related issues: #4776 , #12886

**Comment by obrakmann** [comment]
> "A-move" : doesn't work with me (is it supposed to ?)

That's the way the code works for now. I have a branch where a-move is queueable, but it still needs more work.

**Comment by dsimmons87** [comment]
Just to add to this if you queue a move order then a capture for an engineer, it seems to capture first then move after.

**Comment by dragunoff** [comment]
A couple of related issues: #11582, #12852 and #4773

**Comment by ubitux** [comment]
Demo truck doesn't support queued explosion either.

**Comment by matjaeck** [comment]
- A-Move is hopefully fixed by #16105 
> MCV move & deployment : seems to either not work at all, or deploy at the first location of a path
- MCV deploy orders can be queued (also after other move orders)
> Repair at Service Depot : works with movement. But at the end of the last order, the unit then goes to the rally point of the SD. Can cause unintended behaviour
- This behavior is unchanged. However, there is a new bug that queued orders will not be executed in the order they are given if the sequence contains a repair order. See this GIF: <details><summary>GIF</summary>
I queued move+repair+move
![fix](https://user-images.githubusercontent.com/37185497/51863213-bdc20900-2340-11e9-8469-50afe7f35bc9.gif)
</details>

- #11582 and 
    > Demo truck doesn't support queued explosion either.

   should get fixed by #16065 and #16060

**Comment by matjaeck** [comment]
Related: #16599, #16381

**Comment by matjaeck** [comment]
Related: #16993

**Comment by abcdefg30** [comment]
Seems like we're done here.
