### ISSUE TITLE
Railgun effect

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13447]
https://www.youtube.com/watch?v=7D8KoO-AGX0

Hi, I attempted to make railgun effect.
If this is good, I'd make a PR.
If so, should this be in mods.common or mods.TS?

**Comment by reaperrr** [comment]
From the looks of it, I'd say it's definitely good enough for a PR.
Mods.TS was merged into Mods.Cnc, though ;)

Personally, I'd vote for Mods.Common, since stuff like AreaBeam is currently there as well. Mods.Cnc should be mainly for very C&C-specific stuff that wouldn't be of too much use for most external non-C&C mods (though there is certainly some stuff that could go either way).

**Comment by forcecore** [comment]
PR made, closing
