### ISSUE TITLE
HitShapes behave erratically with Rectangle->ApplyToAllTargetablePositions.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#13452]
![targetableoffseteh](https://cloud.githubusercontent.com/assets/1136302/26762821/cede871e-4948-11e7-87c2-37ddb8be4ca3.PNG)

Barracks and Warfactory has a line of bibs which offsets the mid but thzat can be called intended. The centerposition gets another rectangle though. I don't remember what the greenish radius is around it though.

**Comment by reaperrr** [comment]
The only reason I didn't remove `ApplyToAllTargetablePositions` in my HitShape PR yet was because I didn't want that PR to grow even larger and take longer to merge (and didn't expect it to be used that much), but it's a hack with too many drawbacks that probably needs to go.

The green circle is the OuterRadius used for actor look-ups in warheads, for example (one reason why ^ needs to go, as warheads without custom, larger victim scan will no longer find the outer cells).

**Comment by GraionDilach** [comment]
So, let me understand this correctly...

A simple, easy to set-up solution for hitboxes is called as a hack, so you're forced to do crazy insane hitbox setups which shall involve trial-by-error guessworking for proper results and ofc will harm perf longterm esp if someone starts doing big buildings.

**Comment by pchote** [comment]
Actually it's `ApplyToAllTargetablePositions` that will harm perf longterm, because it means that every impact has to be checked against [number of targetable positions] hitshapes instead of the minimum achievable number (which would be 1 for the rectangular buildings shown above).

**Comment by reaperrr** [comment]
Additionally, I'll provide shapes for TS shortly which - thanks to the recent world unit scaling fix - should be applicable to any isometric building with the same footprint in any mod, so in many cases it will just be a matter of copy&paste.

**Comment by GraionDilach** [comment]
Closing since this issue is a NOTTODO on developer side and modders should fix this via setting up custom hitshapes.
