### ISSUE TITLE
Add a project code of conduct.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#13509]
See https://github.com/blog/2380-new-community-tools and https://opensource.guide/code-of-conduct/.

The Contributor Covenant looks reasonable to me, although IMO version 1.3 (used by mono, the .NET foundation, and others) reads as being more genuine than the 1.4 version offered as a default template.

**Comment by jrb0001** [comment]
The code of conduct should explicitly include when and how to censor offending comments. Editing a comment is the worst thing to do IMO because GitHub doesn't make it clear enough what was written by whom. Deleting a comment and recreating it would be much better because then the author is actually correct.
