### ISSUE TITLE
Proposal, 50% faster TraitDictionary

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#13577]
Proposal to make TraitDictionary a singleton or to remove it. And to make TraintContainer<T> instances also global singletons.

I.e. ```TraitContainer<T>.Singleton```

The advantage is that the trait container for a type can by looked up by relying on .net to resolve the generic type and accessing the singleton. There is no longer need for the lookup of the TraitContainer inside the TraitDictionary. For a 15 minute multi player game it results 20 million less function calls and hash table lookups. 

Disadvantage is that when a new World is created the TraitContainers may need to be emptied manually. The adding of traits becomes slower due to the need of reflection.  
 

Number of calls per TraitDictionary method:

![image](https://user-images.githubusercontent.com/12512948/27765566-3e0cd376-5eb5-11e7-93c8-1668afa56d76.png)

Total time spent in msec in methods in TraitDictionary:
![image](https://user-images.githubusercontent.com/12512948/27765652-da4aa4e6-5eb7-11e7-9c97-991bcb356016.png)

I.e. in the game of 15 minutes the WithInterface call got 1.2 seconds faster. 

Percentage improvement 50+% faster

![image](https://user-images.githubusercontent.com/12512948/27765572-66d30adc-5eb5-11e7-9653-e7e9ee33af44.png)

Avg time in mec spent in method
![image](https://user-images.githubusercontent.com/12512948/27765723-bc35d816-5eb9-11e7-84ba-306f0c7bb366.png)

I'm using Mono.

Rough example implementation:

```c#
class TraitDictionary
{
               // Needed only to be able to remove actors from all trait containers
		static readonly Dictionary<Type, ITraitContainer> sTraits = new Dictionary<Type, ITraitContainer>();

		public static void RegisterTraitContainer(Type type, ITraitContainer container)
		{
			sTraits.Add(type, container);
		}

		void InnerAdd(Actor actor, Type t, object val)
		{
			//InnerGet(t).Add(actor, val);
			var genericType = typeof(TraitContainer<>).MakeGenericType(t);
			var singletonField = genericType.GetField("Singleton", BindingFlags.Public | BindingFlags.Static);
			ITraitContainer singleton = (ITraitContainer) singletonField.GetValue(null);
			singleton.Add(actor, val);
		}

// All function should become static. Or better yet remove them and call TraitContainer directly.
		public T Get<T>(Actor actor)
		{
			CheckDestroyed(actor);
			//return InnerGet<T>().Get(actor.ActorID);
			return TraitContainer<T>.Singleton.Get(actor.ActorID);
		}

		public T GetOrDefault<T>(Actor actor)
		{
			CheckDestroyed(actor);
			//return InnerGet<T>().GetOrDefault(actor.ActorID);
			return TraitContainer<T>.Singleton.GetOrDefault(actor.ActorID);
		}

		public IEnumerable<T> WithInterface<T>(Actor actor)
		{
			CheckDestroyed(actor);
			//return InnerGet<T>().GetMultiple(actor.ActorID);
			return TraitContainer<T>.Singleton.GetMultiple(actor.ActorID);
		}

		public IEnumerable<TraitPair<T>> ActorsWithTrait<T>()
		{
			//return InnerGet<T>().All();
			return TraitContainer<T>.Singleton.All();
		}

		public IEnumerable<Actor> ActorsHavingTrait<T>()
		{
			//return InnerGet<T>().Actors();
			return TraitContainer<T>.Singleton.Actors();
		}

		public IEnumerable<Actor> ActorsHavingTrait<T>(Func<T, bool> predicate)
		{
			//return InnerGet<T>().Actors(predicate);
			return TraitContainer<T>.Singleton.Actors(predicate);
		}

		public int CalcSyncHash(ref int n)
		{
			//return InnerGet<ISync>().CalcSyncHash(ref n);
			return TraitContainer<ISync>.Singleton.CalcSyncHash(ref n);
		}

		public void RemoveActor(Actor a)
		{
			//foreach (var t in traits)
			foreach (var t in sTraits)
				t.Value.RemoveActor(a.ActorID);
		}


	
}
```

```c#

class TraitContainer<T>
{
			public static TraitContainer<T> Singleton = new TraitContainer<T>();

			static TraitContainer()
			{
				TraitDictionary.RegisterTraitContainer(typeof(T), Singleton);
			}

...
}

```

Also by removing the TraitDictionary member from World and calling TraitContainer<T>.Singleton.GetMultiple() directly saves the lookup of 2 levels of indirection x 20 million calls. I.e. in Actor.cs not Actor.World.TraitDictionary.TraitContainer.GetMultiple().

**Comment by pchote** [comment]
Global state in the core engine has been an endless source of pain and crashes, and gets in the way of some interesting ideas such as loading the world in a background thread so we can have smoothly animated loadscreens with player chat.  Can these performance gains be earned in other ways?

**Comment by anvilvapre** [comment]
Alternatives are discussed here https://github.com/OpenRA/OpenRA/pull/13547

Trait types having an unique sequential index. Which would require mods to register traits to get a unique index and after use this index in a variable to retrieve a specific trait container. This to by pass generic type lookup time and the need for a hash map. Not a pretty solution that would break a lot of code.

```
// Register trait at start of game with core.
uint MyTrait.StaticAtInitAquiredUniqueTypeIndex;

// actor.TraitsWithInterface<MyTrait>();
actor.TraitsWithInterface[MyTrait.StaticAtInitAquiredUniqueTypeIndex]().Select()
// Short form
actor.TraitsWithInterface[MyTrait.TraitIndex]().Select()

```

The solution in this issue is cleaner. You could still have a 2nd non static TraitDictionary on the side, in which you load the World which then after you have to copy to the static version. 

You could combine both.

**Comment by RoosterDragon** [comment]
Certainly, a faster `TraitDictionary` would be nice and performance improvements are welcome if we can do so without affecting the current API or ergonomics of the class too much.

The current design supports a lot of nice things, like querying for traits generated at runtime without having to register them, and not containing global state, and not being coupled to internals of specific traits such as `ISync`. Lookups in the `TraitDictionary` don't slow the program as a whole down all that much, so it's not worth giving up all these nice things for a tiny bit of performance.

If we could keep all the nice things and still improve performance, that would be great.

When it turns out traits lookups are slowing down the program, we can cache the results is most cases and thus avoid the lookup cost entirely! We do this *all the time* to avoid traits lookups becoming an expense.

We cache traits on creation with `var traits = self.TraitsImplementing<T>().ToArray();` which we can do since traits never change after creation. There's no lookup or enumeration cost for TraitDictionary any more, everything is in a speedy array. Even if we sped up TraitDictionary 10x, we'd still be doing this to avoid paying that cost every time.

If you look at the `traitreport.log` in the Logs folder, it will list the most queried traits. Anything high up in the list could probably benefit from caching like this.

To answer a few points from https://github.com/OpenRA/OpenRA/issues/13574#issuecomment-312381582:

> Also please add the local actor variable to the Actors method in TraitContainer to avoid 2 array index lookups.

Once we pay the cache miss on the first lookup, the others are likely to be free. But worth doing nonetheless.

> Also the use of late binding is said to have a negative performance impact.

In C#, late binding typically refers to reflection or the use of `dynamic`. Could you clarify what you mean here?

> Also consider to make the `Enumerable<>` objects a local variable of a TraitContainer to avoid creating new objects each time.

I think that would be useful. We should do that.

> Also, to save 20% of trait memory usage - consider skipping the System.Object base type in TraitDictionary, avoiding the creation of a `TraitContainer<Object>`. Since all Traits have this base type all traits will be added to this container. Yet this container never seems to be queried.

Also a good idea. Let's do that too.

> Also, consider storing Actor Trait pairs are `TraitPair<T>` in the TraitContainer. This allow you to return the pairs as is - not having to create TraitPair for each enumaration call.

`TraitPair<T>` is just a struct and is basically free to create. Combining the two arrays into one would slow down calls that only traverse one of the arrays, they'd have to pay in extra cache misses for all the data they were skipping.

> Also, consider storing the top 2 to 10 most queried traits that are queried by actor also as local variables of an Actor.

Actor already caches several important traits. Even better, individual traits can cache other traits they care about as described above. This means individual traits can cache what they like (even if it's less common) and we don't need to gum up Actor with traits it doesn't care about. Win-win for everybody.

> Also, add a `TraitDict` and `TraitContainer.Apply(Func<TraitPair<T>, bool> func)`

Is this to try and avoid enumeration costs because of the `IEnumerator` interface? You'll end up just transferring those costs to creating and invoking a `Func` instead.

> [Repeated lookups] i.e. in WorldUtil TemporaryBlocking

If this pattern is common enough, and there are enough actors, it might be worth fixing this. It's only worthwhile if it happens enough to actually matter. As you mention, temporary blockers often end up being just one actor. Unless another use of this pattern somewhere actually uses enough actors for it to matter, we're just writing more code to fix a non-problem.

**Comment by reaperrr** [comment]
@RoosterDragon related to performance, I noticed you replaced LINQ (.First, .Any etc.) with foreach loops in some places, is the performance difference large enough to check if there are more places we can/should do that? (I have a local branch that does this for the `CreateEffectWarhead` and `Bullet` HitShape look-ups, I just have no idea if it's worth it).

**Comment by anvilvapre** [comment]
@reaperrr in general i wouldn't propose to replace Linq call unless you know they are slower. foreach like Linq calls uses the IEnumeration interface. So the speed will be similar.

Only when you have 3+ foreach loops inside each other or where there are a lot of items being iterated it is worth while to try and see if you can use Array's or List and for loops not foreach loops.

@RoosterDragon 

The original changes proposed in this issue break the current interface minimally/not. No registration etc needed.

Late binding is the use of ```var``` variables over declaring them as i.e. ```int```. I read it. I don't know the (f)actual impact. Wouldn't propose to do it everywhere, just in important areas if it helps. 

Regarding the TraitPair<T>. Iterating over a primitive array of uint with actor ids seems to make the search 10% faster.  But it requires storing all actors once more. 

While the current 2 arrays of actors and traits are faster when iterating over all traits - it somewhat slows down  iteration over actors, since you are searching in a larger array of actor ids. But iterating of all/traits should be fastest.

Yeah I was aware of the overhead cost of having to call Func. Still i is one function call over 2. Perhaps not worth while.

You mention the caching of traits. Please realize that even with  caching the trait containers are queried 20 million times.

**Comment by RoosterDragon** [comment]
@reaperrr: In the few places that matter, it makes a noticeable difference. But it only matters in a tiny fraction of places (There's a `// PERF: Avoid LINQ.` comment in like 30 places? We must use LINQ in 1000s of places). I generally prefer LINQ for readability unless profiling says otherwise.

@anvilvapre: This PR does require global state to be created and maintained though, which is a detriment the current design.

To put it in perspective, your graph tracked the total milliseconds spent in a 15 minute game on both branches? Eye-balling it, it looks like 5.8 seconds on bleed and 3.6 seconds on your branch.

Over the 15 minute game, that represents 0.64% of the total time on bleed being reduced to 0.40% of the total time on your branch.

I'm not against 0.24% speedups, but in my opinion adding global state to a design is a poor tradeoff for such a small speed gain.
