### ISSUE TITLE
Unlogical sorting of desert beach tiles in Map Editor

### ISSUE THREAD

**Issue by noobmapmaker** [OpenRA/OpenRA#13587]
The current way the beachtiles are sorted is not very logical. Some of the tiles that seem to belong to one group are placed somewhere else. More logical grouping (in my opinion):

Small corner group:
413, 414, 415, 416

Big corner group:
417, 418, 423, 424, 425, 426, 427, 428, 429, 430

Group beach right, water left:
419, 420, 424, 437, 438, 441

Group beach left, water right:
421, 422, 435, 436, 442

Group beach top, water below:
400, 401, 402, 403, 404, 405, 431, 432, 439, 440

Group beach below, water on top:
406, 407, 408, 409, 410, 411, 412, 433, 434

**Comment by GSonderling** [comment]
Do you want the 424 in `Big corner group` or in `Group beach right, water left`?

**Comment by noobmapmaker** [comment]
In the 'big corner group' because it's a big corner (top side connects to horizontal beach and right side connects to vertical beach). The beach right, water left only allows vertical beach to connect above and below.

**Comment by GSonderling** [comment]
I asked because you put it in both categories. 

Anyway, I don't know if this kind of thing would be accepted as pull request, but one way or another, if you want the tiles reordered you can try this branch [https://github.com/GSonderling/OpenRA/tree/desertbeachtileresort](https://github.com/GSonderling/OpenRA/tree/desertbeachtileresort).

I reordered the templates as you wanted, tested it in editor and encountered no issues.

I recommend using just the `\OpenRA\mods\ra\tilesets\desert.yaml` file, since it's the only file I had to change.

**Comment by abcdefg30** [comment]
Would you mind sending a Pull Request?

**Comment by GSonderling** [comment]
Not at all, I'm sending it right now.

**Comment by Mailaender** [comment]
Fixed in https://github.com/OpenRA/OpenRA/issues/13644
