### ISSUE TITLE
Game gets unplayably slow when AI can't find route

### ISSUE THREAD

**Issue by Beep6581** [OpenRA/OpenRA#13661]
Using `release-20170527`
The game becomes unplayably slow when the AI is unable to find a route.
For example play a 4-player game, you vs 3 AIs, on a map where landmasses are connected by a bridge, then blow up the bridge.

**Comment by pchote** [comment]
This is a known issue with the AI that is not possible to fix with the current AI.  Instead, the AI should be disabled on any maps where this can happen - was this on an official map?

**Comment by Beep6581** [comment]
This was on "Poland Raid".

**Comment by Mailaender** [comment]
In https://github.com/OpenRA/OpenRA/pull/6215 I disabled bots for the map. https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/maps/poland-raid.oramap is currently shipped.

**Comment by GSonderling** [comment]
OpenRA uses A* algorithm if I'm not mistaken. Since A* "fails" if it runs out of nodes in open set and since maps are obviously finite it should be possible to use this to limit bot use of pathfinding method.

So, for example, if the search for path fails `n` times the bot would have to wait 'm' milliseconds before using pathfinding method again.
