### ISSUE TITLE
Chronotank ability doesn't work with shift key (playtest 20170722)

### ISSUE THREAD

**Issue by Smittytron** [OpenRA/OpenRA#13751]
I imagine it has something to do with waypoints on the stance bar.

**Comment by pchote** [comment]
This is an intentional bug fix.  Having this available on shift broke the ability to queue move orders (#9046), and was inconsistent with the rest of our activity system.

Use Force Move (alt/commandbar) to teleport instead.
Force move is our "go here, and don't dawdle" command:
 - Tanks will move to the location, crushing enemy units if they can at the location
 - Chronotanks will teleport to the location, crushing enemy units if they are at the location
 - If target is a transport and the transport is full, units load into a nearby transport instead
 - Carryalls will fly to the location and hover instead of dropping their cargo
 - (proposed/planned) Chinooks and other flying transports won't land
 - (proposed/planned) Infantry won't go prone if shot at while moving
 - (idea that probably won't happen) Planes circle at the location instead of returning to base
