### ISSUE TITLE
AI assumes that all buildable MCV actors are deployable.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#13840]
FindAndDeployBackupMcv queries the TransformsInfo directly without a nullcheck - https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/AI/HackyAI.cs#L977.

This breaks with mods which lacks true MCVs (Nomad Galaxy), but on the other hand, allows to abuse the Mcvs list for deployable buildings (say, Mobile War Factories) at the cost of the MCV-replacement feature.

Note that every other stage of the AI, it just unconditionally orders the MCV actor to DeployToTransform, which results with the order being dropped if it can't do that ofc, which is why it doesn't crash in the first tick, but only when a spare MCV gets available.

**Comment by GSonderling** [comment]
Would the problem be fixed by simply skipping elements that lacks the TransformsInfo trait?
Something like:
`var factType = mcv.Info.TraitInfo<TransformsInfo>().IntoActor;
if (factType == null)   continue;
`

**Comment by GraionDilach** [comment]
Probably, but your example still queries the traitinfo without a nullcheck (Incase you don't understand - your setup should look like `if (!mcv.Info.HasTraitInfo<TransformsInfo>()) continue; var factType = mcv.Info.TraitInfo<TransformsInfo>().IntoActor;`

**Comment by GSonderling** [comment]
Oh, you meant to check if `TransformsInfo` is null, not 'IntoActor'. 

Anyway, the question is if this wouldn't cause issues somewhere else. We would have to test it on Nomad Galaxy or something with similar issues to find out. All I know is that it works in Red Alert itself.

**Comment by GSonderling** [comment]
To rephrase my earlier comment:
Do you have access to Nomad Galaxy mod, or do you know about some other mod with these issues I could use to test potential fix?

**Comment by DoGyAUT** [comment]
The reason he found out about this problem is because of my 2nd project I am working on. I asked Graion for help and this is the result of it.

I had several random crashes after a timeframe of 13-18min. The problem was that I had no units listed in the HackyAI Mcv: list. So I had to use a dummy unit with fake buildable trait which never gets used anyway.

I couldn't add the commander tanks in the Mcv common list because it crashed rightout at the start of the game.

My WW2 project has no real MCV units compared to the more classic setup in Crystallized Doom, but has instead Commander Tanks, which act as mobile bases.

**Comment by GSonderling** [comment]
I tested the code @GraionDilach  suggested with the non-transforming MCVs you provided and it seems to work. Meaning, it compiles and after hour or so on full 8 player map it didn't crash, nor did AI behave in any weird way.

If you want, you should submit a PR.
