### ISSUE TITLE
Igloos in TD are named Haystacks.

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#13936]
On the WINTER & SNOW tilesets the civilian structures V12 & V13 display as Igloos but are still named "Haystacks".

![openra-2017-08-29t155230768z](https://user-images.githubusercontent.com/22008761/29832379-081653d0-8cb6-11e7-9102-dfca974485b1.png)

**Comment by Mailaender** [comment]
Wait, are they haystacks on temperate? Then this may not be easy to fix.

**Comment by pchote** [comment]
It can be done with a condition toggling the tooltip.

**Comment by GSonderling** [comment]
The question is how to override the default tooltip?
Hardcoding the string is obviously sloppy, especially because it is essentially needed for single corner case.
Implementing another key just for V12/V13 (and related husks) seems even worse, since all other units have at most one name. And again it would only be used for single building on couple of maps. 

Considering this, wouldn't it be easier to make two new buildings, and replace the haystacks with them on all relevant maps?

**Comment by pchote** [comment]
Actors can define multiple tooltip traits that can be switched at runtime based on generic conditions.  We just need a trait that toggles the condition based on the current tileset.

**Comment by GSonderling** [comment]
So I guess we need to write new condition that evaluates the tileset. Because none of those I can see in current code can do that and there is no documentation about yaml condition types.
