### ISSUE TITLE
Missing explosion effects on CTFLAG, ^CivField, and V19.Husk

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#13960]
Related to #13686 / #13693

**Comment by reaperrr** [comment]
The problem is that they have a HitShape, but no Targetable, which makes `CreateEffectWarhead`s consider them explicitly invalid.

Lack of Targetable makes them invulnerable anyway (damage warheads ignore anything with no targetables), so these structures simply shouldn't have HitShape/Health (and Explodes, since it depends on those).

I'll push a fix.
