### ISSUE TITLE
Attacks on bridges play both water and ground impact animations

### ISSUE THREAD

**Issue by evanb90** [OpenRA/OpenRA#13989]
Using Playtest 20170902 and the base RA mod.

Pretty easy to reproduce. Attack bridge sections that are over water. Both animations get played.
Not present in Playtest 20170304 or Release 20170527

![openra-2017-09-06t182144151z](https://user-images.githubusercontent.com/31705956/30127924-e1ccef5e-930e-11e7-8709-12274c65f84d.png)

**Comment by reaperrr** [comment]
Introducing a Bridge target type and making that explicitly invalid for effect warheads with water splashes should do the trick.

The cause of the issue is that bridges have only the Ground and Water target types, and Ground cannot be made invalid for water splashes because due to how our terrain and actor target types are set up, that would cause too many regressions in other places.
