### ISSUE TITLE
Allow vehicles to fire while moving

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#14009]
Most of explaining is in [this thread](http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=20242)

**Comment by pchote** [comment]
How is this different to the standard attack move order?

**Comment by HappyORA** [comment]
In the current build vehicles stop and shoot when A moved which leaves them very vulnerable. For example a Ranger can out run rockets but if it stops to attacked it will be hit. In Whocares idea the ranger will keep moving which means it can out run the rockets and shoot. This can add a new level of micro skill of using certain vehicles to trigger rockets etc etc. It would really enrich the game play. But it needs to be tested that it doesnt overpower certain things.

**Comment by GraionDilach** [comment]
Don't we have a ticket for this already as part of proper TS support?

The topic blends in proper-fire-on-the-move with the current turrets-stuck-in-attacking-the-target bug. I can understand why though - a player can't really see the difference. That being said, the latter needs to be fixed and axed though for certain, but we also need the former for TS/RA2 anyway.
 
@pchote The difference is that attack-move - as being an activity itself - stops the unit in range, while fire-on-the-move means that the turret acquires targets on it's own without disrupting the move order/active activity. War Miners even require this to function properly.

Infact, this feature alone was the reason why RA2 Soviet metagame evolved into a Rhinofest, due to Apc lacking fire-on-the-move.

**Comment by netnazgul** [comment]
> How is this different to the standard attack move order?

it's to be implemented into a move command (as described in the thread); A-move is not changed by this. 
Basically it's what @GraionDilach said - turret being independent of a vehicle. WhoCares includes other units to that too (such as rangers or apcs), so that's debatable.

**Comment by pchote** [comment]
@GraionDilach: Can you please outline (either here or in a more appropriate ticket) the specific details of how TS/RA2 should behave?

**Comment by GraionDilach** [comment]
I'll go with RA2 nomenclature (replace OpportunityFire with NoMovingFire for TS).

If a turreted unit has OpportunityFire=yes (which I imagine would be an AttackTurreted flag in OpenRA system), then it'll keep trying to query a target within range unless there is an explicit target already preset (either caused by the player's direct attack command OR picked up by autotarget during idling/guard) and it will automatically drop this nonexplicit target when the distance would pass the firing range. This behavior only applies to activities not related to attacking (move, harvest). Take note that ordering the unit for these activities dropped the unit's active abilities, leaving this passive-attacking permanently enabled.

Some might find the behavior of TS/RA2 buggy in the matter that a turret with OpportunityFire functions more responsive on plain move orders than attack-move (because attack-move would stop the unit when it enters into firing range against a target), and turns the unit ideal for hit'n'run attacks.

**Comment by GraionDilach** [comment]
Related: #2327.

**Comment by Mailaender** [comment]
Duplicate of https://github.com/OpenRA/OpenRA/issues/7566.

**Comment by reaperrr** [comment]
I've been wondering for a while whether parts of the attack logic should even be activities to begin with.

I might be too optimistic and overlooking some caveats here, but this particular feature would be much easier to implement and handle if attacking was purely trait logic and independent from any activities, only ever using activities to move the actor towards (or away from) the target until within range, if necessary. 
Basically, the attack logic shouldn't even care whether the actor is currently moving except if some boolean like `NoMovingFire` is explicitly `true`, in my opinion.

**Comment by pchote** [comment]
See also the discussion in #13716, and at least one other place I don't recall.  The way I see this working is to have individual Attack*'s for logical groupings of weapons that operate independently from activities, and then some master controller trait that controls what the actor itself is doing using activities.  We do still need some activity logic here for following / stopping to attack / etc.

**Comment by GraionDilach** [comment]
Reverse-duplicate of #11156.

**Comment by Smittytron** [comment]
I'm not sure if this belongs in a separate ticket, but a problem I've been coming across is that moving turreted actors have to enter the next cell and stop before acquiring the target they have been ordered to attack. This is an issue because keeping your tanks moving in a pitched battle is vital. 

I will often target a pillbox or artillery and then immediately issue a move command past the enemy because i want my tanks to fire while moving. Because most of the tanks haven't entered the next cell in the time I issue both commands, they won't acquire my target, which wastes important DPS vs high value targets.
