### ISSUE TITLE
Bug report : repair burned friend mcv and get friend unit abilities

### ISSUE THREAD

**Issue by AliT1993** [OpenRA/OpenRA#14019]
in multiplayer 2v2 game one of enemies build mcv and send that to his friend base
allied person explode friend soviet mcv and repair that with mechanic and get new mcv with soviet abilities!!!
after that allied person can build IC and Tesla and soviet building & units & superpowers !!!!
its really bad bug and after i see this in game i surrend because i cant win this unfare game!!!
replay attached here  : 
[OpenRA-2017-09-12T151523Z.orarep.zip](https://github.com/OpenRA/OpenRA/files/1299820/OpenRA-2017-09-12T151523Z.orarep.zip)

**Comment by dragunoff** [comment]
That can be exploited in TD mod as well with engineers. It's an easy way to recover after losing your only MCV. Of course considering that your ally has to build that extra MCV first (which in TD costs a lot of money). 

I'm not sure if this should be considered a bug, but it definitely affects game balance...

**Comment by abc013** [comment]
It's the expected behavior that the player who captures a mcv husk gets the mcv's faction.
>  it definitely affects game balance...

I agree with that.

**Comment by AliT1993** [comment]
i think player must have own units MCV after get ally burned MCV
if this bug (thing) stay in game, everybody can do this in multiplayer mode and have both type units/building/superpowers and its not fare

**Comment by abcdefg30** [comment]
Why should you get your own faction's mcv? You salvage the other factions mcv after all, so it doesn't sound logical to me when you suddenly get your own faction.

Balancing is another point, but consider that your ally has to build an extra mcv (costs money and blocks the vehicle queue) and you thus have less tanks. Imho it is fair to "reward" that risk (+ you still have to build the other factions structures, which again costs time and money you could have spend on units).

**Comment by Elizadmin** [comment]
An option could be added in the lobby : " [ ] Allow mechanics to capture MCV husks".

@abcdefg30 : IIRC Soviet tanks and Soviet MCVs have the same cost and the same production time, $2000 and 00:40 (with one war factory), so you have only __one__ _missing_ tank ? :trollface:

**Comment by abcdefg30** [comment]
Ok, if you're building Mammoth Tanks (which I don't really see often in MP games ^^).

**Comment by netnazgul** [comment]
What if that friend's MCV has just died to enemy attack and your mechanic is the only one close enough to re-capture it?

Actually I can only suggest allowing hijackers to target friendly vehicles to completely balance the issue between factions :P

**Comment by AliT1993** [comment]
its really hard to decide what can do for it!
if you play against one person who have IC and Chrono then you know other player is invincible
other play have mamoth tank and helicopter or have tesla and AA! how you can win this ?!
it will not be a good and fare game ! and you cant know other side already do this or not!

**Comment by airetaM** [comment]
This has been changed a while ago, before you didnt capture other factions with a MCV.
I just found out 2 enemys did this in a game when i watched a replay this week, but this is a new tactic i didnt recognize this before.
Balance wise i think it would be nice if the captured Mcv wouldnt be able to build the other factions Tech center, because T3 units and especially chrono and IC is the problem.

**Comment by dragunoff** [comment]
An elegant solution might be to simply restore the salvaged MVC (or any other husk) to its original owner for team players. And then the only way for a player to get another faction's MCV would by salvaging an enemy husk (which is much harder and thus not easily exploited).

**Comment by WhoCaresora** [comment]
It's unbalanced only because the tech exhchange goes one way, allied to soviet due to mechanics abillity

One way to make it fair is able "force capture" with enge on your teammate structure, that would bring the balance to the tech exchange.

As for 1V1, having the opponenet tech is a fair reward for salvaging a husk of a misplayed mcv or a fleeing one  . kinda disapointing when opponenet is allied ^^.

**Comment by AliT1993** [comment]
i agree with dragunoff idea and told this afew comments before

**Comment by WhoCaresora** [comment]
I don't agree, in a perspective of future competitive teamgame, tech exchange can proove to be a valid (costly) strategy (If highjackers are allowed to highjack fiendly units). In that regard, it alwais resumes about you letting the time and the money to your ennemy to do it and get the double tech reward by not applying enought pressure on them. I would at least let the game shape itself now that team players just start to realize that it's possible (only after 2 years) to see it will become viral and grame breaking. As now it'is not.

**Comment by SoScared** [comment]
Seem like @dragunoff suggestion is the only one that address the problem without taking away the reward of MCV capture or balance (bastardize) team-play by allowing the hijacker to cap friendly vehicles.

**Comment by Smittytron** [comment]
Agree with @dragunoff that the husk should return to the team-mate in a team game. 

If we move husk restore from the mechanic to the engineer the team game problem will only be compounded. An allied-soviet team could get double tech on both players while a team made of the same faction would be at a further disadvantage.

By having a restored husk return to a team-mate instead of the capturing player, the obviously exploitative practice of intentionally destroying your own MCV in team games will end.

**Comment by pchote** [comment]
@Smittytron: this sounds like an idea I proposed a while back, and which I still like the idea of: recast the "capture" ability to "repair" - in the same way that you can repair a damaged friendly vehicle but not a damaged enemy vehicle, make them "repair" a destroyed friendly vehicle (returning it to its original owner) but not destroyed enemy vehicles.

**Comment by matjaeck** [comment]
> To clarify, what I am thinking is if the husk belongs to you or an enemy, it is restored as your unit. If it belongs to an ally, it is restored to the ally.

See #9960. If this gets implemented like this, it would be good to have a repair wrench cursor for husks of allies and the normal enter cursor for other husks.

**Comment by pchote** [comment]
The current mechanic features are logically consistent because they are treated as two distinct features:
* Repairing, which follows the standard "repair" conventions (works on own and allied forces, never on enemies).
* Husk recovery, which follows the standard "husk" conventions (all husks are equivalent, ownership doesn't matter)

Of course, this has balance implications, which is why this issue exists...

My proposal above was to unify both cases on the "repair" conventions, which allows you to repair your own (for you) or allied (for your ally) husks, but *not* enemy husks.

The splitting the husk recovery into separate results for ally vs enemy (repair vs capture) breaks the logical consistency, which is bad gameplay design. IMO that would be an arbitrary hack that I expect some people will think is a bug.

**Comment by pchote** [comment]
I agree, and consider this a Red Alert-only discussion/plan.

**Comment by Smittytron** [comment]
> The splitting the husk recovery into separate results for ally vs enemy (repair vs capture) breaks the logical consistency, which is bad gameplay design. IMO that would be an arbitrary hack that I expect some people will think is a bug – I certainly would if I didn't know the backstory behind it.

We might have to agree to disagree on this one. I just don't see this method as any more arbitrary than not being able to restore enemy vehicles. I could argue that it doesn't make sense that you can fix your own medium tanks but not your enemy's. They're both the same kind of tank.

Honestly not making a change at all would be better received than removing the ability to restore enemy husks. Removing gameplay options is where we run into trouble with community feedback.

**Comment by dragunoff** [comment]
> This is how the game works for tanks that have between 1-99% health. Why does it make sense for this to suddenly change when it reaches 0% in such a way that it also makes sense to change the owner for enemy-owned tanks but not ally-owned tanks?

The difference is that tetween 1 and 99% health the unit is still controlled by the player while at 0% heath it's considered dead. But anyway - if we think of it this way then mechanics should be able to repair enemy husks and restore them to the original owner (the enemy). Which IMO doesn't make sense... It's a vehicle husk, and when a player sends own unit inside of it they expect to reclaim it. That makes sense and that's the current "capture husk" game mechanic. Thus the game mechanic is not broken, there are only some balance implications in team games.

The solution that I suggested a while back (restoring to the ally) does indeed contradict this basic game mechanic. But there are already many such exceptions in the game when it comes to your allies - you can't capture allied buildings with engie, your units don't auto-target allies, you can repair at their service depot, you have shared vision, etc). What I'm stressing here is that players expect the game mechanics to work differently in team games.

Though thinking about it now and in light of the recent discussions here and on discord, I'd say that maybe it's better to not touch this. The only real benefit of obtaining other faction's tech is the double IC and parabombs which doesn't sound too overpowered to me. Being able to produce other faction's units is largely irrelevant in team games. Of course I'm talking only about the core RA mod. This may indeed prove imbalanced in other mods that use this game mechanic.

> Honestly not making a change at all would be better received than removing the ability to restore enemy husks. Removing gameplay options is where we run into trouble with community feedback.

And I totally agree with @Smittytron here.

**Comment by pchote** [comment]
To be clear, the thrust of my argument above was not pushing for removing the ability to capture enemy husk, but pointing out the inconsistency with the argument above.  We could take a pragmatic approach of accepting the inconsistency and doing it anyway (but i would like for everyone to at least be on the same page first, if we go that way) or keeping the current mechanics but moving them to engineers.

**Comment by dragunoff** [comment]
@pchote Those are all valid points you're making.

Regarding moving the capture husk ability to engineers I'd agree with @Smittytron :
> If we move husk restore from the mechanic to the engineer the team game problem will only be compounded. An allied-soviet team could get double tech on both players while a team made of the same faction would be at a further disadvantage.

**Comment by GraionDilach** [comment]
Just limit allied engineers to only be able to resurrect allied units and soviet engis to resurrect soviet units. This way you can prevent the MCV husk recapture issue bit still have a consistency.

**Comment by matjaeck** [comment]
It seems there is no consistent solution that doesn't have negative implications. Engineers (2500HP) can not survive at frontlines where husks usually appear, mechanics can (8000HP) and have a passive ability that makes their presence useful. Moving husks repair/restore ability to the engineer will eliminate most of the common use cases I think. Soviets might profit because they have husks that are actually worth restoring (mammoths, heavy tanks). 

> Just limit allied engineers to only be able to resurrect allied units and soviet engis to resurrect soviet units. This way you can prevent the MCV husk recapture issue bit still have a consistency.

This would feel very disappointing when you run into an enemy MCV husk but can't restore it because the tooltip says "soviet" while it looks just like an allied husk. I'm not sure if I would understand the reason behind this.

Maybe we should remove the ability to restore husks completely, risk trouble with the community but solve the problem once and for all.

**Comment by KOYK** [comment]
Can we at least make it an option in the lobby? kinda feels like taking the fun out of the game. In RA2 you could take an mcv of an other faction by crates, or by breaking an alliance with an other player then capturing his mcv and then form an alliance again. I mean its not out of the ordinary, its fun! We all liked that mcv crate surprise from RA2 right? So whatever the solution you come up with, please add a lobby option to enable\disable it.
