### ISSUE TITLE
Allow removal of auto-arrangement of players with the map.yaml

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#14041]
The default arrangement of players when spawns has not been selected helps sorting out spawns for players either not familiar or caring with the lobby's spawn selection system. At the same time it also takes away opportunities for play with maps having more spawn than players that allows the player the excitement of exploring the map in order to locate the enemy.

![examples](https://user-images.githubusercontent.com/2715583/30519889-955a0f1c-9ba1-11e7-85b4-c1a44b558122.png) Using examples of the official map pool.

This option would also help competitive players with all mods to expand their selection of maps going beyond 1v1 maps. At the start-up of the RA Global League a few 2v2 maps was added to the map pool only to later realize the players by default spawning on polar opposite sides on the maps.

**Comment by ZxGanon** [comment]
I was also planning to use maps with 4 player positions like in Starcraft for new TD and RA maps I have been planning. But with a set value of players spawning on polar positions there will be no interaction in scouting and different build orders because of the same spawning interaction.

I wanted to create some maps based on SC2 were you usually start on a map with 4 positions and you have to scout if your opponent ist either close, close air or cross position towards you. That really dertemines which build order you choose/what your opponent is gonna do. It also creates a new art of base building because expanding to the coners of maps allows players to set up biggers bases and larger areas to control rather than expanding towards your opponent.

It would be very nice to at least change some yaml values to delete "polar spawning" and enable random positioning.

**Comment by SoScared** [comment]
Another good example is the explosive interest for NoobMapMaker's 'Dark Tournament' which appeal is the unknown, the unexplored. The thrill of exploration has somewhat been lost in the modernization of RA which this could help bring back within certain aspects.

**Comment by netnazgul** [comment]
I've given it a thought and I don't understand how placing players on furthest spawn points helps casual gaming. Average casual player won't even know about this feature because it's not evident, and will play as if the spawns are not predefined (also I'd bet average casual player won't remember where the spawns are on a map). And if someone does know of this feature he will exploit it most likely by rushing to a known location without scouting. 
I suppose it can give some slack to team games, but in every team game I saw players always select the spawn points anyway.

So it will be helpful if someone elaborates on why this feature was brought into the game in the first place.

**Comment by GraionDilach** [comment]
>I suppose it can give some slack to team games, but in every team game I saw players always select the spawn points anyway.

Yes, because this game doesn't support random teamups. Something I was very fond of in Mental Omega casual MP rules (random locations, left versus right, ingame teamup). Generals, Warcraft 3 and YR included a map preview image in the loadingscreen where the spawn locations were revealed to set this up as well.

**Comment by pchote** [comment]
That really needs #2992 to be done well.

**Comment by SoScared** [comment]
Implemented with https://github.com/OpenRA/OpenRA/pull/15137
