### ISSUE TITLE
AutoTargetPriorities + AttackGarrisoned interactions aren't exactly modder-friendly.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#14044]
AutoTargetPriorities can be nicely utilized to imitate the threat-rating logic of TS's, however for TR logic, a modder might need to setup a complicated passenger-condition setup (especially when multiple passenger slots are present).

A good alternative would be to create some sort of an ATP interface and then Cargo/AttackGarrisoned (or a different trait) could gather the ATP interfaces and return the summaries to the transport actor for use with AutoTarget.

**Comment by reaperrr** [comment]
This is not the first time `AttackGarrisoned` has been the problematic outlier due to all the special sauce it's doing. 
In my opinion we should at least investigate whether it wouldn't be better to just drop that trait in favor of moving all possible infantry weapons to the garrisonable structure and then activating them via conditions (we'll eventually need some `GrantConditionOnPassenger` trait anyway, I think), so the garrisoned structure can simply have a more normal, less unique/hacky attack trait.

Just my 2 cents.

**Comment by GraionDilach** [comment]
That sounds even worse to maintain for units like the YR Battle Fortress or the Generals Humvee.

**Comment by MustaphaTR** [comment]
> (we'll eventually need some `GrantConditionOnPassenger`trait anyway,)

We already have PassengerConditions under Cargo, used by IFV in RA2 mod.

**Comment by GraionDilach** [comment]
Considering that conditions gained more ground since the issue was opened and autotargetpriorities got further refined with assault-move, this is not a bug, but a feature. The ticket is moot.
