### ISSUE TITLE
Submerged submarines are damaged by surface fire.

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#14054]
This is caused by the addition of "Water" to the SS & MSUB underwater TargetTypes.
I think simply removing "Water" from the SS & MSUB Underwater TargetTypes should fix this.
SS & MSUB:
->Targetable@UNDERWATER:
-->TargetTypes: **Water**, Underwater, Repair

[playtest-20170902 & bleed]

**Comment by Smittytron** [comment]
I was under the impression that force-firing water to fish for suspected submarines was a correct and legitimate tactic.

**Comment by FrameLimiter** [comment]
It was never a tactic in the past, it was unintentionally introduced into the playtest when refactoring CreateEffectWarheads. #13543

**Comment by pchote** [comment]
All these regressions wrt water effects are starting to feel a bit silly now.  @reaperrr would this be better solved by introducing a new set of target types for RA?

**Comment by reaperrr** [comment]
> I think simply removing "Water" from the SS & MSUB Underwater TargetTypes should fix this.

I doubt it's that easy, iirc I added it because otherwise water splashes would not display on cells occupied by submerged subs, indirectly revealing their position. At the very least I know I added it for a reason.

> @reaperrr would this be better solved by introducing a new set of target types for RA?

Technically yes, the main cause of this whole mess is that `Ground` and `Water` are shared between actors and terrain, so getting the behavior right in every combination is currently a brain twister from hell.

However, I'm not convinced we can get that right in one try without causing another, new set of regressions, because many trait and weapon properties default to `Ground, Water` for target types.
I'd like to first make one last attempt at fixing this with as few changes as possible, and then revamp the RA target types from scratch for Next+1 to bring back some sanity into the setup.

**Comment by pchote** [comment]
Ok, that sounds fair.  I suppose that here we can get away with adding a new Submarine target type that is invalid for damage but valid for effects.

**Comment by pchote** [comment]
A hacky workaround would be to use the cloaked condition to activate a different armor type that recieves 1% damage from Water damage types.

**Comment by reaperrr** [comment]
Actually I just tested with `Water` removed from target types and didn't spot any issues with the cursor.
Not 100% sure if that was really the problem.
I think it's safer to revert it and risk reopening a minor issue than introducing such a hack. I'll file a PR.
