### ISSUE TITLE
Map lag

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#14080]
What can cause a map to lag ? 

I've been playing this map http://resource.openra.net/maps/22951 (Jungle Law) several times online, with different people, and there seems to be a problem with the map causing the lag.

Could it be the interaction between ore and cliffs/trees ? (cf expansions at the back of each base)

**Comment by GraionDilach** [comment]
I'd blame pathfinding. L and U cliffs are susceptible for causing such, when the pathfinder ends up in the inner corner of the L/U and the have to retract instead of O cliffs where the inner area of the cliff si unreachabler and the pathfinder realizes immediately it hit an obstacle. Notsure if the pathfinder considers trees as obstacles though, equal to cliffs in that matter.

**Comment by FRenzy-OpenRA** [comment]
Ok I see, thanks

Watching some replays, the only interactions I see with cliffs are at the back expansions. The cliffs are quite linear, but maybe the trees are causing it. 

Will test a new version without those trees

**Comment by FRenzy-OpenRA** [comment]
Ok played the new map with trees being removed. 
One game was still laggy, but other games were perfectly fine with players being all over the map and using the cliffs. 
Not sure if the trees were the problem, but now I don't think the map is to blame anymore. 

Case closed, thanks for the help !
