### ISSUE TITLE
Attack helicopters will ignore orders if given queued attacks during rearming.

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#14094]
Hind & Longbow:
If you queue up attack orders on structures while the hind or longbow is returning to rearm. They'll ignore all commands after rearming and suicide toward the queued targets.

To reproduce:
∙Build a hind or longbow in RA.
∙Attack an enemy structure.
∙While your air unit is returning to rearm, queue an attack order on a different structure. 
∙After the helicopter has rearmed it should pursue the newly queued target. You will be unable to stop this attack and your helicopter will ignore all orders to stop. 

--
release-20170527 & playtest-20170930

**Comment by Kanar** [comment]
Also, yaks ignore queued attacks (even when fully armed) sometimes. :(

**Comment by pchote** [comment]
This is caused by https://github.com/OpenRA/OpenRA/blob/297be6d6cc70b7ffd6ad544211c8020f510e4248/OpenRA.Mods.Common/Activities/Air/ResupplyAircraft.cs#L41

Queuing `NextInQueue` as a ChildActivity sets an internal parent pointer to the `ResupplyAircraft` activity, which is not cleared when that same activity is later returned as a not-child activity.  When you later try to cancel the activity (by issuing something else) the cancellation code follows the parent pointer and cancels the `ResupplyAircraft` instead. This obviously doesn't work, so the `HeliAttack` continues until it completes normally.

Ping @obrakmann who can complain at us about doing it wrong and hopefully suggest a proper solution. I still don't have a feeling for the composite activity concept, and completely failed to get them to work with the move activities in #16150 (this is why it explicitly manages the inner activity), so I'm not sure i'm qualified to comment here.

**Comment by matjaeck** [comment]
We should test this again.
