### ISSUE TITLE
Impose chat character limit

### ISSUE THREAD

**Issue by oraservers** [OpenRA/OpenRA#14141]
In multiplayer games, it is possible for individuals to flood and sometimes crash player clients by sending large amounts of text. Suggest imposing a reasonable character limit for a message. Not sure if this should be done on the client and/or sever side or both.

**Comment by anjew175** [comment]
It's completely possible to intentionally and consistently crash players client using this exploit as long as a certain amount of characters are reached. It is possible to put too many characters in and crash only your own client. 
I really suggest trying to do this ASAP as this is something that has existed for a very long time and has been exploited before, even in public on SoScareds stream.

**Comment by GSonderling** [comment]
What would be considered reasonable? 140, 280, 300?

**Comment by anjew175** [comment]
I'm no expert on the character limits however its worth noting that this problem only exists when we are talking about characters into the tens of thousands. I know players that exceed 300 characters in a message and I know many players that will copy paste segments of discussion because right now OpenRA has no way to copy paste or hyperlink.

I would really hate to see a 140 character limit and I think 300 is still too small. I personally have exceeded 400 in normal discussion.

**Comment by pchote** [comment]
The server already has this, applied to *all* orders.  Clients that send too large of an order will be disconnected.  If long chat messages are causing crashes then that is a separate bug, and it would be silly to try and fix that without crash logs or verification that it hasn't already been fixed.

This is way to nebulous of an issue to reasonably diagnose and implement before the final release on Saturday, so dropping from the milestone.
