### ISSUE TITLE
Crash using bogus text

### ISSUE THREAD

**Issue by anjew175** [OpenRA/OpenRA#14176]
As release 20171014 it's possible to crash clients. Unsure of the users system but this is the crash log https://pastebin.com/1HcCmzEN

I believe this is the text that is used but I believe its a specific glyph or has to be a certain length
 https://lingojam.com/GlitchTextGenerator
It was just posted in the lobby and caused a player to consistently crash

**Comment by pchote** [comment]
The crash log shows that they are running Linux, so it is possible that they are running a Freetype version that throws a different error (either because it is too old or too new) than what we are used to.

In any case we should be catching these type of errors and gracefully degrading instead of crashing.
