### ISSUE TITLE
Use waypoint to load units into multiple transports

### ISSUE THREAD

**Issue by Logue-Yne** [OpenRA/OpenRA#14208]
Right now if you put waypoints for a group of unit to multiple transports the units wil just go and load into the last one you clicked on. Unit that cannot, will wait nearby.

The idea is to have the following behavior,
Units load into the first transport and go to the next once the first is full, following the waypoint order until all the group is loaded or no more room is left in the transports.

**Comment by MustaphaTR** [comment]
If you Alt+Click on a transport, units will try to enter other nearby ones after one is full.

Still, waypoints indeed also should work.

**Comment by MustaphaTR** [comment]
If you Alt+Click on a transport, units will try to enter other nearby ones after one is full.

Still, waypoints indeed also should work.

**Comment by dragunoff** [comment]
+1 for making waypoints work in this scenario - it's logical and intuitive and is present in other RTS. Also it gives the player finer control than the force move action.

The force move feature also has its place because it makes the task of loading to multiple transports easier. The problem however is that it's rather obscure - if I had not heard about it I woudn't have discovered it by myself - it's just not intuitive.

**Comment by pchote** [comment]
Improving support for queued orders is one of the goals for the next release, so this is an obvious thing to fix.

For what it's worth, the force-move loading feature is mentioned in the command bar tooltip.

**Comment by matjaeck** [comment]
Related to the discussion in #13039 and the controversy if we should remove force-loading in favor of queued loading.

**Comment by pchote** [comment]
This may already have been fixed by the ongoing activity work.

**Comment by matjaeck** [comment]
> Units load into the first transport and go to the next once the first is full, following the waypoint order until all the group is loaded or no more room is left in the transports.

This is fixed on bleed in the requested way.
