### ISSUE TITLE
Traits Documentation too long

### ISSUE THREAD

**Issue by CH4Code** [OpenRA/OpenRA#14225]
Hi, recently the wiki on Traits has been showing this
![grafik](https://user-images.githubusercontent.com/16046997/31831699-a4380484-b5c4-11e7-9639-2d4a48c64512.png)
probably because there is so much awesome content in OpenRA even the Wiki cant handle it!

In an attempt to dirty-fix this (delete from bottom to at least show some of the traits) I might have broken the edit button somehow o.O ooops.

**Comment by GraionDilach** [comment]
This will be really problematic, considering that we've already added a bunch of traits since last release. Can't we split the Traits page based on namespaces?

**Comment by pchote** [comment]
Thanks for reminding us of this.  We should fix this for the second playtest alongside the planned upgrade rules overhaul.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Traits-%28playtest%29 looks fine to me, so removing from the milestone.

**Comment by pchote** [comment]
IMO the long term fix for both this and the Lua API should be to change the utility rule to output json instead of markdown.  An externally managed project can then present a web interface with a version selector (to change the json source) and a filter field that can be used to quickly narrow down the results to whatever is wanted.

**Comment by GraionDilach** [comment]
It became really dependant on GitHub's server usage at the moment, and i feel it breaks more often than not these days.

**Comment by matjaeck** [comment]
> IMO the long term fix for both this and the Lua API should be to change the utility rule to output json instead of markdown. An externally managed project can then present a web interface with a version selector (to change the json source) and a filter field that can be used to quickly narrow down the results to whatever is wanted.

As in intermediate solution, we could use the generated markdown files in an external project and make them more accessible. I have an example of how it could look like set up [here](https://matjaeck.github.io/OpenRADocs/traits/development/). The software used can be configured to work like a PWA which means that pages you visited earlier in a session are still available offline.

Required changes here would include minor modifications in the formatting of generated files and adjustments to push the generated files to the external site on commit / tag.

While at it, I'd do the same for the lua and weapons documentation. If the external project would get approved by OpenRA members, I'd like to transfer its owbership to the OpenRA organization in similar fashion like we did with [OpenRA/openrauseraccounts](https://github.com/OpenRA/openrauseraccounts).

**Comment by matjaeck** [comment]
It would still be very useful for other projects that interact with the trait/lua data (for example an online tool to create rules) to let the utility output json instead of markdown.

**Comment by matjaeck** [comment]
I have a prototype of the `ExtractDocsCommand` that uses the Newtonsoft.Json dependency to optionally output JSON instead of markdown. It can also optionally write each trait data-object in markdown or json to a file named after the trait.

> An externally managed project can then present a web interface with a version selector (to change the json source) and a filter field that can be used to quickly narrow down the results to whatever is wanted.

I don't know which other fields besides the trait name would be worth filtering. The only advantage I see would be that all versions would be avaiable at one page. Currently each version has its own page. Using static markdown pages has the advantage that they are offline available after loaded in the browser. Unless I get feedback or guidance how to proceed, I'll do the following:

- have a markdown document with all traits like now and a filter field in the table of contents, where trait names are listed to find and jump to the desired section
- have a markdown document for each trait linked from the section with additional git log information, showing the last N changes with a link to the commit on github
- rework the search function to show seach results in tabs for the different versions

**Comment by matjaeck** [comment]
I'm getting the feeling that the mkdocs theme I'm using is not the right thing for us. I like it but it has a ton of node dependencies and we have nobody that is used to work with node and webpack and I am concerned that I will be the only one being able to work with it. And my edits are really ugly and bad hacks that likely conflict with any updates upstream. It would have been fine to use the distributed theme but I think we are not able to maintain a customized fork.

**Comment by Wilmatron** [comment]
Hi all, It appears the Traits wiki page is problematic again as I'm getting "the wiki page took too long to render. This wiki page’s content is too large to render on this page". Just making you aware. Cheers.

**Comment by Mailaender** [comment]
Use https://openhv.readthedocs.io/ in the meantime.

**Comment by Mailaender** [comment]
Ping @Rekojeht who currently blocks the proper OpenRA subdomain.

**Comment by Rekojeht** [comment]
I’ve updated the ReadTheDocs to point to the proper GitHub repo. Let me know of any questions or issues! :)

**Comment by abcdefg30** [comment]
https://openra.readthedocs.io/en/latest/# still seems to point towards `.rst` files that no longer exist in the repository.

**Comment by Mailaender** [comment]
Try setting it to https://www.mkdocs.org/ (MarkDown)

**Comment by Mailaender** [comment]
and maybe add some OpenRA members to the team.

**Comment by pchote** [comment]
> and maybe add some OpenRA members to the team.

It should be basic common security sense to not host any official project services on servers/services that aren't exclusively controlled by the core team.

**Comment by Mailaender** [comment]
Also https://github.com/OpenRA/docs/blob/master/api/release/traits.md etc. now exists which is also rendered and does not seem to suffer from the wiki timeouts.

**Comment by Mailaender** [comment]
We have set up https://docs.openra.net/ now for quite some time.
