### ISSUE TITLE
Make hijacker uncrushable

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#14222]
ZxGanon mentioned this in his stream, and I've thought it's a decent idea to give it a go.

While hijackers are still quite bugged and hence unusable, it can be somewhat a solution to make them not susceptible to crushes so they at least don't die 90% of time they try to capture things.
I remember that half-baked solutions are not exactly favoured, but this at least gives life to a neglected unit and is actually not that bad if you think about it, as hijackers should be proficient with vehicles to not be killed by them right away.

Also #9879 and #10351

**Comment by anjew175** [comment]
This is technically a balance suggestion, not really a fix to the actual problem. The problem with uncrushable hijackers is what happens when there is an unattended hijacker and your only method to kill it is crushing it? You will have to pull all the vehicles (that suck against inf) from the area and move your infantry up. You can say that's fine, but i think its unintuitive to say that an unattended hijacker can't be crushed, especially when they are sitting just outside your ore field.

There is a planned fix outlined in #10351 but obviously due to a lack of manpower, it hasn't be implemented: https://github.com/OpenRA/OpenRA/issues/10351#issuecomment-168159686

**Comment by Smittytron** [comment]
Also keep in mind an uncrushable hijacker can block an ore refinery much like a phase transport can. The ore truck will then wait one cell away, which will make it even easier to capture.

**Comment by pchote** [comment]
Fixing the `MoveIntoTarget` / `Drag` code isn't *that* hard, and would solve the problem properly.

**Comment by netnazgul** [comment]
@Smittytron, by "uncrushable" I'd assume he will always get out of the way of vehicle (so it's probably more like 100% escape chance).

Still the proper solution is of course a better one.

**Comment by AoAGeneral** [comment]
@netnazgul units only move out of the way for your own units. If it is an enemies, they won't budge. Infantry that are uncrushable will ignore the auto move because the tank is unable to drive on the same cell they are standing.

**Comment by matjaeck** [comment]
Fixed by https://github.com/OpenRA/OpenRA/pull/15661#issuecomment-427656171?
