### ISSUE TITLE
Music tracks have different volumes

### ISSUE THREAD

**Issue by Diranus** [OpenRA/OpenRA#14231]
Hello,

the music of the tiberian dawn variant of this game has large differences in volume of the background music. Especially the ones that weren't included in the original C&C game.

For example, the track "Act of Instinct" is there in two variants. One of them is much louder that the other.

One or two in the list are extremely loud and bassy so the music tends to be louder than the sound FX.

This is a bit annoying because I need to adjust the music volume in the game settings every few tracks^^.

Please normalize them or use ReplayGain or something like this so the volume is equal for each track. :-)

The original C&C game hasn't this issue.

**Comment by dan9550** [comment]
I think the way to go "hear" is to work on sourcing better quality music files for in game. Most tracks can be sourced from the game OSTs. Even 128k MP3s should yield a noticeable improvement.

This would remove the need to have the two versions of Act on Instinct as the master on the OST includes the vocals. The game originally had that track removed as the vocals could cause performance issues at the time.

**Comment by GraionDilach** [comment]
>The original C&C game hasn't this issue.

The original C&C didn't enabled the Voiced variants/Heartbreak/Untamed Land. The variant on CnCNet does enable them though, so pretty sure there this same issue appears. Normalizing/ReplayGain is out of the question, because both solutions would involve replacing the files from the original installation which is a no-go.  (ReplayGain is based on metadata, which AUDs can't even store.) There isn't any difference in playback volume from the original game in this regard.

>Most tracks can be sourced from the game OSTs. Even 128k MP3s should yield a noticeable improvement.

The most complete method to gather the songs would be Frank's on-site jukebox (which uses 128 kbps mp3s indeed). However AFAIK even that omits some of the songs.

However, assuming we do have a better quality source for all songs, atm only WAV is supported as high quality audio (OpenRA AUD decoder is limited, see #9227) and WAV filesizes are huuuge to be utilized effectively. In order to consider supporting a HQ music pack - emphasis on consider - there's the implicit prerequisite to include support for a modern audio compressed format.

**Comment by dan9550** [comment]
The easiest solution right now technically and legally would be using the game audio engine. I would have thought that the audio engine in game would allow some kind of limiting / compressor. 

@GraionDilach in an ideal world i would gather songs from Frank's site and rips from my own soundtrack CDs to create a high quality music pack. Adding mp3 to the engine is a little beyond my skills and time right now :( However something i really aspire to do in eventually.

Does someone want to add mp3 support? *nudge nudge*

**Comment by pchote** [comment]
#16034 added a `VolumeModifier` parameter for notification sound definitions.  We can easily define something similar for music if someone wants to volunteer to define a list of modifiers that should be applied.

**Comment by reaperrr** [comment]
> if someone wants to volunteer to define a list of modifiers that should be applied.

The values are rough guesses based on my own, subjective impression:
- TD
  - all Covert Ops tracks: 1.25-1.33
  - all .var tracks: 1.5-1.8
- RA
  - Twin Cannon Remix (CS): 1.25
- D2k: all fine as-is
- TS
  - Nod Crush: 1.2-1.25

**Comment by dan9550** [comment]
I'm happy to give it a go. Let me have a look and I'll have an update in a few days.

**Comment by pchote** [comment]
Tentatively putting this on the milestone because it fits nicely with, and should be trivial to do after, #16034.

**Comment by dan9550** [comment]
So I've taken a glance at the music tracks for RA and TD (with the exception of three as i did not have them). Pulled them out of the MIX as wave files and applied ReplayGain against them.

I have some values we can try out. If these all go well I'll do the same with the missing TD tracks as well as D2K and TS.

@pchote I assume the new VolumeModifier is a percentage based value? E.g 0.33 is 1/3 of the original volume.

**Red Alert**
![screenshot from 2019-01-29 22-38-34](https://user-images.githubusercontent.com/2210900/51908906-f7d3ef00-23c2-11e9-98b2-d0fd05bea9b3.png)

**Tiberian Dawn**
![screenshot from 2019-01-29 23-27-55](https://user-images.githubusercontent.com/2210900/51908925-08846500-23c3-11e9-895f-03a76e3e167b.png)
