### ISSUE TITLE
The "CABAL"-AI fails horribly against easy creep tanks

### ISSUE THREAD

**Issue by Diranus** [OpenRA/OpenRA#14250]
Hello,

I made a skirmish map for six players.
It has some creep buggies here and there. A few creep turrets too. The ones around you are really easy to beat using the handful of units you get in the beginning, when you check at least "light support".

These buggies are more intended to overtake the harvesters here and there during gameplay.

(There are a few mammoth tanks too, but these are far away from each player and weren't involved into this issue. Wether I had to fight them or these kept untouched)

The area near the spawn point is absolutely free of creep units. You can build up your base without the fear of creep attack. And if there is a creep attack, you have the initial units to kill that unit.

So, I played the map two times against the AI of the type "CABAL".
One time with "Light support" and one time with "Heavy support"

Here is, what I discovered during my first attack:

First game:
It horribly failed against one(!) creep buggy and one(!) creep turret :'-(.
To win, I just had to destroy the last leftover - a very damaged power plant.

Second game:
The construction yard was destroyed and the AI had no harvesters anymore and no cash so it stuck with a few cyborgs. 
The harvesters were shot by one turret and it seems that the AI never attempted to destroy that turret. It had more than enough units to destroy a few of them.

Then I started a third game and attacked him using all my initial units just after the beginning - And I lost. He fights hard to me. So he can.

In my next attempt I started a game against two CABAL AI's but with explored map and with "light support". And I just watched, what the two AIs do.

The first one (I made screenshots from it, if you're interested in it):
At first, he moved the MCV out of his army to build somewhere else but not at the spawn. During its way, it gets attacked by two creep buggies. The damaging is low because buggies are weakly armed. He pops out the construction yard and started building.
The initial units are still untouched at the spawn.
He builds a power plant... a refinerie.... a silo.... another power plant... another refinerie... but doesn't come to the building of a cyborg factory because the construction yard gets destroyed just before. That destroying process took minutes. He had enough time to move the initial units to fight the buggies.
Unable to play further from that situation.

The other one:
Pops up the construction yard just where the MCV is. He build the buildings in almost same order. But his harvester was slowly destroyed so he ran out of cash. It is the "harvester against turret" situation. He didn't ever use his initial units to fight that turret. It is only one single turret.
Also unable to play further from that situation.

So he can fight. But he isn't willing to do it, if he gets attacked by a creep tank. It seems to be a difference ;-)

Edit: I forget one important information: It is the Tiberium Dawn variant of the game.

**Comment by GraionDilach** [comment]
Could you upload the map to the Resource Center and link it here?

**Comment by Diranus** [comment]
Yes, I could do it.

But I'm relatively new to GitHub and don't know, how. I can't find the Resource Center :-(.

**Comment by abcdefg30** [comment]
http://resource.openra.net/

**Comment by Diranus** [comment]
Here is it:
http://resource.openra.net/maps/23438/

But this does not happen on just this map. It happens even on a simpler map with nothing but tiberium and creep buggies.

**Comment by GSonderling** [comment]
Well the ai is really simple. In this case it seems that it has trouble issuing attack order against creeps. It could be an issue with the "player" these creeps belong to.

**Comment by GSonderling** [comment]
I did some testing and it looks like the issue is **not** with the player owning the creeps. But with the initial units of Cabal player.

**Comment by reaperrr** [comment]
For the record, we've had complaints in the past about AI attacking Creeps instead of players/other AIs, so it's possible this exception to ignore Creeps was intentionally coded in somewhere (not sure, though).

**Comment by GSonderling** [comment]
I see. However this behavior (ignoring creeps), seems to be limited to initial units the AI gets.

**Comment by GSonderling** [comment]
Ok, I think I have it. 

The issue stems from how AI handles units, specifically, squads:
1. The initial units AI gets are not enough to form a proper squad. Because of that the AI defaults to not creating any squads.
2. The AI can form a squad from any number of units, and send them against the enemy, even if it is suicidal. **But only if the harvesters or buildings come under attack.**

And here lies the crux of the problem, MCVs aren't buildings. 
Even if it has only one left and no construction yards it won't defend it.

Simply adjusting one condition, thus allowed me to mostly get rid of the issue.

Unfortunately there is another, somewhat unrelated, problem. The MCV looking for a better spot to deploy. You see, MCV doesn't consider the fact that it's under attack. **So it just keeps moving.**

The units will do their best to help. But since the MCV has a head start, they just can't catch up.
I don't know why the MCV goes on the trip in the first place. 

However, even with the MCV going haywire and running away, the AI still mostly manages to fight of the buggies and survive. 

Here is the relevant condition from HackyAI,
https://github.com/OpenRA/OpenRA/blob/2e3f302088b15aefba6145c076190dc4a5365d76/OpenRA.Mods.Common/AI/HackyAI.cs#L1260-L1266

And here is my version of the condition:

https://github.com/GSonderling/OpenRA/blob/029e061a3fa7cc10e952b7cc59265844cf5a8732/OpenRA.Mods.Common/AI/HackyAI.cs#L1261-L1266



Arguably I could include a check, to make sure it doesn't fire for just any owned MCV. But since MCVs are a big investment, and AI builds them only rarely it makes sense they should be defended at all costs.

**Comment by GSonderling** [comment]
And here is my version of the condition:
https://github.com/GSonderling/OpenRA/blob/029e061a3fa7cc10e952b7cc59265844cf5a8732/OpenRA.Mods.Common/AI/HackyAI.cs#L1261-L1266



Arguably I could include a check, to make sure it doesn't fire for just any owned MCV. But since MCVs are a big investment, and AI builds them only rarely it makes sense they should be defended at all costs.

**Comment by GSonderling** [comment]
I think this can be closed.
