### ISSUE TITLE
Transforms on condition

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#14297]
As the title say above^ 
I wonder why there isn't any actor replace condition instead of using conditions for every trait, we could just replace the actor, i mean it is more easy that way. 

So can some one make and add this?

**Comment by penev92** [comment]
There isn't because for a long time now we've been trying to move away from everything that has to do with `Transforms`. (it hasn't been removed simply because there are cases like the MCV/ConYard that are way too complicated and fiddly to do with conditions)

In any case, the trend is to move *away* from `Transforms`, not add more traits that use it.
It has a number of inherent issues that range from "very-hard-to-resolve/not-worth-the-effort" to "plain-unfixable".

So I'm gonna have to 👎 the idea.

**Comment by GraionDilach** [comment]
I have it downstream, only for 3rd-party workarounds - I'm not using it myself.

https://github.com/AttacqueSuperior/Engine/blob/master/OpenRA.Mods.AS/Traits/Conditions/TransformOnCondition.cs

**Comment by KOYK** [comment]
It wont be fixed\added, closing it.
