### ISSUE TITLE
Possible description bug. Behaviour of unit in return fire stance doesn't match tooltip description on command bar.

### ISSUE THREAD

**Issue by goonyaa** [OpenRA/OpenRA#14341]
From tooltip description:
> Set the selected units to Return Fire stance:
>- Units will retaliate against enemies that attack them
>- **Units will not move or pursue enemies**

Set unit stance to "ReturnFire".
Enemy unit comes in range.
Enemy unit attacks.
Unit retaliates.
Enemy unit moves away.
Expected unit to not move according to tooltip description.
Unit pursues enemy unit instead.

Tested in openra-ra(release-20171014) on Ubuntu 17.04

**Comment by matjaeck** [comment]
Present in playtest-20180729.

**Comment by matjaeck** [comment]
Present in playtest-20180729.

#14341 shows how deadly this bug can be.

**Comment by reaperrr** [comment]
Moving to Next+1 milestone so we don't forget to at least investigate this.

**Comment by dsimmons87** [comment]
Chasing - especially with infantry - doesn't play well with the cell based OpenRA engine, so I'd suggest removing the chase part - at least for infantry.

**Comment by FrameLimiter** [comment]
Well it isn't *making* it a feature as this is how it has *always* functioned. It's a tooltip typo as it doesn't align with the expected behavior of the stance. 

 Tooltips describe behavior; whether you like this behavior is a separate issue. You shouldn't leave tooltips bogus in hopes the behavior it's suppose to describe will someday be adjusted to match.

**Comment by matjaeck** [comment]
Then have different expectations  - I wouldn't expect or want units to chase enemies when they are in return fire stance, regardless of the tooltip (which I have to admit is what this issue is about. From my perspective, the nature of the return fire stance is closer to the nature of hold fire than anything else. I would expect to use in on units which usually should not attack on their own, but defend themselves - like discovered submarines or stealth tanks. Chasing just doesn't make sense in this context to me, but I can live with another not usable stance.

**Comment by pchote** [comment]
Fixed by #15567.
