### ISSUE TITLE
(bleed) AutoRenderSize returns int2.Zero for WithSpriteBody with any required condition

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#14449]
The bug was introduced (or at least triggered) by the split of Render and Selection bounds.
On bleed this breaks the RA V2 launcher (making it invisible and unselectable), so this is obviously a playtest blocker.

As long as one of the actors' sprite bodies doesn't have any required condition, it works fine, but even with correct condition setup (like for the V2), it breaks when all bodies have some kind of required condition, even if one of them is/should be currently "active".

**Comment by pchote** [comment]
The traitinfo has an EnabledByDefault field that you could use.

**Comment by MunWolf** [comment]
AutoRenderSize checks if (b.Animation.Animation.CurrentSequence) in the where, what if none of the bodies have a CurrentSequence because they have never been enabled? (Shot in the dark here)

**Comment by penev92** [comment]
@MunWolf They have `CurrentSequences`, but they are not enabled, yes.

@pchote 
We're talking about `RenderSprites` checking `Animations`, so `WithSpriteBody`'s `EnabledByDefault` doesn't help here.
Regardless, here are two possible solutions I came up with:

***Option 1.*** IF (and that is a very big "IF" that I don't believe in) it's safe to cache the size of a random (whichever is first) sequence, which was the old/current behaviour and use that forever (pretty sure "deploying" actors can easily invalidate that, but let's leave this for future PRs), then we can easily not care about which is the first visible sequence in order to get its size and just get the size of *the first* (visible or not).
The code in question is:
https://github.com/OpenRA/OpenRA/blob/f249554b4f565099fba5c57d638b4a2a1a149d66/OpenRA.Mods.Common/Traits/Render/RenderSprites.cs#L245-L252

I think we can safely drop the `IsVisible` from that and still keep the old behavior. At some point we'll probably want to *not* cache the size and then we'll need it back.
Also if we go with this I want to point out from now that we want the end result to look more like this
```
		public int2 AutoRenderSize(Actor self)
		{
			var anim = anims.FirstOrDefault(b => b.Animation.Animation.CurrentSequence != null);
			return anim == null ? int2.Zero : (anim.Animation.Animation.Image.Size.XY * info.Scale).ToInt2();
		}
```


***Option 2.*** Due to the nature of `Contitional` traits and the fact that the condition results are applied after the actor is created, in the `Actor`'s constructor there is actually nothing enabled (which you implied with that `EnabledByDefault`), but that is when the bounds are calculated. So if we deffer the calculations for a later time, then the issue solves itself because by the first `Tick` of the actor's lifetime it already has an enabled animation that provides a valid size.

Going with Option 2. may even be better in the long run as I'm pretty sure we'd want to get rid of the caching of the bounds, unless I'm missing something that modders can do to make it work when switching to a different "model" under some condition (deploying into something bigger comes to mind).

**Comment by pchote** [comment]
Deferring the calculation until after the Created calls have been run should be the best option here.
