### ISSUE TITLE
[Wiki] Update coding standard wiki page release number & revise

### ISSUE THREAD

**Issue by aaronfranke** [OpenRA/OpenRA#14679]
https://github.com/OpenRA/OpenRA/wiki/Coding-Standard

The page begins with "As of release-20110511,"

If the coding standard is still the same today, perhaps this should be updated to show that this is still the coding standard? Maybe it should be changed to "As of 2018" rather than a release number. 

Additionally, perhaps we should revise the guide. In particular, I dislike the "Use `var` when declaring temporary variables inside methods" rule, as I love explicit types.

Either way I would like to get the OpenRA team's feedback on this before changing anything.

**Comment by Phrohdoh** [comment]
Hi @aaronfranke,

The coding standard page could probably use some attention!

I'm sure small things have changed over time.

> Additionally, perhaps we should revise the guide. In particular, I dislike the "Use var when declaring temporary variables inside methods" rule, as I love explicit types.

I do not see OpenRA changing from this for a few reasons (read: _opinions ahead_):

1) Once you are familiar with a particular section of the codebase the explicit types are just noise
2) Explicit types force you to update callsites needlessly if return types change (which isn't often the case with OpenRA)
3) I hope this doesn't sound harsh but... I do not think a 10 year old codebase will change something like this that will touch almost every file just because some people prefer explicit types over implicit

**Comment by aaronfranke** [comment]
Well, there's no reason to replace existing working code, but why not allow explicit types for new code?

**Comment by GraionDilach** [comment]
Considering how long names most of our classes have along with the fact that abbreviations aren't used much as a variable's name, using explicit types might end up forcing us to add in linebreaks just for the sake of adhering the rules length rule, while they don't provide any benefit at all.

**Comment by pchote** [comment]
I did a quick pass over the page and updated a couple of outdated points.  The page has be moderately maintained over the years, so was already a good reflection of what we expect.

**Comment by LipkeGu** [comment]
Class definitions like ```RendersEntireVertextBufferObjects<OpenGLRender> renderedVertexBufferObjects = new RendersEntireVertextBufferObjects(VertexBufferobjectsToRender)```

is not very reading friendly... :(

**Comment by pchote** [comment]
> but why not allow explicit types for new code?

I'd like to turn this question around: *why* allow explicit types for new code?

The two common arguments I see are
* The names provide important context in cases like `List<MyFoo> a = Calculate();`.  This is only true because `a` and `Calculate` do not follow best practices for variable and method naming.  We try pretty hard to enforce good naming conventions in OpenRA, so this shouldn't be a problem here.
* This is what i'm used to from &lt;insert other language here&gt; or &lt;the legacy .NET projects I maintain at work&gt;. `var` is considered best practice in the modern .NET world, and tools like Resharper will actually give a warning if you use explicit types.

I'm interested in hearing any other arguments that you have in favor of this.

**Comment by LipkeGu** [comment]
i found a video what im watched a long time ago, related to this topic. https://www.youtube.com/watch?v=ZsHMHukIlJY

**Comment by aaronfranke** [comment]
First I want to say that I completely understand @LipkeGu 's argument. That line of code is indeed very long. For things that end in `new Something();` then the first `Something` does seem redundant. Except of course, if you wanted polymorphism: `Fruit test = new Apple();`

I like explicit types because it gives me flexibility in what types I can use. For example:

    var a = 5;

This will probably default to an `int`. But, what if `a` never needs to go above 100? Why not use `byte` or `sbyte` instead? On the flip side, what if, for some crazy reason, you need to go over 2 billion? Then you'd *need* `long`.

Alternatively, what if you need to force this type to be floating-point? And what type of floating point? It would make sense to me to write `float`, `double`, or `decimal` to enforce that type. What if you wanted a `float` but accidentally wrote `5.0` instead of `5.0f`? Also, `5` would be auto-cast to the floating types if they were explicitly declared.

For context, I'm not new to C#, but I am new to OpenRA and large projects in general. If what I am saying is bad practice, I apologize.

**Comment by LipkeGu** [comment]
We should and could also include this into the wiki: https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.30.pdf

**Comment by penev92** [comment]
>If what I am saying is bad practice, I apologize.

Like @pchote said, the common/best practice for .NET, set by Microsoft, is to use `var` for a multitude of reasons. The acceptable exceptions are when you declare a variable without assigning it and when you really need to force a different type than the one it would default to.

**Comment by abcdefg30** [comment]
No progress since a while, I can think we can close this (the wiki page was adjusted). Feel free to leave a comment if you disagree, I can reopen the issue then.
