### ISSUE TITLE
Playtest 20180102 - Actions/min doesn't count move (and other) commands

### ISSUE THREAD

**Issue by Arular101** [OpenRA/OpenRA#14671]
Tested by ordering the MCV around. Watching the replay afterwards the actions/min stayed at 0.
Attack command is also not counted. However, clicking on structures/units to build in the build-tab is counted.

Thanks FiveAces for noticing it.

**Comment by jongleur1983** [comment]
PlayerStatistics.ResolveOrder() is never called, thus not counting orders.
The PlayerStatistics trait is indeed created and it's ITick.Tick() is called in the game loop.
This updates the statistics (Actions/min and so on), but based on the wrong numbers (number of orders stays 0 due to the missing ResolveOrder)

I have no idea what's the root cause of that, so I can't solve the issue, but perhaps this helps someone else.

**Comment by pchote** [comment]
The APM calculation has always been bogus in OpenRA.  If nobody can volunteer a fix then IMO this should be removed from the observer interface instead of delaying the release further.

**Comment by pchote** [comment]
This was "broken" by #13876.  It turns out that the APM code was *so* bogus that it only accidentally worked by detecting the `CreaterGroup` order.
