### ISSUE TITLE
Selection boxes are rendered about the shroud.

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#14689]
When we select Units like infantry (and keeping them selected) and restart the mission after that, the selection boxes will be rendered about the Shroud.

**Comment by pchote** [comment]
This doesn't make much sense because the selection belongs to the world, which is disposed and recreated when the game is restarted.

I fail to reproduce this by starting Soviet01, selecting the infantry in the base, and then restarting the mission.  Can you please provide specific steps to reproduce and a video?

**Comment by pchote** [comment]
Any updates here @LipkeGu?

**Comment by LipkeGu** [comment]
Yes select a civillian or enemy unit, and let it move into the shroud...

**Comment by matjaeck** [comment]
> Yes select a civillian or enemy unit, and let it move into the shroud...

Can not reproduce.
<details>

![selectionbox](https://user-images.githubusercontent.com/37185497/56495657-bef57300-64f6-11e9-8fba-6da769ae8569.gif)

**Comment by LipkeGu** [comment]
in your Image it is seeable @harvester

**Comment by matjaeck** [comment]
@LipkeGu so, can we close this?

**Comment by deleted-user-1** [comment]
[Comment above](https://github.com/OpenRA/OpenRA/issues/14689#issuecomment-485382374) indicates this was fixed, although not tested against TS.
