### ISSUE TITLE
"Destroy all enemy units" missions are frustrating to complete

### ISSUE THREAD

**Issue by alercah** [OpenRA/OpenRA#14720]
In Dune 2000 in particular (as that's what I'm playing right now), when destroying all enemy units is an objective (which is usually the case), it can get quite frustrating. Because OpenRA includes fog of war, you can't easily find enemy units even if you earlier scouted the entire map, forcing you to scout it a second time and hope that they haven't moved in the process. While it's likely they haven't, or if they are moving it's towards your base, it still leaves a bad taste. This is especially annoying on maps where the enemy gets random reinforcements by carryall.

Perhaps the condition could be weakened to something like "destroy all enemy buildings and all but X enemy units?" on most maps?

**Comment by denartha** [comment]
Dune 2000 is my all time favourite RTS and I've been playing it off and on pretty much since it ever came out. The first computer I played it on was Windows 95 with 4 Megabytes of RAM. As much as I love it, that was always a slight annoyance. You could take over all buildings and kill all obvious troops and still spend another hour scouting around for that last surviving Harvester. To be honest, what I would do is have war fog lift once all enemy buildings are destroyed, because lets face it once that happens, you pretty much control the map.

**Comment by pchote** [comment]
Another option would be to disable the fog of war completely in the missions.

**Comment by Crypto00** [comment]
The "Short Game" option could also be available for the missions.

**Comment by tux314159** [comment]
This is also relevant for Red Alert...

**Comment by Smittytron** [comment]
If there was a list of missions this is a problem in I could tackle this issue. Most likely by setting a trigger for all remaining enemy units to attack when their base is destroyed.

**Comment by PunkPun** [comment]
As of #20299 you no longer need to kill all harvesters
