### ISSUE TITLE
"Fetch Community News" disabled still sends a HTTP request to http://www.openra.net/gamenews

### ISSUE THREAD

**Issue by jrb0001** [OpenRA/OpenRA#14787]
I discovered this in current bleed.
![grafik](https://user-images.githubusercontent.com/2380263/35808404-f061c550-0a85-11e8-95b8-01b9d9013d0b.png)

**Comment by reaperrr** [comment]
@pchote No idea how hard this is to fix, but if it's really easy, we should try to get it into the playtest, in my opinion.

**Comment by pchote** [comment]
Easy.

**Comment by pchote** [comment]
Does somebody plan to take this on, or shall we remove it from the milestone?
Despite being easy, i'm burnt out on OpenRA and already having to force myself to finish the other remaining issues.  I will not be taking this one on.

**Comment by jrb0001** [comment]
You might want to prioritize this bug as the GDPR with its huge fines might be applicable here. OpenRA is leaking personal data even though the user explicitly denied the consent for that (the denial wouldn't even be needed. no explicit consent = you not allowed to process it). And yes, IP addresses can be personal data depending on the situation which you can't control.

**Comment by pchote** [comment]
http://www.openra.net is hosted by github pages, so we don't have access to IP addresses or other request data.

**Comment by jrb0001** [comment]
Sure, GitHub is a Data Processor. But who is actually the Data Controller? And who is creating the software which initiates those connections? It might not be as easy as we would like it to be. I am not a lawyer, but if the bug is solved, this discussion becomes obsolete as well.

**Comment by pchote** [comment]
Please file a PR if you are able to fix this.

**Comment by jrb0001** [comment]
Nope, my IDE (monodevelop) still crashes as soon as I try to open the .sln file.

**Comment by lawando** [comment]
The issue seems to be that [LoadAndDisplayNews](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Widgets/Logic/MainMenuLogic.cs#L285) is called without checking if [FetchNews](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Settings.cs#L189) is true. It's more complicated to fix because the object with the system information is integrated into the function and sent when fetching info (if `SendSystemInformation` is true). It's probably a good idea to split the function into one for each purpose, fetching news and sending sysinfo, but this reuqires knowledge of the server side and could require changes there too (i.e. send the sysinfo to another route so that disabling `FetchNews` does not break sending sysinfo.

If we start to consider HTTP requests without any personal information attributed aside from the IP issuing the request as legal issue, then we can just shut down the internet. Don't think this is critical in this regard.

**Comment by jrb0001** [comment]
I retested the bug and clicked through all menus except the multiplayer one and didn't see a single packet caused by OpenRA.

@lawando The issue here is that you can't assume it's a dynamic address. In my case it is a static one and everybody could link it to my full name and address easily as the data for that has to be publicly available.

**Comment by jmat** [comment]
(@lawando is now @jmat)

> The issue here is that you can't assume it's a dynamic address.

Good point.

> In my case it is a static one and everybody could link it to my full name and address easily as the data for that has to be publicly available.

Could you elaborate on this? I'd like to know how that works.

**Comment by jrb0001** [comment]
@jmat Yes, it's whois but no, it isn't run by a "DNS provider". For address space and AS numbers (except legacy resources), the RIRs are responsible and thus queried.

**Comment by jmat** [comment]
> For address space and AS numbers (except legacy resources), the RIRs are responsible and thus queried.

TIL, thanks!
