### ISSUE TITLE
Playtest 20180208 Crash mhuh1.aud missing

### ISSUE THREAD

**Issue by GRAUPS** [OpenRA/OpenRA#14801]
[exception-2018-02-09T034248Z.log](https://github.com/OpenRA/OpenRA/files/1709781/exception-2018-02-09T034248Z.log)

mhuh1.aud was included in previous versions. Is not included in playtest 20180208.

**Comment by pchote** [comment]
The aftermath assets were removed from the bits folder as part of the installer improvements in [release-20161015](http://www.openra.net/news/release-20161015/) last year.  It is now installed from the aftermath files.

Your specific exception happens when you install the aftermath files from the corrupted iso file that is hosted on CNCNZ.  Delete the ra files from your content directory, and then reinstall the in game assets when prompted by the game.

**Comment by matjaeck** [comment]
Voting for closing as the question regarding missing audio files has been answered.
