### ISSUE TITLE
PUBG mode is possible?

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#14828]
Something like this differences from other modes:
1) huge maps, about like 4 maps from RA2 for 8 players molded into one.
2) a large abundance of civilian structures, neutral military bases, military patrols, hostile to all players, and so on (ie, many units, both neutral and hostile)
3) the number of players in this survival mode is large, from 20 to 50.
5) players start the game by a randomly selected unit that is able to either capture the base (engineer, yuriy), or build it (harvester, MCV)
6) from time to time, shuttles fly to the map or sail boats with MCV AI bases in an amount equal to the number of surviving players in a random place that are at odds with each other and with the players.
7) Unions can not be concluded in this mode
8) The game lasts until only one player left, or until the time specified by the host is over before the game starts. In the second case, the winner is determined by points, which depend on the number of frags, the recruited resources and the lost units.

**Comment by aveferrum** [comment]
PUBG mode? Bah! :) What you mean is "Sole Survivor".
http://cnc.wikia.com/wiki/Command_%26_Conquer:_Sole_Survivor

**Comment by MunWolf** [comment]
I am not sure if we have a hard limit on the number of players in a game. But the main problem I see with it since the multiplayer component is in lockstep so it is not really built for so many people, we already struggle with lag in 8 player games and especially when there is a player with a bad connection.

Big maps also struggle currently especially if they are complicated geography because of the pathfinder logic so at least in its current state I would not consider it possible unless you want to play it in slow motion.

Maybe if we implement some less computationally intensive way to pathfind, and you have 20-50 people that all have a good internet connection it could work out at least in the early game.

**Comment by Unit158** [comment]
@cjshmyr was looking at implement Sole Survivor, but there were some pretty major technical blockers involved IIRC.

**Comment by abcdefg30** [comment]
This is more suited as custom sole survivor style mod.
