### ISSUE TITLE
Actors sometimes ignore other orders when in AttackMove

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#14822]
Tried to find an issue for this first as it is quite old, but couldn't so decided to raise a new one.

Actors sometimes tend to continue attacking the target they acquired during AttackMove command and not respond to successive commands issued to them. Supposedly AttackMove order reverts to Attack order for some of those actors instead of desired Move order (judging by the visual green/red lines).
This makes ordering retreats from bad fights rather annoying as you need to repeatedly issue several move commands (sometimes in a span of up to 2 seconds) so that the whole army finally starts moving, which together with pathing issues and thus prolonged thinking on orders can leave your units under enemy fire for a much longer time than you've anticipated.

![openra_ignore_order_in_amove](https://user-images.githubusercontent.com/1614714/36241358-d8fdad9a-1226-11e8-8305-319bd14ef3cc.gif)
![openra_ignore_order_in_amove2](https://user-images.githubusercontent.com/1614714/36241361-df2e35fe-1226-11e8-833a-f0c30bbb3ca5.gif)
https://youtu.be/XN1ZZ2z3cu0

**Comment by HappyORA** [comment]
This is a pretty annoying problem atm and it coincided with the changes of the auto-targeting as well with other issues with rockets being awful against air units. Right now micro is counter-intuitive because it's far better to position your armies and keep still than make active attacks because the more commands you give units the higher the chance of them breaking and doing stupid stuff.  However, this does not apply to air units. Maybe it's something to do with pathing? I don't know.

**Comment by netnazgul** [comment]
@HappyORA behaviour is the same in 20170527

**Comment by Smittytron** [comment]
Good catch. I've known about this behavior for a long time. I've just always thought it was me mistakenly retreating with an attack move instead of a move command.

**Comment by GraionDilach** [comment]
TBH this looks to me as an engine bug, where the attack-move's switching to attack overriding the retreating move order, because of order throttling (asin, the retreat order is delayed because of reasons like pathfinding and attack-move's interrupting attacks jumps before the move order is actually resolved).

**Comment by pchote** [comment]
Attack Move is a buggy mess that frequently cancels unit activities.  It then has a hack that detects idle units and re-issues the attack-move.  It is likely that is involved here.

**Comment by HappyORA** [comment]
On a related note. The s key seems even worse bugged. Currently, theres times where I have had to mash the s key for my units to finally stop moving. I think it is a related issue.

**Comment by AoAGeneral** [comment]
You can reproduce this problem.

Build vehicles and infantry.
Group vehicles to 1 and group infantry to 2.
Attack move order the vehicles then switch to group 2 quickly.
You will notice the attack move reticle is still on and never got canceled by switching groups.
Issuing attack move on the new group will not work and instead stand by. You must issue the order again.

**Comment by Smittytron** [comment]
Harvesters also have this problem when they are mining. If you order them to move away from an attack they will not respond until they are full.
Do harvesters use the same attack logic or is that a separate issue?

**Comment by AoAGeneral** [comment]
I think its a seperate issue. Because the harvester does move off from the patch. It will only act this way if you click on another area to mine at.

Right click move on ore/tiberium = Harvester/ore truck will stay on its location and mine current spot.
Right click move on open ground = Harvester/ore truck will move.

**Comment by netnazgul** [comment]
> Right click move on ore/tiberium = Harvester/ore truck will stay on its location and mine current spot.

correction - harvester will stay and mine until the spot is empty/it is full. If it becomes empty, harvester will then move to the cell ordered; if harvester is full, he will return to refinery and forget about the last order.
