### ISSUE TITLE
Destroyed airstrip doesn't give money back for undelivered vehicles

### ISSUE THREAD

**Issue by anjew175** [OpenRA/OpenRA#14847]
OpenRA Version: Release 20180218
Mod: Tiberian Dawn

Issue Summary:
If the airstrip is destroyed while a vehicle is en-route, no money is refunded for the lost vehicle.
The money should be refunded to player upon destruction or when the plane leaves the map.

**Comment by abcdefg30** [comment]
Is this still an issue?

**Comment by anjew175** [comment]
Yes

**Comment by abcdefg30** [comment]
The problem is that we just return here https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Buildings/ProductionAirdrop.cs#L103-L104 instead of refunding. I don't know what the best way to refund is though. Perhaps passing the production cost from the queue to `Production` via a parameter of `Produce`?

**Comment by pchote** [comment]
That is probably the simplest solution for now.
