### ISSUE TITLE
[RA] Bug in V2 Rocket Launcher targeting behaviour

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#14921]
Origin: http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&p=306940#306940

Noticed by several people already, highly likely that #14734 is related in a way.

1. When in a-move, V2RL acquires a target and fires onto it. When the target is dead or out of sight, a-move order reverts to a simple move order [until its weapon is ready again].
2. If ordered an a-move command while reloading, V2RL still moves to target and doesn't acquire a target.

Here is my behaviour test on record: https://youtu.be/U6VilFInyrk

Looks like there are two distinct bugs there - first, V2RL reverting from a-move to move when its target is dead and no other targets in weapon range (not consistent, but 90% happening chance); and second, V2RL doesn't look for targets at all when its weapon is reloading, simply moving forward. This is not the case for Artilleries f.e., they still stay on one place and do not move to a-move point when target is dead.

Probably first one is happening as a mix of second one and general buggy a-move behaviour.

**Comment by reaperrr** [comment]
This will be an issue in how our Attack/AttackMove code deals with 'paused' Armaments, because the use of pausing the weapon via condition is the only difference between V2s and artillery.

**Comment by netnazgul** [comment]
Just checked 20171014 and it works correctly there - V2RLs correctly acquire targets even when reloading.

Which means this is a regression.

**Comment by CH4Code** [comment]
Solved this in my d2kA mod for the harkonnen artillery which uses a paused armament by adding a dummy weapon with high reload time and no damage (but same range and targeting).

**Comment by MunWolf** [comment]
Can we use the 'hidden' modifier on the conditions to specify if the Attack Move should ignore it or not?
Just making it so that AttackMove and Attack don't ignore paused armaments is makes it so having a unit that changes into an 'engineer' of sorts will be impossible.

@CH4Code solution also works but I consider it a hack.

**Comment by netnazgul** [comment]
@MunWolf @CH4Code important question here is why this behaviour has changed since previous release.

**Comment by CH4Code** [comment]
Yes, so basically it was similar to having a dummy weapon before, except there had to be an extra trait for it. (AimSequence).

Pausing a trait removes it without causing crashes when some other trait requests if a trait of that type is there. But it is still considered non-active. For armaments and targeting that makes sense, since if you pause them they should be gone. Planes use pausing on armaments for empty ammo pools for example.

The targeting logic has some flaws currently _(camoPB; attack orders on frozen-in-fog but dead actors converted to move command; selecting instead of attacking when attacking with a group of units including one unit which cant target the target (with left-click-orders); turrets following targets indefinitely; turrets not targeting independetly from the tank body move commands; harvesters being non-responsive to commands to harvest elswhere etc..)_ but it is hard to fix apparently so re-adding a 5 line fix for the only unit that works this way seems reasonable to me.

**Comment by netnazgul** [comment]
@CH4Code at least 2 units - MLRS also has this logic now

**Comment by FrameLimiter** [comment]
The issue is the PauseOnCondition added to the armaments.
AutoTarget uses a default ScanRadius of -1 (use weapon range). When an armament is paused it no longer has a weapon range. Dictating a ScanRadius should resolve this.

**Comment by MunWolf** [comment]
@netnazgul We already knew why it happened @reaperrr literally said why in his first commit.
That yaml code changes how we handle reloading the weapon into using conditions.

**Comment by netnazgul** [comment]
Ok, it seems that @FrameLimiter 's suggestion fixes it. Bringing a PR up
