### ISSUE TITLE
Engine support for persisting lobby settings between games

### ISSUE THREAD

**Issue by chrisforbes** [OpenRA/OpenRA#14938]
From OpenRA/ra2#452

**Comment by CarterWilliam** [comment]
I've got a proof-of-concept done for this (https://github.com/CarterWilliam/OpenRA/tree/save-options) but I'd just like to double check the next steps as there are a couple of design decisions that need to be made. Here's a gif of the functionality achieved so far demonstrating saving/loading skirmish options and the map:

![save-skirmish-options](https://user-images.githubusercontent.com/7325691/88839422-f3181300-d1d2-11ea-98a9-1af3cf655e4e.gif)

I think the next step is to allow users to save multiple game templates and to allow them to be renamed/deleted etc. I guess something similar to the game save/load browser widget is what's required here? This will require a lot of changes to `GameSaveBrowserLogic` as all the code relating to saving a game will need to be extracted.

Another query I have is should player settings be added to the saved options or not? It would be nice to have human players saved so you can keep team settings and start points but what happens if they aren't in the lobby yet? Perhaps we should only save the settings for AI players? Or perhaps its easier not to remember player settings at all?

Please let me know about the two questions above and I will complete this in the next week or two.

A massive thanks to the OpenRA community for this project. It's incredible.

**Comment by dragunoff** [comment]
This has been discussed several times already, see #4122 and https://github.com/OpenRA/OpenRA/issues/16699#issuecomment-640288902 that suggest adding support for presets.

And this issue is actually a duplicate of #4122 🤔

**Comment by abcdefg30** [comment]
> Another query I have is should player settings be added to the saved options or not?

Imo no, for the reason(s) you outlined: The player slots will be filled vastly different between games and for different maps.

The save game browser should still be replaced by something looking more like the replay browser, so I wouldn't re-use the same widget logic, but clone it and adapt the clone to what the needs are. (I suppose a simple text display with `Load`, `Rename`, `Delete` might be enough for this usecase.)

**Comment by pchote** [comment]
Closing as duplicate of #4122.
