### ISSUE TITLE
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library.

### ISSUE THREAD

**Issue by bokorember2** [OpenRA/OpenRA#14953]
### Issue Summary

Hello,

My OpenRA game just doesn't let me even start the game. When I run the shortcut then the screen flashes and the game crashes. I attached the exception.log file if you can work out something out of it.
How can I fix it?

Thank you for your help!

#### System Information
- **Operating System:** Windows 10
- **.NET / Mono Version:** could not work out
- **OpenRA Version:** 20170527
- **Mod:** no mods
#### Additional Information:

- Logs

[exception-2018-03-19T190727Z másolata.zip](https://github.com/OpenRA/OpenRA/files/1826597/exception-2018-03-19T190727Z.masolata.zip)
- OpenRA Replays

- Screenshots & Videos

![nevtelen](https://user-images.githubusercontent.com/37554798/37617311-12c54a38-2bb3-11e8-8253-570883ac3333.png)

**Comment by pchote** [comment]
It looks like you are running the old "OpenRA.exe" launcher instead of the mod-specific launchers (Red Alert, Tiberian Dawn, etc).  Did you install a new version of OpenRA on top of an older one?

You should do a full uninstall of OpenRA (you may need to manually delete any leftover files in Program Files and your start menu) and then reinstall the latest version.

**Comment by bokorember2** [comment]
Hey,

thank you for your fast response. What do you mean by "the old OpenRA.exe"?
I installed the game first on 27.05.2017. and this is my very first time
running it. I guess the installed program is the original OpenRA without
any mods. I'll install the newest version now with a full uninstall of the
old one. Let's see what will happen!


2018. márc. 19. du. 8:34 ezt írta ("Paul Chote" <notifications@github.com>):

It looks like you are running the old "OpenRA.exe" launcher instead of the
mod-specific launchers (Red Alert, Tiberian Dawn, etc). Did you install a
new version of OpenRA on top of an older one?

You should do a full uninstall of OpenRA (you may need to manually delete
any leftover files in Program Files and your start menu) and then reinstall
the latest version.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenRA/OpenRA/issues/14953#issuecomment-374341097>, or mute
the thread

**Comment by abcdefg30** [comment]
> I'll install the newest version now with a full uninstall of the old one. Let's see what will happen!

Did uninstalling & reinstalling yield any results?

**Comment by bokorember2** [comment]
Unfortunately not. i tried to start the game with the different mods'
shortcuts, but no result. May the integrated video card makes any sense?

2018. márc. 26. du. 6:41 ezt írta ("abcdefg30" <notifications@github.com>):

**Comment by abcdefg30** [comment]
`graphics.log` might contain some useful information then.

**Comment by rodger-swaggins** [comment]
Newcomer here, I found out what the issue was (at least for me): OpenRA(?) assumes that a 24/32-bit color depth is available.
Source: Was getting the same error log (graphics.log reported "Invalid window") while having my monitor color depth set to 16-bit and OpenRA launched fine after I set the color depth to 32-bit in the control panel for my integrated graphics device.

**Comment by bokorember2** [comment]
Thank you very much for your help, I didn't expect that somebody will find
out what my problem was. In this one year period I bought a new laptop and
OpenRA works fine on it.

Thank you very much!

rodger-swaggins <notifications@github.com> ezt írta (időpont: 2019. márc.
11., H 8:09):
