### ISSUE TITLE
Vision of part of a cell uncovers all units within

### ISSUE THREAD

**Issue by anjew175** [OpenRA/OpenRA#14979]
### Issue Summary
https://imgur.com/a/2vAk1
As evident in the picture, infantry on one side had vision of an entire cell while the other side saw nothing. I think it's expected behaviour to have equal vision.

IRC thoughts: https://logs.openra.net/index.php?year=2018&month=03&day=22#21:54:28

**Comment by Stx3000** [comment]
I use it all the time since few years.
Sad to see it has been discovered. 🤣 
If you have five riflemen in one cell, move them to an adjacent cell to gain a full vision of one cell in the opposite way.

|   |   |   |
|---|---|---|
|   |your __FIVE__ guys here|   |
|   |   |   |

|   |   |   |   |
|---|---|---|---|
|   |   |move them to the right to get the vision in the extra cell on the left|   |
|   |   |   |   |

|   |   |   |
|---|---|---|
|   |your __1-4__ guys here|   |
|   |   |   |

|   |   |   |
|---|---|---|
|   |here they moved to the right but you have the standard vision|   |
|   |   |   |


You can do this "trick" only if you have five riflemen, so doing it is _expensive_.

**Comment by matjaeck** [comment]
> https://imgur.com/a/2vAk1
> As evident in the picture, infantry on one side had vision of an entire cell while the other side saw nothing. I think it's expected behaviour to have equal vision.

This is #16334 and has been fixed in #16953. I think you can not have vision of parts of a cell since it looks like visibility is only calculated for full cells (which would be a separate issue). In that case the title is somewhat misleading, but I might be wrong.

**Comment by reaperrr** [comment]
Closing issue as duplicate, then.

> I think you can not have vision of parts of a cell since it looks like visibility is only calculated for full cells (which would be a separate issue)

The shroud/fog sprites of Westwood games weren't really designed with anything else than full cells in mind, so there hasn't been a real reason to implement support for that yet.
