### ISSUE TITLE
Allow AIs to use inheritance.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#15079]
ATM all AIs are a trait on the Player actor, which prevents them to ingherit from each other, which would be nice to reduce duplication in the common AI settings (like UnitsCommonNames etc).

It would be better to have the AI yamls separated from the rules entirely (like how sequences/voices are) to allow these settings inheritable.

**Comment by pchote** [comment]
The `Inherits` keyword is implemented at the yaml parser level, and #14859 made it so that the actor loader will completely ignore anything starting with `^`.

* Define your AIs as top level blocks starting with `^`.  Use Inherits as you would for actors.
* Define a *second* `HackyAI@myai` block on the player actor, and then use `Inherits` indented by three tabs to pull in the main block of definitions.

This is obviously not a very clean solution, but it should work.

**Comment by GraionDilach** [comment]
I couldn't get it working though.

**Comment by GraionDilach** [comment]
Pretty much resolved with modular AI rewrite.
