### ISSUE TITLE
Buildings with empty footprint dont appear on radar

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#15186]
By empty footprint i mean

Building:
		Dimensions: 1,1
		Footprint: _

on the other hand, this footprint and the regular one works.

Building:
		Dimensions: 1,1
		Footprint: x

**Comment by MunWolf** [comment]
This is because the AppearsOnRadar trait only queries for
```foreach (var cell in self.OccupiesSpace.OccupiedCells())```
but I would say this is a feature not a bug, a footprint with _ is not supposed to be a part of the building so it should not show up on the radar.

If you want to have a cell that is a part of the building but still walkable by units use '=' instead of '_' or 'x'

**Comment by ABrandau** [comment]
No, i double checked that information on the current OpenRA build, an Actor that uses only '=' signs on its footprint wont display itself on radar, same for '_' , just like you mentioned before.

**Comment by reaperrr** [comment]
`OccupiesSpace.OccupiedCells()` only returns cells that block other actors from entering, which iirc is intentional (since it's used in other places as well). The original games only showed occupied cells on the radar, too.

In my opinion that's not a bug. Besides, as long as it's a single-cell actor like in the OP's example, you can just enable `UseLocation` (which is what we do on aircraft, which don't return any occupied cells either, for obvious reasons).

The only problem is that that doesn't work (properly) for buildings that have more than one cell, but all of them _ or =.
That's still more a limitation than a bug, though.

**Comment by ABrandau** [comment]
Use location works, im clossing this commit as it solves the problem.
