### ISSUE TITLE
Chrome OS support?

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#15289]

**Comment by hathlife** [comment]
As I know，Chrome OS has a chroot feature which provides a normal GNU/Linux environment that support gpu. you can try it.

**Comment by pchote** [comment]
My understanding is that Chrome OS is specifically designed to prevent users from running software that isn't a repackaged website or a repackaged Android application.  From this perspective I would say no - as a complicated desktop application, there is no way that we can support Chrome OS.

As mentioned, there are backdoors that you can use to bypass the OS's limitations, but that is making Chrome OS support OpenRA rather than OpenRA support Chrome OS.

Saying that, I have never used or even seen Chrome OS in use, so my understanding may be flawed or outdated.

**Comment by hathlife** [comment]
If you do mean “OpenRA support Chrome OS”,see #8217,since Chrome OS does provides Android runtime.

**Comment by yaaaaa** [comment]
https://techcrunch.com/2018/05/08/you-can-now-run-linux-apps-on-chrome-os/
