### ISSUE TITLE
GitHub links give SSL error on ingame Content Manager on Windows

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#15518]
I was trying to add Music installer to Generals Alpha and noticed GitHub links don't work. Seems like similar problem with #14855.

**Comment by pchote** [comment]
Related to https://github.com/OpenRA/OpenRAWeb/issues/372  We need to fix this in our default mods before we can enforce https on the main website.

**Comment by pchote** [comment]
The default for `System.Net.ServicePointManager.SecurityProtocol` on Windows 10 includes only SSL3 and TLS1.0 - both of which have been EOLed.  This can be fixed by defining `System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;` in an appropriate place - probably our `Download` class.
