### ISSUE TITLE
Dogs die due to grenadier explosion.

### ISSUE THREAD

**Issue by BlackenedRA** [OpenRA/OpenRA#15537]
This kinda defeats the purpose of dogs in anything besides the small extra vision they get.

**Comment by matjaeck** [comment]
What would be the appropriate fix here? Why should dogs not be affected by the grenadiers explosion on death, what justifies the exception here? 

>  the purpose of dogs in anything besides 

This sounds more like a general problem with dogs than like an issue that is specifically caused and thus fixable by changing the behavior regarding the explosion.

**Comment by Smittytron** [comment]
Is this a regression? I want to say that dogs weren't damaged by this before.

**Comment by BlackenedRA** [comment]
Well dogs aren't shooting something explosive so I don't know why they would cause an explosion. The same could be said for zombies/ants too I guess. 

This was changed when grens were changed to always explode. I think the 20170523 release. It went unnoticed I guess.

**Comment by GraionDilach** [comment]
Wrong. This is introduced in this cycle.

This is caused by #15304 - previously dogs triggered the grenadier explosion and units are immune to their own explosions by default - https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Warheads/Warhead.cs#L47 - resulting with attacking dogs safely triggering grenadier explosions without scratches. However with the PR aforementioned, the explosions are now triggered by the dying grenadier, thereby the dog lost it's immunity.

**Comment by GraionDilach** [comment]
>Dogs don't apply damage types

Except that they do. #14777
