### ISSUE TITLE
Add Pixel Tripling

### ISSUE THREAD

**Issue by muchweb** [OpenRA/OpenRA#15963]
Pixel doubling does not produce large enough image on my high-density screen. I want image to stay crisp, so changing display resolution is not considered.

Previously there were unsuccessful attempts for adding arbitrary zooming, but they did not succeed .

Therefore I propose adding basic pixel tripling (x3 zoom).

Pixel multiplication options should be rotated in `x1-x2-x3-x1…` order by a single keypress (<kbd>.</kbd> by default). Checkbox in settings should be replaced with a drop-down.

**Comment by pchote** [comment]
OpenRA has native HiDPI capabilities, but they are disabled by default on Windows and Linux because of poor OS support.  If you're on Windows and *only* if you use an integer display scaling factor (2 or 3, but not e.g. 1.75) then you can add `DisableWindowsDPIScaling: False` under the `Graphics` section in your settings.yaml.  If you're on Linux you can define an environment variable `OPENRA_DISPLAY_SCALE=2`(or 3 or whatever - again this needs to be an integer) before launching the game.

**Comment by muchweb** [comment]
> If you're on Linux you can define an environment variable `OPENRA_DISPLAY_SCALE=2`(or 3 or whatever - again this needs to be an integer) before launching the game.

Thanks. This resolved the issue.

>Pixel doubling is intended as a quick toggle for when you need finer unit control. Introducing additional options in a cycle would hurt this main usecase.

Makes sense
