### ISSUE TITLE
Aircraft fail to properly target a frozen actor after they detect it.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#16010]
Can be easily reproduced with RA Hinds, target a frozen actor, when it detects the frozen actor it stops instead of moving in range and fire.

**Comment by pchote** [comment]
Only affects helicopters - `HeliAttack` was forgotten about (because I was expecting it would go away).

**Comment by pchote** [comment]
`HeliAttack` is a bit of a mess because of the custom move-to-last position fallback.  It may be worth trying to go all in and fix #10223 instead of bodging it further.

**Comment by pchote** [comment]
As discussed on IRC and discord, the problem here goes a lot deeper than just the Actor &lrarr; FrozenActor transition for helicopters. #15866 forgot about (and in some cases broke) everything that wasn't FrozenUnderFog.

https://github.com/pchote/OpenRA/tree/restore-hidden-targets is tracking my current progress on fixing all this properly, which unfortunately means it is much larger than the original #15866. I'll try to give proper context for each group of commits when its ready to PR, so it shouldn't be as intimidating as it might first look.
