### ISSUE TITLE
Potential airstrike camera regression

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#16137]
Reported [on the forum](https://forum.openra.net/viewtopic.php?p=309782#p309782):

>I catched a bug, i parabombed an ai and he shot one of my planes while they dropped the bombs, one of them outcome and flew away.
>The camera then didn't disappear and i had a permanent sight on my enemy.
> I can upload the replay if this helps you.

Sounds like a regression from #15835.

**Comment by dragunoff** [comment]
Most likely a regression from #15835. I can take a look into it later this week.

**Comment by airetaM** [comment]
I made a fast debug game to show when this bug appears with one of the last parabombs i catched it.

https://www.file-upload.net/download-13489621/Camerabug.orarep.html

**Comment by dragunoff** [comment]
This issue is still present on playtest-20190302

Attached is a replay. It happens at minute 19 after a paradrop. The first plane gets shot down before entering range, the rest of the planes get shot down when in range.

[Upps_vs_mo.orarep.zip](https://github.com/OpenRA/OpenRA/files/2954358/Upps_vs_mo.orarep.zip)
