### ISSUE TITLE
Regression: AA Defenses Slow Turn Rate at Max Range

### ISSUE THREAD

**Issue by Orb370** [OpenRA/OpenRA#16251]
AA Defenses at max range (both Sam Site and AA Gun) have slow turn rate when auto acquiring targets.

https://cdn.discordapp.com/attachments/279290580201373696/551288554349789195/AA_Defense_Bug.mp4

Hard to tell, but fire rate seems to be affected as well.

The bug goes away when you manually target or you close in beyond max range.

This behavior isn't present in release.

**Comment by ZxGanon** [comment]
This bug might also cause the turret twitching on most vehicles when something breaches into their maximum range (especially worse for Flak Tracks).

**Comment by pchote** [comment]
This has the same underlying cause as #15345.  The target acquisition and weapon firing code mostly calculates range based on the muzzle position, but `AttackFollow.AttackActivity` calculates range based on the actor center. The two are out of sync within ~1/2 a cell of the max range, with the target being acquired, ticked once, and then cancelled because stationary defenses can't move to close the assumed range gap.  This cycles every AutoTarget scan period, giving the observed stuttery behaviour.

The fix here will be to change all combat logic to uniformly calculate ranges from the actor center - "real" ranges are nice in theory, but too difficult to work and present to the player in a consistent way.

**Comment by GraionDilach** [comment]
Is this the same reason why I keep noticing 2D-3D range inconsistencies in TS/RA2-based mods between air-ground interactions? It implies to me that at some places within the attack code, range is considered in 2D with height differences ignored but at other places height is calculated within.

**Comment by pchote** [comment]
Height should be ignored everywhere. The issue is for weapons that are offset from the center of the actor.

**Comment by GraionDilach** [comment]
TS/RA2 did not ignore height and since missiles have a rangelimit which is based on the travelling distance, height should not be ignored at all.

**Comment by pchote** [comment]
That is really outside the scope of this issue...

**Comment by pchote** [comment]
General bogosity aside, it turns out that this specific issue is caused by a much simpler oversight.
