### ISSUE TITLE
Tiberian Sun / incorrect Power Turbine building

### ISSUE THREAD

**Issue by vgaming** [OpenRA/OpenRA#16325]
In original Tiberian Sun game, the GDI power plant had 2 slots for building "power turbine". It works by having two separate spaces on each of which you can add the turbine.

### Problem
The problem now is that I can "build" another power turbine on top of an already existing one. The overall energy production won't increase, but instead the building slot and associated money is just lost.

### Expected
It'd be nice if "power turbine" would not be allowed to build on a place where a power turbine has already being built.

P.S. I'm testing on "bleed" branch, a3325277d919a27e65c63f1a580458931e8004f5

**Comment by dragunoff** [comment]
How about allowing placement on any slot and autmaticaly filling the next available slot (as long as there are free slots available)?

**Comment by KanoYugoro** [comment]
That's how the GDI powerplant worked in TS, but I actually enjoy picking which slot upgrades go onto.  I could see a scenario in a custom mod where permutations and placement of upgrades on a building matters.  These options aren't mutually exclusive, you could use one as a default behavior and have a property to define the other pattern.

**Comment by vgaming** [comment]
Just to be clear -- the last two comments discuss how to fix the problem, but the problem is indeed there.

**Comment by pchote** [comment]
IMO the best solution from a usability perspective would be to allow plugs to be placed on any cell in the building footprint, but prioritize a specific slot if it was selected specifically.

This could be implemented by changing `Pluggable` to define a footprint instead of an offset, with different symbol types for blocked / accepted / priority. When a plug is placed it can filter all pluggables based on the footprint, ordered by priority/accepted.

**Comment by vgaming** [comment]
Thanks! :+1:
