### ISSUE TITLE
Sudden performance drops

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16350]
Something in this replay causes bad performance. Whatever the cause is seems to happen between (mm:ss): 09:05 - 10:32, 12:18 - (12:26) - 12:51
![Bildschirmfoto von 2019-03-18 23-38-56](https://user-images.githubusercontent.com/37185497/54882953-e574af80-4e5f-11e9-9d83-6fdbd7dd9dec.png)

[OpenRA-2019-03-18T215038Z.zip](https://github.com/OpenRA/OpenRA/files/3000611/OpenRA-2019-03-18T215038Z.zip)

**Comment by St3x** [comment]
Classic pathfinding issue, usually related to units blocked by walls or by missing bridges (like in this game).
The first lag between 09:00 and 10:30 is caused by an artillery owned by I/O near the bottom bridge.
At the exact second (10:32) it stops trying to cross the bridge the lags ends.
The second lag between 12:00 and 13:00 is caused by the five rocket soldiers owned by Antonio Seruti and located 2-3 cells near the bottom bridge.
Again, at the exact second they stop trying to go to the island the lag ends.
To find which units causes the lag in a replay you can pause it, select a lot of units to see their targets and find the ones who can't reach it.
When you experience a lag like this ingame, players can select their units and press S to ask them to stop their current action so nothing will try to cross a non-existent bridge.

**Comment by matjaeck** [comment]
Thanks for explaining this! Closing as a duplicate then.
