### ISSUE TITLE
Streamlining shortcuts for queueing up of attack move orders

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#16381]
Currently to queue up attack orders you need to follow this cycle 
a - hold shift - mouse click - release shift - a - hold shift - click - release shift
and continue this cycle

I propose letting people switch to attack move while holding shift so it would be
a - hold shift - mouse click - a - mouse click - a - mouse click - release shift

**Comment by matjaeck** [comment]
A thing that always bugged me is that attack move has a activate / deactivate behavior while force move is activate only. What I mean is that force move is only active as long as you hold down the force move button but attack move will still be active after button up. Might be related to the feature requested here.

**Comment by pchote** [comment]
Attack move is a distinct order generator, while force-move and force-attack are *modifiers* that affect multiple order generators (including attack move).

**Comment by matjaeck** [comment]
Makes sense. I'm  probably using it wrong then, sometimes it happens to me that I'm still holding down the attack move hotkey after the click order so the attack move order generator becomes (unintentionally) activated again. Retracting my previous statement then.

**Comment by tovl** [comment]
I think the current behavior for the attack-move hotkey is weird and not very practical though. The problem is that  it is a strange sort of 'half switch': you can switch attack-move on, but you can never turn it off again without giving an order (unless you activate another order generator hotkey). Yet for some reason it will turn off automatically after you give the first order. 

It would be much more practical if it would either act like a true switch or as a modifier key.

By switch I mean: Press 'a' and the cursor will stay in attack-move mode until you press 'a' again (or another order generator hotkey). This is similar to how the sell/repair/power order generators already work.

By modifier key I mean to act just like 'ctrl', 'alt' or 'shift': The cursor will stay in attack-move mode as long as it is held and reverts immediately after it is released.

Punsho's example would then look like this:
- tap 'a' - hold 'shift' - mouse click - mouse click - mouse click - release 'shift' - tap 'a'

or this:
-  hold 'a' - hold 'shift' - mouse click - mouse click - mouse click - release 'shift' - release 'a'

It seems to me that either way would make queuing attack-move orders a lot more user friendly. (The argument also applies to 'd' as guard hotkey)

**Comment by matjaeck** [comment]
I would definitely vote for 

> hold 'a' - hold 'shift' - mouse click - mouse click - mouse click - release 'shift' - release 'a'

but this does not work well with the assault move modifier. A radical way to solve the problem would be to remove the assault move modifier since you can just attack-move in attack anything stance.

**Comment by Punsho** [comment]
> you can switch attack-move on, but you can never turn it off again without giving an order (unless you activate another order generator hotkey)

Currently when you press a to get the attack cursor and you cancel it by pressing the left mouse button (right m.b. if using left-click orders)

> A radical way to solve the problem would be to remove the assault move modifier since you can just attack-move in attack anything stance.

Assault move is really handy as for example I forget to put my units back into the defensive stance when using the mentioned method
