### ISSUE TITLE
Harvesters refusing all mining orders on bleed

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#16412]
When an ore patch is mined out some harvesters seem to enter a state in which they start to refuse ALL mining orders. One can still issue move orders and set them to a return trip to refineries

![Harvester bug](https://user-images.githubusercontent.com/37534529/56085521-687c9a80-5e4d-11e9-9291-39fd9591fa88.gif)

A replay where it happens (last bleed commit #16241):
[OpenRA-2019-04-13T211331Z.zip](https://github.com/OpenRA/OpenRA/files/3076756/OpenRA-2019-04-13T211331Z.zip)
 it was first found in RV.

Also I heavily dislike that when an ore patch is mined out Harvesters start a suicide mission to mine ore all the way across the map

@tovl

**Comment by matjaeck** [comment]
The underlying issue that they enter this locked state was also present on bleed before #16193 was merged, see https://github.com/OpenRA/OpenRA/pull/16193#pullrequestreview-215324177. 

> Also I heavily dislike that when an ore patch is mined out Harvesters start a suicide mission to mine ore all the way across the map

This has also been part of the discussion when reviewing #16193, see https://github.com/OpenRA/OpenRA/pull/16193#issuecomment-473103622 and the previous set of comments. Might be better to handle the issue with search locations in a separate issue, since it is not connected to the issue demonstrated above.

**Comment by Punsho** [comment]
@matjaeck it is not the same as it still happens when refineries aren't blocked and the state never goes away

**Comment by matjaeck** [comment]
Then we all have missed this during reviewing it seems. Thanks for clarifying.

**Comment by tovl** [comment]
I'm aware of the issue. It was fixed in #16193 at some point but was then broken again in a later revision. I've already fixed it again in #16408 (first commit). The problem was that `harvester.LastSearchFailed` was never reset, so it would just give up immediately.

> Also I heavily dislike that when an ore patch is mined out Harvesters start a suicide mission to mine ore all the way across the map

They do not go across the entire map (unless the map is very small), but search for resources in a limited radius around the refinery. The search radii are fully exposed to yaml so mods can tweak them to their needs. They are called `SearchFromProcRadius` and `SearchFromOrderRadius` and can be found in the harvester unit definition.

By default they are 24 and 12 cells respectively, but it seems Red Alert overrides them to be 30 and 11. I don't know why these numbers were set that way but 30 seems a bit much to me. If you want harvesters to be extremely cautious (at the risk of them idling more) you could reduce `SearchFromProcRadius` all the way to 12. You could even set it to 0, but then newly build harvesters would idle immediately and that's probably not a good idea. I encourage you to experiment a bit with these numbers yourself and see what leads to the best behaviour.
