### ISSUE TITLE
There needs to be a cluster weapon logic

### ISSUE THREAD

**Issue by RedlerSchnyder** [OpenRA/OpenRA#16438]
For example, when a projectile hits a cell, a second logic would fire a weapon from the cell the previous weapon hits upon. Range depends on what the cluster uses, and make the cluster fire in different facings, or set it to automatically target units(i.e. Red Alert 2's Prism Tank beam).

Also, let me know if there's anything similar and I'll close this forum.

**Comment by pchote** [comment]
This will be fixed by #16363.

**Comment by GraionDilach** [comment]
How I read it though, that this ticket asks for explicit shrapnel logic with child projectiles targeting actors. Cluster targets cells. Explicit actor targeting is not handled within the associated PR.

Note that I have separate warheads between cluster and shrapnel usecases too because of this targeting distinction.

**Comment by RedlerSchnyder** [comment]
@pchote I should've looked at #16363. Thanks for that. Closing now.
