### ISSUE TITLE
Aircraft remain on the service depot after repair

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#16463]
Repro case on bleed: damage a mig and order it to repair at the service depot. Wait for it to finish repairing.

Expected Behaviour: It should take off immediate after repairing (like vehicles) or at worst remain on the ground until another unit needs to repair (like the airfield).

Actual result: It remains on the depot, blocking other units from repairing, until it is manually ordered to leave.

#16352 does not appear to have affected this.

**Comment by reaperrr** [comment]
Migs and Yaks in RA do have `TakeOffOnResupply: false`, so that part is technically correct.
However, the reservation logic - including the yielding part - currently only works on aircraft.

Two possible solutions would be (and from a modders' perspective I'd say we should support both):
1) When #16464 is implemented, refactor `TakeOffOnResupply` into a `TakeOffOnResupplyTypes`, and let MiGs and Yaks auto-takeoff on repair only.
2) Move the part of reservation/yield logic located in `Aircraft` to the upcoming `ResupplyManager` and adapt it to support ground units as well.

**Comment by reaperrr** [comment]
As the roadmap for the docking/resupply refactor has changed quite a bit, the above is no longer up-to-date and fixing this properly for next rlease is unrealistic (too many prerequisites that would need to be tackled first).
I'd say we either defer this to Next+1 entirely, or use a hacky stop-gap work-around for now (hardcode aircraft to always take off on repair) to 'fix' the RA Yak/MiG blocking service depots.

**Comment by pchote** [comment]
Still present after the Land rework.
