### ISSUE TITLE
Revisit artillery changes

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16513]
The timing to merge these parts of  #16244 was not ideal IMO since nobody could forsee how they would fit with the targeting changes and the specific changes we merged have not been the ones that have had extensive testing, mainly because of requests during the the long playtest period. 

The glasscannon our artillery always has been is now more like a sniper unit without enough damage to fit in this role. Especially their accuracy is too high IMO. The damage fall-off has had a good impact overall but could be slightly reduced to make artillery a little bit stronger vs infantry blobs again.

Their effectiveness vs base defences did not really change and overall I'm questioning the shift to an high-accuracy, high firerate, low damage unit.

**Comment by matjaeck** [comment]
Updated.

**Comment by Punsho** [comment]
Ummm, I don't see the underlying reason behind these concerns. It is much better against base defences and is used to kill them. The spread damage change is minor and isn't noticeable unless compared side to side. Because of the increased accuracy and #16109 pr it requires micro to properly hit infantry instead of luck. Artie is not niche, it is a commonly used tool.

**Comment by ZxGanon** [comment]
I agree with Punsho. New Arty is very strong and it´s new accuracy is amazing. Now using micro to shiftfire into blobbs pays off a lot.

I don´t understand these concerns either.
