### ISSUE TITLE
Turreted units do not target enemy units while moving

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#16540]
It's difficult to reproduce the bug by your self. He's the steps:

1. Open 2 clients
2. On one build a light tank. On the other build 2 apc's
3. Attack one apc with the light tank while moving (you have to click on the apc). Key here is to never stop turning/moving
4. Go away from the apc until it's under fow
5. Engage the light tank with the second apc
6. The light tank will not target it nor it will target anything else you send his way apart the the original apc.
I'm repeating again, once the light tank stops. The bug goes away.

![OpportunityBug](https://user-images.githubusercontent.com/37534529/57720128-e8369880-7689-11e9-8021-21e4be7b3cb5.gif)

**Comment by matjaeck** [comment]
It looks like the tank is not dropping the target correctly. With this setup it is easy to reproduce:

<details>

Note the facing of the light tank. Give an attack order, then spam normal move orders.

![Peek 2019-05-18 22-14](https://user-images.githubusercontent.com/37185497/57974589-e7b83d80-79ba-11e9-84a4-9b7aed09587c.gif)

</details

**Comment by Punsho** [comment]
move orders don't need to be spammed

**Comment by matjaeck** [comment]
@Punsho can you reproduce this on bleed?

**Comment by Punsho** [comment]
I can reproduce it easily on bleed

**Comment by pchote** [comment]
Can you please upload a replay based on bleed (you'll also need to mention which commit it is based on) demonstrating the bug?

**Comment by Punsho** [comment]
Here's a replay in skirmish. Last merged pr #16561. Just rename the ending .zip to .orarep
[TurretBug.zip](https://github.com/OpenRA/OpenRA/files/3195182/TurretBug.zip)

**Comment by pchote** [comment]
Thanks.

This happens when https://github.com/OpenRA/OpenRA/blob/a2775a5c0f30490da4881a73f0c261189ee828d7/OpenRA.Mods.Common/Traits/Attack/AttackFollow.cs#L132-L143 sets `RequestedTarget` while the actor is still moving, and the queued attack activity is cancelled before it has a chance to tick. The `RequestedTarget` therefore stays set, blocking the opportunity fire logic from working.

I have a workaround in mind for this, so adding to the milestone.
