### ISSUE TITLE
TD production tooltip icons not aligned

### ISSUE THREAD

**Issue by teinarss** [OpenRA/OpenRA#16606]
Regression from? #16359 

![image](https://user-images.githubusercontent.com/19173272/58501267-48e2cc80-8184-11e9-86f2-bf2040d01ec6.png)

**Comment by teinarss** [comment]
Also saw that the game admin icon was misaligned in the lobby tooltip.

**Comment by dragunoff** [comment]
It is 1px off to the left comared to release. But that's because the sprite on release is 1px off to the right. That may have been intentional. The actual graphic is 6px wide but there is one empty pixel column in the sprite. When I was remaking the sprite I changed the definition to start at the graphic and not 1px before it.
