### ISSUE TITLE
Fix artillery facing when carried with carryall

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#16604]

**Comment by adriencorbalan** [comment]
Hey! @matjaeck can you upload some picture? Thanks! e

**Comment by matjaeck** [comment]
@adriencorbalan See below. Not sure if it's the facing or some offset that is wrong, but the bug should be obvious when testing it ingame. Otherwise I would have written a summary.

<details>

![OpenRA-2019-05-29T152946236Z](https://user-images.githubusercontent.com/37185497/58570055-8f453380-8237-11e9-8689-7eb2ebed9d51.png)

**Comment by reaperrr** [comment]
The only obviously wrong thing I see there is that the barrel of the deployed artillery is rendered as well.

**Comment by deleted-user-1** [comment]
Issue description is wrong so this should probably be closed.

**Comment by pchote** [comment]
This is probably a duplicate of the long standing "ActorPreviews don't understand conditions" limitation.
