### ISSUE TITLE
Update target line and rally point rendering

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#16616]
This issue is for discussion split from #16549.

OpenRA currently uses a single-width line with square end caps for both unit targets and rallypoints:

![Screenshot 2019-05-29 at 21 19 20](https://user-images.githubusercontent.com/167819/58588467-9a0fc080-8257-11e9-8296-992985a9f475.png)

![Screenshot 2019-05-29 at 21 19 04](https://user-images.githubusercontent.com/167819/58588441-8bc1a480-8257-11e9-95d3-ebcc2373a568.png)

Rally points use the player's color, and target lines use the following colors:

* Move: Green
* Attack: Red
* AttackMove: Red
* Guard: Yellow
* Chronotank-shift: LawnGreen
* Harvester move to harvest: Green
* Harvester move to unload: Green
* Harvester move while docking: Green
* Carryall move to pickup/unload: Green
* Supply truck move to donate cash/experience: Yellow
* Engineer move to capture: Red
* Engineer move to repair: Yellow

The general idea being:
* Offensive actions are red
* Defensive actions are yellow
* Other actions are green

These lines are too thin to be easily seen at high resolutions, so we should consider how we can update and improve the visibility and perhaps modernize the style.

For reference, Tiberian Sun and RA2 used dashed lines in the player color (without end caps) for rally points:

![Screenshot 2019-05-27 at 23 11 24](https://user-images.githubusercontent.com/167819/58589634-3e930200-825a-11e9-90a3-9836d4dce3c5.png)
![Screenshot 2019-05-29 at 21 10 39](https://user-images.githubusercontent.com/167819/58589710-6bdfb000-825a-11e9-8e09-db97d73f8888.png)

And single-width lines with end caps for units:
![Screenshot 2019-05-29 at 21 04 15](https://user-images.githubusercontent.com/167819/58589642-418df280-825a-11e9-8f70-ee3dea1ee9b3.png)
![Screenshot 2019-05-29 at 21 11 08](https://user-images.githubusercontent.com/167819/58589735-769a4500-825a-11e9-8f05-5b2d51b4789c.png)

(our current target lines were based on these).

RA2 used a different style for the lines when waypoint mode is active (equivalent to our shift-queueing, but modal):

![Screenshot 2019-05-29 at 21 11 48](https://user-images.githubusercontent.com/167819/58589900-dee92680-825a-11e9-90e1-543f803883e3.png)

Oddly, all lines are drawn in the player color, and note that the currently active line is drawn thinner than the queued lines.

**Comment by pchote** [comment]
#16549 proposes changing the unit target line (but not rallypoints) to a 3px wide line without end caps, with new color assignments:

* Harvester move to harvest: Red
* Harvester move to unload: Blue
* Harvester move while docking: Green (unchanged)
* Carryall move to pickup/unload: Blue
* Supply truck move to donate cash/experience: Blue
* Engineer move to repair: Blue

The general idea being (I think):
* Offensive (expanded to include harvesting) actions are red
* Regular movement is green
* Other actions are blue

![Screenshot 2019-05-29 at 21 36 42](https://user-images.githubusercontent.com/167819/58589501-ebb94a80-8259-11e9-898d-85eaedfd3f48.png)
![Screenshot 2019-05-29 at 21 35 44](https://user-images.githubusercontent.com/167819/58589513-f542b280-8259-11e9-9335-d915ce24aed1.png)

**Comment by pchote** [comment]
IMO the 3px line is too thick, and would much prefer a 2px line with 3px end markers:

![Screenshot 2019-05-29 at 21 51 15](https://user-images.githubusercontent.com/167819/58590423-f2e15800-825b-11e9-857f-2e5552a9fd1a.png)

Rally points should match the line thickness, and we could perhaps think about making them dashed too. We could perhaps consider removing the rallypoint flag indicator considering that we are planning to focus on improving our game mode support in hopefully Next + 1.

I would also prefer to keep the yellow = defensive convention at least for engineers - I don't have a strong objection to using blue for supply trucks and harvesters. I find the shade of blue to be painfully unreadable, however, and think this needs to move more towards cyan.

**Comment by Punsho** [comment]
These lines are just too thick, maybe making them dotted would help

**Comment by pchote** [comment]
![Screenshot 2019-05-29 at 22 25 09](https://user-images.githubusercontent.com/167819/58592583-b532fe00-8260-11e9-8618-aea6089e835e.png)

![Screenshot 2019-05-29 at 22 20 49](https://user-images.githubusercontent.com/167819/58592594-b8c68500-8260-11e9-8c22-356c462c49d0.png)

**Comment by matjaeck** [comment]
> I think it would be interesting to experiment with supporting dashed red/green lines to indicate attack-move, but this may end up being visually awful and cause problems for color-blind players.

After reconsidering, the accessibility concern should IMO not block good ideas like to use a color concept for the order categories. I think the concept with another blue color makes sense, but I prefer an unobtrusive design with 2 colors more that does not displace the ingame artwork more than required, which is most important for me. Colorblind support should be a long term goal.

The dotted lines look very nice, the more examples the better! I would also welcome a different line style for production waypoints since I sometimes forget  whether  I have set a way point or given a move order.

**Comment by netnazgul** [comment]
> These lines are too thin to be easily seen at high resolutions

At the same time, lots of lines (i.e. controlling a huge infantry force) make the lines occupy pretty much half of the screen on move/attack orders, as the lines are opaque. Dotted style will certainly help, but only so much. Mass lines should definitely be checked on impacting visibility when proceeding with this.

**Comment by teinarss** [comment]
Dotted lines looks very good! Could also try it with shadows as in the RA2 image.

**Comment by GraionDilach** [comment]
> We could perhaps consider removing the rallypoint flag indicator considering that we are planning to focus on improving our game mode support in hopefully Next + 1.

All these years I felt that the flag indicator was a really good polish compared to the WW methods, because some color combinations blended the target line into the ground. Considering that ORA player colors are less restrictive than WW, I don't feel even a generalization movement would worth the loss of said polish.

**Comment by tovl** [comment]
Just for the record: The lack of endcaps was an oversight. (Also, 2px lines with 3px endcaps looks good.)

You also forget to mention what I think is the most important color change: AttackMove to yellow and Guard stays yellow.

The idea is that it is important when queueing orders to be able to distinguish AttackMove from both Move and Attack, especially if we do not render the target lines for the attack part of AttackMove. Since Guard is really just a variant of AttackMove and is already yellow it made sense to make them the same color. (I'm not a fan of dashed red/green because I think it would just look too busy.)

Also, with respect to color-blindness, I think we can easily change the specific hues of red/green/yellow/blue to be more distinguishable from eachother with deuteranomaly. Moving away from pure red/green/blue would probably be more comfortable to the eyes for the rest of us as well.

**Comment by pchote** [comment]
The screenshot above is a bit misleading as to the quality of the visuals of the dotted lines. They really don't look very good when used with moving units, groups of units, or moving groups of units.

**Comment by Punsho** [comment]
A gif would help. Tbf the current lines also don't look good on groups of units

**Comment by pchote** [comment]
```
[21:55:34] | <Mesacer_> pchote have you pushed the dotted rallpoints?
[21:55:44] | <pchote> i have a branch called target-lines
[21:55:59] | <pchote> i figured someone would ask so just pushed it
[22:03:18] | <Mesacer_> i agree with you on your comment
[22:03:44] | <Mesacer_> a bit too much distraction
[22:03:45] | <pchote> yeah, its a shame
[22:03:54] | <pchote> see the comment in the code about using b - offset
[22:04:03] | <pchote> it helps a bit, but looks weirder
[22:04:35] | <pchote> e.g. when you have a group of infantry moving to the same cell
```

**Comment by teinarss** [comment]
![rally](https://user-images.githubusercontent.com/19173272/58747533-a9b42280-846c-11e9-96f4-a57c697835fd.gif)

**Comment by Punsho** [comment]
I feel like before we get pathfinding done so units aren't just directed to one cell like in Tiberian Sun & RA2, we won't be able to use dotted nor dashed lines. What could work for the current system is all queued lines being dotted and the action in progress being a full line. Also dots for production rally lines

**Comment by netnazgul** [comment]
Well, that dotted gif above still looks better than the current implementation - at least it creates a "semi-transparent" feel for the lines, so it doesn't obstruct the view as much as solid lines do.

**Comment by dragunoff** [comment]
Er... IMO dotted/dashed lines for immediate orders look bad - it's rather jarring. I suggest to stick with solid lines - 2px with 3px cap seem to be OK. 

Dotted lines for waypoints (every order after the first one) seem reasonable.

For rally points I think that the flag icon at the end should not be removed (I get behind what @GraionDilach said).

I'm not sure about the colors but I agree that it should be an intuitive system with sufficient contrast.

**Comment by pchote** [comment]
I have updated my test `target-lines` branch to base it on #16549 and enable the dotted lines for queued orders only.

This looks a lot better, but the proof of concept will need further refinement if we do want to move forward with this idea.

**Comment by matjaeck** [comment]
I think the dotted lines for queued orders look good. On the one hand it is useful that you now see if a unit is already executing an order, because the dotted lines also appear when the unit has to finish its current move, but on the other hand this adds some visual noise - not sure what to think about it.

Preview of the current `target-lines` branch:

<details>

![lines](https://user-images.githubusercontent.com/37185497/59137561-a77c2780-8988-11e9-97e9-ef2d25064d1e.gif)

**Comment by pchote** [comment]
> the dotted lines also appear when the unit has to finish its current move

> the proof of concept will need further refinement if we do want to move forward with this idea.

:wink:

**Comment by netnazgul** [comment]
One of the reasons I'm concerned with thicker target lines:
![image](https://user-images.githubusercontent.com/1614714/59565734-c56c1b00-905f-11e9-9ff1-9dcfedd7855b.png)
![image](https://user-images.githubusercontent.com/1614714/59565741-d157dd00-905f-11e9-903a-ce0e04793860.png)

You can't see most of the units at all when issuing an order. Spamming the orders obviously makes it worse.

**Comment by tovl** [comment]
Well, those screenshots clearly show that this is already a problem with thin target lines, so not having thick target lines doesn't solve that issue.

Looking at how other games do it: In Supreme Commander issuing an order to a group of units renders only one target line (a very thick one) starting at the center of mass of the units. The target lines are also semi-transparent so any units in between are not obscured. Seems to me like two good ideas.

**Comment by pchote** [comment]
TS/RA2/etc would be better precedent here than supcom.

**Comment by tovl** [comment]
It's a game that is most well know for having tons of units and having a great UI. We would be foolish not to take lessons from it. Also, that's not an argument against any of the actual solutions proposed.

**Comment by matjaeck** [comment]
> Well, those screenshots clearly show that this is already a problem with thin target lines, so not having thick target lines doesn't solve that issue.
> 

But it would make it worse. What about this idea: We show the target lines only when the player is queuing orders with shift or is pressing the ALT key and otherwise don't show them. Other successful RTS (and RA) didn't show any target lines at all. IMO we can mitigate the hard to solve visual issues of mass target lines and get more freedom for the design of the new features if we hide them when giving orders / selecting units (gets us also closer to the original). If people really need them, their purpose to indicate where the unit is going could also be solved by showing only some kind of indicator at the target location, but without a line.

**Comment by tovl** [comment]
That is something worth considering. C&C3 also only showed target lines when queueing orders. 

Another thing to note is that in Tiberian Sun waypoint lines and rallypoint lines where rendered below units (but above buildings). This can be seen in the third screenshot of the OP. C&C3 does something similar but renders the lines below buildings as well. I think either rendering the lines below actors (like C&C3) or making them transparent (Like SupCom) would be the way to go to solve the issue of units being obscured by target lines.

That alone would of course not solve the issue of many target lines merging into a solid block of color. For a relatively small number of lines this could be mitigated a bit by having a border of a different color. Many games do this (including RA2 for waypoints) but this makes at least a three pixel width necessary. 

For a very large number of units (like in the screenshots by netnazgul above) this would still be a visual mess. The only plausible way to solve this completely is to actually reduce the number of target lines drawn, which is why I pointed to SupCom here. Also note that C&C3 already goes halfway in this because infantry are organized in squads which only get one target line each.

**Comment by dragunoff** [comment]
Perhaps we should consider adding waypoint support to rally points (see #15371).

**Comment by netnazgul** [comment]
> Well, those screenshots clearly show that this is already a problem with thin target lines, so not having thick target lines doesn't solve that issue.

Having thick target lines certainly makes it worse though. And I'm still to see the valid reason to make them thicker?.. Is it really a problem on high resolutions?

**Comment by Punsho** [comment]
Another thing that could be added is visualisation of queued deploy orders

**Comment by netnazgul** [comment]
Having some games on the new devtest build, waypoint lines aren't as obstructive as they were due to the new "shown only in waypoint mode" option. Then again, line thickness doesn't really change or enhance the experience at least at 1080p, only stands out in gen1 mods as something non-native cause 1px lines felt like they were to be in the original and 2px+ aren't.

**Comment by abcdefg30** [comment]
:+1: to restoring thinner lines.

**Comment by tovl** [comment]
@netnazgul you make a good point about the thick lines not looking native with the lo-res graphics in gen1 mods. Visibility is still a problem with a moderately sized 1440p monitor (or higher) though, but this is also true for the sidebar and other UI elements. Let's just hope something like #10382  gets implemented soon then.
