### ISSUE TITLE
In replays when 50%, 200% or Max speed is chosen the timer is repeatedly blocked

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#16676]
![Speed](https://user-images.githubusercontent.com/37534529/59182299-123c8700-8b72-11e9-9a33-50a514b1291b.gif)

This is a big annoyance when trying to skip to a specific part in a replay

**Comment by matjaeck** [comment]
An easy fix would be to remove the speed from the timer display, since you see the selected speed already below. Any other ideas how it should be handled?

**Comment by dragunoff** [comment]
I'd say that these labels are redundant and should be removed for the benefit of seeing the timer. Only the "Paused" label should probably stay.

**Comment by GraionDilach** [comment]
IIRC TD, TS and D2k isn't affected in this because the blinking status is under the timer. Moving the blinking status messages under the speed selection buttons (as a floating text below the UI box) would be best of the two worlds.

Personally I believe the blinking texts are much more intuitive then just looking at the buttons alone.

**Comment by Krokoschoko** [comment]
I don't see a need for anything but the buttons. Just removing the text would be preferable to adding another element to the UI. But either option is preferable to what we have now.
