### ISSUE TITLE
build this source code on a webserver

### ISSUE THREAD

**Issue by moh1122** [OpenRA/OpenRA#16692]
Hello
Can you please show me a documentation on how to build this source code on a webserver, i have a linux dedicated webserver and I want to run this source code on it so users can login through a url and play the game, is that supported.

**Comment by matjaeck** [comment]
It's not supported to run the game in a browser if that is what you meant.

**Comment by rautamiekka** [comment]
If I'm not wrong, he wants people to use a web address to login before you can join the 'Minecraft' Server.

**Comment by moh1122** [comment]
Hello 
Thank you for he quick replies 
What i want exactly is to run the game on a webserver. So when i call the url link or web Ip the game runs smoothly.
If that is not supported, please le me know.
I would also like to know if its supported on ios devices?

**Comment by matjaeck** [comment]
You can build the source code on any machine - but to play you need the game client. You can join a lobby from the web browser (if your system supports this out-of-the-box), see http://www.openra.net/games/. Servers can be configured to restrict access via a basic authentication system. https://github.com/OpenRA/OpenRA/wiki/Dedicated might help if you want to setup a game server.

**Comment by moh1122** [comment]
ok thank you @matjaeck 
is there a way to build that client on iOS

**Comment by St3x** [comment]
@pchote said Android/iOS support were not planned (in 2016) : https://github.com/OpenRA/OpenRA/issues/10604#issuecomment-174888338

Just found https://visualstudio.microsoft.com/vs/mac/ and https://blogs.msdn.microsoft.com/cbtham/how-to-use-c-sharp-to-create-ios-app/. You _might_ be able to compile something targeting iOS but I doubt it would work in any way because of the dependencies.

**Comment by moh1122** [comment]
Thank you for your support @st3x
