### ISSUE TITLE
Service Depot bug: new rallypoint movecmd even thought other movecmd exists

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#16761]
After a vehicle is repaired on the service depot a new move command is added to the bottom of the units move cmd list, even if it already has other commands.
This results in vehicles moving back to the rallypoint (after individual move cmds where executed).

Tested with TS service depot and RA service depot on bleed.

Regression [PR #13093](https://github.com/OpenRA/OpenRA/pull/13093)
![openra_bug_servicedepot](https://user-images.githubusercontent.com/25386322/60912250-41373d00-a285-11e9-986c-d4cc56c35f62.gif)

**Comment by reaperrr** [comment]
I had already fixed this locally, but then dropped that because it would break the guarantee of _"first move off host when resupply is cancelled to make sure we don't stay on host when the new order is not a move order"_ which was the reason why this part of the code was introduced to begin with.
As far as I can tell, we can't have both the guarantee that the actor leaves the host AND make it as responsive as requested in this issue without making things horribly complicated, which I'm not motivated to do (especially so close to a playtest).
Personally I agree this is a bigger issue (and more annoying) than the risk of actors staying on the host when the resupply was cancelled via a non-move order, but first I want @pchote' opinion so I won't have to fix/revert/change things multiple times.

**Comment by pchote** [comment]
The simple fix here is to check if `NextActivity` is a `Move` and skip the nudge.

**Comment by reaperrr** [comment]
My point is that this presumably won't trigger for activities that use `MoveTo`, `MoveAdjacentTo`, `MoveWithinRange` or anything of that sort, but yeah, I guess it'll work for normal "Move" orders.

**Comment by reaperrr** [comment]
#16721 should fix this now.
