### ISSUE TITLE
Repairs on Service Depot off-center

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#16782]
A vehicle can be repaired off-center on service depot (all Mods). On **bleed**.

![repair-offcenter](https://user-images.githubusercontent.com/25386322/61291073-b3e87100-a7cd-11e9-94ce-eb44d1cf7718.gif)

**EDIT
RA**: Vehicle must be damaged, moved to edge cell of sevice depot and than clicked on repair. No special conditions to reproduce required.

replay: [repair-offcenter-replay.zip](https://github.com/OpenRA/OpenRA/files/3396857/repair-offcenter-replay.zip)

**TD, D2K, TS**: Similar, but you can't directly drive to an edge of the service depot. You have to repair as normal, before fully repaired press the Stop-Key and as the vehicle moves away, press the Stop-Key again.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25386322/61291693-83a1d200-a7cf-11e9-960e-eb8aae829070.gif)

Regression of #16721 i guess.

**Comment by fruestueck** [comment]
This also allows for repair of several units at once.
![Unbenannt](https://user-images.githubusercontent.com/25386322/61300460-48f56500-a7e2-11e9-92e8-87b0ca4d8f90.PNG)

**Comment by reaperrr** [comment]
This is a bit weird since (at least in theory) `Resupply` checks the distance to host center every tick. Looks like something is wonky there.

**Comment by reaperrr** [comment]
Fun. Unless I'm misreading the code, it looks like this _is not be a regression, but rather an old bug_.

`Target.IsInRange` checks against the closest target position, not against the target center. Basically, every since we gave buildings multiple targetable positions this bug should have been present, but probably got unnoticed in practice. For the record, I've seen this happen with ships before, but back then I thought it had to do with activities just not getting cancelled properly in some cases.

A local test with a speculative fix reinforces that assumption, because it seems to fix the issue in RA. Will file a PR.

**Comment by fruestueck** [comment]
> Fun. Unless I'm misreading the code, it looks like this _is not a regression, but rather an old bug_.
A test on current release shows the following behavior:
- A unit can be send to the top/bottom Cell of the servicedepot (see first post).
- But it can't be repaired off-center. It will use the SD as intendet.

So it seems to be an old bug which just got revealed with the new docking mechanism.
