### ISSUE TITLE
Crashes during single player skirmish (System.NullReferenceException)

### ISSUE THREAD

**Issue by Rude-Boy** [OpenRA/OpenRA#16800]
### Issue Summary

Red Alert crashes after ~15min playing on skirmish (Screen freezes, sound plays on).

#### System Information
- **Operating System:** Kubuntu 19.04
- **.NET / Mono Version:** ... idk sorry but if you tell me how to get this Information, I'll hand it in. 
- **OpenRA Version:** release-20190314
- **Mod:** Red Alert

#### Additional Information:
- Steps to reproduce
	1. start Game (Player vs AI)
	2. Play for about 15 minutes
	3. Screen freezes, sound plays on (for about 2 Minutes), than goes back to desktop

- Logs

[Logs.zip](https://github.com/OpenRA/OpenRA/files/3411710/Logs.zip)

**Comment by pchote** [comment]
Thanks for the report!

This is caused by a bug in the version of mono that is included with (k)ubuntu 19.04. We have already implemented a workaround for this in the next version, which should be available as a playtest within the next few weeks.

Until then, you can work around the crash by updating to the latest Mono release following the instructions on https://www.mono-project.com/download/stable/#download-lin

**Comment by Rude-Boy** [comment]
thanks for the Support! I will try it again with the latest Mono release
