### ISSUE TITLE
Not all the player color picker checks are performed at the same time

### ISSUE THREAD

**Issue by ubitux** [OpenRA/OpenRA#16837]
How to reproduce:
- create a lobby in `openra-ra`, with a forest biome map (might be reproducible with other types)
- click on the color widget, tab "Palette", and select black (bottom-right)
- the following message will appear: "Color was adjusted to be inside the allowed range"
- click on the color widget again, but cancel the operation (clicking away)
- the color will be adjusted again and the following message will appear: "Color was adjusted to be less similar to terrain"

This is reproducible with `openra-20190314` and `bleed` @ c00b13a

This behavior allows the use of forbidden colors.

**Comment by robpvn** [comment]
An important point here is that the colour is not actually changed when you get the message "Color was adjusted to be inside the allowed range" (and you can start the game with this colour), but is is changed when you get "Color was adjusted to be less similar to terrain". So I dug a bit more into it to try to figure it out.

If you pick a terrain colour on the first try, the message "Color was adjusted to be less similar to terrain" will appear and the colour will be changed at once to a less similar colour. 

If you pick the same colour as another player, it will show the message "Color was adjusted to be less similar to another player." while the color is changed at once to a random colour from the preset palette.

So it seems to me:
 - Adjusting to be inside the range is broken
 - Adjusting away from terrain works fine
 - The message is a bit misleading when changing to avoid player colours since it is not adjusted, but randomised.

**Comment by robpvn** [comment]
Correction: The randomised change if you pick the player colour is actually only if you choose exactly the same colour from the palette, if you manually choose from the mixer something as similar as possible it only gets adjusted. (Sometimes so little that it's still hard to tell the difference.) So the text is correct in that case.

**Comment by robpvn** [comment]
Oh bother, I didn't tag this issue correctly for auto-closing when I submitted the PR. @pchote has merged the fix, so this issue can be closed.
