### ISSUE TITLE
Update the issue template

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#16875]
![grafik](https://user-images.githubusercontent.com/7704140/62424128-e994c180-b6ca-11e9-9ec9-0cbe36638cf3.png)

See https://help.github.com/en/articles/about-issue-and-pull-request-templates and https://help.github.com/en/articles/creating-issue-templates-for-your-repository.

**Comment by matjaeck** [comment]
Creating custom templates with default labels looks interesting. I find the instructions as part of the placeholder text not very user friendly though. 

Alternatively, since GitHub shows the link to CONTRIBUTING.md in the sidebar when creating issues, we could instead move the instructions there and only refer to it in the placeholder with something like: "Please read in the contributing guidelines (see "Helpful resources") the section about submitting crash reports and fill in the placeholders below."

This would allow to add clickable links to the instructions, like for example https://github.com/OpenRA/OpenRA/issues?q=is%3Aissue+is%3Aopen+label%3ACrash when asking the user to search for existing issues.
