### ISSUE TITLE
TakeOffOnResupply inconsistency

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16888]
In RA, `TakeOffOnResupply` is true for helicopters but they stay landed in case the helicopter automatically rearmed after giving a force attack or attack order. The expected behavior is they take off.

Tested on 8ffd8ae822e404683927a348b6620970af6b499d.

**Comment by tovl** [comment]
> AbortOnResupply is set to true in RA but planes and helicopters continue their attack-move in case the unit automatically rearmed. Expected behavior based on the trait description is that the unit cancels its previous activity after resupplying. 

This was changed intentionally in #16721 so that orders queued after a resupply activity are not prematurely cancelled. The new expected behavior is that only the current attack gets cancelled and any other activities in the queue are left alone. 

Attack-move and guard are a bit of an edge-case because they will requeue attacks as childactivities. You can argue either way on them but in my opinion they should not be aborted by a resupply. After all, you wouldn't want a unit set to guard to just abandon its ward the first time it has to reload. Similarly, a unit set to attack-move is expected to make an effort to actually arrive at the destination and not give up at the first sign of trouble.

**Comment by matjaeck** [comment]
I agree with https://github.com/OpenRA/OpenRA/issues/13474#issuecomment-306865331 in this regard, but ok, opinions differ. Note that once the aircraft reaches it's attack-move location without encountering enemies, it will idle there with the default stance "Hold Fire". It will not guard anything and just die when attacked, unless you changed the default stance. This makes continued, autonomous attack-moves quite unpredictable IMO and even more dangerous.

**Comment by matjaeck** [comment]
I edited the issue to only focus on the issue with `TakeOffOnResupply`. The attack-move behavior is in this regard the same as in last release and changes can be discussed separately.
