### ISSUE TITLE
Hide target lines by default

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16892]
#16616 shows that even 1px width target lines are problematic when many units are selected. Hiding them by default and only showing them on pressing shift would be an improvement regardless of the target lines' design. As mentioned in https://github.com/OpenRA/OpenRA/issues/16616#issuecomment-502478773 and the following comment, RA1 and the later titles behaved similar (no target lines / no target lines on orders).

One counterargument is that the player loses information. This is essentially only true for the case when you select a group of moving units and immediately see their target lines and also *want that information*. IMO it is not too much effort and can be expected from the player to press shift in case they forgot where they ordered their units, want to inspect queued orders or automatically generated move orders like RTB. Another usecase that is more of a debugging thing is that the target lines indicate whether a unit has giving up on reaching the location it was ordered to or is just blocked. Same goes for the question if the unit is still attack moving. Testing in real games would be needed to say more about the impacts here.

On giving orders, the target lines do not provide any additional  information - the feedback that an order was given is still provided by the circle which appears where clicked.

Opening a new feature request to separate the discussion from the general topic in #16616. The design suggestions there could coexist with this feature.

**Comment by pchote** [comment]
I already have a branch mostly complete that replaces the "Display Target Lines" checkbox in the settings with a dropdown that has three states ("Automatic" - current behavour, "Manual" - only in Waypoint mode, "Disabled" - never show). This will be a no brainer to include in the playtest.

The controversial part which will require further discussion is whether we should change the default from Automatic to Manual.

**Comment by pchote** [comment]
> As mentioned in #16616 (comment) and the following comment, RA1 and the later titles behaved similar (no target lines / no target lines on orders).

TD and RA1 did not have target lines at all.
TS and RA2 behaved like OpenRA does now.
C&C3 only showed target lines in waypoint mode.

**Comment by tovl** [comment]
> TD and RA1 did not have target lines at all.
TS and RA2 behaved like OpenRA does now.
C&C3 only showed target lines in waypoint mode.

As an addendum to that: TS and RA2 did not visualise waypoints the way we do (and C&C3 did). Their waypoints where a completely separate thing from target lines and so target lines where always just a single line segment. In TS and RA2 the visual clutter was made slightly less dense because the lines pointed towards the distributed movement targets. It has been suggested before that this would alleviate our problem as well. However, with our C&C3 style waypoints, showing the distributed lines actually makes the problem much, much worse. This is why I intentionally supressed these lines in #16883; It was a complete visual mess otherwise. Also, I think our problem with target lines is probably worse in the RA and TD mods than it was in TS and RA2 because the sprites themselves are smaller and thus more easily obscured by even the thinnest lines; The original assets simply weren't made with target lines in mind.

I agree with matjaeck that for nonqueued orders there already are sufficient other forms of immediate visual feedback. However, for delayed feedback, target lines are still valueable bits of information even for nonqueued orders, especially for things like guard and attack-move. I still hope that we can adapt the lines to not get in the way of the other visuals too much so that we can fully enable them again (I think the most promising avenue here would be to render them beneath the actors) but barring that I agree that not immediately showing them (except when queueing) is probably for the best.

That said, if we indeed do not show them any more except when pressing shift, I would really like to push for adding an additional hotkey that acts as a toggle instead of a modifier and does not have any other functions (so that you are not forced to first hide existing target lines before you can give a non-queued order for example). I guess the most immediately obvious candidate for such a hotkey would be caps-lock. It is not used for anything else currently and the relationship between shift and caps-lock is already well established by every text editor out there.

**Comment by pchote** [comment]
The main issue with capslock is that it will interfere with the game chat in MP.

I'm hoping / betting on the fact that most players who want the old behaviour will want the old behavior all the time, so they can enable them once in the settings menu then forget about it.
