### ISSUE TITLE
Red Alert: crash with a NullReferenceException when aircraft try to resupply

### ISSUE THREAD

**Issue by rucker** [OpenRA/OpenRA#16925]
### Issue Summary
Game crashes with a `NullReferenceException` when aircraft try to resupply.
... ... ...

#### System Information
- **Operating System:** Ubuntu 19.04
- **.NET / Mono Version:**
```
Mono JIT compiler version 5.18.0.240 (Debian 5.18.0.240+dfsg-2ubuntu2 Wed Apr 17 23:39:09 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       preemptive
	GC:            sgen (concurrent by default)
```
- **OpenRA Version:** release-20190314 (also reproduced with release-20181215)
- **Mod:**  Red Alert

#### Additional Information:
- Steps to reproduce
	1. Begin skirmish game
	2. Build forces until a single aircraft can be created
	3. Order aircraft to attack a target
	4. Crash will occur when aircraft reaches base to resupply

Note: Crash also occurs when AI opponents produce the same scenario.

- Logs
[exception.zip](https://github.com/OpenRA/OpenRA/files/3489308/exception.zip)

The key call in the stack seems to be:

` at OpenRA.Mods.Common.Activities.ResupplyAircraft.OnFirstRun (OpenRA.Actor self) [0x000de] in /home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Activities/Air/ResupplyAircraft.cs:45`

**Comment by pchote** [comment]
Thanks for the report!

Unfortunately the bug here isn't with OpenRA, but with the version of mono shipped by Ubuntu 19.04 and Debian 10. If you want to stick with OpenRA's release-20190314 you can work around the problem by switching to the upstream mono packaging from https://www.mono-project.com/download/stable/#download-lin

If you want to try something more bleeding-edge, we have just released a development preview for the next OpenRA release at https://forum.openra.net/viewtopic.php?f=82&t=20976, which solves this problem (and others) by including its own runtime.
