### ISSUE TITLE
Add visual feedback for the active selection mode

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#17013]
Selection modes (see #15839) are already in the game but they are not exposed in the UI. The user has to know about the feature and even if they know they can't be sure if a mode is active because there is no visual feedback. 

One way to solve this problem is by changing the cursor. A basic illustration of the idea can be seen in this gif:
![cursor-decoration-seletion-modes](https://user-images.githubusercontent.com/1355810/63981461-de656380-cac7-11e9-8912-3de489b080d4.gif)

Another solution that I can think of is to change the color (or fill) of the selection box.

**Comment by tovl** [comment]
I think changing the color of the selection box might be a better solution than changing the cursor. The cursor shape/color is already used for indicating the order mode and adding a separate label next to the cursor might be a bit too much visual clutter. modifying the selection box appearance makes it immediately clear that it is the selection mode that is affected.

**Comment by dragunoff** [comment]
Yes, I agree that changing the color of the box is sufficient given that players know what it means. A cursor would provide more information but would be harder to implement and would introduce some visual clutter. 

For players to know the meaning of any visual cue the actual way to trigger the modes should be exposed (in the settings or in the in-game UI). Modifiers in general are obscure (some of the are described in tooltips) so adding a list of available modifiers to the game or even making them configurable is something worthy of consideration (see #15879).

**Comment by tovl** [comment]
Indeed. These modifiers need to be more discoverable. Order modifiers are exposed through the command bar tooltips (which also provides an on-screen way to access that functionality). Other modifiers could use something similar. (Something like #3954 for example.)

Another option is a one-page manual with all controls on them that is directly accessed from the in-game menu. This is something that many arcadey games do and IIRC 8-bit armies does this as well. We might expand on that idea and make this also the place where all controls hotkeys are configured. So it would be an item directly under the in-game menu instead of being hidden behind the settings menu.

Finally, I think we need to have tooltips in the settings menu in general, so we can explain what a certain option actually does without being limited by the cramped windows.
