### ISSUE TITLE
[playtest-20190825] Aircraft fails to shoot and goes for another pass

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#17050]
Reported in #bug-reporting and on forums.

> 01:22] upps: (PT) Why is the Mig doesn't shoot? Ok the first time I missclick, but on the other flybys?

https://cdn.discordapp.com/attachments/279290580201373696/618571666863161386/Mig_Bug.mp4

**Comment by pchote** [comment]
Can you please provide the replay for this? There is very little that can be debugged from the video.

**Comment by UppsAlert** [comment]
[Minute 29 Mig bug.zip](https://github.com/OpenRA/OpenRA/files/3585902/Minute.29.Mig.bug.zip)
starting arround minute 29 by the black IC

**Comment by pchote** [comment]
The replay shows that the aircraft stays in the `FlyAttack.Fly` child activity much longer than usual, exiting only once it is on top of the target (it is usually a few cells before). It has already passed the minimum range for the weapons, so isn't able to fire.

See:
![Screenshot 2019-09-07 at 21 07 29](https://user-images.githubusercontent.com/167819/64479783-c8d0f780-d1b3-11e9-898c-251cb42c9e70.png) (bugged)

vs

![Screenshot 2019-09-07 at 21 06 29](https://user-images.githubusercontent.com/167819/64479788-e7cf8980-d1b3-11e9-80c8-78a6c574508d.png) (normal).

My gut feeling is that this is probably related to `lastVisibleMaximumRange` and visibility. Any thoughts @tovl?

**Comment by tovl** [comment]
> The replay shows that the aircraft stays in the FlyAttack.Fly child activity much longer than usual, exiting only once it is on top of the target (it is usually a few cells before).  It has already passed the minimum range for the weapons, so isn't able to fire.

That shouldn't matter here. Remember that `FlyAttack` now works completely different than before, because it is now based on `AttackFollow`. The firing part is independent from the movement part and it doesn't care which childactivity it is in. It is the trait code that handles the actual firing, so it staying in the `FlyAttack.Fly` activity shouldn't by itself prevent it from firing. However, it could be caused by the same thing as what is preventing it from firing.

**Comment by tovl** [comment]
Just did some testing. This can be reproduced reliably when you order the plane to attack a building exactly one tick before it disappears under the fog. So it appears the logic for frozen actors is the culprit here. It does not happen when you order the attack earlier and the building becomes frozen at a later point, nor does it happen when you order an attack on a building that is already frozen.
