### ISSUE TITLE
TS shellmap, infantry on move order

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#17073]
The TS shellmap infantry looks to be on moveorder as they pass each other before attacking. Could it be a regression?

**Comment by tovl** [comment]
They are indeed on move order as part of the reinforce path. This error seems to have been present since the map was added.

Unfortunately, that is not the only thing wrong with the TS shellmap: If you run it long enough it will always end up with GDI spawncamping the nod base. It also showcases some pretty bad tile passability errors.

**Comment by fruestueck** [comment]
![gdi-samping-nodbase](https://user-images.githubusercontent.com/25386322/64991522-51494980-d8d2-11e9-90d7-c8e193a6e250.PNG)
Oh, thats really bad. Didn't know GDI is superrior : D
