### ISSUE TITLE
Potential pathfinder regression

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#17158]
The light tank can't move directly to the position below the cursor (simply does nothing when ordered), but is able to go there when manually pathing it:
![pathbug](https://user-images.githubusercontent.com/7704140/65820052-cdbe1f80-e224-11e9-9d95-d55fb6e6bd12.gif)

**Comment by tovl** [comment]
I guess this is bleed, not the playtest?

In that case it is likely a consequence of #16408 and it's interaction with the nearEnough logic. Since the tank is within the nearEnough distance to the target, it will end the move when it get's confronted with an obstacle. In this case it seems to ignore the buggy on the initial pathing instead of pathing around it. That is odd though, because it should not be ignoring stationary actors (only moving actors should be ignored in the initial pathing, unless a path is not possible that way).

If this is playtest, then I have no idea what might be causing this.

**Comment by abcdefg30** [comment]
This was on bleed. Unfortunately I haven't been able to reliably reproduce this so far.

**Comment by pchote** [comment]
Possibly related to #17089, which we now know is caused by stale information in the locomotor pathability cache.

**Comment by abcdefg30** [comment]
I was not able to reproduce this, so closing as potentially fixed.
