### ISSUE TITLE
Pilots spawned from aircraft killed above water freeze in the air

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#17286]
Regression from #17254.

**Comment by tovl** [comment]
This is actually not exclusive to spawning above water. The same thing happens when the aircraft is killed above land. It seems actors spawned upon death do not parachute or perform any kind of initial activity at all (normal paratroopers work fine). When this happens above land, they will glitch to their proper ground position before performing a move order. When above water, they are stuck as they obviously cannot path through water.
