### ISSUE TITLE
Rewrite OpenRA from scratch in C

### ISSUE THREAD

**Issue by openranyet** [OpenRA/OpenRA#17326]
Time and time again, players of this uniq mod have asked about the performance. It routinely performs abysmally, dropping to low-teen framerates in games with more than 6 players. So here I am, asking again on behalf of the entire community. WTF is with up with the terrible perforamnce of this game??

And don't even give me that crap about "it's the players with poor connections or old computers' fault". I can play ANY rts with the exact same players, without having this disgusting performance. This includes RTS's that are more modern than OpenRA, as well as ones that are older. In fact, I can play the ORIGINAL red alert with the same people, created in 1995 for PC's and networks of 1995, without issue. How do you explain that??

The only explanation I can think of is the fact you've chosen .NET for some godforsaken reason. Please immeidately begin work on remastering the game from scratch using a normal language. Thanks!

**Comment by pchote** [comment]
You might find https://github.com/TheAssemblyArmada/Chronoshift to be more up your alley. 

Rewriting OpenRA in C is not a reasonable request, closing as unactionable.

**Comment by GraionDilach** [comment]
> In fact, I can play the ORIGINAL red alert with the same people, created in 1995 for PC's and networks of 1995, without issue. How do you explain that??
>
> The only explanation I can think of is the fact you've chosen .NET for some godforsaken reason. Please immeidately begin work on remastering the game from scratch using a normal language. Thanks!

If the 1995 game (or TS vice versa for the matter) had an option to trigger isometric view instead of orthographic and you manage to enable it, give me a call. Or if you can edit the pathfinder in those games to change the amount of subcells within a cell and not have it optimized for a fixed amount. I have debugged YR and I didn't see any option there doing so for either.

To put it bluntly, the original games had a lot less featuresets than what OpenRA already have. If you want to compare it with something in terms of internal depth, that game shouldn't be a traditional WW game, but should be Warcraft 3 or Generals, because the end principles are closer to those two (just with 2D assets mostly instead of 3D). Everything else is within discussions marked with a "Performance" label over this very bugtracker.

Hardcoding is simple, easy and leads to faster paths, but flexibility is supposed to be this project's forté, which does have a performance cost.

**Comment by reaperrr** [comment]
> Hardcoding is simple, easy and leads to faster paths, but flexibility is supposed to be this project's forté, which does have a performance cost.

And that's also the reason why even a full rewrite of the engine in C, even ignoring the fact that some devs are unfamiliar with it and the amount of work would be completely unmanageable with the remaining dev resources, wouldn't even have that much of a positive impact on performance to begin with (if any).
