### ISSUE TITLE
Balance: Allow mechanics before service depot

### ISSUE THREAD

**Issue by abmyii** [OpenRA/OpenRA#17414]
One of the most frustrating things that can happen in a game (especially early on in a long game) is to lose your MVC/construction yard before building a service depot (in favour of using that time for other buildings) and not being able to capture one from the enemy or take one from your team-mates.

I think it should be possible to build a mechanic after making a war-factory. This still means that you have to capture an MVC or wait for your team-mates to make one, but it doesn't cripple you totally.

**Comment by Punsho** [comment]
Currently if you have 0 mcv's there's a high chance to get one from a crate.

That aside, losing your mcv unintentionally in early game is rather hard. Once deployed it has the most health out of all buildings and incase of serious earlygame danger it can undeploy and run away. That danger can be a large mass of flamers / grenadiers / rocket soldiers or an engineer. All of those are hard countered by static defences mcv itself can produce at will and if undeployed it is faster then they are and can dodge projectiles. There can also be a combined rush of light tanks what only high skill commanders can pull off successfully. That gets countered by just a few anti-armour defences or / and handful of rocket soldiers. The only other threat is a basepush, it can only work if you didn't scout it and your army is caught out of position or you were greedy and didn't build one in the first place. Even then you can undeploy and escape. But losing important infrastructure to that basepush can already cost you the game. Overall if you manage to lose your main mcv it is usually because of the combination of you making a huge error and your teammates not supporting when you need help. 

IMO you should be punished for mistakes. It is not a game where everyone wins, someone must lose. Also in a teamgame if you lose your mcv and the game keeps going for a long time it means that your teammates are much better then the opponent team and possibly that enemies sacrificed lot to kill you and are getting punished for it

**Comment by abmyii** [comment]
> Currently if you have 0 mcv's there's a high chance to get one from a crate.

I got two - no good.

We've discussed this issue quite a bit on the balance-and-playtesting section of the Discord server and came to the conclusion that thieves and mechanics should be ubiquitous across factions (I was playing Soviets, therefore I couldn't steal one), such that it is **not impossible** to recover from the situation, thought still very difficult (having to find and steal an enemy MVC). I think it's a bit too much to make this an irrecoverable situation.

Conversely I think that the chance of getting one from a crate **shouldn't** be high. I think it's too easy of a way out compared with the method I am proposing.

**Comment by Punsho** [comment]
Most of the time competitive games are played with crates off already. It is more a feature for casual play. It isn't very fair to get a light tank from a crate or additional cash is very early stages of the game.

@abmyii I'm not really sure what you are even proposing, I don't know if you noticed but people on discord were agreeing pretty ironically to that proposal as allies already have mechanics and soviets already have thieves.

**Comment by abmyii** [comment]
Allies have mechanics but not thieves, and soviets have thieves but not mechanics. I was asking for **both** to be available to all factions.

**Comment by abcdefg30** [comment]
> since it doesn't make sense that they should be faction-dependent, and therefore why that was ever done.

Faction asymmetry, i.e. pretty much the same reason Soviets have no Medic and Allies have no Shock Trooper.

**Comment by abmyii** [comment]
> IMO you should be punished for mistakes. It is not a game where everyone wins, someone must lose. Also in a teamgame if you lose your mcv and the game keeps going for a long time it means that your teammates are much better then the opponent team and possibly that enemies sacrificed lot to kill you and are getting punished for it

The most interesting games are the ones where someone can come back from the brink of defeat.

> Faction asymmetry, i.e. pretty much the same reason Soviets have no Medic and Allies have no Shock Trooper.

Makes sense not to have shock troopers (because of Tesla), but not a very good reason for the other units (including medic).

Since, it seems, my ideas aren't ideal, I suggest the crates be fixed ASAP so that they actually work the way they were intended.
