### ISSUE TITLE
Placing an AUTHORS file for ModCredits into a mod's main folder will override game's own AUTHORS ingame.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#17459]

**Comment by abmyii** [comment]
Should they concatenate?

**Comment by abmyii** [comment]
Here's the offending line - it looks to be intentional:
https://github.com/OpenRA/OpenRA/blob/2c6c2c00b40110ffeb1bbaf9cc870e7b67f0ea8d/OpenRA.Mods.Common/Widgets/Logic/CreditsLogic.cs#L77

**Comment by GraionDilach** [comment]
Maybe I was too vague.

The issue is that if you name your own file as AUTHORS and add it in that way, it's contents will be shown on both the OpenRA and the "Mod" tab.

**Comment by abmyii** [comment]
Weirdly I don't see tabs, even with an `AUTHORS` file in a mod. All that happens is that the Credits are overridden by the mod's authors.

**Comment by abmyii** [comment]
I tested the code and found that this line: https://github.com/OpenRA/OpenRA/blob/2c6c2c00b40110ffeb1bbaf9cc870e7b67f0ea8d/OpenRA.Mods.Common/Widgets/Logic/CreditsLogic.cs#L42 is loading the mod's AUTHORS. I think it might have to do with the "current directory" of the engine.

**Comment by GraionDilach** [comment]
@abmyii You need to add the `ModCredits` block to `mod.yaml`.

```
ModCredits:
	ModTabTitle: Test
	ModCreditsFile: ra|AUTHORS
```

to get the tabs.

**Comment by pchote** [comment]
The simplest workaround here is for mods to use a different filename.

The simplest "fix" here is to allow mods to override the engine credits file in the `ModCredits` block, which would let mods define an explicit mount for the engine root and tell it to load the main credits file from there.

The real issue here is that files in mod directories were deliberately designed to transparently override files in the engine root back in the early days of the engine. This doesn't make much sense anymore, and the filesystem code really should be redesigned based on our 2019/2020 requirements.

**Comment by abmyii** [comment]
I have a simple workaround until a proper fix is implemented. Should I make a PR?

**Comment by GraionDilach** [comment]
@pchote Sure, I went with the simplest workaround already, but that still renders the bugreport valid.

@abymii No point in touching the code for an engine-level workaround IMO - that'd just sweep the underlying issue under the rug until another example of it comes in.

**Comment by abmyii** [comment]
I think the solution is quite rigorous. How about I submit it and we can see if it is viable?
