### ISSUE TITLE
Make a new key for transports to unload passenger & more

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#17486]
1. Alternative unload key

I think the transport is kinda hard to use in Openra during a fast combat, for its transport function key is mixed up with deploy/trigger ability function. I know it is due to orignal settings of 2D CNC, but still annoying when use. I think give a new hot key for transport to unload can avoid this probelm, as well as can make modders give transport deploy/trigger ability when no needs to consider the conflicts between them.

2. Alternative unload key also includes auto-load passengers function

The extension idea of alternative unload key. There are many transport units in Openra mods, the unloading is easy, which needs one bottun pressed, while the loading is not easy. It makes muti-transports hit-and-run is almost unachievable for casual players, even when we can muti-load up by using Shift key. Therefore, I have an idea. If a key here can let passengers in selection set automatically get on transports in selection set, the transport system will be in more use than normal, and those which can carry one more passenger will be turly useful than those not. The same get-on-transport order can also be applied to AI players make it more smart in attack team with transport units.

To sum up, this function has usecase like:
1. Independent hot key to load/unload for transport. Instead of F for deployment/trigger.
2. when player press the transport hotkey:
    2.1. Passengers in selection set will try to get on transport units in selection set if have any passenger can get on transport.
    2.2. If 2.1 generate no orders, all transport units in selection set will unload panssengers, and game will put panssengers into current selection set together if selectable.
    *2.3. If there is muti-transports can transport each other like Russian dolls, probably we should apply a transport level or transport priority for transport units. But I don't think this function should focus on this problem, afterall it is just a function for tansport combat, which should done within 2 transport level.

**Comment by GraionDilach** [comment]
Unload wired to deploy still makes more sense than the "Attack Ground as Force Attack" hardwire.

**Comment by dnqbob** [comment]
Imagine you build a mine layer APC like CNC3,  or an APC can use EMP pulse when deploy. 

If you are going to achieve things like above, this function is necessary.

**Comment by GraionDilach** [comment]
Both can and should be done differently, minelayers use a different UI function altogether and the pulse-"deploy" can and should probably be done via using regular attack logic.

Red Alert 2 was doing fine without deploy rewired to a second function on the IFV.

The first bullet point makes sense though, but considering the force-attack-as-attack-ground OpenRA invention, the bleeding is justifiable. The second bullet point requires more effort from the coding side than necessary and makes no sense (especially the AI usecase). BTW, Red Alert 2 had matrioshka transport situations with abusable transport slots (flak tracks holding 5 infantry and amphibious transports holding 4 flak tracks, because the trucks themselves took three slots in a transport, regardless of their load).

I like how you talk about modding here as justification but you clearly have no idea about that one.

**Comment by dnqbob** [comment]
I agree with attack ground as force attack to trigger the special weapon.  I didn't think of that

In transport combat part, I just thought there can be something achieve a failed idea in C&C General. In CCG the APC of CHN can use attack to trigger a unload passengers and make passengers attack targets automatically.  This is probably due to EAP wants to make transport combat more automatically and friendly to casual players,  but it seems not successful.

**Comment by abcdefg30** [comment]
Sadly this is out of scope for the default mods. Downstream mods can fork Cargo etc. and implement own behaviour.
