### ISSUE TITLE
Mouse cursor is invisible on loading screen

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#17559]
This might not be such an issue in (pseudo-)fullscreen mode, but if windowed and while multi-tasking it's irritating to not be able to see where the cursor is while it's on the ORA window.
I'm also pretty sure this is a recent regression.

**Comment by pchote** [comment]
This was an intentional feature, and has always been the case - unless #17517 fixed a bug that was accidentally allowing them to be shown?

The issue here is that we render at a low and inconsistent framerate during loading, so software cursors won't work. We could consider whether we want to show hardware cursors if windowed or fullscreen in a multi-monitor setup, but this would introduce an inconsistency between the two cursor modes.

**Comment by reaperrr** [comment]
Hm, ok. It's possible I just didn't notice it before.
Not important enough to put work into creating an inconsistency, I think.
