### ISSUE TITLE
Make networking async

### ISSUE THREAD

**Issue by matthias-hoste** [OpenRA/OpenRA#17664]
## Motivation

I read an issue stating that a lot of observers causes slowdowns(#17656), so I dived into the code and found that the networking part is done in a huge while loop(on a different thread) I'd like to propose the usage of asynchrous socket usage to solve the issues the loop creates

## Proposed solution

I suggest(and am currently writing a PoC) to use Sockets instead of TcpListener and use async calls like BeginAccept, EndAccept, BeginReceive, EndReceive to not have it all going in the same thread in a huge while loop. It would definitely make the server faster and able to handle more connections.

## Side effects

Since I'm new to the codebase I can't predict any side effects. As far as I can see it should work out of the box without negative side effects.

## Alternatives

Keep the while loop, but god, why.

**Comment by abcdefg30** [comment]
@jrb0001's #17571 is currently changing parts of the networking code. I fear there will be conflicts?

**Comment by matthias-hoste** [comment]
Thanks for pointing that out, didn't see that pull. It would conflict only in the Server.cs file though, since he wants to make a list of TcpListeners whilst I think it would be more efficient to just use async. But it will need some discussing with him then

**Comment by pchote** [comment]
OpenRA (like most RTS games) uses a deterministic lockstep model for networking, which is inherently synchronous. Making the sockets async won't help because the game clients still need to block on orders/sync data from all clients before simulating the next tick.

The real fix for spectator lag is to change the client handling so that spectators aren't expected to send non-immediate orders, and to change the main tick loop timings to allow spectators to tick as fast as possible to catch up if they end up behind.

**Comment by jrb0001** [comment]
@lifecoder-phoenix The fix for the spectator lag is to "disconnect" all spectators from the game so the player clients no longer wait for them. My server implementation already does that and it works (but can corrupt replays due to workarounds in the replay loading code).

If you want to rewrite the networking code for async, I strongly recommend using async/await/Task based on TcpListener over using the socket directly. TLS with ALPN (currently blocked by the migration to netstandard2.1) can only be done that way: `SslStream.AuthenticateAsClientAsync(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken)` and `SslStream.AuthenticateAsServerAsync(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken)` are the only ones that accept ALPN configuration.

**Comment by Leonardo-Ferreira** [comment]
> OpenRA (like most RTS games) uses a deterministic lockstep model for networking, which is inherently synchronous. Making the sockets async won't help because the game clients still need to block on orders/sync data from all clients before simulating the next tick.
> 
> The real fix for spectator lag is to change the client handling so that spectators aren't expected to send non-immediate orders, and to change the main tick loop timings to allow spectators to tick as fast as possible to catch up if they end up behind.

This is very interesting... for a couple of hours now I've ben trying to predict what would happen if such lock was dropped... im working on the theory that on modern days connectivity this is not as badly needed as before (when latencies were around 500-1000ms all the time and the bandwidth was smaller than 128kbps)

@pchote would you indulge me and predict what would happen if this lock was removed?

**Comment by Leonardo-Ferreira** [comment]
@Mailaender were you able to progress on your POC? need any help?

**Comment by Mailaender** [comment]
I just added a label like this to the issue. It won't work as it goes towards the wrong direction should actually be closed instead.

**Comment by Leonardo-Ferreira** [comment]
I actually think otherwise... making the network async, or at least `Task` based, is actually a great idea in my opinion. The direct allocation of threads is something that is being discouraged by MS themselves, favouring `Task` that can much more efficiently use the machine resources...

indeed that are some considerations in place and adjustments that need to happen, but as in "overall direction" using `async` has been proving as a very fruitful endeavour.
