### ISSUE TITLE
unrecognized framework

### ISSUE THREAD

**Issue by Maxosaure** [OpenRA/OpenRA#17699]
Hello,

I use a computer with Vista. 

with the Release 20180923 no problem.

But the installation failled with the last version with the message "Openra need framework 4.6.0 or later for work" 

I have the framework 4.6.1 in my computer but obviously openra doesn't recognize it.
I have delete and reinstall the framework but same problem.

have you a solution ? THKS

**Comment by abcdefg30** [comment]
Sorry, sounds like we are out of luck here since .NET 4.6.1 does not seem to be compatible with Vista. (See https://social.msdn.microsoft.com/Forums/en-US/8611be58-4ba0-40a0-846c-1df5de2c164f/net-461-on-windows-vista and https://en.wikipedia.org/wiki/.NET_Framework_version_history )
Your best option will be to upgrade your operating system.
