### ISSUE TITLE
Crash at launch any of cnc/ra/d2k (invalid character in path)

### ISSUE THREAD

**Issue by Aset-Ala** [OpenRA/OpenRA#17804]
- Operating System:  WINDOWS 10
- OpenRA Version: playtest-20200303
- OpenRA Mod: All three.
- Source: www.openra.net/download/

```
OpenRA engine version playtest-20200303
Date: 2020-03-15 17:36:21Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.FileNotFoundException`: File not found: ra|uibits/loadscreen-2x.png
   in OpenRA.FileSystem.FileSystem.Open(String filename)
   in OpenRA.Mods.Common.LoadScreens.SheetLoadScreen.Display()
   in OpenRA.ModData..ctor(Manifest mod, InstalledMods mods, Boolean useLoadScreen)
   in OpenRA.Game.InitializeMod(String mod, Arguments args)
   in OpenRA.Game.Initialize(Arguments args)
   in OpenRA.Game.InitializeAndRun(String[] args)
   in OpenRA.WindowsLauncher.RunGame(String[] args)
```
   here:
ra|uibits/loadscreen-2x.png
d2k|uibits/loadscreen-2x.png
cnc|uibits/chrome-2x.png

all mentioned files in place.

**Comment by pchote** [comment]
@Aset-Ala did you install the playtest on top of an older OpenRA install? Try doing a full uninstall, delete any left over files, and then reinstall. Also make sure that it has not been quarantined by any antivirus software.

I haven't seen any other reports of this issue and can't think of a way that it could be caused by a bug (without affecting everybody), so I expect that this must be caused by a locally corrupted install.

**Comment by Aset-Ala** [comment]
Thanks for attention.
Problem solved.
It was antivirus function, checking installer files during installation.
It is strange that this did not interrupt the installation.
