### ISSUE TITLE
[playtest-20200303] Shellmap crash

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#17801]
```
OpenRA engine version playtest-20200303
Red Alert mod version playtest-20200303
on map f6c528c39e04c6880343ef6be5d2a43d086980fa (Desert Shellmap by Scott_NZ).
Date: 2020-03-15 11:50:58Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.ArgumentException`: Элемент с тем же ключом уже был добавлен.
   в System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   в System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   в OpenRA.Primitives.SpatiallyPartitioned`1.<>c.<.ctor>b__7_1(Dictionary`2 bin, T actor, Rectangle bounds)
   в OpenRA.Primitives.SpatiallyPartitioned`1.MutateBins(T actor, Rectangle bounds, Action`3 action)
   в OpenRA.Primitives.SpatiallyPartitioned`1.Add(T item, Rectangle bounds)
   в OpenRA.Traits.ScreenMap.Add(IEffect effect, WPos position, Size size)
   в OpenRA.Traits.ScreenMap.Update(IEffect effect, WPos position, Sprite sprite)
   в OpenRA.Mods.Common.Effects.SpriteEffect.Tick(World world)
   в OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   в OpenRA.World.Tick()
   в OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   в OpenRA.Game.LogicTick()
   в OpenRA.Game.Loop()
   в OpenRA.Game.Run()
   в OpenRA.Game.InitializeAndRun(String[] args)
   в OpenRA.WindowsLauncher.RunGame(String[] args)
```

**Comment by pchote** [comment]
How long was the shellmap running for before this happened?

**Comment by netnazgul** [comment]
Just several seconds after start, a very strange occurrence. Haven't had any crash issues like this before or after this one.

**Comment by pchote** [comment]
Looking at `SpriteEffect.Tick`, I can see some bogus code that we probably should fix whether or not it fixes the issue. Adding back to the milestone because I do think we should look into this more before we forget about it. We don't necessarily need to block the next playtest.

If `!initialized` we set up the animation and add it to the screen map. We then immediately tick the animation and the position and then update the screen map again. This means that we skip the first frame in the animation and could potentially cause problems like the crash above if the position or size of the sprite change in that first animation/position tick. This is possibly related to #9243.

We are also missing an `initialized` check in `Render`.

I expect that the correct fix will be to put everything after the if() into an else, but this has some risk as it changes behaviour. A safer fix that may fix the crash without changing behaviour would be to add the else, but then also tick the anim and pos before calling ScreenMap.Add in the if().
