### ISSUE TITLE
Allow mod authors to define colors in tooltips

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#17952]
Like so
![16colors - Copy - Copy](https://user-images.githubusercontent.com/5400487/79457729-5fdb1900-7ff9-11ea-82ac-38aa1a668b29.png)

This will help Tiberian Dawn Original mod, to be more well original.

**Comment by pchote** [comment]
This should already be possible - copy `WorldTooltipLogic` into your mod dll project, rename it to `ClassicWorldTooltipLogic`, and change the logic to set the font colour and background image.

IMO adding this logic into the default `WorldTooltipLogic` would be a bad fit, because it depends strongly on mod-specific details (background image definitions, etc).

**Comment by KOYK** [comment]
@pchote Ok so ill close this issue, and then try to do what you said.

**Comment by KOYK** [comment]
How do you set deterrent colors based on players stance?
Red for enemy 
Green for your own
White for neutral
Blue for allied maybe?
