### ISSUE TITLE
[Red Alert] Brainstorming new faction-specific support powers to enrich allied sub-factions variety

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#18093]
Decided this one warrants a separate discussion platform from #18084.

As I said in Discord, #18084 would solve some problems wrt overall faction balance - we have roughly equal number of assets for Allies and Soviets, but Allies have an extra sub-faction so require 2 more assets to be used as faction-specific.
Here's a list of what we currently have. Orange are missing asset "counterparts", light green are faction-specific, yellow is potential aircraft rework with Return of The Hind and a soviet air transport.
![image](https://user-images.githubusercontent.com/1614714/81779002-7f803700-94fc-11ea-9c40-4fe6fbe7e303.png)

After giving it some thought, I'd say removing England feels ~~a French thing to do~~ avoiding liability - it's just too cheap and easy and we should do better. The table above gave me the impression that the direction we should look when considering faction balance is Allied support powers, as there is a much wider room for imagination: support powers don't invade the settled gameplay and nostalgia as much as new artwork assets. And there is already quite a lot of ideas in this regard that even have roots in campaign and feel "in place". 

British Spy should definitely be removed from the game, either making Spy faction-specific (which is fitting and not game-breaking if you think of it) or just removing British one and give England something of the powers mentioned below. 

I suggest we concentrate on something of the list below(mostly taken from @Punsho list at Trello), feel free to suggest other stuff :

1. Chinook drop (_pun intended_)
Could just land and leave infantry or give a full Chinook as well. 
  - 5 riflemen, 3 rocket soldiers
  - 3 riflemen, 3 mechanics, 2 medics
  - 2 spies
  - 3 riflemen, 3 medics, 1 engineer
  - 3 free Chinooks filled with 24 technicians

This one has references to campaigns as Chinooks are frequently used to bring reinforcements for allies. Drop-and-leave implementation seems to require making a slightly different artwork/look for Chinook to distinguish it from player-built ones. If Chinook is made a part of the drop assets, it places a rather large free bonus, so will likely have to be alleviated by a longer timer to balance it against Soviet Paradrop. Alternatively, such drop may also impose some cost to be requested (AFAIK, RV already does something like that for tank drops), though this adds a new implicit mechanic to gen1.

2. Paradrop
  - 2-3 Light Tanks
  - 2 Light Tanks and Ranger
  - 3 mechanics, 2 medics
  - MRJ and Ranger (so an option to get MRJ at T2)

Allies might be granted their own paradrop, either a defensive one (mechanics, medics, engineers) as a counterpart to Soviet's offensive, or even a cargo vehicle drop. Issues here are Badger being Soviet Tu-16 plane (so maybe custom artwork, which will kinda defeat the purpose...) and in case of vehicle drop - its asset cost.

3. Chrono reinforcements
  - 2 Medium Tanks
  - 3 Light Tanks
  - 2 Chrono Tanks?

Has strong references to campaigns. Can potentially substitute German Chronosphere for Germans, with that shared to all Allies (because small Chronosphere is quite underwhelming). If units aren't made permanent (and behave same as usual player chronosphere; probably with a longer timer), asset count can be increased. Also some additional work needed to the look of this power to distinguish it from player-built one.

4. Black Hawk reinforcements, grants 2 Black Hawks.

**Comment by KOYK** [comment]
Those changes feel more like a mod idea and less of a classic streamlined game. This is :-1:  from me, I can go into details but I doubt I will be heard. And more importantly I don't have the time to go from post to post and explain why some ideas might be too far fetched. But I can try if my opposing opinion is important to you.

**Comment by netnazgul** [comment]
@KOYK the proposed idea to introduce faction-specific support powers seems to be the least-intrusive way of providing 2 specials per each sub-faction for Allies. Current faction-specifics for Allies are just too  boring (British Spy) or lackluster (MGG), but there is nothing to substitute them with.

Answering to parallel comments here:
> No idea why people try to balance countries that much, since in MP any one can take any country. Even if some one wants to 1vs1 can just take the same country as his opponent and balance it out.

Well, exactly because in MP anyone can take any country, and if one country is inferior to others it won't be picked, while getting it as Random pick results in handicapped games. In total this just leads to imbalanced and non-varying games (like last release where everyone played Ukraine or 3 years back when everyone played England).

**Comment by Orb370** [comment]
I had a support power where 3 rifleman, a medic, and a mechanic were dropped. It was nice because you could use the mechanic to reclaim husks on the fly.

A lot of these have too much value. I'd model the amount of "free stuff" to the paradrop.

Also the spy drop Soscared implemented was annoying and I don't agree with it as an option.

**Comment by KOYK** [comment]
>  the proposed idea to introduce faction-specific support powers seems to be the least-intrusive way of providing 2 specials per each sub-faction

To me it seems that is the other way around, and it is already intrusive as it is, especially with the German chronosphere, Adding more to this it will only confuse players, and unbalance the game. Allies already can transport units with chinook, and players dont need to be spoon feed by giving them the ability to use paradrops, as the can do that already manually. vehicle paradrop is way too unbalanced to even consider it. chrono reinforcements will only allow allies to literally use 2 chronos, just imagine that.

>  Current faction-specifics for Allies are just too boring (British Spy) or lackluster (MGG), but there is nothing to substitute them with.

I cant comment on personal flavors, tho personally I dont found the MGG boring, since you can chrono it behind enemy lines with some artilleries and lay waste without getting counter by enemy artilleries or v2. further to that I will add that certain aspects of any game can be boring, But the spies are considered an necessity and the tool for unlocking other opportunities in the game, also spies are meant to be used with combination of other units and most importantly tactics, an example will be power down enemy defenses then move in with army. Every RA title has it, no exception in here.

> Well, exactly because in MP anyone can take any country, and if one country is inferior to others it won't be picked

Then the said players should not pick them if they are not going to work on 1vs1 in the first place, if they do they will eventually learn not to take them. Then they can take those countries on team games. 

> while getting it as Random pick results in handicapped games

We can make a new random option named 1vs1 random picks, you can even add this on your own map rules.

> (like last release where everyone played Ukraine or 3 years back when everyone played England).

Who was responsible for those changes?

**Comment by netnazgul** [comment]
> especially with the German chronosphere

German chronosphere can be considered for removal (or sharing to all Allies instead of current one, this is one of the ideas in the community, though I also feel it is damn too powerful) if there are sufficient alternatives.

> I dont found the MGG boring

The point for MGG was not boring, but not giving enough utility to warrant its use. Some rework on GG/MGG is planned, mentioned here https://trello.com/b/y5kxKj9y/gvai-balance-works Maybe it will fix some issues with GG/MGG.

> But the spies are considered an necessity and the tool for unlocking other opportunities in the game, also spies are meant to be used with combination of other units and most importantly tactics, an example will be power down enemy defenses then move in with army.

The mentioned problem is not with Spy itself but with a cheaper version of it existing for England that has no specific artwork. 
Another Spy problem is that some players find it impossible to detect properly while others don't find it a problem at all, this a result of somewhat implicit implementation of its disguise, lack of proper detectors and the mechanic of that detection. It was already mentioned that Dogs do not properly detect Spies even 3 cells apart, and understandably you can't cover your base in Dogs as it defeats the purpose. To balance that Spy actions need to be made less impactful to not make them too powerful.

> Then the said players should not pick them if they are not going to work on 1vs1 in the first place, if they do they will eventually learn not to take them. Then they can take those countries on team games.

Unbalanced faction is always unbalanced, be it 1v1 or 5v5. My comment wasn't attributed specifically to 1v1s.

**Comment by KOYK** [comment]
>  Current faction-specifics for Allies are just too boring (British Spy) or lackluster (MGG)

> The point for MGG was not boring,

I am getting confused here. Is it boring or not?

> but not giving enough utility to warrant its use

Well I mention one use before, but I will mention some others too.

- MGG can be used to cover your army as you approach the enemy base.
- MGG can be used to confuse the enemy and make him think that you have multiple armies approaching his base. ie a decoy.
- MGG can be used to cover an ally if "build off allies" lobby option is turned off
- MGG can be used as an alternative to GG if no con yard is present.
- MGG can be used instead of GG to save power.
- MGG can be used in a sequence as you forward your base from point A to point B without spending money on GG every time you move your mcv.
- MGG can be used to cover your actual army size vs GPS

If you don't think those are not enough, then :man_shrugging: I don't know what to say.

> The mentioned problem is not with Spy itself but with a cheaper version of it existing for England that has no specific artwork.

Why is that a problem? the owner knows that the spy he build is the cheaper version.

> Another Spy problem is that some players find it impossible to detect properly while others don't find it a problem at all, this a result of somewhat implicit implementation of its disguise

That is fixed, with the new scale UI, player can now see all units when he zooms in\out. The old players as far as I know they have no problem with this, and that is logical too since an experienced user can detect them by getting used by the color palette of the game and the actors. That is for the owning player, for the enemy players it does not matter any way since the spies have to use disguise, other wise units will automatically kill them.
On a side note on that, phase transport is harder to detect by eye than the spy.

> It was already mentioned that Dogs do not properly detect Spies even 3 cells apart, and understandably you can't cover your base in Dogs as it defeats the purpose.

Give dogs larger detection range.

> Unbalanced faction is always unbalanced, be it 1v1 or 5v5. My comment wasn't attributed specifically to 1v1s.

My previous comment(s) still stands, please take the time to re-read them.

But I will pinpoint my arguments exactly so they can be clear, so you wont have to search for them.
And not miss the point, as I might have not been clear in the first place.

> Well, exactly because in MP anyone can take any country, and if one country is inferior to others it won't be picked, while getting it as Random pick results in handicapped games. In total this just leads to imbalanced and non-varying games (like last release where everyone played Ukraine or 3 years back when everyone played England).

Quoting my other post below from the PR #18084

> My point here is that all countries have their counters and they can counter other countries in MP. The problem is that people fail for some reason to see this. Usually new players, and they stuck with the idea that they are weak as they are now.

And

> And also Certain countries can be adjusted to further support their role, for example some countries can be made to work better in a 1vs1 game but less in team games, and other countries might be good in team games, and get a more of a team supporting role.
> 

And

> And different combinations of countries in team games can also lead to a more specialized overall strategy that team mates can pick suited more to their game style (imagine clans and team tournaments here). Allowing for even more "streamlined" MP gameplay seen in other games like starcraft or dota, were tournaments and competitive gameplay takes place more often than in RA.

So since you presented all the reasons on why this idea should be used. 
And as you can see I am still not convinced that this idea can work out, unfortunately this is still :-1: from me. But if you came up with a more viable solution this might change.

But this is my opinion always. Other people might like it.

**Comment by netnazgul** [comment]
> If you don't think those are not enough, then man_shrugging I don't know what to say.

I didn't say that there are no uses to MGG, you keep answering to points that you invent for yourself. 
All the things you mentioned don't give MGG enough utility to have an intention to build it instead of other units.

> Why is that a problem?
> That is fixed, with the new scale UI, player can now see all units when he zooms in\out.

Same as above.

This discussion strays away too much from the OP, so I don't see the point for debating on it further here. 

Note on "don't add any more support powers" is taken.

**Comment by KOYK** [comment]
> I didn't say that there are no uses to MGG

> The point for MGG was not boring, but not giving enough utility to warrant its use

> I didn't say that there are no uses to MGG, you keep answering to points that you invent for yourself. 

It seems you are unable to think strait at this moment. 

> This discussion strays away too much from the OP, so I don't see the point for debating on it further here. 


As I said and quote

> So since you presented all the reasons on why this idea should be used.
> And as you can see I am still not convinced that this idea can work out, unfortunately this is still -1 from me. But if you came up with a more viable solution this might change.
> 
> But this is my opinion always. Other people might like it.

It is clear that you are upset, And by repeating what I said in an aggressive manner only confirms it.
I would suggest to calm down and re think your behavior attitude.  We are all working for the same cause here. It is not polite to react in this way, especially when I was being polite in the entire conversation to you friend. It is ok, some people some times don't like our ideas, so there is no need to get their opinion on a personal level. Any way thank you for trying to come up with an idea, even if not a viable one. and I say again in my opinion friend.

**Comment by Inq8** [comment]
I support @Mailaender 's suggestion in #18084 of making the British spy, the only spy.
The unit even has an existing English accent so it is literally perfect for a faction unit.

Adding to that, I like the idea of moving the Mobile Gap Generator to another faction or made another common Allied unit. With the loss of the Spy, France & Germany would lose their spy detector so I think this ability should be passed to MRJ's or MGG's to give these units additional functionality & usefulness in the game.

The removal of MGG from England allows the inclusion of a faction support power.

In the original game, Allied players could infiltrate Soviet airfields to gain the para-drop ability, therefore the Spy & Para-drop would go hand in hand together as faction abilities.

I feel the English version of the para-drop would be the least outlandish support power idea & probably the most palatable for classic Red Alert players, mitigating the amount of community backlash received. 


Additionally, on the subject of Chronosphere, the idea of making all Allied factions have a 3x3 box has been bouncing around for years but no one has done anything about it. 

The main hangup/point of contention is "what do we give Germany if they lose German Chrono?"

All I can think of at the moment is either discount Chronosphere production cost or some support ability like Chrono reinforcements that's been discussed above.

**Comment by Orb370** [comment]
I would dislike MGG/MRJ having spy detection. We just got done removing all the arbitrary cloak detectors.

If it comes down to it, no one (or almost no one) uses spies to detect spies. The main detection method has always been seeing them come in. There will also be less spies on the field since only Britain can field them.

If we could, it would be really nice if Chronotanks can be made a common allied unit, before touching the German chrono. Allies don't have a lategame main combat unit (Tanya is a hero unit, MRJ is support, Longbow a skittish flier).

**Comment by netnazgul** [comment]
To end the topic on Spies and detection (I feel it warrants a separate issue) - the best way would be to share dogs between factions, as well as [greatly] increase Dogs' Spy detection radius so that they will actually be useful to catch spies. I.e. something like 10-15 cells, so Dog starts running towards enemy Spy and catches him long before he infiltrates anything.

**Comment by pchote** [comment]
Provided that doesn't mean also expanding the dogs vision range (the slow growing creep of vision in RA has become a major source of perf problems, as we saw recently with aircraft), that could be good.

**Comment by abcdefg30** [comment]
This would be how RA2 handled it. We'll need to add an override for the campaigns, but that will not be a problem.

**Comment by Orb370** [comment]
I don't like having dogs on both sides, since allies have medics as an early game advantage, and soviets have dogs. It's a nice dichotomy.

It wouldn't be the end of the world though.

**Comment by pchote** [comment]
If the spy becomes england-specific, do we really need a general detector unit for them? It's all well and good to theorycraft, but are players *actually* going to spread dogs around their bases every time they play against an english opponent?

**Comment by tovl** [comment]
I don't really have a horse in this race, but I feel I have to comment, because it seems you are all missing the elephant in the room here:

Why insist on having _two_ unique units per subfaction?

The original game had no unique units for subfactions whatsoever and the same total number of assets (except the flak truck). The inspiration for this feature seems to have come from RA2, but even that game only gave _one_ unique unit to each subfaction. Why do you want to make twice as many units exclusive to subfactions using assets that where never meant to be divided at all, while also insisting you can't add anything new either? Is it that much of a surprise then that you end up with at least one weak subfaction and a unit roster that seems somewhat incomplete?

So I'd suggest to consider having just one unique unit/power per subfaction. That would give you a lot more wiggle room to make this work and if it's good enough for RA2, why wouldn't it be good enough for RA1?

**Comment by Orb370** [comment]
I would be in favor. Fake buildings for France, Phase Transport for Britain, German Chronosphere for Germany. Make Chronotank and MGG general Allies units.

Soviets is a bit more tricky. Tesla trooper can be global (Russia retains Tesla Tank). I'm not sure how to handle Ukraine though. I'm half tempted to say remove Parabombs, but I know people love the ability. It most most sense for Ukraine to have demo truck option, so I guess parabombs would be made a general soviet ability? Maybe we could increase the cooldown some.

**Comment by pchote** [comment]
FWIW all factions got the demo truck in the OG aftermath, but it feels much more appropriate as a faction special. Removing the parabombs to somewhere rare (crate special? tech structure?) would be the easiest way to fix all the balance complaints surrounding that, too.

**Comment by Smittytron** [comment]
> I would be in favor. Fake buildings for France, Phase Transport for Britain, German Chronosphere for Germany. Make Chronotank and MGG general Allies units.

Phase Transport and German Chrono >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Fake Buildings

**Comment by Orb370** [comment]
Both are late game bonuses, Fake Buildings are useful even at the start of the game.

Phase transport isn't as powerful as it used to be and no one builds Chronospheres.

**Comment by Orb370** [comment]
Also any way you look at this France is going to get fake buildings as their ability (it's not going to be a general Allies perk), so I don't really see any other options, even if we do agree fake buildings aren't good.

**Comment by netnazgul** [comment]
Least intrusive way of approach then:
- England: Phase Transport;
- France: Fake Buildings;
- Germany: Advanced Chronosphere ;
- Russia: Tesla Tank;
- Ukraine: Demo Truck;

- British Spy discount is removed, MGG and Chrono Tanks are shared to all Allies;
- Tesla Troopers shared to all Soviet;
- Parabombs are removed, potentially left to some neutral capturables.

I feel CTank may be German unique instead this way and Adv. Chrono removed completely as it is way to massive in teamgames.
Also would be sad to see Parabombs go, but well. Solves a lot of directional powers issues this way too.


@KOYK see, good ideas came out of all this in the end ;)

**Comment by netnazgul** [comment]
@Smittytron you haven't seen Moods' Fakepush done to you then.
This is a screenshot of 2v2 where WhoCares drowned me with fake power plants:
https://media.discordapp.net/attachments/697864027421802640/710498325396455474/france_fake_spam.png

**Comment by KOYK** [comment]
@netnazgul I never said that its not possible, I just generally don't agree with the OP idea.

> Parabombs are removed, potentially left to some neutral capturables.

Why we want to remove this? (in details please)

> I feel CTank may be German unique instead this way and Adv. Chrono removed completely as it is way to massive in teamgames.

I strongly agree with this, But let me explain some things first. Personally I used the German Chronosphere a lot in team games, using my infamous 14 med tanks and 20 mechs tactic. 
And it always solve problems, but also countless times players get really upset by it. 
And this is understandable, meaning that as much as I enjoy using it, I also understand how annoying and unbalanced this is for other players.

Though there is a problem, in maps like bombardment islands (maps that deny ground combat, and air attacks are impossible due to massive anti air defenses) the first player who builds a nuke usually wins. So the game end up being just a race vs time, and no fun whatsoever, and people we already have the option to set a timer in the lobby :p.

So the only way to disarm the enemy team from its nukes is the German chronosphere, since sending 5 units with the regular chronosphere wont work as they die the moment they are teleported. So I will **STRONGLY** suggest that we should add a lobby option for Nukes and separate them from the Tech Level option. This will allow to prevent games like these to happen but also allow the usage of chronosphere and iron curtain separately.

It will also be wise to separate Iron curtain and chronosphere while we are at it, from Tech Level since we can do this now using the new LobbyPrerequisiteCheckbox trait. Allowing the players to further customize their game experience the way they see fit. But separating Iron curtain and chronosphere from the Tech Level option can be done in an other PR. 

> Tesla Troopers shared to all Soviet;

> British Spy discount is removed

We need to balance other aspects for this though. 
Probably Like RAGL IX maps solve this, by adding more HP to the medium and light tanks. 
Since the British with this change, no longer get the ability to produce the tank numbers that are needed to counter soviets (without penalties on eco). And most importantly sharing shock troopers will most definitely require those changes to be added on the Light and medium tanks.
Other wise the balance will favor the soviets and players wont pick allies any more.

Also a side note to compare things.

In the original game:
Light tank had: 300 hp
Medium tank had: 400 hp
Heavy tank had: 400 hp
Mammoth tank had: 600 hp

In openra:
Light tank has: hp 22000
Medium tank has: hp 45000
Heavy tank has: hp 60000
Mammoth tank has: hp 90000

So as you can see above we really need to boost medium and light tanks health, as they are currently paper tanks.

**Comment by Smittytron** [comment]
The problem with giving each faction only one special unit is people will go back to picking one nation as one bonus will clearly stand out from the rest.

The main reason I set out to swap the phase tank and MGG was to stop this habit of only picking only one nation. I believe I have succeeded in this goal, and I believe that one-sided nations are a greater problem than uninteresting nations.

I'd also like to point out that this is an incredibly minor issue compared to the recent controversies. No one is trashing OpenRA because 'england is boring' like they were trashing us for having an Allied hind. If every other idea around this is too controversial, nofix is the way to go here.

That said, here are a couple of ideas of my own:
A) Move MGG and possibly ChronoTank and Shock Trooper down to radar tech. Kazu recently had a game vs me where he used MGG to great effect. It's certainly not worthless. If people had more time to build the things you don't see built, you might just see them pop up in games.

B) https://www.youtube.com/watch?v=E-8jVmM5bs4 (don't think too hard about this one)

**Comment by PunkPun** [comment]
@KOYK 
You are operating under some misguided info, when comparing stats you need to compare cost as well (850 vs 1150). When you compare Medium to Heavy tank, medium has slightly higher health per cost, slightly higher dps per cost, and medium is plain faster. The only thing heavy tank has going for it is burstyness in its weapon and its cost. They are pretty well balanced, with the current consensus being that heavy tank is bit stronger

**Comment by KOYK** [comment]
@Punsho yeah because I am not comparing prices, I am comparing the issue of allied paper tanks vs old RA. I am not trying to balance the entire game in one post of course. I Just pinpoint one problem. I don't know, what do you think about allied tanks, are ok as they are now?

**Comment by netnazgul** [comment]
@KOYK @Punsho no real point to debate over LT/MT health not being buffed, if it is already considered to get a health buff next release?


> Parabombs are removed, potentially left to some neutral capturables.
> Why we want to remove this? (in details please)

Parabombs were just too wacky-random before directional support powers took place. But now they are still a balance problem in a different way, its effectiveness being heavily biased by maps as it is just a free damage dealt at the edge of the map. Adding teamgames with multiple Ukraine factions being picked (I mentioned that already above), and you get a teamplay a-bomb levels of damage (and even more actually) dealt every... 6 minutes (?) at the cost of having an airfield. Slowing the bombs was an immediate counter-nerf to it, but it doesn't address the inability to spot and react to edge Badgers, while still punishes near-edge stationary armies.

There are potential ways to balance that, one of them is to introduce "edge zones" on the map where you won't be able to request the directional power from the near edge at X cells from it, only from other directions. This will require some engine work, isn't clear to be explained gameplay-wise and will also need some UI clarification as well. Also no guarantee it actually fixes the issues, as it might work in an opposite way and actually make edges safer because you'd need to cover less directions from air threat.

Alternatively number of Badgers/bombs can be tweaked to make it less powerful (i.e. reduce number of Badgers to 2, but 7 bombs per row, so the area of impact becomes a line rather than square). Fwiw originally it was just a single bomber plane.

**Comment by abcdefg30** [comment]
Fwiw, I all my games I've never been exploited by mass parabombs and have never seen a coordinated use of more than two. (I don't even know if I have seen even two.)

**Comment by Inq8** [comment]
> Alternatively number of Badgers/bombs can be tweaked to make it less powerful (i.e. reduce number of Badgers to 2, but 7 bombs per row, so the area of impact becomes a line rather than square). Fwiw originally it was just a single bomber plane.

So with Parabombs being made common Soviet, just reduce it to 1 plane but still keep the directional attack? - that way maintaining a use vs unaware opponents & much-reduced effectiveness against well-managed units.

**Comment by KOYK** [comment]
> @KOYK @Punsho no real point to debate over LT/MT health not being buffed, if it is already considered to get a health buff next release?

@netnazgul 
It is? Well then, indeed no idea why there is an argument by @Punsho, on what ive said.
But any way, I guess now we argue for the sake of arguing.

### On Parabombs 

@netnazgul 

> Parabombs were just too wacky-random before directional support powers took place. But now they are still a balance problem in a different way

Yeah I know, finally people now get it why it wasn't a good idea in the first place :)
The trait it self is fine for user mods, but not for parabombs in RA.

@abcdefg30 
> Fwiw, I all my games I've never been exploited by mass parabombs and have never seen a coordinated use of more than two. (I don't even know if I have seen even two.)

Yeah same here.

> Parabombs are removed, potentially left to some neutral capturables.

We first need to understand why we need parabombs.
Players use them in 2 cases mostly, kill an incoming blob, or kill defenses including base push with defenses and artillery\v2 support.
So to me parabombs are fine for what they do. 
But directional attack it is cheating, lets be honest here.
 
I remember suggesting somewhere that parabombs need to arrive from the edge of the map near  the starting location of the owning player. 
It makes sense and also there is no confusion, so people will know from where to expect them, and not get paranoid and start building defenses in the back of their bases near the map edge too.

But of course no one listens to me, not back then and probably not now. And to be honest I regret being part of this conversation because of that, and because me having an opposing opinion on balance changes always ends with me being the bad guy. But in this case removing one country 
 as an easy fix to balance some aspect of the game was too much for me, to stay silent once more. Now if you will excuse me I will go back to my mod and stay silent again.

**Comment by tovl** [comment]
> I remember suggesting somewhere that parabombs need to arrive from the edge of the map near the starting location of the owning player.

I implemented a similar logic for `ProductionAirdrop` a while ago for use in third-party mods. If there is a demand for it, I could implement it as an option for airstrikes as well.

**Comment by KOYK** [comment]
@tovl Yes please.

**Comment by wippie-openra** [comment]
Why not removing visible GPS timer from one of the subfactions? Its a major tell that the opponent has teched up. Also in line with fake buildings. Therefore i would recommend it for France subfaction

**Comment by abcdefg30** [comment]
Closing as stale.
