### ISSUE TITLE
Weapons with BurstTargetOffsets will ignore valid/invalid target types

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#18147]
Ground only weapons will fire during Strafing attacks against airborne targets.

To reproduce:
-Give the yak a strafe attack like the original game, but also give it an anti-air armament.
```
YAK:
	-Inherits@AUTOTARGET: ^AutoTargetGroundAssaultMove
	+Inherits@AUTOTARGET: ^AutoTargetAllAssaultMove
	AttackAircraft:
		-AttackType: Default
		+AttackType: Strafe
	+Armament@AA:
		+PauseOnCondition: !ammo
		+Weapon: Nike
		+LocalOffset: 256,0,0

ChainGun.Yak:
	+Burst: 4
	+FirstBurstTargetOffset: -768,0,0
	+FollowingBurstTargetOffset: 512,0,0
	+BurstDelays: 1
	+InvalidTargets: Air
```

**Comment by reaperrr** [comment]
Our strafing implementation internally works by force-firing at the target's position at the moment of firing, not by actually firing on the target actor as such.
As a result, weapons think they're firing at empty space, and the target validity checks against the targeted actor don't run, only accounting for terrain.

And since weapons don't (yet) have the concept of `TargetTypeAir`, which we use for some warheads, they only check against the terrain target types on the cell they landed, regardless of altitude above it.
