### ISSUE TITLE
Map Editor - Distance Measure tool

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#18222]
Shouldn't be hard to implement, the only issue I see is the UX of it.

Would be very useful to measure cliff gaps, distances between resources, spawns, capturable locations and all that, without the need to do trigonometrics in one's head.

**Comment by ghost** [comment]
Found https://github.com/OpenRA/OpenRA/issues/10932#issuecomment-197287486

**Comment by BlackenedRA** [comment]
https://github.com/OpenRA/OpenRA/pull/20175 is sufficient to what I had in mind.

the only thing I think might be better and more specific is if the distance tool highlighted (the same as the copy/paste tool does) the distance between the two cells and any cells that the line intersected on top of giving the diagonal length,, rather than highlighting a whole box like the aforementioned tool does.
