### ISSUE TITLE
Building Bib cell where Carryall has picked up Vehicle becomes Impassable

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#18268]
Carryall picks up Vehicle standing on = cell of a Building, which also happent to be part of it's bib.
Carryall drops that Vehicle on another unrelated, empty, unoccupied cell.
another (any other), second vehicle is ordered to go to the cell where Carryall has picked up the first unit. Now somehow that cell has became unreachable, the second vehicle will path around it.
Its as if something of the first vehicle that has got picked up and then dropped has remaint in that cell.
see .gif
![carryallbibimpassablebug](https://user-images.githubusercontent.com/48881353/84251575-38df2600-ab16-11ea-81db-19086901b235.gif)

**Comment by teinarss** [comment]
Prolly something that is missing to update the locomotor cache.

**Comment by pchote** [comment]
Can anyone confirm whether the same issue happens in d2k?

**Comment by MlemandPurrs** [comment]
just checked it.
didnt happen with the automated carryall lifting an damaged tank to service depot from cell right before construction yard.
so i guess it works correct for automated carryalling.

**Comment by Logicon2020** [comment]
This is Tiberian Dawn not Sun, whoever added the Label.

**Comment by dnqbob** [comment]
meet the same problem today

**Comment by dnqbob** [comment]
![1](https://user-images.githubusercontent.com/13763394/115961581-a1c26780-a549-11eb-84ff-508d328055b2.gif)

![2](https://user-images.githubusercontent.com/13763394/115961592-a6871b80-a549-11eb-95c6-fa11036f8362.gif)

Move the carried unit is useless and cache won't go until this unit dies.

**Comment by reaperrr** [comment]
This isn't limited to bibs. Any cell an actor was picked up from by a manual carryall becomes permanently 'occupied'.

I've (presumably) identified the cause to be that the carryall somehow doesn't properly remove its influence on take-off.
If I add
`self.Trait<Aircraft>().RemoveInfluence();`
to the FrameEndTask in `PickupUnit`, the issue is gone.

That's really weird though, because `TakeOff.OnFirstRun` should already handle that, and `DeliverUnit` does the same.
