### ISSUE TITLE
Unit move order ignored for an unknown reason

### ISSUE THREAD

**Issue by ubitux** [OpenRA/OpenRA#18278]
Around 3m55s in the attached replay, a ranger move order is being ignored for an unknown reason: [ranger-move-ignore-around-3m55s.orarep.gz](https://github.com/OpenRA/OpenRA/files/4774496/ranger-move-ignore-around-3m55s.orarep.gz)

![why-no-move](https://user-images.githubusercontent.com/34467/84567448-07b26000-ad79-11ea-8528-fa1b436aecd3.gif)

Version: `openra-20200503`

**Comment by ubitux** [comment]
To give some insight on what happened: the move order that happens after the automatic harv targeting was a shift move, which caused the automatic `AttackFollow+AttackActivity` on the harv to take over the `Move` one. This wouldn't have happened if the `shift`+`move` order had been issued before reaching the destination point, even if it had automatically engaged the harv.

Since this was not an explicit attack order on the harv, shouldn't the move order take over?

**Comment by deleted-user-1** [comment]
> To give some insight on what happened: the move order that happens after the automatic harv targeting was a shift move

> Since this was not an explicit attack order on the harv, shouldn't the move order take over?

I think no. You can either give an order to execute immediately or to execute it after whatever the unit is doing at the moment. When a unit is attacking something (be it explicitly or automatically targeted), queueing an order means to execute after this target is eliminated. Imagine move order took over: then you could not say "when you're done destroying this, move here". Changing behavior based on explicit/implicit order is IMO very bad, since what counts is not how you might have given (or not) an order in the past, but what the unit is doing now.

It would be a bug if the unit did not execute the subsequent move order when reaching the first "waypoint" and stopped because of opportunity fire engages. But this is not the case as you said.

> This wouldn't have happened if the shift+move order had been issued before reaching the destination point, even if it had automatically engaged the harv.

So everything is working as it should as far as I can tell.

**Comment by ubitux** [comment]
OK
