### ISSUE TITLE
Pillbox damage has regressed (bleed)

### ISSUE THREAD

**Issue by Smittytron** [OpenRA/OpenRA#18312]
Pillboxes now take 4-5 bursts to kill riflemen instead of 1-2. This is likely a TargetTypes regression. Although that should be an easy fix, we might want to wait on #18170 instead.

**Comment by pchote** [comment]
The problem is that weapons rely on inheriting `ValidTargets: GroundActor, WaterActor` definitions from their default (e.g. `^HeavyMG`) template. This works for `Warhead@1Dam`, but not any others. `Vulcan` defines 5 additional warheads that are now missing `ValidTargets` definitions and therefore don't work.

#18170 covers the pillboxes, but we should check that no other weapons have the same problem before we allow that to close this issue.

**Comment by Smittytron** [comment]
I played around a bit with every combat unit, defense structure,  and superweapon; comparing bleed and release side to side. I did not see any more damage disparities.
