### ISSUE TITLE
Define IdleBehavior and AttackType for aircraft in the tiberian sun mod

### ISSUE THREAD

**Issue by deleted-user-1** [OpenRA/OpenRA#18319]
## Motivation

With the tiberian sun mod progressing in development it becomes necessary to discuss unit/unit type behavior in more detail and therefore define the fundamentals we can build unit roles and balance upon. For aircraft the most basic behavior aspects and as such scope of this issue are
- `IdleBehavior`,
- `AttackType` 

#### Pro `Land`
- Replicating the original behavior is the most authentic and easiest to justify 
- It discourages unit spam and rewards player attention

#### `Cons`
- Landed aircraft are very vulnerable

#### Pro `Circle`:
- This is the behavior in modern C&C games like C&C 3 (see below)
- Most realistic option for fixed wing aircraft
- Does not need repulsion and circumvents problematic engine limitations

<details>

![fh](https://user-images.githubusercontent.com/13763394/85223395-68830d80-b3f5-11ea-9afa-008c6f563c86.gif)

 ![scrin](https://user-images.githubusercontent.com/13763394/85223441-d3ccdf80-b3f5-11ea-999d-6b15557d1f99.gif)

</details>

#### Cons `Circle`:
- Does not contribute to better unit control
- Conflicts with the original unit behavior (nothing similar in ts)
- Conflicts visually with isometric grid: They do not fly circles but in an ellipse. More important, they move visually faster horizontally than vertically. This makes it looks far less smooth than in C&C 3.
- Produces visual noise in an atmospheric game. This the biggest blocker for me personally.

#### Pro `Hover`
- Allows the same precise unit control as the original without the frustrating landing part
- Conceptually compatible with a VTOL aircraft and conflicts less with the original ts
- Can be made more natural by adding small movement and tilting

#### Cons `Hover`:
- Requires #13954 to look good
- Requires TS-style distributed pathing to look good (looks bad when a bunch of aircraft bumb into each other when reaching the destination)
- Suffers from required `Repulsable` and its required optimization
- *They do attack in strafes, therefore it is odd that they hover. (If they can hover, why do they not attack hovering but in strafes?)*

#### My subjective Conclusion
For me the determining factors are maintaining the original game's atmosphere and improving the gameplay. Both can in my opinion better be achieved with `Hover`. The current limitations that make it looks bad need to be solved eventually. Contrary, `Circle` requires a level of smoothness to look good at that I think can not be achieved with the current engine.

Therefore I propose to make all TS aircraft hover instead of circle when becoming idle, *unless* there is a realistic perspective to make it look like in C&C 3 where they circle real slow within a small radius while moving otherwise fast when not idle.

### `AttackType`
In original tiberian sun banshees fly 3 attack strafes and then return to their helipad. This behavior should IMO be maintained. It is compatible with any idle behavior. Without going into too much details as I hope this to be less controversial, I propose to make banshees and orca bombers use `Strafe` as attack type with `CanSlide: false`, highlighting their bomber traits and replicating iconic cutscene behavior from C&C 3 (see below)

<details>

![s1](https://user-images.githubusercontent.com/13763394/85220460-27cbca00-b3de-11ea-9bd5-8f7c8f44bdbc.gif)

</details>

Contrary, orca fighter and harpy should be highly microable units that can shoot while hovering. In the original, they cycle around angles from which they attack. `Hover` is the most similar that is currently available but it might be replaced by a new attack type that replicates the original behavior more closely.

#### My subjective conclusion
Attack type `Strafe` fits bets for orca bomber and banshee. They should need to fly curves to attack. Orca and harpy should hover while attacking, possibly cycling attack angles like in the original.

## Side effects

I don't expect that these proposals will change the meta fundamentally away from what is displayed in https://youtu.be/8U2AWYNYY1c?t=291. The following minutes display how banshees are used in an original TS 1v1 game.

## Alternatives

Have been considered above.

Issue results from a debate in #18231, cut scene recordings have been contributed by @dnqbob in #18314, which this issue aims to supersede.

**Comment by abcdefg30** [comment]
To add to the cons of Hover: They do attack in strafes, therefore it is odd that they hover. (If they can hover, why do they not attack hovering but in strafes?)

**Comment by pchote** [comment]
> (If they can hover, why do they not attack hovering but in strafes?)

As bombers: because they want to damage a larger area than just the point immediately below them? 😉

**Comment by abcdefg30** [comment]
Yeah, I was referring to banshees.

**Comment by tovl** [comment]
> unless there is a realistic perspective to make it look like in C&C 3 where they circle real slow within a small radius while moving otherwise fast when not idle.

This is pretty easy to add and would be a nice bit of polish for D2K carryalls as well.

**Comment by deleted-user-1** [comment]
> To add to the cons of Hover: They do attack in strafes, therefore it is odd that they hover. (If they can hover, why do they not attack hovering but in strafes?)

Agreed that this doesn't make much sense. Given the current limited options to define the circling behavior and the strafing behavior in cutscenes and ingame, I'd prefer the original LandOnIdle behavior. It's not that bad actually, as it forces player attention and makes controlling big blobs harder.

**Comment by dnqbob** [comment]
Firstly,  I think the idea which put orignal TS as goal of remake is wrong. 

1. TS is imbalanced itself and PVP is hardly to see so it is unnecessary for us to get as close as possible to original game. 

2.  TS has many options in skirmish,  and some of them can change the game balance completely.  For example **the shroud you said in "Motivation"**,  TS can turn on/off transparent shroud and it can make some of the units valuable while some become useless.  Therefore, we should build a default game mode from those which is stable for PVP.  Just imagine if aircrafts can't enter the black shroud and they have little sight to avoid them see through black shroud (original TS), when we apply the recoverable transparent shroud they will be completely useless due to the aircrafts have little sight themselves. However, if we don't apply transparent shroud,  the ground combat will become unacceptable for most RTS fans here. 

The only idea to solve it I see and make it as close as original game is to build two sight system: one is for black shroud and one is for recoverable transparent shroud. But pchote is probably against that for maintenance cost & unusable for other mod and I will also against that because I am still wait in queue for those core devs to check my AI fix-up.

**Comment by matjaeck** [comment]
@dnqbob Please note the title of the issue and its scope. Everything you said is relevant for the game, but discussing everything (shroud/rulesets/goals) at once will not help to get us further with this specific topic.

**Comment by dnqbob** [comment]
Secondly,  the idle behavior of aircraft. 

I agree for all circling aircrafts in opra, there need to be an option on circling speed to slow it down. 

I prefer the cnc3 style and not like the "landWhenIdle" except only one situation: Openra-TS applys ion storm as a factor in PVP map.  If there is not,  I think an always flying in idle can be better to improve the game experience: if a aircraft is always landing then get attacked by ground units, I will consider it a disaster instead of apm fun.

**Comment by dnqbob** [comment]
> @dnqbob Please note the title of the issue and its scope. Everything you said is relevant for the game, but discussing everything (shroud/rulesets/goals) at once will not help to get us further with this specific topic.

Update: let's begin this topic again with less joke. I thought I can make the atmosphere easier but I have to point the point out now. 

First we recall in original TS,  WW block "MoveIntoShroud" by using two methods:
1.  setting the aircraft cannot move into black shroud at least
2.  make all aircrafts have little sight.  

You worry about circling will explore the shroud uncontrollably and hope aircrafts cannot move into shroud but ignore the entire setting of TS doesn't do well at this either: 

1. I can still use hover aircrafts explore the shroud at the edge little by little even if they have little sight.  Although it will be inconvenient. 

2. Besides,  **you must consider what will happen when we apply the recoverable transparent shroud as an tradition of OpenRA mod**-- if we don't even allow aircrafts move into recoverable shroud the aircrafts will be completely useless.  However,  even if we allow aircrafts move into recoverable shroud there is still sight problem make aircrafts useless.  Question is,  every opra mod applies recoverable shroud for the flavor of fans so how can you get close to your Original TS Goal meanwhile solve this problem?  Take a look at the aircrafts when you turn on the transparent shroud in original TS,  are they even worth to build? 

The aircraft idle I see here is heavily related to this issue.  You use this issue as an important factor to prove that the original TS way of idle is the best way to achieve aircrafts can't "MoveIntoShroud".  But you ignore when  aircrafts can't "MoveIntoShroud",  there will be tons of edge case will conflict with OpenRA design itself.  Why we have to stick to this setting?

**Comment by deleted-user-1** [comment]
Quoting @pchote from Discord: 

> Atm its not even possible to have a sliding+strafing bomber
> Even though that is our preferred option

**Comment by deleted-user-1** [comment]
@dnqbob I can't make in any more clear than in the comment you quoted. I removed the apparently misleading mentions of shroud in the opening post.

**Comment by dnqbob** [comment]
Ok if you drop the concern in "MoveIntoShroud",  I will put it simple again;

I agree for all circling aircrafts in opra, there need to be an option on circling speed to slow it down.

I prefer the cnc3 style and not like the "landWhenIdle" except only one situation: Openra-TS applys ion storm as a factor in PVP map. If not,  when I see an aircraft is always landing then get attacked by ground units, I will consider it a disaster instead of apm fun. 

I am already used to controlling circling and strafe aircrafts in Cnc3 alike and OpenRA.  Although they are hard control,  they are fast -- which is the balance in game while also fit the common sense that fixed wings are a lot of faster than helicopter.

**Comment by deleted-user-1** [comment]
Regarding the sliding behavior, see the gifs from the original below. All aircraft except banshees seem to be able to slide.

<details>

GDI

![orcas](https://user-images.githubusercontent.com/59416324/85235185-6760d900-b413-11ea-82ce-bfc316ed0a5a.gif)

Nod

![nod](https://user-images.githubusercontent.com/59416324/85235186-6c258d00-b413-11ea-8b40-f0ce339b2c0d.gif)


</details>

**Comment by dnqbob** [comment]
![modified](https://user-images.githubusercontent.com/13763394/85240266-2811a700-b46a-11ea-91f5-d56744042954.gif)

>Regarding the sliding behavior, see the gifs from the original below. All aircraft except banshees seem to be able to slide

Banshee slides when it trying to turn around.  I think this one in gif is most obviously and in fact Banshee always slides when turn around in your gif if pay attention. 

TS in fact use only one aircraft setting to all aircrafts when flying.

**Comment by dnqbob** [comment]
We also have to modify engine code to get a proper aircraft behave ecosystem which includes "land when IDLE" like TS. It is not easy because we can't get it from simply modified the yaml.

Example: when attack and target die, aircraft will return to base no matter how its ammo state is.

this one will be tricky because it conflict with currently OpenRA airforce behave: only return when out of ammo (CNC3 type in CNC3 aircraft behave ecosystem of OpenRA). **Meanwhile, "land when IDLE" is coupled with this, when target is done this mechanic will keeps aircrafts all in flight or in safe place** -- if only the "land when IDLE" in OpenRA-TS, the aircrafts will land on the attack position when they have ammo -- which will be a disaster for players because airforce managing will be babysiting due to that: you have to give it target or move around to keep it fly or press F let them return, it is inconvenient even compared to orignal TS.

So there will be related engine change if we take "land when IDLE" and don't have better idea on this issue. But should we change engine code for TS's special case? "land when IDLE" and "return to base after attack"? Will it be useful to other mods/game? Then should we finally refactor this as a state machine alike? Will our code maintainer have enough of these?

And I am afraid it is not the only issue for the entire aircraft behave ecosystem of TS. "land when IDLE" will be the spark light the entire demotruck.

**Comment by deleted-user-1** [comment]
> Banshee slides when it trying to turn around. I think this one in gif is most obviously and in fact Banshee always slides when turn around in your gif if pay attention.

@dnqbob No, that is just wrong!

As seen in the image orcas and harpy do easily move to the cell next to them while banshee has to fly a curve when moving to the cell left or right from it. There is a clear distinction between banshees and other aircraft which is the entire reason why I made the recordings to document that behavior.

**Comment by deleted-user-1** [comment]
Besides, I intentionally (who would have thought!) wrap these recordings so the issue stays readable and consumes less bandwidth when opening from mobile...

**Comment by dnqbob** [comment]
Upon curve I think they all fly a curve here. Banshee curve a little bit more.  and I think it is due to there is only one aircraft behavior in TS with some different in data.

**Comment by deleted-user-1** [comment]
Sorry, it looks we simply have a different understanding of what slide means. It's true that none of them really slides to the side, they all turn a bit before moving sideways. The difference I wanted to highlight was that only banshees have to do a whole "approach" when moving sideways. And I have to correct myself - you have been right and I only see now what you mean. Banshee indeed flys in a different direction than it is facing in the sequence you posted.

**Comment by dnqbob** [comment]
In fact cnc3 style aircrafts don't have the curve like this when order to next pos. I don't know if OpenRA-TS will/can do something like orignal TS.  I think we will probably end up with all aircrafts hardly curve in OpenRA TS.

**Comment by tovl** [comment]
> I don't know if OpenRA-TS will/can do something like orignal TS.

Yes it can: #18322

**Comment by dnqbob** [comment]
OK, since now aircrafts can do curve, let me list other TS flight related behaviors and mechanicals.

1. Aircrafts can not move into shroud.

2. Aircrafts have little sight

3. Aircrafts/jumpjets can only move to the closest available landing ground when ordered to move to sw. In other word they can only move to position where they can land & out of shroud, and an auto-correct system will make sure it when player clicks on a invalid position.

4. Aircrafts always land when IDLE.

5. When ordered to attack and target die, aircrafts will return to base no matter how its ammo state is.

6. Aircrafts queue in repair pad

Just mention these here and we can accept or reject. However, TS aircraft system is a mixture of RA1 and something not yet seen in any of RTS game, it is an innovation but seems somehow not popular at that time. Maybe we will reject almost all and make it CNC3/OpenRA style for common mordern CNC fans, or recover this innovation aircrafts system and walk on the old road of TS -- may we make it more useful and competing on this road.

**Comment by dnqbob** [comment]
TS orignal airforce design theories (probably):

1. Aircrafts cannot scout/move into at least the black shroud.

2. Usage of Aircrafts must with a decent scout opration first.

3. Like RA2, aircrafts are support units and their firepower cannot last long in combat, so they will return to airpad location once the targets in a row is dead or out of ammo. 3D CNC series has a completely new design like OpenRA, but it also has some shortages compared to 2D CNC.

4. The end of a set of activities is always landing, which means when left unchecked the aircrafts can be assault by any ground units. 

Again this post just mentions TS airforce design theories here from the aspect of tatical. We can follow these theories or not. But I need to put it here: those aircraft tatical theories did not do well in TS and if we take this way of design we need to find our own way on balancing and life improvements on players interaction.
