### ISSUE TITLE
Going Low Power by building/capturing a building doesn't disable that building.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#18454]
First noticed on RV, can reproduce on RA on bleed too. To reproduce start a game, enabled all cheats, disable unlimited power, build a power plant and build 3 radars, you'll see that the 3rd one won't be disabled.

![resim](https://user-images.githubusercontent.com/7933210/88661791-c6380300-d0e1-11ea-9713-aef41362e554.png)

**Comment by pchote** [comment]
Regression from #18303?

**Comment by MustaphaTR** [comment]
Maybe, this started with a recent engine update i did in RV, didn't check what actually regressed it. But that looks like a possible candidate.

**Comment by abcdefg30** [comment]
This seems to happen because `TraitEnabled` runs before the actor is added to the world. It is then not included in the actors that are set low on power. Three ideas here:
- Don't update the power state from `TraitEnabled` when the actor is not in the world and let the `INotifyAddedToWorld` callback handle it
- Put the update callback in a `FrameEndTask` like we do in `INotifyCreated.Created`
- Set the power state regardless of if the actor is in world or not (probably not that good of an idea, seeing how actors not in the world don't grant or consume power)
