### ISSUE TITLE
Turret is pointing in the wrong direction

### ISSUE THREAD

**Issue by fusion809** [OpenRA/OpenRA#18618]
## Issue Summary
Oddly one of my turrets is shooting at the correct target but aimed in the wrong direction. I'm using commit 82a2148.

## Reproduction
Load this saved game:

[turret-wrong-direction.zip](https://github.com/OpenRA/OpenRA/files/5243057/turret-wrong-direction.zip)

and observe how the turret in the north-east region of the map is pointing north but shooting at ore trucks to the south-east. 

## Expected behaviour
Turrets should point at what they're shooting at.

## Screenshots / Screen recordings / Replays
![Screenshot_20200918_124559](https://user-images.githubusercontent.com/4717341/93550160-3199a500-f9ae-11ea-8fdf-963e98ae03db.png)

**Comment by pchote** [comment]
The savegame desyncs when I try to load it on 82a2148300.

Can anyone else successfully load the game, or otherwise reproduce the issue?

**Comment by fusion809** [comment]
If it helps with reproduction of the issue, I ran it from an AppImage built on an up-to-date Arch Linux system.

**Comment by pchote** [comment]
Can you share a link to the appimage?

**Comment by fusion809** [comment]
I've since deleted the AppImage I used and replaced it with a newer one. But I just opened the saved game with my latest AppImage (built from 930f8ab) and it loaded fine and I saw the bug, so I'll just upload that AppImage:

[OpenRA-Red-Alert-devel-x86_64.zip](https://github.com/OpenRA/OpenRA/files/5288809/OpenRA-Red-Alert-devel-x86_64.zip)

**Comment by pchote** [comment]
I'm fairly confident that there is an issue in your AppImage because:
* The savegame desyncs when trying to load it on a locally compiled build on the same commits.
* When I unpack the AppImage I can confirm that the mod files are consistent with 930f8ab, but the output of `OpenRA-Red-Alert-devel-x86_64.AppImage --utility --docs` is missing the documentation changes from b8e60ca8ec9a7076f44ed7c92ac43bc35a6f7a1e and 4627387ae35241137b1c351e3c4b847ed141ac7d, which are both before 930f8ab in the git history.

Its then plausible (but of course not guaranteed) that this issue would be caused by a mismatch in the engine version vs mod yaml version. We've changed a fair bit in the packaging scripts recently, so we may have real regressions on our end or more likely have broken some assumptions that your own wrappers may be making.

**Comment by fusion809** [comment]
Here's how I built the AppImage, I opened a terminal and ran:

```bash
cd /data/fusion809/GitHub/others/OpenRA # My local copy of this repo, not a fork
git stash
git pull origin bleed
make clean
make
cd packaging/linux
./buildpackage.sh $(git rev-list --branches bleed --count).git.$(git log --oneline | head -n 1 | cut -d ' ' -f 1 | head -c 7) ~/Applications
```

That's it. There's no fork, no special builder scripts.

**Comment by reaperrr** [comment]
Haven't done any debugging yet, but my best guess is that this is the same underlying problem as when turrets are shot at during their make animation, presumably that the turret internally turns because it acquired a target before the make animation finished and as a result, the sequence and actual facing get "out of sync".
Maybe pausing (or disabling?) `AttackTurreted` during make anim would prevent this.

**Comment by reaperrr** [comment]
Well derp, this is actually rather obvious once you really start digging into the code.

`WithEmbeddedTurretSpriteBody` sets `turreted.QuantizedFacings = DefaultAnimation.CurrentSequence.Facings;` when enabled, but since we aren't disabling it while the make anim runs, things go haywire if anything happens during the make anim (which only has 1 facing).

My attempt to use conditions to make things work failed when using `WithEmbeddedTurretSpriteBody`, but succeeded when using a placeholder `WithSpriteBody` for the make anim and `WithSpriteTurret` for the rest.
Regardless of whether the issue was on my end, we should consider deprecating and eventually removing `WithEmbeddedTurretSpriteBody`, provided we can get TD sam sites to work without it.

**Comment by pchote** [comment]
Are you able to reproduce this issue on bleed? If not, maybe #18641 has already solved it?

**Comment by reaperrr** [comment]
> Are you able to reproduce this issue on bleed?

Yes.
