### ISSUE TITLE
Right-click pan, interferes with issuing unit commands and rally\way points

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#18646]
If right-click pan is enabled, it can interfere with giving right-click commands to units, for example multiple right clicks can lead into moving the camera, instead of giving a move command to the selected unit, or when moving the camera (holding right click down) while holding shift and a production building is also selected, there is a chance to place "random" rally\way points as you move the camera.

Right-click pan is an old problem btw, I just decided to finally make an issue now.

**Comment by abcdefg30** [comment]
I'm not sure what the fix for this would be. There is basically no way to have both working fool proof.(?)

**Comment by tovl** [comment]
Hey, old problems need reporting too. Can't fix things if we don't know about them. :wink: 

Could you elaborate? Do you mean right-click pan + right-click commands is prone to misclicks, or is there some other issue?

I can't myself replicate the second issue, but it seems to me like this could happen if you have a wireless mouse with a flaky connection. I remember stuff like that happening all the time when I still used a wireless mouse.

I find the first issue is easy to reproduce indeed, but it doesn't seem to be a bug perse. It is just very easy to accidentally move the mouse a little bit when clicking rapidly. It can be fixed though. We could add a small time delay after pressing the mouse button before the panning is initiated in addition to the deadzone. I found this solution to work quite well for left-click mouse-drag orders in #17099 

Speaking of mouse-drag orders, my own preferred solution would still be to just remove the combination right-click orders and right-click panning. Because right now, having to support this combination is the major blocker for being able to introduce those. I had a lot of plans with those last year :cry:

**Comment by KOYK** [comment]
>Could you elaborate? Do you mean right-click pan + right-click commands is prone to misclicks

I mean like, when you give a unit a command (using right-click) the right click pan could kick in and, instead of giving a command to a unit, you actually start panning.

>Speaking of mouse-drag orders, my own preferred solution would still be to just remove the combination right-click orders and right-click panning. Because right now, having to support this combination is the major blocker for being able to introduce those. I had a lot of plans with those last year cry

Oh no, don't remove that please, tbh I am very used to it in openra and from other games like cnc3 kanes wrath, generals. 
Adding extra delay would fix it as you said.

@abcdefg30 
> I'm not sure what the fix for this would be. There is basically no way to have both working fool proof.(?)

what @tovl said:
>We could add a small time delay after pressing the mouse button before the panning is initiated in addition to the deadzone.

>Hey, old problems need reporting too. Can't fix things if we don't know about them.  :wink: 

Yeah you are right XD

**Comment by KOYK** [comment]
It wont be fixed\added, closing it.
