### ISSUE TITLE
Bleed: TD Campaign Trees disappearing while zooming (Spooky!)

### ISSUE THREAD

**Issue by Orb370** [OpenRA/OpenRA#18761]
[Spooky Trees.zip](https://github.com/OpenRA/OpenRA/files/5417833/Spooky.Trees.zip)

Just in time for Halloween.

Also the building right below it, the well is poking through the tree.

Similar issues occur on other campaign missions.

**Comment by pchote** [comment]
The tree and the church are placed on the same cell, so are zfighting. Setting a 1 unit zoffset on the tree would fix this.

**Comment by Orb370** [comment]
Oh, well I guess it _is_ a campaign issue. I'll modify the title.

**Comment by abcdefg30** [comment]
Actually, something else must have changed the behaviour here recently. I can see a similar glitch with two houses above the middle Oil Derrick of RA's Warwind.

**Comment by pchote** [comment]
yes, #18709.

**Comment by RoosterDragon** [comment]
The change on https://github.com/OpenRA/OpenRA/pull/18709/files#diff-e37c01bf644b176c5767d080615f285ca88ed4c8dadab10ea499520dbfe27612R136 from `OrderBy` to `Sort` is the culrpit. `OrderBy` is a stable sort and preserves the input order of elements that have the same z position. `Sort` is unstable - elements with the same z position could appear in either ordering.

Previously elements with the same z position would at least appear in a consistent order depending on which get created first, now they can swap every frame.

Various solutions:
1. Revert the change and go back to `OrderBy` (and document the reliance on the stable sort it provides - it's subtle and I missed it). This keeps the old behaviour at a minor perf cost.
2. Change the comparer to have some tie breaks for equal z positions, e.g. comparing their x, y, z, offset components individually. This gives things a consistent order again so it won't flicker between frames, but it might differ from the old behaviour (e.g. maybe some tree is now chosen to be in front of a building, but before it was behind)
3. Decide this to be a problem to be solved in the maps themselves.
4. Write our own stable sort for List, since I can't find one in the library that does it.

I'd probably lean for 1 or 2.

**Comment by pchote** [comment]
2 sounds best to me, IMO.
