### ISSUE TITLE
Replace ActorsWithTrait in more location with ApplyToActorsWithTrait

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#18798]
Please consider using `ApplyToActorsWithTrait` over `ActorsWithTrait<ITick>()` also in the below locations.

See https://github.com/OpenRA/OpenRA/commit/38f1f1e5c2391376dea774beb0b9f9747692e5ac

Locations called often:
- `WordRenderer.GenerateOverlayRenderables` line 148
- `WorldRenderer.GenerateAnnotationRenderables` line 188
- `WordRenderer.Draw` line 272
- `WordRenderer.Draw` line 280
- `OpenRA.Mods.Common/Widgets/RadarWidget.cs` line 397

Optionally any other location where `ActorsWithTrait` is used in a `foreach` statement or in a LINQ statement where it can easily and cleanly can be rewritten to lambda callback `Action`.

Benefit:
- 25% faster - useful when a trait type has many instances.

I could optionally implement this - for as long as you agree upfront.

**Comment by RoosterDragon** [comment]
Wrapping the callsites into a lambda `Action` would likely involve allocations due to captured variables, so you might be swapping the perf gain of looping over a list directly via `ApplyToActorsWithTrait` with the loss of allocating a bunch of `Action` delegates.

`List<T>` exposes a public type from `GetEnumerator` for the purposes of improving performance as the JIT compiler is able to do more with with a known concrete type like `List<T>.Enumerator` rather than an interface like `IEnumerator<T>`. I wonder if exposing `AllEnumerable` and `AllEnumerator` as the public return types would result in a similar benefit where maybe the JIT complier will have more luck working out the mechanics and give you similar performance to iterating the loop directly like with `ApplyToActorsWithTrait` - might be worth investigating?

**Comment by anvilvapre** [comment]
I believe it tried an `Apply` method back then for the other enumerators i.e. for `Actors()` - however it did not give much/any benefit - because it only enumerates existing objects already in the collection. And because it breaks the current interface it would only mean a lot of rewrites.

For `ApplyToActorsWithTrait` it is beneficial because it avoid having to allocate the temporary trait pairs.

No harm in using the `List<T>.Enumerator` either way.

I'll may run some tests some time.
