### ISSUE TITLE
Make 'squadmanager' does not tick squads all in one tick

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#18825]
## Motivation
`SquadManagerBotModule` ticks all squads in one tick after every `AttackForceInterval`, but squad logic can include some heavy performance cost lines, such as scanning enemy from all actors, scanning the entire map and using some function in 'AttackOrFleeFuzzy' in a loop. More squads AI have, more possibilities of spikelag after each `AttackForceInterval`. It will be also a important thing needs putting into consideration when we refactoring the `SquadManagerBotModule`.

## Proposed solution
`SquadManagerBotModule` tick 1~2 squad each tick and remember the index/key of the ticked squad, which will refreshed after `AttackForceInterval`.

## Side effects
Need to solve an edge case that refresh index/key of the ticked squad after `AttackForceInterval` but squads are not all ticked.

## Alternatives
Make squad logic very simple.

**Comment by pchote** [comment]
AI logic isn't allowed to change world state, so in principle there is no reason why things like this can't be run in parallel on multiple threads, between ticks.

**Comment by dnqbob** [comment]
but will it cause disynchronization if we put it on multi-threads with multiplayer game?

**Comment by pchote** [comment]
It doesn't change the world state, so no.

**Comment by dnqbob** [comment]
and there can be many squads defined by users after the AI project plan. Will we open each squad a thread? If not how we can solve a similar edge case list in post?

**Comment by anvilvapre** [comment]
Is it "AI" or is it "an activity" (if not the same). 

An alternative could be multi-logic-tick running task within the main thread. A task that is aware of how much time it took - and pauses itself. This would make sense if many actors would run such a task often and you don't want to start a thread for each each time, if it would be a typical activity.

Would be complex and error prone to let the implementation of an activity be responsible for pausing itself.

Sounds like the game needs an (activity) scheduler ; ) Some sort of (python) "Green threads".

The Wait activity could then reschedule itself, rather than actively polling for tick time to pass. (trivial/no benefit, bad example)

**Comment by dnqbob** [comment]
>Is it "AI" or is it "an activity" (if not the same).

It is the AI

```
			if (--attackForceTicks <= 0)
			{
				attackForceTicks = Info.AttackForceInterval;
				foreach (var s in Squads)
					s.Update();
			}
```
