### ISSUE TITLE
Make possible to disable the handicap feature on multiplayer

### ISSUE THREAD

**Issue by ubitux** [OpenRA/OpenRA#19077]
Being a maintainer of competitive game server instances, the incoming handicap feature in the lobby is a source of concern wrt fair matchups. Would it be possible for the game server to disable it, or in the worse case have the possibility to grey them out like the other options by patching the mod?

**Comment by pchote** [comment]
It turns out that I did actually account for this when implementing the feature. Maps can set `LockHandicap: True` in their player definitions to disable this, the same way they can lock teams, faction, and spawn.

While it would be technically possible (and quite simple) to bodge a new trait with a flag to lock the option at a mod level, IMO this would set a bad precident that would lead to further problems in the future.

So my feeling here is that the competitive maps should disable the handicap as part of their custom ruleset, and leave the engine implementation as it currently is.

**Comment by abcdefg30** [comment]
Several servers already provide their own custom rules to overwrite the defaults, so this can be closed imo.

**Comment by ubitux** [comment]
> Several servers already provide their own custom rules to overwrite the defaults, so this can be closed imo.

Apparently there is no way for servers to do that except patching the maps.

**Comment by abcdefg30** [comment]
https://github.com/OpenRA/OpenRA/wiki/Lock-server-settings documents how this was done in the past with other options. The same principle should still work with the newest playtest.

**Comment by abcdefg30** [comment]
I see now, this is not controlled by a trait so we can't do the same as before. Sadly the only option will be changing the maps.
