### ISSUE TITLE
Contrail change

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#19084]
for experiment to remove a solid contrail delay (even if I set contrail delay to 0 in bullet, there is still a delaying in bullet projectile) and simplified the code.

I change this:
<img width="501" alt="2" src="https://user-images.githubusercontent.com/13763394/105631472-8e8bf700-5e89-11eb-91c0-3c58ad1f7c4e.PNG">

to this:
<img width="501" alt="1" src="https://user-images.githubusercontent.com/13763394/105631471-8d5aca00-5e89-11eb-8bd2-608cb708fc76.PNG">

and the effect is pretty good and delay is removed:
![modify](https://user-images.githubusercontent.com/13763394/105631585-1e31a580-5e8a-11eb-8e5d-22544a70a353.gif)
![f](https://user-images.githubusercontent.com/13763394/105631586-1eca3c00-5e8a-11eb-83f4-d72a0a4f22cc.gif)
![G](https://user-images.githubusercontent.com/13763394/105631589-212c9600-5e8a-11eb-80b3-a4848e7e01c3.gif)

So I have some question about the original code:

1. Why do we need
```
var nextPos = Average(trail[Index(j)], trail[Index(j - 1)], trail[Index(j - 2)], trail[Index(j - 3)]);
```
when the `Average` does little to contrail smooth while reduce contrail length by 4?

2. why do we need
```
			// Need at least 4 points to smooth the contrail over
			if (length - skip < 4)
				return;
```
? if we need this we should inform user about contrail length should > 4, right?

**Comment by pchote** [comment]
#2798 demonstrates why the smoothing was added.

**Comment by dnqbob** [comment]
and that is strange, for me it doesn't feels like wrong

**Comment by dnqbob** [comment]
aircraft contrail does have problem, though

**Comment by reaperrr** [comment]
Smoothing is mostly needed when a) the contrail source has a rather low amount of facings and b) the contrail offset is shifted along the width of the source as well (like aircraft wing tip contrails).

But the former doesn't affect voxel actors as much and the latter doesn't affect projectiles that much.

Best of both worlds would probably be to make the smoothing optional in the renderable, default to 'enabled' on the `Contrail` trait and possibly default to disabled on projectiles, because the length requirement is definitely limiting flexibility for the latter.

> if we need this we should inform user about contrail length should > 4, right?

That's long overdue either way, yes.
