### ISSUE TITLE
In the thick of it polish

### ISSUE THREAD

**Issue by darcyrush** [OpenRA/OpenRA#19183]
Minor polish, but if you kill the three troops guarding the tech center before the two to the top left, one will kill Einstein when he is released.

The civilians have a random chance to be run over by the ore truck. It is possible for Tanya to C4 the ore truck as it unloads, but for a first mission, the timing and knowledge of C4ing vehicles seems unreasonable and this probably would look more like a bug for new players.

**Comment by abcdefg30** [comment]
What do you suggest as alternative? Removing all ways the player can fail an objective sounds odd.

**Comment by Smittytron** [comment]
I'd want to compare it to the original but the other guards can be added to the list of actors that must be killed to free Einstein.

The civilian objective has annoyed me too. The best way I've found to win that objective is to block the ore truck at the refinery with a ranger so it won't inevitably run over a civ, which feels quite gamey.

**Comment by pchote** [comment]
What if we added a scripted event where the civilians will run to a safe rally point (or follow your troops?) if you send some infantry in to escort/protect them? or make them uncrushable and have a timed event where soviet troops will attack them?

**Comment by abcdefg30** [comment]
The troops will attack the civilians once Einstein is freed.

**Comment by Smittytron** [comment]
The OG had the guards mentioned above attack after one of the tech center guards is killed. So the 1st part of this issue is easy to address.

The civilians getting run over is a bit more ambiguous. OG had the same issue except the civs were a bit less aggressive in following the ore truck around. We could just have them move and roam around in an attack anything stance.
