### ISSUE TITLE
On macOS some users may have 2 GPUs have a setting to allow forcing to use 1 of the GPUs

### ISSUE THREAD

**Issue by Chasapple4** [OpenRA/OpenRA#19311]
Some of the Macs that have Nvidia GPUs have been buggy from macOS 10.13 though macOS 11 (macOS can become unstable and some images tear and others turn green).   Played a game last night where I forced the integrated GPU and it was more stable (tho fans spun faster) than the dedicated GPU

## Motivation

Reason for this is to work around an old macOS Nvidia GPU bug (that was introduced in macOS 10.13) where that GPU becomes unstable (have had it crash).

When the Nvidia GPU is in use the video memory is nearly maxed out, while on the Intel GPU video memory is around 60 to 75%. (seeing this info in iStat Menus)

REQUEST MOTIVATION

## Proposed solution

PROPOSED SOLUTION
Have the option to force one of the GPUs (with a note that it might not be stable). 

## Side effects

EXPECTED SIDE EFFECTS
Test a game last night (was around 2 hours) and it was fine, tho fans might spin faster and depending on what else is running in the background might have stability issues for other apps or processes.

## Alternatives

ALTERNATIVES
Been trying to work with Apple for a few years on this bug (have sent lots of logs)

**Comment by anvilvapre** [comment]
It would be a custom solution for MacOS. 

Perhaps you can use an external command to set CPU affinity once a process has started, or by letting a parent process launch the game that sets the affinity somehow. Under Linux you have something like `taskset`. 

https://superuser.com/questions/149312/how-to-set-processor-affinity-on-os-x

**Comment by Chasapple4** [comment]
> It would be a custom solution for MacOS.
> 
> Perhaps you can use an external command to set CPU affinity once a process has started, or by letting a parent process launch the game that sets the affinity somehow. Under Linux you have something like `taskset`.
> 
> https://superuser.com/questions/149312/how-to-set-processor-affinity-on-os-x

Tho it is the GPU I am trying to not not CPU (the Intel GPU is integrated (and more stable), the dedicated GPU is the Nvidia one that has been unstable for years.   It is the WINE Mono that is trying to force the dedicated GPU on macOS.  I have played 3 games while forcing it (using a 3rd party tool) to use the Intel GPU and the game is much more stable.

**Comment by anvilvapre** [comment]
Ah, i misread.

Perhaps also on a Mac you can disable the secondary GPU in the BIOS? Only that way you also can't use it for other applications.

Surprised to hear that the MacOS version of OpenRA uses Wine? Or you only used Wine for other games? Since I would assume mono would use libsdl that would use mesa as software opengl renderer?

**Comment by Chasapple4** [comment]
> Ah, i misread.
> 
> Perhaps also on a Mac you can disable the secondary GPU in the BIOS? Only that way you also can't use it for other applications.
> 
> Surprised to hear that the MacOS version of OpenRA uses Wine? Or you only used Wine for other games? Since I would assume mono would use libsdl that would use mesa as software opengl renderer?

Apple does not give users UEFI access.  

OpenRA uses Wine MONO ([https://wiki.winehq.org/Mono](https://wiki.winehq.org/Mono)) has been around since the builds  came out on macOS & Linux (before the macOS build I was playing it via CrossOver), it is Mono that is trying to force the use of the dedicated GPU.

**Comment by pchote** [comment]
Wine uses Mono to run .NET code, but Mono itself is an unrelated project that is much more general (not to mention much more native) than Wine.

As to the proposal here, i'm sorry to say that this is simply not feasible. Graphics card switching is highly OS-specific and would require a significant amount of effort, code, and testing to implement. Since you already have the ability to work around this issue locally, its simply not going to be worth the effort it would take for us to implement this as a dedicated OpenRA feature. Sorry!
