### ISSUE TITLE
Stop message spam on in game chat and the lobby 

### ISSUE THREAD

**Issue by dwwwj222** [OpenRA/OpenRA#19386]
Hi, 

I was wondering if it would be possible to stop people spamming the chat firstly in the lobby and secondly in the game, in the game I had seen people spam the chat with a lot of rubbish to the point where the server crashes, they are probably copy pasting large amounts of text to do this. Perhaps a limit of 10 messages per minute would solve the issue if that's possible.

I've also seen people doing similar in the lobby chat and leave to just repeat, the temporary banning seems to temporary perhaps a bit longer and also the ability to ban them once they left by clicking their name might be helpful to stop people being able to leave before someone can ban them.

Thanks

**Comment by daniel-s** [comment]
We have just been experiencing a denial of service / spamming nuisance in the lobby while waiting for players to join.

The best description is that an automated script (an assumption based on the very high speed of spam messages) is spamming the chat with offensive text. It is also impossible to kick the user from the chat because the bot keeps jumping between a spectator and open playing slot, so it's difficult to click on the name and kick them from the game.

I suggest rate limiting the speed with which a user can move between open slots / spectator, and limiting the rate at which users can send messages to the chat.
