### ISSUE TITLE
Ability to test the map without restarting the game.

### ISSUE THREAD

**Issue by Gavolot** [OpenRA/OpenRA#19420]
Why does the open-ra load all the resources in bulk? Moreover, when you start the game and then when you start the level.

It is very inconvenient to test any missions. I would like to do solo missions. Studied lua. But I like cameo mods, and I just can't do it. It takes too long.

Suggested solution: missions need to be updated, possibly with some kind of note in the config "in development, dynamic update".
I cannot constantly restart the game to test the map. It just kills any motivation, because I won't get paid for it.

**Comment by Smittytron** [comment]
I don't understand this issue. You can make changes in a map and restart a mission without restarting the client.

**Comment by Leo512bit** [comment]
> I don't understand this issue. You can make changes in a map and restart a mission without restarting the client.

I think what he means is that if you mod a .yaml file for a map you have to reload the game for it to take effect

**Comment by Smittytron** [comment]
> I think what he means is that if you mod a .yaml file for a map you have to reload the game for it to take effect

I think you can. I know for sure you can change a .lua without restarting the game client.

**Comment by anvilvapre** [comment]
A intermediate solution perhaps could be that you can start a map/game from the command line. Similar to how you can start the game with a replay. This would skip the main menu and just start in game. Would avoid loading the shell map.

Reloading the resources of a map - restarting a map - is possible. Reloading the yaml files that are part of a mod is likely not something that can be done dynamically easily or very fast - as it would require a full reload of all yaml files, the whole internal game state. Marking yaml files as dynamic/in-development/reloadable is not an easy solution to implement - because of the many relations between objects in a mod.

**Comment by pchote** [comment]
> A intermediate solution perhaps could be that you can start a map/game from the command line. 

This is already possible!
```
./launch-game.sh Game.Mod=ra Launch.Map=a88670ababc446033321595026f7104800c9aa6b
```

will launch directly into allies-01 (using the map hash on bleed, hash might be different on other tags - use `./utility.sh ra --map-hash mods/ra/allies-01` to find it).

**Comment by anvilvapre** [comment]
Perhaps a nice feature if you could start the game with a Replay and tell it stop replay x ticks before the end - after which the player can take over and continue to play where he/she left off in the past. Or more in general, that you can take over a replay - that has no remote players.

**Comment by PunkPun** [comment]
#19885 should address the main concern
