### ISSUE TITLE
TS subcell coordinates are incorrect

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#19618]
Original game:

<img src="https://user-images.githubusercontent.com/167819/130231367-3e4bd6c2-9967-4fc0-b9eb-c2fbc927cef2.png">

OpenRA:

<img src="https://user-images.githubusercontent.com/167819/130231397-ed94851a-8c1e-42ca-8e3b-140107030440.png">

Comparison:

![subcell](https://user-images.githubusercontent.com/167819/130231461-000bdd77-9c05-48f6-a081-ea4990c88ffb.gif)

OpenRA places the middle subcell to the top of the cell instead of the bottom, and the left/right offsets also appear to be wrong (but this might be an issue with the infantry's center position, so this needs to be investigated instead of blindly offsetting the subcell positions to compensate).

**Comment by penev92** [comment]
I'll leave these here for reference:
https://modenc.renegadeprojects.com/TemperateOccupationBits
https://modenc.renegadeprojects.com/SnowOccupationBits
https://modenc.renegadeprojects.com/Cell_Spots

**Comment by reaperrr** [comment]
> https://modenc.renegadeprojects.com/Cell_Spots

Going by this, the correct subcell offsets in OpenRA's subcell order (I assume we'll keep this order, to avoid regressions and since the map importer can handle the mapping for us?) would be

`SubCellOffsets: 0,0,0, -362,0,0, 0,362,0, 362,0,0`

which happens to look correct with enabled terrain debug overlay as well:
![subcells1](https://user-images.githubusercontent.com/2857877/130296216-74b5da61-b0f6-454e-a219-9c4302fa179f.png)

**Comment by penev92** [comment]
Also reading the above links made me think TS (and subsequently RA2) were supposed to have more than 3 usable subcells (which always looked weird/annoying to me, even as a kid) but something broke and they never got around to fixing it, so they just ended up using only 3 subcells.
(Ofc for TS and RA2 I don't expect we'll change that anyway, just an interesting observation.)

**Comment by reaperrr** [comment]
Yeah, wouldn't put that past them. Some devs follow a 'don't fix what ain't broken' policy, WW followed a 'don't fix what (most) players might not perceive as broken' policy :)
