### ISSUE TITLE
ShortGame lobby checkbox plumbing is bogus

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#19638]
The checkbox is defined by the `MapOptions` trait (on world), but is used by the `*VictoryConditions` traits (on player). These other traits access the checkbox state via a property called from their respective constructors. This doesn't break because the world actor is created before the player actors, but is bad practice and fragile.

The checkbox definition and lobby option should be moved to the victory condition traits instead.

**Comment by obrakmann** [comment]
> The checkbox definition and lobby option should be moved to the victory condition traits instead.

That won't work because not all games use victory conditions, e.g. missions don't.  But you need a place where you can store the `ShortGame` bit for `Actor.HasNoRequiredUnits` to work. I would suggest sticking it onto the `GameModeManager` from https://github.com/OpenRA/OpenRA/compare/bleed...obrakmann:new-game-modes-3 eventually, if we ever decide to go down that route. Otherwise the `MissionObjectives` trait would lend itself as the least bad choice, although it doesn't really belong there either, logic-wise.

**Comment by pchote** [comment]
IMO it doesn't make sense to have the option in missions at all, and all the missions that I know of (singleplayer plus the three RA multiplayer missions) have it locked and disabled. We could work around the Lua API by introducing a new interface for Conquest/Strategic victory conditions to expose the option?

**Comment by abcdefg30** [comment]
I'm pretty sure not all missions in the originals use the same short game setting, but force-disabling it for missions shouldn't be a problem. (Worst case `MustBeDestroyed` can be removed from certain actors to emulate a "short game".)

**Comment by obrakmann** [comment]
FWIW, that pattern is used in a few more places as well: `BaseAttackNotifier`, `BaseProvider`, `BridgeHut`, `Harvester`, `Sandworm`, `SpawnActorOnDeath` for starters, plus probably a whole bunch more that do the same thing with interfaces.

And yes, since the ShortGame option basically is only needed to distinguish between missions and multi-player, it could in theory even be removed completely. I'm pretty sure that noone ever unchecks that box in the lobby options, so it's just taking up space there. The downside is that the distinction would then be hard-coded.

**Comment by pchote** [comment]
> FWIW, that pattern is used in a few more places as well:

Hmm, I see. I guess i'm making a bigger deal out of this than is justified!
