### ISSUE TITLE
GrantConditionOnDeploy prevents AttackMove TargetLine being rendered

### ISSUE THREAD

**Issue by Inq8** [OpenRA/OpenRA#19793]
## Issue Summary

As title, Present on live & bleed TS mod.

## Reproduction

Load TS, build Tick Tanks or Juggernauts, issue queued move orders and you will see it displays properly with shift held.
Now repeat with attack move and the Target lines are not rendered but the orders are still followed.
 
## Expected behavior

Target Lines should render.

![attackmove](https://user-images.githubusercontent.com/42888724/140258458-664d5d32-b2ef-4e06-90e8-fd7c8638a364.gif)

**Comment by abcdefg30** [comment]
The problem is that `GrantConditionOnDeploy` inserts an activity that wraps the actual move activity: https://github.com/OpenRA/OpenRA/blob/c5a6577ceed57fe94f500cb4640dcef860702c8f/OpenRA.Mods.Common/Traits/Conditions/GrantConditionOnDeploy.cs#L151-L153

`AttackMove` then asks that wrapping activity instead of the actual `Move` activity for target lines: https://github.com/OpenRA/OpenRA/blob/c5a6577ceed57fe94f500cb4640dcef860702c8f/OpenRA.Mods.Common/Activities/Move/AttackMoveActivity.cs#L102-L105
