### ISSUE TITLE
M1 applesilicon arm64 support

### ISSUE THREAD

**Issue by ggongaware** [OpenRA/OpenRA#19805]
Good news, I was able to make and run OpenRA on an M1 cpu. 

I did a bunch of manual things that should be a real Pull Request, but I wanted to share this quick work around until I or someone makes a real Pull Request.

Step 1:
install .NET 6 for MacOS Arm64. 
https://dotnet.microsoft.com/download/dotnet/6.0

Step 2:
brew install some dependencies.

```bash
brew install sdl2
brew install openal-soft
brew install freetype
brew install lua51
```

Step 3:
link everything inside this OpenRA project

```bash
ln -s /opt/homebrew/Cellar/sdl2/2.0.16/lib/libSDL2.dylib            libSDL2.dylib       
ln -s /opt/homebrew/Cellar/freetype/2.11.0/lib/libfreetype.6.dylib  libfreetype6.dylib  
ln -s /opt/homebrew/Cellar/lua@5.1/5.1.5_8/lib/liblua.5.1.5.dylib   liblua51.dylib      
ln -s /opt/homebrew/opt/openal-soft/lib/libopenal.dylib             libsoft_oal.dylib
```

Step 4:
Patch .NET target:
```diff
diff --git a/Directory.Build.props b/Directory.Build.props
index 720b520913..3c3fc08e5e 100644
--- a/Directory.Build.props
+++ b/Directory.Build.props
@@ -17,7 +17,7 @@
   </PropertyGroup>

   <PropertyGroup>
-    <TargetFramework Condition="'$(Mono)' == ''">net5.0</TargetFramework>
+    <TargetFramework Condition="'$(Mono)' == ''">net6.0</TargetFramework>
     <TargetFramework Condition="'$(Mono)' != ''">netstandard2.1</TargetFramework>
   </PropertyGroup>
```

Step 5:
Build
```
make all
```

Step 6:
Run and play!
```
 ./launch-game.sh Game.Mod=ra
```

**Comment by pchote** [comment]
Thanks for investigating and reporting on this!

#19780 is already working towards the net6 update, so in principle all we should need to support self compiled builds using `make TARGETPLATFORM=unix-generic` is to add the arm64 brew path to https://github.com/OpenRA/OpenRA/blob/bleed/configure-system-libraries.sh

This would be a good next step before tackling the full packaging changes.

**Comment by Mailaender** [comment]
https://www.youtube.com/watch?v=OlBHnbJoUzE seems to work out of the box.

**Comment by pchote** [comment]
It works out of the box via the Rosetta translation layer, which isn't native support.

**Comment by pusewicz** [comment]
@pchote Opened https://github.com/OpenRA/OpenRA/pull/19887 to address that.

**Comment by taoeffect** [comment]
Is there a reason this manual linking is needed with .NET? I was able to get the game to compile and run just fine with mono, but when switching from mono to .NET while debugging ra2 mod https://github.com/OpenRA/ra2/issues/804, I installed .NET, and now I have to do this manual linking as described above to run even the mods that ship with the engine.

Also, the macOS readme / installation instructions might want to mention this issue...

EDIT: also, my understanding was that mono was a thing because .NET didn't exist on macOS and Linux. Was I mistaken? Now .NET does exist on these other systems, so does that mean mono is no longer needed?
