### ISSUE TITLE
Add the `WINTER` tileset to the Red Alert mod.

### ISSUE THREAD

**Issue by Leo512bit** [OpenRA/OpenRA#19960]
## Motivation

Red Alert already has a snow tileset and I think it makes sense to have the `WINTER` tileset as well. Especially if anyone wants to make a new campaign where the snow can "melt".

## Proposed solution

Add it from TD

## Side effects

The tileset will get more use.

## Alternatives

Don't add it.

## Other thoughts
I personally think the reason why the `JUNGLE` tileset doesn't get used is because not very many people know about it because it was unused in TD. Also I've seen people try to create jungle maps for RA but they can't do it very well so it would be nice if this would get ported as well as there is now some small demand for it.

**Comment by Inq8** [comment]
`I personally think the reason why the JUNGLE tileset doesn't get used is because not very many people know about it because it was unused in TD.  `

It wasn’t part of TD…it was created as a mod tileset for the original.

Pretty sure it will be removed when the Remaster assets are eventually added to oRA because we don’t have an HD Jungle tileset.

**Comment by Leo512bit** [comment]
>It wasn’t part of TD…it was created as a mod tileset for the original.

Not according to tcrf:

>The game contains a perfectly valid Jungle theater in the internal listing of theaters, which would use a jungle.mix with .jun files inside it. However, since all templates (map tile graphic pieces) and terrain objects (trees, rocks, decorations) have an 'ownership' value that determines which theaters they can appear in, and none of them are set to be available for the Jungle theater, the missing Jungle can't be reactivated without further modding.

I also wouldn't be surprised if there's also a version in the remaster because lots of unused content got remastered.

**Comment by Inq8** [comment]
> 
> Not according to tcrf:
> 

I don’t know who or what that is but you can literally find the origin of the jungle tileset on cncnet from 8 years ago:
[Jungle Tileset](https://forums.cncnet.org/topic/2058-jungle-tileset/) 

I assure you it was was not part of The original C&C95/TD.

**Comment by Mailaender** [comment]
Yes, Jungle is fan made, although it looks phenomenal. The references of a JUNGLE theater are probably cut content.

**Comment by Mailaender** [comment]
Whenever porting from TD to RA you have to fill in numerous gaps. The palette indices for water rotation will also differ and need to be adjusted. See the DESERT tileset.

**Comment by penev92** [comment]
We probably need to mention that this might be a really bad idea with regards to the C&C Remastered Collection assets, since we already have problems with custom content in RA.

**Comment by Leo512bit** [comment]
> We probably need to mention that this might be a really bad idea with regards to the C&C Remastered Collection assets, since we already have problems with custom content in RA.

But the `WINTER` tileset is not custom content and there is a remastered version.

**Comment by pchote** [comment]
The issue is that the TD tilesets are extremely limited compared to RA, and lacking a number of tile types that the multiplayer community consider essential for making good maps. Something like 150 custom tiles were added to the Desert tileset to bring it up to RA standards, and I expect something similar might be needed for Winter. Its these custom assets that are the problem (just ask @Therapist1911, who has been trying to create suitable remastered desert assets), and without those I expect that the tileset will draw a lot of complaints.

I don't think we want to deal with the "why did you even bother if we can't use it properly" complaints, or be committed to the extra work of making new tiles!

**Comment by Leo512bit** [comment]
>I don't think we want to deal with the "why did you even bother if we can't use it properly" complaints, or be committed to the extra work of making new tiles!

Alright so does that mean I should give up on this unless I learn pixel art?

**Comment by Mailaender** [comment]
Yes, sorry.

**Comment by Leo512bit** [comment]
Well lets hope I don't make those addons too ugly :P

**Comment by Mailaender** [comment]
Well, and you need a plan for the remasters. While this hurdle didn't exist when we added all the other tilesets years ago, it is a factor now.

**Comment by Leo512bit** [comment]
I'm not to motived to work on this right now so I'll just close this issue for now.
