### ISSUE TITLE
more then 1 unit at FIX

### ISSUE THREAD

**Issue by ihptru** [OpenRA/OpenRA#2018]
Sent HARV to FIX (Service Depot), then sent YAK and it landed on HARV. Looks like both repaired, then HARV left FIX and another  HARV used depot without problems while YAK was in there.

Screenshot:  http://files.ihptru.net/misc/Screenshot-18_1.png

Replay: Not required - Reproducable

To reproduce: happens with any combination of AIR / NON AIR units

Version: 2012-0315
##

**Comment by StexoO** [comment]
Still reproducable in playtest-20160424
![simultaneous repair](https://cloud.githubusercontent.com/assets/8930382/14914058/6627bf6a-0e07-11e6-81ca-945bec508c3b.png)

**Comment by whi7ed3vil** [comment]
Better approached with something like a semaphore. This also applies to helipads while reloading longbows automatically using the latest playtest logic. I'm overjoyed that the longbows will reload themselves (with a little coaxing after blocking each other for a bit), but once they start down, they will overlap each other. Reproducible with any smaller number of helipads than helis. If helis are told to reload specifically, they will choose a queueing order and reload the first batch. That batch will then lift off and land again. Immediately after that, the next group will land on top of them and begin reloading. The issue here is simply that the choppers do not exit for a rally point after taking off. They instead fall back to the pads and do not occupy space, allowing the second helis to land with a functional reload.

**Comment by Smittytron** [comment]
> (To reproduce :
> Take a damaged vehicle and a damaged air unit then send the vehicle to the service depot and before it reaches it send the air unit to the service depot)

You can actually order the aircraft to land after a vehicle starts to repair and vise versa. As far as I can tell aircraft and vehicles are simply allowed to repair at the same time.

**Comment by matjaeck** [comment]
Present in playtest-20180729.
