### ISSUE TITLE
Error with zsync - OpenRA is not a proper AppImage

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#20232]
This started popping up after installing [appimaged](https://github.com/probonopd/go-appimage/blob/master/src/appimaged/README.md):
![image](https://user-images.githubusercontent.com/1355810/187378014-a96b4cba-4107-4937-bb2d-09911ef970f6.png)

**Comment by pchote** [comment]
This is IMO a bug in `appimaged`, not in OpenRA: it is rather braindead to require a url to end with ".zsync" in order to be considered valid.

Still, we can work around this by changing https://github.com/OpenRA/OpenRA/blob/bleed/packaging/linux/buildpackage.sh#L113 to add a dummy argument to the end of the url (e.g. `&format=.zsync`) that will be ignored by the server while satisfying the validator.

**Comment by dragunoff** [comment]
![Screenshot from 2022-10-10 23-25-09](https://user-images.githubusercontent.com/1355810/196248053-2f3774e6-4e83-4501-9aaa-d636deb8d5d0.png)

Still getting the warning on the devtest that includes the fix from #20280. I digged into appimaged's source and found out that it's checking the path portion of the URL, which makes sense because query params can come in any order:
https://github.com/probonopd/go-appimage/blob/dbb75b3cc88460357fc064ae60ddba2ebf092a3a/internal/helpers/updateinformation.go#L117

So we need to add `.zsync` to end of  the path `https://master.openra.net/appimagecheck.zsync`.
