### ISSUE TITLE
Issues with the new colorpicker

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#20415]
Im opening this issue with the context of providing a centralized feedback for any issues that may arise with the new colorpicker.
All others please feel free to contribute your concerns and feedback with this upcoming change in the next release also.

Before, it was possible to conveniently input hex color code to provide teamcolor presets. With the change to hsv this has became no longer possible as it wants to arbitrarily restrict into a narrow range.
Further issues present in the process of converting a hex color into a format this new colorpicker understands, i would dare even say its not exactly human useable in its current state.

The intention was to make C4B060 pickable,
to that end have entered:
```
    ColorPickerManager:
        PreviewActor: fact
        PresetHues: 47
        PresetSaturations: 51
        HsvSaturationRange: 0.3, 0.97
        SimilarityThreshold: 0.16
```
this resulted in a entirely different color ingame:
![coloringame](https://user-images.githubusercontent.com/48881353/198895862-80961301-4d2e-49be-b198-9be776cc8b18.png)
while this was expected:
![colororig](https://user-images.githubusercontent.com/48881353/198895883-8e7271f7-efe3-4714-918f-9c2a855d40c1.png)
The difference occured because the colorpicker is expecting a different hue, 0-255 rather than 0-360. 
Been told to multiply the obtained hue by 255 / 360, however that also resulted in a color other than the one wanted.
Later a close enough color #c2ac5f could be obtained by inputting 0.13 as it's hue.
![tonediff](https://user-images.githubusercontent.com/48881353/198896150-0ef6531e-000f-4cd8-912e-1d230139b251.png)
On the left the color obtained, on the right the color would like to get.

Another factor is since you can change only H and S, while V remains forcedly the same for all this contributed towards resulting in a different color alltogether.

I would deem this inacceptable in this time and year, you should able to get the color you want, that feels like wrestling with colormatic at paintshops, only to get a wholly different thing delivered anyhow.
Also should able to disable it alltogether like i can do before.

**Comment by MlemandPurrs** [comment]
I might have realized one more thing about this. In the old system each given color is its own seperate entity, in the new system they are all part of a sequence, unless im mistaken this might potentially mean:  
1. that it gets more restrictive the more preset colors are provided.  
2. including certain colors might mean others becoming unavailable due to how it averages out.

**Comment by pchote** [comment]
I don't condone recent behaviour and am not inclined to reward it by implementing a fix, but @PunkPun has asked very nicely for information about how the colour system works so they can try to tackle it themselves. So here we go:

OpenRA's remapping logic is implemented in [PlayerColorRemap.cs#L31-L50](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Graphics/PlayerColorRemap.cs#L31-L50) and [combined.frag#L211-L224](https://github.com/OpenRA/OpenRA/blob/bleed/glsl/combined.frag#L211-L224). These two implementations *must* be kept reasonably equivalent for remaster compatibility (note however that the paletted version currently only preserves the HSV value and uses an absolute hue rather than a delta).

The RGB remapping implemented in the remaster can be seen in [TextureManager.cs#L282-L370](https://github.com/electronicarts/CnC_Remastered_Collection/blob/master/CnCTDRAMapEditor/Utility/TextureManager.cs#L282-L370). This includes several extra tweak parameters (`InputLevels`, `OverallInputLevels`, `OutputLevels`, `OverallOutputLevels`) that are unused (all zero) in the remaster, so I did not implement them in our version.

The remaster did support a V (i.e. brightness) offset, but it is only sparsely used so I also omitted that as it allows us to pack all the information into a single RGBA pixel. The first step towards supporting brightness offsets will therefore be to expand the `HardwarePalette.ColorShifts` texture to add a second column that can be sampled to access this extra information from the shader.

Modifying `V` itself behaves quite poorly in general - there are going to be specific hand-picked values that look good (which is what the remaster did), but most of the range gives very ugly looking results. You may have better luck by implementing `InputLevels` and `OutputLevels` and defining some mapping to them from a brightness slider.

Another option could be to change the color picker UI entirely to have a set of modder-defined base colours (i.e. what the remaster did, which can include hand-picked V offsets to produce darker base colours) and then provide sliders to modify the hue/saturation in a range around them.

**Comment by PunkPun** [comment]
The palette remapping issue exists even with verified colors. One of the more offensive ones is:

RGB: #0C3AF2 
HSL: (228, 91%, 50%)
HSV: (228, 95%, 95%)

<img width="420" alt="Screenshot_2023-02-26_at_21 54 42" src="https://user-images.githubusercontent.com/37534529/221437153-b695dbbf-8cb8-4809-a71b-637346b44b5e.png">

<img width="100" alt="Screenshot 2023-02-26 at 23 06 04" src="https://user-images.githubusercontent.com/37534529/221437283-a84e76cb-2b4e-4ba7-b735-cfd9763ed78e.png">

**Comment by pchote** [comment]
The color picker displays colours with a constant V=0.95, while the ingame sprites take V from the actual sprites. Lower `ColorPickerManager.V` to better match the ingame sprites to resolve that.

**Comment by PunkPun** [comment]
This shouldn't have been closed
