### ISSUE TITLE
Issue stop command on production buildings to reset rally points

### ISSUE THREAD

**Issue by MikillRosen** [OpenRA/OpenRA#20414]
In the original Red Alert 2, you can reset a production building's rally point by issuing a stop command on it. This is useful if you misclicked with a rally point or you want to change the rally point and reset it instead of setting it near the building yourself.

**Comment by ThomasChr** [comment]
I'll tackle that one!

**Comment by ThomasChr** [comment]
@MikillRosen I've got two ways to do that.
The first one would be to allow the Stop Button on all Production Buildings at all times - this is just a minor change in the yaml Files. The downside is that the Stop Button is also active at all times - even when there is no Rally Point set. I do not see this as a problem because with units it's the same. You can click the stop Button even if they are already stopped. Simply nothing will happen and we will be consistent with this approach.

The other way would be to activate the Stop Button in OpenRA.Mods.Common/Widgets/Logic/Ingame/CommandBarLogic.cs:304 - so it will be activated when we're switching to an Actor/Building which has a Rally Point set at the moment. This avoids changing anything in the yaml file BUT it will change a few (more) lines of code, adding another test everytime you switch Actors and also we need to activate the Stop Button right after setting the Rallypoint, presumably in RallyPoint.cs - which is also not that nice.

What do you think?

**Comment by MikillRosen** [comment]
I'll go with the first one, but what do people think?
