### ISSUE TITLE
Allow hotloading custom traits in maps

### ISSUE THREAD

**Issue by Leo512bit** [OpenRA/OpenRA#20530]
## Motivation

I know that this probably will never be added but its worth a shot. As we all know there has been many requested features that will never be implemented upstream because they will never be used in the main game but still might for modmaps. Sure you can make your mod but here's the harsh reality: no one will care about your mod. "Professional mods" like CA, OpenHV(no offence @Mailaender OpenHV is a great mod and I enjoy it)RAClassic, TDOriginal, and OpenSA (and even earlier ones like the WWI mod) have tried to reach some popularity and they _all_ failed. So unless you're creating SP missions for yourself, willing to play against bots, or have friends making your own is pointless. So there is only one solution: mod the things that everyone is already playing.

Yes I know there are many considerations and a big example is security.

**Comment by abcdefg30** [comment]
> Yes I know there are many considerations and a big example is security.

Exactly, allowing people to run arbitrary C# code on other people's computers just because said other people downloaded a map is a bad idea. Without having a solution to this there is no way to go forward here.

**Comment by Leo512bit** [comment]
I'm not too familiar with C# but a few ideas that I have (which I'm not sure is even sure if it's practical or possible) Sandboxing, restricting `using` to only what's needed for most custom traits, one class per file.

**Comment by ben132** [comment]
Wouldnt it be better to implement a Library system for custom traits, with a collection stored on the OpenRA git, as a seperate Repo, where people with custom traits could add to them.

**Comment by PunkPun** [comment]
The SDK already exists to fulfil such a purpose. People can add custom traits without modifying the engine

**Comment by abcdefg30** [comment]
Storing custom traits in the main repository has its own problem. Namely that we'd have to maintain those traits, and, the additional burden aside, without usecases this is error prone and not easy to do properly.

**Comment by Porenutak** [comment]
I agree with Leo point. Can it be done via (at least in theory) LUA scripts? Right now if you want create new behaviour for unit or weapon with LUA its limited, or really _tricky_.

**Comment by Leo512bit** [comment]
> The SDK already exists to fulfil such a purpose. People can add custom traits without modifying the engine

You still need to create a mod even if it's just an overlay style.


> Wouldnt it be better to implement a Library system for custom traits, with a collection stored on the OpenRA git, as a seperate Repo, where people with custom traits could add to them.



> Storing custom traits in the main repository has its own problem. Namely that we'd have to maintain those traits, and, the additional burden aside, without usecases this is error prone and not easy to do properly.

Yeah that's why I'm more in favor of hotloading traits in the map.


> I agree with Leo point. Can it be done via (at least in theory) LUA scripts? Right now if you want create new behaviour for unit or weapon with LUA its limited, or really _tricky_.

Are you talking about weapon traits? If so then no. I'm talking about C# traits.

**Comment by penev92** [comment]
I'm sorry to have to kill the enthusiasm here, but it seems to me like nobody stopped for a minute to consider whether what they're asking is even technically feasible. And I have to say it is not. I even did a quick search to humor the idea and the closest I got was
 - This experiment that is deprecated because it relies on a .NET-Framework-only feature - https://github.com/fadden/DynamicScriptSandbox
 - This issue (that the above links to) that explains that this isn't going to be a thing in the new .NET - https://github.com/dotnet/runtime/issues/4108
 - Several random posts over the internet saying basically "don't do it"

C# isn't Lua and you can't just sandbox it like that and I'm pretty sure none of us would agree on putting in the work just so we can create a huge vulnerability. So while I understand the request and see the benefits, I should inform you that it's not going to happen.
It just occurred to me that we could technically have maps ship .cs files, not ddls and compile the code ourselves and load the resulting assembly on map load, but:
 - it would require looking for referenced namespaces in that code and having a whitelist/blacklist
 - it would mean that players will need the .NET SDK instead of the runtime
 - would still be quite the undertaking for a pretty iffy result
 
 I won't close this now just in case anyone else has any thoughts on the matter, but I will add it to the to-be-closed list on Discord as unfeasible to implement.

**Comment by Leo512bit** [comment]
>It just occurred to me that we could technically have maps ship .cs files, not ddls and compile the code ourselves and load the resulting assembly on map load.

Yeah that was my idea, but like I said I'm not a C# person so I have no idea about the feasibly about it.

>would still be quite the undertaking for a pretty iffy result

I suppose it can be an interesting experiment if anyone wants to make a mod (_**that nobody will ever use**_)

>I won't close this now just in case anyone else has any thoughts on the matter 

I'll close this issue in about a day.

But I do strongly think that this trait limitation really should be solved.

And for the people here that say "just make your own mod with the SDK" with all-due-respect you are a tad tone-deaf because it is clear that 3rd party mods (at least with what history is showing us) will _**never**_ be popular otherwise I would've made my own a long time ago.

PS.
>Discord 

Gross why can't we still just use IRC?

**Comment by ThomasChr** [comment]
What would be if we find a way to play mods easily? I never tried any mod and tbh some of time sound complicated to install. I would find it great if we would have a sub-menu for mods where every "official" mod can be presented and played with just a click.
There can be a warning that this allows "full" control of your computer to the mod author.

**Comment by Leo512bit** [comment]
It is not that hard, it's just like installing OpenRA, there used to be a
mod switcher but that was done away with when the .ORAMod format was killed
(iirc)

**Comment by abcdefg30** [comment]
There is https://github.com/dragunoff/OpenRA-Launcher by @dragunoff.
