### ISSUE TITLE
Add controlable Carryalls into D2k

### ISSUE THREAD

**Issue by Porenutak** [OpenRA/OpenRA#20543]
Motivation
As I said on Discord, we can use #20398 PR also for D2k. There was always lot of complains that you cannot control your harvesters while they in flight. Often flying right into middle of enemy army, or sniping them on landing zone.

Side effects:
Obvious side effect is that you will be able pick up any vehicle and put it anywhere on the map.

This can be fixed in multiple way's:
- rename side effect to feature :D
- remove **AutoCarryable** from vehicles except for Harvesters. This will will have its own side effect that carryalls cannot pick up damage vehicles going into the repair pad.
- Make **Selectable** trait conditional. which allow carryall to be controlled only when they have cargo or only when they have Harvesters.

I leave it open for more discussion.

**Comment by abcdefg30** [comment]
> Make Selectable trait conditional. which allow carryall to be controlled only when they have cargo or only when they have Harvesters.

That sounds like a decent idea.

**Comment by dnqbob** [comment]
Make `Selectable` conditional can be also considered an important step for #20425.

We have a application in https://github.com/EoralMilk/OpenMeow on making `Selectable` conditional, which is for a self-made carryall trait which is made to see if #20425 is possible in code, not perfect though.

(From our application, I think if we want to make `Selectable` conditional, we need to also consider to remove the actor from player's selection when `Selectable` is disabled or paused)

**Comment by dnqbob** [comment]
However, as for D2K, I would prefer that:
![carryall2-showcase](https://user-images.githubusercontent.com/13763394/197808115-33d43cb3-1832-403b-91f8-f4b04f76e650.gif)
1. Carryall is selectabe. 
-- By doing so we can have better control to them to avoid very strange situation like, carryall cannot unload properly so it somehow refuse to unload and become `flyidle`, you can never find a way get your passenger back at this situation (you can reduce the `SearchFromProcRadius` and `SearchFromHarvesterRadius` to 1, and have an AI player use its `HarvesterBotModule` to reproduce this bug quickly).

2. We use deploy when carryall has no passenger, in order to switch between auto-command and manual-command.
-- With https://github.com/OpenRA/OpenRA/pull/20398 or similar applied

**Comment by PunkPun** [comment]
#20398 was merged
