### ISSUE TITLE
MacOS freeze / crash on moving the game window

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#20642]
Hey all, got a very simple crash here.  Happens reliably, every single time I so much as click the titlebar.  Game plays flawlessly for hours except for this one issue.  I am playing this on the new MacBook Air with the screen notch, if that's somehow relevant.

I first noticed the issue in the previous playtest from December, but I decided to go ahead and report it now because it also exists in this version.

Let me know what other information you need.  Thanks!

Edit: Happens in both Red Alert and Tiberian Dawn.

**Comment by penev92** [comment]
Thanks for the report!
At this stage it is likely too late to try and address that for the upcoming release (unless our lead developer feels motivated to prove me wrong again 😄 ), but hopefully we'll have it sorted for the one after that.

**Comment by nickp-ca** [comment]
Also saw the same in prior builds but thought this may have been another issue on my system.  Glad to see someone else has reported it.  Any MOVE of the windowed mode OpenRA will result in a hang of the app.  The music on the current track will continue to play but all input is frozen and graphics frozen too.  This seemed to be the case since this entire gen of RA on more recent MacOS versions (this one on my end is MacOS Ventura with an M1 processor [Arm not Intel] )

**Comment by PunkPun** [comment]
> will result in a hang of the app

For me on Monterey it freezes as well

**Comment by jbrugman** [comment]
If running on dual screen, using legacy full-screen and then focus on your other screen, you'll have the same issue.

**Comment by PunkPun** [comment]
I dunno what fixed this, but it seems that this bug is no longer present on the [devtest](https://github.com/PunkPun/OpenRA/releases/tag/devtest-20230531)
