### ISSUE TITLE
Targeting can jump to a further target if attacked before a closer target

### ISSUE THREAD

**Issue by BlackenedRA** [OpenRA/OpenRA#20731]
I'm not sure what exactly the best title for this is.

from bug reporting:

Roosterdragon: 
> Took a look at this - can see one of the tanks is switching between infantry and tanks as targets. There's two behaviours at play here. If an idle unit is attacked, it will retaliate against the attacker. Also when idle the auto-targeting will scan every 3-8 ticks for a unit to attack. When you stop the unit to make it idle, if the target scan happens first it will attack a tank as preference. If instead it gets attacked by the infantry before the next scan it will retaliate against them. Once it is attacking it won't change targets until it goes idle again - or is forced idle.

I'm not sure what the general consensus will be but I'm going to guess that not targeting the closest available target is less preferred than this alternative especially since its not exactly easy to do this on purpose.

The expected behavior for a stop command is to allow a unit to retarget the closest unit to it. So the proposed solution would be instead retaliating against the unit that fired on your unit, your unit should retaliate against the closest target as this keeps the most logical consistency with how the game currently works.
attached is the relevant map/replay
[replayandmap.zip](https://github.com/OpenRA/OpenRA/files/10913029/replayandmap.zip)

**Comment by RoosterDragon** [comment]
We can change the "when damaged" logic in AutoTarget to resolve this as follows.
https://github.com/OpenRA/OpenRA/blob/939f715e3c1cd82a080a26d57c29b5f049f6f4bb/OpenRA.Mods.Common/Traits/AutoTarget.cs#L219

- If the unit is on `ReturnFire` stance, then keep the existing retaliate against attacker behaviour.
- If the unit is on a stance greater than `ReturnFire`, change the behaviour to attack the target given by `ScanForTarget`.
- If `ScanForTarget` locates an invalid target, then retaliate against the attacker as before.

This means both retialiate attacks and idle scanning attacks will prefer the same target and avoid this disparity. The ReturnFire stance can continue to target the attacker, because idle target scans don't run for this stance so there's no conflict to worry about.
