### ISSUE TITLE
Harvester unload on allied refinery automatically.

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#21027]
![harvester-bug_084410](https://github.com/OpenRA/OpenRA/assets/13763394/ca3f942e-9403-41ab-a179-cb98aa370e38)

Is it a bug or feature by recent change? You can reproduce it at bleed easily.

**Comment by PunkPun** [comment]
It is a recent regression from the docking refactor. It appears that in the countless rebases I made a mistake, but I do have a comment mentioning this as a future issue. (it even has a typo)

https://github.com/OpenRA/OpenRA/blob/bf643398904a8c69c9d622424eecf2f5541498eb/OpenRA.Mods.Common/Traits/DockClientManager.cs#L316C1-L318

The issue is in how to best fix it. There are 3 situations at play. 
* You want harvesters to prioritise your refineries, repair and repair stations
* In situations where your's is really far you may want to prioritise your allies docks
*  #17452 as harvesters aren't linked to refineries and we don't want them to be, how to handle intentional dropping off to allies refineries?

When it comes to harvesting I'd assume that you don't want to dump into allies refineries unless explictely ordered

**Comment by pchote** [comment]
IMO there is only one sensible approach, so i'm not sure why/if there is a debate:

* Units should never automatically acquire a dock owned by a different player
* Units should always obey an order to dock with a specific building (provided is valid) and not decide to go somewhere else. Harvesters can switch back to "best dock" on the next unload cycle.

It was a mistake (and i'm not sure even explicitly explained) to break the linking behaviour as badly as it now is.
