### ISSUE TITLE
Enclosed units attacking unreachable causes large perf loss

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#21187]
[stucky and laggy.zip](https://github.com/OpenRA/OpenRA/files/13256933/stucky.and.laggy.zip)

This is a test map on this issue.

**Comment by RoosterDragon** [comment]
If I order one of the large blobs trapped in by the wall across the map, that does indeed generate a large lag spike. If I open up part of the wall trapping them and order them again to the same spot, the lag spike is the same. Is there a scenario you can reproduce that is laggy specifically because the units are trapped in, or is it just that ordering large blobs of units is laggy in general regardless?

**Comment by PunkPun** [comment]
Part of the reason for lag is because due to how attack activity functions the move command is queued every frame. The attack activity always queues move commands if it can't fire at the target without the knowledge on wether it had just queued a move command and wether or why it failed

**Comment by RoosterDragon** [comment]
That sounds like what #20954 is attempting to address?

**Comment by PunkPun** [comment]
Yes, but in an incorrect way

**Comment by RoosterDragon** [comment]
Ah - and yes to underline, a move order cause a lag spike on that tick but then perf returns to normal, but attack moves completly wreck performance for a long period afterwards.
