### ISSUE TITLE
If you add Player starting point in editor, icons and colors broke

### ISSUE THREAD

**Issue by Porenutak** [OpenRA/OpenRA#21313]
this happens only if you add first payer on new map.

version: bleed

https://github.com/OpenRA/OpenRA/assets/100044015/e4aaf3da-488b-41fb-a103-ef430b614ceb

**Comment by drogoganor** [comment]
Just adding to this, alters the entire map color palette in RA, at least the desert shellmap:
[2024-02-06 07-57-50.webm](https://github.com/OpenRA/OpenRA/assets/1639681/5f148668-f174-437d-b0e5-c962c278033b)

**Comment by PunkPun** [comment]
can't reproduce this in RA. It must be related to d2k artwork

**Comment by drogoganor** [comment]
I can still reproduce it on latest bleed ra, but only on the desert shellmap.
To reproduce, simply place two player starting points.

**Comment by towelcoded** [comment]
I have looked into this issue and found out that what causes it is having the palette texture's height being expanded while there already are rendered sprites or terrain. Usually the palettes for players are loaded at the beginning before anything is drawn, but in the map editor placing spawn points adds a palette for the new multiplayer faction.

~~While there is code to recalculate the vertices in the TerrainSpriteLayer, apparently regular sprites aren't "fixed" if the texture height changes on the fly.~~
Edit: Never mind, the actual problem was that the palette does not refresh upon changing its height, no extra work needs to be done.

If you set the height to a large enough fixed value (e.g. 16 in D2k) you can add the spawn point without issue.

Note that this is not unique to D2k, it just so happens that you have 8 palettes at the beginning in the map editor so a single spawn point will trigger the expansion to height 16. I have reproduced the problem on all other mods, you only need to add enough spawn points to trigger the expansion.

**Comment by towelcoded** [comment]
On a side note, while the map editor fully supports different team colors for the different factions all of them (creeps, neutral and all multiplayers) get the default light gray. Wouldn't it make sense to use different colors so one could easily see who the owner of the unit is?

**Comment by PunkPun** [comment]
> On a side note, while the map editor fully supports different team colors for the different factions all of them (creeps, neutral and all multiplayers) get the default light gray. Wouldn't it make sense to use different colors so one could easily see who the owner of the unit is?

#2053
