### ISSUE TITLE
Map Editor Zoom

### ISSUE THREAD

**Issue by Ripley-** [OpenRA/OpenRA#2335]
Pritty obveous
Zooms in to top left corner (i think) 
Makes editing harder than it needs to be
Keep up the Good work people
Thankyou

Don't Forget

**Comment by dannyburrows** [comment]
This is still an ongoing issue, and relates to the Top Left coordinate being the basis for the zoom:

**Replication**
1. Open Editor
2. Create new map
3. Paint a corner to track location
4. Attempt to zoom.

**Expected Behavior**
Zoom is expected to increase the size of the map around the location of the map.

**Actual Behavior**
Zoom increases the size of the area starting from the top left corner regardless of the location of the mouse.

**Research for easy tracking**
In the Surface.cs object, on handling the MouseWheel event, the method  
`protected override void OnPaint(PaintEventArgs e)`  
is called. Drawing of the map occurs inside this method and is recommended to grab or pass the Mouse Coordinates from `MousePosition` and use that in the redrawing of the map.

**Comment by Mailaender** [comment]
Don't waste too much time on the legacy WinForms editor which is about to phase out once https://github.com/OpenRA/OpenRA/issues/3377 is integrated.

**Comment by pchote** [comment]
This has been fixed by the new editor.
