### ISSUE TITLE
Allow Installation of playtests next to stable releases

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#2585]
Requires for Linux:
- installation into different paths like `/usr/lib/openra-playtest`
- different startup scripts `openra-playtest`
- packages need renaming to `openra-playtest`
##

**Comment by pchote** [comment]
#12257 would solve this.

**Comment by pchote** [comment]
#13133 solves this for Windows.  I attempted a similar approach in #13138 but abandoned it because linux gui integration requires many small files to be installed across many directories, and renaming/modifying all of them to distinguish between release/playtest/dev was turning into an ugly and fragile mess.

**Comment by Mailaender** [comment]
Solved for Linux with https://github.com/OpenRA/OpenRA/issues/12663.

**Comment by pchote** [comment]
Not for any of our official packages.  If we want to go this route then this could only be considered solved after removing the deb and rpm builds and integrating flatpak generation into our automated toolchain.

**Comment by pchote** [comment]
The current Flatpak packaging actually makes this problem worse.  The current sandbox configuration blocks the different installations from seeing each other, meaning that the ingame switcher doesn't work.

Related: https://github.com/flatpak/flatpak/issues/1236.
