### ISSUE TITLE
Visualize waypoints set by the player

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#2598]
You can currently use Shift + Click to set waypoints for your units. There should be a flag (suggesting the one from the rally point) to visualize this.

**Comment by x-a-n-a-x** [comment]
+1 for all these ideas.

**Comment by r34ch** [comment]
I didn't think way-points were implemented in the game! This will ease microing significantly...

I assume the waypoint logic could be extended to make nicer visual scripting waypoints in the ingame map editor?

**Comment by huwpascoe** [comment]
I'm now taking on this issue.

**Comment by Turupawn** [comment]
Hey guys! I'm new here and I just started working on this issue.
So far I managed to visualize the waypoint lines.
I made a [video showing my progress](https://youtu.be/jFSLQFePDqA).

I'm currently working on [this branch](https://github.com/Turupawn/OpenRA/tree/queued_lines) but I haven't made a Pull Request yet because the code is **very** messy. But I'll do so soon. Also, I'm waiting to get my other PR approved so I can understand better the workflow, see #11781 

Is this thing still alive? What do you think about my progress?

Cheers!

**Comment by Mailaender** [comment]
I also tried my luck with it, but failed to achieve anything usable. Your progress looks good. :+1:

**Comment by Turupawn** [comment]
I'll keep working on it.
Thanks! <3

**Comment by pchote** [comment]
I strongly suggest using the existing `Activity.GetTargets` code instead of rolling your own.

**Comment by Turupawn** [comment]
@pchote Sure! I'll do so :ok_hand:

**Comment by Turupawn** [comment]
BTW, Thanks for adding me to @OpenRA/bug-assignees. I don't know exactly what that means but I really apreciate it. :blossom:

**Comment by Mailaender** [comment]
You can now show others that you want to pick up a task.

**Comment by GraionDilach** [comment]
If you mean "letting issues assigned to yourself", then sorry to tell, but that never worked. Would have done that sometimes already by now if it would have.

**Comment by Turupawn** [comment]
@Mailaender  Cool!

**Comment by Turupawn** [comment]
Hello again guys!
A quick update about my progress:

* I just managed to make this work without rolling my own tech at #11794
* I just made a [short video](https://youtu.be/A2HpUPjA030) that shows how they look now
* @pchote: I didn't use `Activity.GetTargets` but `GetDestination` which is working just fine, what do you think about it?
* I had to deal with the Activity Queue which was **very** painful. What is wrong with that Queue? Why does it is always losing the references? Maybe I'm missing something because I have never coded on C# for this long...
* Now I want to simplify all this mess I just made so any code review overview would be a huge help at this point

Thanks again guys. This has been a [looooong](https://github.com/OpenRA/OpenRA/pull/11794/commits) trip but I'm having a lot of fun and that's very important to me

**Comment by pchote** [comment]
The activity queue is actively manipulated by a whole bunch of things (many of which really shouldn't be manipulating it), so trying to maintain your own state in parallel to that is going to be very difficult – as i'm sure you already know now!

I still strongly suspect the only way to make this work nicely will be to remove *all* the state from `DrawLineToTarget`, and push that into `Activity.GetTargets` so that the current target path can be queried on demand.

**Comment by huwpascoe** [comment]
Sorry I couldn't finish this, I know I'm one for rewriting classes (when perhaps I shouldn't) but that activity queue is something else... @Turupawn good luck to ye! :+1:

**Comment by Turupawn** [comment]
I could not keep up with the bleed changes on my branch so I switched to this new one which is working just fine: #11998

**Comment by xan2622** [comment]
Hi @forcecore . 

I have just tested your [visualising_waypoints3](https://github.com/forcecore/OpenRA/tree/) branch (for PR #14384) but I noticed that waypoints disappear after 2 seconds.   :confused:

I don't know if it is done this way on purpose but I think this delay is too short (5 seconds should be better) but IMO, I think that waypoints should never disappear after the unit is selected.
