### ISSUE TITLE
Save Game Support

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#2743]
It could just dump the current state of all units into a `map.yaml` file for the following use-cases:
- Share auto-save files to better reproduce and understand desyncs.
- Restart the game loading an auto-save when a player dropped.
- Finish the longer single-player missions tomorrow.

**Comment by WolfGaming** [comment]
well I started work on this again using serialization in last december but I didnt do any pull requests for it since no one seemed able to review it at the time.

Hopefully this will happen when I and the reviewers arent busy.

**Comment by kaneCVR** [comment]
Wish I had the skills to help with this.

**Comment by barfoo4711** [comment]
would be totally awesome to have this fixed ;-)

**Comment by thorsummoner** [comment]
Would really love a quicksave/quickload function too.

**Comment by tohava** [comment]
@WolfGaming - So what happened? did you continue to work at this? Did none of the admins have time? If I am planning to try and understand your work, should I like at https://github.com/OpenRA/OpenRA/pull/6287 or is there something newer?

**Comment by pchote** [comment]
@reaperrr and @obrakmann have been towards two of the main blockers for proper serialization (#12310, #12315).  If you'd like to help advance save games, it would be better to help them.

My experience with using replays to debug desyncs shows that the replay approach will never work well enough to merge (nobody will want to wait 30 minutes to reload a save from an hour into a game).

**Comment by tohava** [comment]
@pchote - I have some questions:

1) `DelayedAction` is bad because you can't serialize Action objects because serializing lambda/code is tricky, right? 
2) What is going on #12315? Why is it needed for save games?

**Comment by pchote** [comment]
1. Correct.
2. The activity code is a hotspot of technical debt and subtle bugs related to the way activities are queued, cancelled, and managed.  The activities need an overhaul to introduce a proper system for tracking the activity hierarchy and to kill off various one-off hacks that will otherwise cause headaches.

**Comment by Mailaender** [comment]
> My experience with using replays to debug desyncs shows that the replay approach will never work well enough to merge (nobody will want to wait 30 minutes to reload a save from an hour into a game).

Could we use that for reproducible performance stress tests instead?

**Comment by WolfGaming** [comment]
@tohava I still have my old save game branch somewhere on my git, it wasn't fully functional and I didn't have the time to finish it.

The main reason why it took so long to do is because of the activities, saving the hitpoints of units, position and money of the players etc is really easy compared to for example saving where a unit is moving simply because activities are quite a mess.

**Comment by TedDancing** [comment]
Hi all,

Apologies for asking a question without knowledge of the project:
Will progress here be usable with the RA2 mod?

Regards.

**Comment by Mailaender** [comment]
Yes.

**Comment by TedDancing** [comment]
Thanks!

**Comment by bartveurink** [comment]
Solution for saving: Just dump whole memory that the game used to a file. When the gamer want resume put the file back to the memory.
Saving is important for me, because i dont have the time to finish a combat in one evening. For resuming is one slot enough. The file with savegame takes up more space, but with one slot is it not a problem.

**Comment by pchote** [comment]
That unfortunately isn't possible with C#.  Objects in memory need to be explicitly serialized and deserialized.

**Comment by bartveurink** [comment]
Thus my idea is not possible. Is there a code available from the idea of the first message for testing and debugging?
Is there a similar project that has a working save-game function? Maybe there is a project written in c# with a save-game function and just copy and modify it.

**Comment by pchote** [comment]
@WolfGaming did a prototype of the replay approach, which showed that it was not feasible (it would take ~30 - 40 minutes to restore the state of a ~1h game).  There is no avoiding doing this properly, which means rewriting the simulation code to be able to dump and restore the world at a given tick.  @reaperrr and @obrakmann have been making progress towards that, but there is realistically a couple of years worth of work left with our current level of manpower.

**Comment by reaperrr** [comment]
> That really only leaves the proper approach... which means rewriting the simulation code to be able to dump and restore the world at a given tick. @reaperrr and @obrakmann have been making progress towards that, but there is realistically a couple of years worth of work left with our current level of manpower.

Since you're talking about years, I wonder what else except getting rid of DelayedAction and refactoring Activities is needed?


I'd also like to point out that some very good commercial strategy games had only 'partial' savegame support, where only some, but not all aspects and states were saved. IIRC in SpellForce only actor positions and maybe health were saved, while even revealed shroud wasn't. Quite annoying, but still far better than no savegames.
MechCommander even only allowed you to save between missions, not during, but that was also better than nothing and at least allowed for campaign progression.

In my opinion starting with a basic, simple, more singleplayer-oriented savegame support that only saves the most important parts - actor position, health, faction and such, trigger states - would be good enough at least for singleplayer, at least much better than no savegames at all.
Also, a campaign progression system that saves between missions would be a great feature as well.

My point is, instead of aiming for the by far largest and hardest part right off the bat - namely fully-fledged multiplayer savegames - we should start with comparatively easier things ^ first.

Otherwise we might run into that unfortunate situation where at some point in the (hopefully distant) future, development comes more or less to a halt, and modders are left with a half-finished but still not working MP savegame system, but not even the most simplistic campaign/mission savegame system, when the latter could have been implemented easily with a smarter order of priority.

**Comment by pchote** [comment]
Two things, really:
* Can't avoid all activity serialization because activities frequently put actors into temporarily inconsistent states (e.g. spanning multiple cells, using custom animatations, etc) and writing special cases to force sane enough data to save/load would be more work than implementing the basic plumbing an essential activity serializers.
* Lua is going to be a giant pain, and so far our best idea is "make the mission scripts deal with that"

**Comment by bartveurink** [comment]
@reaperr, do you mean that after saving a part of the current game, the code can later on be improved.
Some things I want to save:
- Map
- Structures with positions
- Units with positions
- Money

Further on:
- Restart AI on that position

unfortunately it can lose some things, but that is later on. I dont think this will take half an hour.

**Comment by cookgreen** [comment]
I think there are some things we need to keep:
Money
The unit and structure that Player build
The unit and structure that Enemy build
Radar Map
Enemy AI behavior(AI need to 'continue' what they will do)

Further on:
The unit and structure that Player was building and the building percent
Super Weapon Status
Mission Status(Single Player Campaign mode)

**Comment by cookgreen** [comment]
If we want to make resume game looks more natural, we need to keep many things,  save file will be very big of we keep these things saved as text-format file.
But if we can use "save state", the save file will be smaller, but it looks like there is not easy to read the dump data with C#, maybe shall we develop one?

**Comment by cookgreen** [comment]
Shall we make a Serialization for C#?

**Comment by WolfGaming** [comment]
A save state and a 'text format' file in this case are the same thing. If we don't save activities we get things like airplanes stuck in the sky (the ones that drop crates for example) and other bad things.

There really is no shortcut and the devs are slowly making headway to it.

**Comment by cookgreen** [comment]
@WolfGaming that sounds very great!

**Comment by hazelnot** [comment]
I don't really have anything to add, I just wanted to check on the progress with serialization and I don't really know where else to ask.

**Comment by danger89** [comment]
+1!

**Comment by pchote** [comment]
Considering the lack of progress on the serialization front, and the big improvements in tick perf from #15593, it would be worthwhile taking another look at the replay approach again for campaign missions.  The missions will typically have a lot less going on than an arbitrary skirmish, so would likely be a lot more tractable for resimulating from scratch.

If I don't forget, and if other work doesn't take priority, I would like to investigate this option for Next + 1. In order to control scope and expectations this would be limited to missions launched through the mission browser.

**Comment by reaperrr** [comment]
In that case it would be nice if we could fix & finish my mission progression system as well, getting both into the same release would be ideal.

**Comment by pchote** [comment]
I already have a working prototype that looks promising, so lets go one better:
