### ISSUE TITLE
Tire tracks as in Dune II [$10]

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#3188]
https://github.com/OpenRA/OpenRA/issues/7974 but with support for facings.

**Comment by MicroJOo** [comment]
i have made some footstep-graphics for infantry ... this is , how i think this could work (i have no codeskills though to do that ... if someone is interested , i can polish them and upload 

![footsteps footage](https://cloud.githubusercontent.com/assets/9139965/9815717/814b06fa-5898-11e5-8735-0a4693ebe2e7.png)

**Comment by LavenderMoon** [comment]
How will this (the logic, not the artwork) work with 32x32 tilesets, or 24x24 tilesets with 4 subcells instead of 9?

@MicroJOo Those are pretty good!

**Comment by Mailaender** [comment]
Note that our current effect rendering will draw this on top of units. https://github.com/OpenRA/OpenRA/issues/7520#issuecomment-75443959

**Comment by MicroJOo** [comment]
tbh. i have no idea ... i see most of the things im doing out of a "red alert 1" (1 cell = 24x25 pixel) perspective ...i know this is quite contra-productive when it comes to the total view of OpenRA , writing code that makes every mod benefit from a feature ... but since i dont know c# , i dont feel responsible to have a total view ... 

this is no logic at all , i have only heard that we have subcells ... 1 cell consists of 5 subcells (RA1) middle, northeast , southeast , southwest and northwest ... if we could somehow raise that , to 9 subsells ... a 3x3 grid inside a cell ... just for the footsteps ... then i could imagine "infantry footsteps" would work really good 

but the thing is , that we use tracks only for the whole cell ... (TS Hover Missile Tank on the water) or the sandworm ... and this would not fit for tiny little infantry footsteps

**Comment by Mailaender** [comment]
Whole cell tire tracks will be way easier to do.

**Comment by MicroJOo** [comment]
true

**Comment by obrakmann** [comment]
Just an idea, but wouldn't using the smudge layer for that fix the Z-sorting? Just needs a way to remove things from it, if there isn't one already.

**Comment by LavenderMoon** [comment]
Maybe for the infantry footsteps, instead of basing the logic off cells, we could base it off subcells, so that we consistently only need 8 footsteps, regardless of mod.

**Comment by TheRaffy** [comment]
It's an effect doesn't that need to be cell-related at all?
Don't we need just the "walk direction" and draw it frequently if the unit moved?
Having a parameter like every x frames.
ah this could lead to another mutant variable :(
