### ISSUE TITLE
Dune2 mod [$180]

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#3274]
I know there are several open-source projects about Dune2 but it would be cool to be able to play it with OpenRA too, with a mod.

The mod could have some enhancements like a checkbox to enable/disable the multiple units selection. 

This way, players who want to keep the original gameplay as it was, could still enjoy the mod.

Links:
http://forum.dune2k.com/forum/12-dune-ii/
http://dunedynasty.sourceforge.net/

Usuful tools:
http://forum.dune2k.com/topic/19752-list-of-dune-ii-editing-tools/
http://duneii.com/downloads/

**Comment by Unit158** [comment]
@Mailaender How much work have you put into this so far? I would like to contribute to the creation of the mod.

**Comment by Mailaender** [comment]
I need to redo large portions of my asset exploration branch due to the recent changes. https://github.com/OpenRA/OpenRA/pull/7461

**Comment by evgeniysergeev** [comment]
>Format80 is already supported -- C&C and RA use it.
any example how to load dune II original .pak files? 
I have this error in assets browser then trying to open any .SHP file from DUNE.PAK:

Exception of type `System.IO.InvalidDataException`: UNITS.SHP is not a valid sprite file
  at OpenRA.Graphics.SpriteLoader.GetFrames (System.String filename, OpenRA.Graphics.ISpriteLoader[] loaders) [0x00000] in <filename unknown>:0 
  at OpenRA.Graphics.SpriteLoader.GetSprites (System.String filename, OpenRA.Graphics.ISpriteLoader[] loaders, OpenRA.Graphics.SheetBuilder sheetBuilder) [0x00000] in <filename unknown>:0 
...

>A 90% complete GFX pack of Dune 2
>http://arrakis.dune2k.com/downloads/D2TMGFXPACK.zip
>
>this here is the main site : 
>http://arrakis.dune2k.com/downloads.html

How legally is to grab images from this GFXPACK and pack in new .SHP files?

**Comment by TheRaffy** [comment]
Does the OS SHP Builder support Format80?
Can you try open them by using the OS SHP Builder? Just for curiosity purpose.

**Comment by evgeniysergeev** [comment]
SHPs is in DUNE.PAK. I extracted them using python script and try to open using OS SHP Builder.
Result is: "Open Source SHP Builder 3.38 is unable to open this file” for every file that I try.

**Comment by GraionDilach** [comment]
The D2 SHP format is NOT the TD format - it always required a separate toolkit. IIRC TD/RA mouse were the sole assets which used that format in the C&C games which is why OS SHP Builder does not support it.

**Comment by TheRaffy** [comment]
Is there 1 .shp each unit? You talked about UNITS.SHP  
If they are all in one, I guess we need to seperate them anyway. 
I once used the Dune II Depaker for opening the .pak file
http://ds.nahoo.net/Games/Dune2.html
I also found that: 
SHP: This is a series of frames compressed into a single file. It is used for unit, smudge and menu button graphics. Unlike the later versions of SHP format (used in Command & Conquer for example), each frame can have different shape.  Here: http://forum.dune2k.com/topic/19752-list-of-dune-ii-editing-tools/

**Comment by pchote** [comment]
We have a specific sprite parser for d2 shps. You may need to enable it in your mod.yaml first.

**Comment by evgeniysergeev** [comment]
Thanks. d2 shps can be opened in asset browser if you specify ShpD2 in SpriteFormats section in mod.yaml

**Comment by evgeniysergeev** [comment]
can read dune2 .shp. but can't find .shp for structures. is any way to load original dune2 sprites for buildings?

**Comment by evgeniysergeev** [comment]
My idea is to split dune2 mod to two steps:

1) allow art from dune2 on d2k maps. two types of mcv. two production trees. if user on map have mcv only from dune2, than only dune2 building avialable. I hope that at some moment battles between old-school dune2 and modern  dune2000 players can be possible. Have some troubles on that way. create topic for that on forum: http://www.sleipnirstuff.com/forum/viewtopic.php?f=83&t=18593  
2) using knowledge from step 1, create separate dune2 mod that do not use anything from d2k.

I trying to work on 1). but have troubles with art.
1.1) I can't load images for buildngs from original DUNE.PAK. if anybody already do that, please share info how.
1.2) Have no answer: is it possible to just grab images from that link (found upper in discussin for that issue): 
> A 90% complete GFX pack of Dune 2
> http://arrakis.dune2k.com/downloads/D2TMGFXPACK.zip
and create .shp using it. Will EA allow that. I know that dune2 for android was removed from google store because it was use original graphic.

**Comment by Nyerguds** [comment]
There's a bunch of info about reading the icon.map and icon.icn on the fed2k forums, here:
http://forum.dune2k.com/topic/19099-format80-decompression/page-2
Apparently Olaf Van der spek wrote code for that too, but I'm not sure if it's actually in the xcc repository.

Besides icon.map and icon.icn, you also need the building dimensions and frame configurations. Those can be found in the rules dumps I made with my editor:
http://nyerguds.arsaneus-design.com/dune/dune2rules/

**Comment by pchote** [comment]
You *could* convert everything to shp, but you don't need to, and it would be a sub-optimal choice.  The OpenRA engine supports writing custom code for parsing sequences (which you'll need for the mirrored facings), and already supports the PAK format (again, you will need to specify it in the mod.yaml) and sprites.

**Comment by evgeniysergeev** [comment]
> and already supports the PAK format (again, you will need to specify it in the mod.yaml) and sprites.

Can you help with that? I unable to load ICON.MAP in asset browser. 
I added DUNE.PAK in mod.yaml and ShpD2 type, but unable to load ICON.MAP

Exception of type `System.IO.InvalidDataException`: ICON.MAP is not a valid sprite file
  at OpenRA.Graphics.SpriteLoader.GetFrames (System.String filename, OpenRA.Graphics.ISpriteLoader[] loaders) [0x00000] in <filename unknown>:0 
  at OpenRA.Graphics.SpriteLoader.GetSprites (System.String filename, OpenRA.Graphics.ISpriteLoader[] loaders, OpenRA.Graphics.SheetBuilder sheetBuilder) [0x00000] in <filename unknown>:0 

 Any existing OpenRA code example, that can load Dune2 buildings sprites? I know that dune2 clones can do that, but don't know how to do that in OpenRA

**Comment by pchote** [comment]
You'll need to write a sprite parser for the .MAP format - the info that @Nyerguds gave above describes the format. You can include this in a mod dll that you reference from your mod.yaml, so don't need to modify the core engine code (although we would probably accept it into the core project if you wanted to file a PR with it).

**Comment by Nyerguds** [comment]
It's a peculiar format... each cell uses a subset of 16 colours from the main palette. I'm not exactly sure how it works, myself, and unfortunately the original website of the tile editor is gone.

**Comment by Nyerguds** [comment]
If I remember correctly, icon.map's first twenty or thirty-something entries are actually indices in the same file indicating the starts of frame ranges. These indices are the "Structure graphics ID" in my rules files. At that index in icon.map you will find another index in icon.map. On that second index, you will find the icon.icn frames for that building.

So, for example, take an icon.map with 5 buildings. The first five bytes will look like this:
[5][13][27][35][44]

At index 5 in the file you will find the first cell for the first frame for building 1. At index 7, you'll find the second cell of the first frame, etc, until you reached the amount of cells for that building's foundation. Say it was a 2x2, then you will find its second frame at index 9.

This can learn us two things:
1. The value in the first byte is effectively the length of the table of contents; it ends at byte 5.
2. In combination with the foundation size, this will accurately determine how many frames each building has.

The building animation scripts I linked to earlier will give the actual usage of these frames.

If you search for the "structAnim" array in the source code of my dune II editor (which generated the rules file), you can easily interpret the scripts from the rules.ini. That source code can be found here:
http://nyerguds.arsaneus-design.com/dune/dune2edit/source/duneedit_v2.02.2.pas

**Comment by Nyerguds** [comment]
Code to read a specific building frame from icon.map, after loading in all of icon.icn, should go something like this:
(with "Cell" moonlighting for whatever class is used for each cell of icon.icn. I assume icon.icn is an array of "Cell" here)

cellsPerFrame is effectively the foundation size, for for a 3x3 it'd be 9.

    Cell[] ReadBuildingFrame(int structgraphId, int cellsPerFrame, int frameToRead)
    {
        Cell[] frames = new Cell[cellsPerFrame];
        startframe = IconMap[structgraphId];
        startframe += cellsPerFrame * frameToRead
        for (int i=0; i < cellsPerFrame; i++)
        {
            frames[i] = IconMap[startframe+i];
        }
    }

**Comment by MicroJOo** [comment]
@evgeniysergeev : its is possible to convert everything to shp , like @pchote said , but i also would not recommend it , better do it the proper way as he suggested 

i did build a shp with the d2-harvester last year , just to convince myself ... sequences are completly fucked up of course ^^ 

OpenRA DII Harv Test
https://www.youtube.com/watch?v=9hG_TLPP81E

**Comment by evgeniysergeev** [comment]
Thanks a lot for detailed comments. I'll try to load from map file. Just want to know, why everybody say that creating sprite loader is better than creating convertor/extractor from original files to shp.
By my mind, I can extract images from DUNE.PAK, apply diffs that fix color problems, enhance graphics ( I said that I want scaled x2 images, without such modifications it will not look very good. pixels will be very big). arrange sprites as it should be to fix sequences problems(like with harvester in video above).

The easiest and perfect look way is to just extract and modify graphics. The hard way is to extract from original files and apply modifications. Looks like need to implement hard way, but only because it is not legal to distribute original graphics.

About implementing sprite loader. As I can see, Sprite loader receive stream object. but as explained earlier, need two streams, one for .map and one for .icn file. At this moment, it is not very clear for me, how to implement this. read .icn file in ParseFrames for .map file or read .icn before .map and have some reference then loading .map file. Or modify core loading functions and "hardcode" this.

**Comment by TheRaffy** [comment]
These details can be overwhelming. I think it's now a principle thing. OpenRA seems to already support alot stuff like the "dune .shp" and the .pak files. This work could be seen as waisted time, if we bypass that with a graphical approach. Even when it is much more easy to understand how to do it with the graphics. But in the case of maintainability and expandability the RA.shp file will not be as a bad choice as we might think, due to tools like the open ship builder. But in the other hand there are maybe already modifided original .shp files, or modified units out there.

**Comment by evgeniysergeev** [comment]
Thanks guys

I found "Doon Lunacy" library at the link to forum.dune2k.com, that @Nyerguds share earlier in this thread. I think I can port it to c# sprite loader.

> so don't need to modify the core engine code (although we would probably accept it into the core project if you wanted to file a PR with it).

Modifications in SpriteLoader.cs will need to allow SpriteLoaders load additional streams. currently TryParseSprite function accept only one stream.
I decide to create ISpriteLoader2 interface for Dune2 sprite loader. 
[code]
public interface ISpriteLoader2: ISpriteLoader
{
        string GetLinkedFileName(string filename);
        bool AddLinkedStream(Stream s);
}
[/code]
and modify SpriteLoader GetFrames function to work with both ISpriteLoader and ISpriteLoader2.
let me know if you can provide better way for loading dune2 sprites from two files.

**Comment by pchote** [comment]
A simpler (but a bit more hacky) approach would be to have your icn parser open its own stream for the .map file, and then close it once it is done (before returning).  All the frames from a sprite file are loaded up-front, so there aren't any performance concerns related to repeatedly opening and closing streams.

**Comment by evgeniysergeev** [comment]
I like, how flexible is OpenRA sources. don't want to use any "hardcoded" filenames or constants in it.

**Comment by Unit158** [comment]
As flexible as you make them, really.

**Comment by evgeniysergeev** [comment]
Good news! .ICN + .MAP now can be read directly into OpenRA.
But I want to put this loader in common mod and some core files was changed. Any instruction how to create pull request? doesn't do that before.
![screen shot 2015-09-11 at 15 05 13](https://cloud.githubusercontent.com/assets/3105609/9814453/edc29afc-5896-11e5-9174-f15ba9e093cc.png)

**Comment by evgeniysergeev** [comment]
https://github.com/OpenRA/OpenRA/pull/9318

**Comment by x-a-n-a-x** [comment]
Hi evgeniysergeev. 
Thank you for working on this Dune 2 mod, your contribution is really appreciated. 

It would be nice if you joined us on our IRC channel : http://www.openra.net/community/. 

We, (contributors and developers) usually discuss about OpenRA in this chatroom. 
It would be interesting to be able to "talk" to you there.

**Comment by pchote** [comment]
I'm all for adding the file format support needed for an outside mod to build their own D2 clone on top of OpenRA, but expecting us to maintain and ship our own version of it is unrealistic.  There are already several good d2 clones, but the bounty is getting large enough that somebody might try to cash in on it and then leave us to maintain it in perpetuity, which is very unfair on our small development team.

  I'm going to close this ticket now because bountysource doesn't let us restrict bounties on a single ticket.  @evgeniysergeev and others, please feel free to open new tickets for any sub-features that you need to build your own d2 mod project.

**Comment by evgeniysergeev** [comment]
#9654

**Comment by TheRaffy** [comment]
#9580 That's my feature list of the Dune2 mod

**Comment by penev92** [comment]
You should probably talk to @evgeniysergeev about moving that list to his repo - https://github.com/evgeniysergeev/OpenRA as he is the one working on the mod. Then people could place bounties there if they want to.

**Comment by x-a-n-a-x** [comment]
The $180 bounty is still valid.

**Comment by SoScared** [comment]
Letting you know that in the event Dune mod for OpenRA happens, I'll be make a short announcement/trailer video for it. Mixed soundtrack: https://dl.dropboxusercontent.com/content_link/6wsZjcebFZa7WCrFpqNJmafCJsSU1iJroj0Zh2R0z0zLIB7zW9UVbrTW42a90mm6/file

**Comment by yaaaaa** [comment]
SoScared, Error (404)

**Comment by x-a-n-a-x** [comment]
I have started to think of an interface for the Dune2 mod.

https://github.com/OpenRA/OpenRA/issues/3789 might be required for a Dune2 UI (if we want its interface to feature these buttons by default).

![Image of Dune2](https://upload.wikimedia.org/wikipedia/en/3/31/Dune_2_screenshot_attack_on_base.jpg)

But for my Dune2 UI proposal, I would prefer the Order Palette (attack, move, retreat, guard) not to be displayed by default, but only after units have been selected). So unlike the original Dune2 UI (the screenshot above), the order palette would appear below the production palette (for example).

IRC log (pchote's idea is really interesting): 
http://logs.openra.net/?year=2016&month=06&day=15#18:52:22

**Comment by Micr0Bit** [comment]
thought i should post my sketch here ... this is to show what i had in mind about how to use the elements from the oldschool interface ( just an idea , im still open for a different design)

![2gvap2h](https://cloud.githubusercontent.com/assets/9139965/17071374/7d339b74-5061-11e6-9f7d-33bd15ef1471.png)

**Comment by TheRaffy** [comment]
Hey, in my opinion buttons for orders (attack or move,..) are antiquated and should be avoided at all costs. Standards did not establish without purpose. Compare it to the single unit selection. Do you really like to use such old standards? There's no deeper scene in using old standards.
Plz, don't create such order buttons.

nice sketch @Micr0bit.

**Comment by SoScared** [comment]
Agree with @TheRaffy about the attack/move but I'd be super excited about using the classic build options where everything is built in the separate window. Might be a bit outdated but it's at the crux of what Dune 2 was about - environment.  This plus the click-and-order 1 unit at a time made Dune 2 very slow paced RTS, almost turn based even - a modern version might risk streamline the game a bit hard, phasing out the few qualities it had over its' successors. IMO this needs to addressed this if people are to enjoy a D2 mod.

**Comment by MustaphaTR** [comment]
Sketch looks good but i'm not sure if we really want toggle power on d2. Also what about the text box? I really like how it shows percent fullness of harverster here. Also d2 had subtitles enabled when sounds disabled. (I used them because seeing text is easier than hearing, especially for Death Habd Launched notification.) Do we plan to implement these? 

About 1 unit selection and command buttons. I'm fine with them. I also agree with SoScared that full sized building UI can be good. Also if we are not gobna go with that, we should go like TD mod to allow ever stucture work seperately. IIRC this is how d2 works.

**Comment by TheRaffy** [comment]
Well, in the end any working HUD is better than no one :D 
So, for me I like that old design. But I also think the active developer, who is doing stuff, should always have the last word. We aren't much, who care about this mod and I'm happy about any steps towards a more complete d2 mod. That means I changed my mind, please do what you think is the best, motivates you the most and is easy to accomplish.

**Comment by Micr0Bit** [comment]
@Nyerguds : http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&p=297305#297305

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/d2 now.
