### ISSUE TITLE
Request: Ore Trucks prioritize gems.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#3685]
Would be nice if Ore Trucks would prioritize gems over ore. Like when there is an ore field with a few gems in it, they would harvest the gems before going after the regular ore.
##

**Comment by pchote** [comment]
This kind of automatic prioritization has been rejected in other cases (e.g. target selection) as removing too much micro.

**Comment by penev92** [comment]
Yeah I don't like this.

**Comment by MustaphaTR** [comment]
:-1: I agree with @penev92 and @pchote here.

**Comment by Smittytron** [comment]
Ore trucks would lose mining time going after gems that are farther away, which will cost the player in earnings per minute despite gems being worth more. Also, there is nothing more frustrating than ore trucks running off and doing their own thing.

**Comment by evolvingmeat** [comment]
"which will cost the player in earnings per minute despite gems being worth more" @Smittytron can you please tell me more, I don't understand it.

**Comment by Smittytron** [comment]
>  @Smittytron can you please tell me more, I don't understand it.

In the early game, where you only have one or two ore trucks, it is very important to micro these units to harvest the closest ore. Harvesting close ore gets you income faster so that you can build as much as possible in the early game. Even though both players will have the same size ore patch, if you do not micro your ore trucks you will fall behind as your opponent will be able to build more quickly, and their economy will scale faster.

If ore trucks were to seek out gems within their scanning range over ore, this would have them travel further distances for money and would needlessly slow down your early game economy. An ore truck would have to deliver a load of gems faster than the time it would take to deliver two loads of ore to make it worth it. I don't see that happening with how most maps are designed.

**Comment by tovl** [comment]
This seems like a wont-fix. It would be nice if `HarvesterBotModule` could maybe prioritize gems/blue tib over other fields in some circumstances, but I agree this takes away strategic decision-making if applied to human players.

**Comment by Smittytron** [comment]
Closing as won't-fix.
