### ISSUE TITLE
Ore/tiberium/spice silos should be actually useful

### ISSUE THREAD

**Issue by ScottNZ** [OpenRA/OpenRA#3816]
##

**Comment by Mailaender** [comment]
We could also use it for some kind of upkeep mechanism like the houses in Warcraft/Age of Empires.

**Comment by dan9550** [comment]
I greatly dislike the idea of an upkeep system.

**Comment by SilverlineDev** [comment]
:-1: on the upkeep system idea.

**Comment by penev92** [comment]
^ At least for the official mods.

**Comment by TheRaffy** [comment]
How about that idea:
- Silos are just getting filled when all your refineries are full
- A full silo produces money like a tiny oild deck.
- If the refinery stock is longer max, the silo stays full.
- The spies empties the silo
- You can access the ore that is in your silo by selling the silo (spy prevention)

This would create a dessision making:
- Shall I eighter building more refineries, or some silos? 
(As more refineries you have as more stock you need fill until your silos are starting to work.)
- Is it worthy to sell a refinery to get more full silos? Which refinery should be sold?

That also could make the games more interesing when ore runs out.

**Comment by Mailaender** [comment]
My second idea is to remove or drastically reduce the storage capacity of refineries so you need to build at least some silos to float a little bit in cash instead of more refineries which give you another harvester for free, a new drop off point _and_ more storage. It would be closer to the original design, but could be annoying with "Silos needed" being an actual problem you need to solve by building silos and not more units.

**Comment by Unit158** [comment]
i believe @penev92, @theraffy and I came to an agreement that silos giving an income boost makes sense in d2k in light of spiceblooms and the vanilla balance patch. 

On my own, I believe it would also make sense in RA, they would provide too little to matter on maps such as great divide and other high ore maps and be a valuable strategic asset on ore starved maps.

However, they should pose some risk, and one idea is that the silos could fill up one at a time and be depleted in the reverse order, thus making the risk that a single silo being destroyed could make a player lose a somewhat significant portion of their money. This would also allow for interest rates on full silos only, or something along that line.

**Comment by TheRaffy** [comment]
yes, but I also think its a good thing for RA.

**Comment by r34ch** [comment]
Firstly I vote for consistancy. I think of ore silos as holding molten ore, which once spilled would quickly solidify into normal ore. As such, a full silo should spill ore like the ore truck currently does.

Secondly, rather than making drastic changes (at first) I would like to see silos simply do their C&C role, but just much much better.

Cost £150->£100
hp 300->400
Capacity 1500->3000 (maybe even larger) 

With these changes as an example, a few silos would allow your harvesters to clear an ore field rather than sit dumping at the REF. In this case depriving your enemy of an ore field could become more of a viable tactic with cheaper higher capacity silos.

The flip side would be that once destroyed, that income is simply lost. Spies should steal from silos, but the amount dependant on its capacity. £500 is ok for a REF, but a silo should be much higher as to make a profit for a normal spy (half its full storage capacity). Also engis should capture them and keep all the income inside if not the case already. 

The added storage amount means a struggling / crafty player has to inflitrate / capture far fewer enemy silos to have a chance to turn the game around. The lower price and higher hp means players would be a little less hesitant to build them.

Once purposeful for even just one strat, I think silos would loose their stigma in MP games.

**Comment by r34ch** [comment]
And as a completely seperate point, perhaps in MP they could interact with allies in some economic fashion much like the supply truck?

The raffeys idea of silos being mini derricks is cool. Perhaps a secondary function of a silo is to allow it to be 'funneled' to an allied player via some GUI popup or interaction. Then cash slowly ticks away from your income straight into an allied account no matter the physical position of your ally. More silos assigned to a player, the higher the trickle rate.

It could be interesting in team games for one person to focus eco and one to rush. Silos don't require a WF so can help teammates from the very start, but the trickle (and the fact that trickle depends on you having cash) would keep it balanced.

In my eyes, that could be far more useful as a one time investment (build silo, choose ally, let it trickle out of yohr account) than having to micro a supply truck and clog up your production. However, as quick cash boosts, supply trucks would very much keep their usefulness.

With a small trickle rate, silos would be less likely to be sold at various points in the game as it has a purpose that is dependant on time. This in turn could give players more time to capture or inflitrate them.

**Comment by pi99y** [comment]
My take:
Positive effects:
* each silo **when full** reduces unit production time by X% (and it caps at XX%) (that's in addition to the production bonus for having multiple production buildings):
- faster production is always beneficial to a player
- effect being activated only by full silos means: 
 -- can't be in (full) effect too early (early game)
 -- you are encouraged to either mine faster/more or save up for a temp. production boost (different play "styles")
 -- is temporary since spending depletes silos and reduces the effect

Negative effects:
* harvesters stop working when you don't have enough silos for your cash (current behaviour)
* silos must be placed around an ore factory (making them more exposed to the enemy, since refineries tend to be on the edge of the bases)
* a captured, infiltrated or hijacked silo gives all cash from all your silos to the enemy and also cancels your unit production queues (and maybe disables production for X seconds).

:)

**Comment by SoScared** [comment]
I strongly dislike the proposed ideas of making silos money generators and/or reducing production time, or giving them a strong role in the game at all. These are powerful solutions for, let's be honest, a non-issue. Useful for starved maps? If players intentionally made a map starved for ore then that reason becomes nonsensical. IMO there's absolutely no demand for it in terms of gameplay.  It expands an aspect of the game that has no need for it. We're waging war, not managing a budget for the next calendar year of Sim City.

I'd fully support a small tweak that makes silos slightly more attractive - just slightly. E.g.:

- Immune to spies. There's no need to widen the target area for spies against players who's actually building silos.

- Remove power usage.

These are suggestions that would slightly support newer players (e.g. less punished by power outages because of silos), and perhaps players in general not keeping up their production versus income (retaining a strong economy over a longer period of time).

Obrakmans suggestion above makes sense given that the silo would be a necessity for a player loosing control of his/her economy. I like the idea but know that it would probably create a bigger gap between player's skill levels - it strongly rewards better management of your production versus economy. I'd like to see that change in a RA mod with a bigger player base (future feature).

**Comment by TheRaffy** [comment]
I think soscared has a rly good point here. The immune to spies could not only mean spys can't enter silos, we can additionally make it a robber save storeage. I like that. 
But im not sure about the powerfree silo. maybe just 5 instad of 10 power-

**Comment by GraionDilach** [comment]
I personally consider discarding excess resources a bug in the WW games. The silos being spyimmune sounds good but shouldn't that be discussed in the forums first?

**Comment by SoScared** [comment]
x-posted my previous comment to the forum for discussion

**Comment by obrakmann** [comment]
Another contribution to the discussion from @epicelite (quoted from #9878):

> When you build a silo it gets a 10% bonus of ore put into it every time a ore truck dumps a load at your refinery. If you build more silo's your bonus is not increased, but spread out amongst those silo's.
>
> So you can choose to build a single silo, but your enemies will know to take it out and you lose all of your bonus. However, If you build more silos you have a greater chance of getting your bonus but it till take longer.
> IE: 2 silo's = each get 5% and such I'm not good at math.
>
> This can create some target-of-opportunity situations where you're in the middle of an attack and see your enemies silo is almost full, so you should take the time to destroy it so they get no bonus.
>
> Can you guys even understand what I'm saying?

**Comment by pi99y** [comment]
@SoScared I read your suggestions in the forum and trust you know the game better than I do, however silos not loosing money when destroyed seems off (and as you suggested would need a visual change - roofs). My question is: Isn't it enough of a protection that you can build silos deep inside your base, where they are more protected, since harvesters don't need acces to them - like with the refineries? Roof seem like "hard to implement (new artwork)" and we loose the cool original visual effect of them filling up.

**Comment by SoScared** [comment]
@pi99y The silo with the suggested overhaul still wouldn't be a particularly prioritized target and it's easier to build them in safe spots. Silos not losing ore when destroyed ties in more with the idea that the ore you collect is sold and what you retain from it is now numbers in your account rather than physical ore, as suggested with the ore behavior of the refinery. It's not a prefect analogy, I know, but still makes more sense than what we have now. It's all a bit up in the air tho because in the end, the red alert ore economy really makes no sense in reality :) Number wise, the liability of building a silo (losing its content) will never be balanced out by a new found usefulness, unless you give it some kind of ridiculous OP property. Say we wanted to implement the suggested changes and you build 2 ore silos for $300 to raise your cap and safeguard up to $5000 credits from spies. But alas, you lose the entire $5000 because of a random paradrop, destroying them in 5 seconds.

direct link to comment in the forum post: http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&p=293113#293113

I think the use of ore silos in OpenRA is so completely absent that I'd be willing to trade off the original visual effect (a shiny metal roof) if in exchange gaining a legitimate reason to build them.

**Comment by pi99y** [comment]
Thanks for the replay @SoScared.

In general:
I really don't see how silos would become a big liability. But admittedly I suck at the game :) 
I do care deeply for the game nevertheless and really wish it had no "useless" or missing (if it was in the original) stuff.

You (any of you) might have allready pointed this out and I didn't get it but wouldn't this be still much better than it is right now (and not a big liability)?

Example:
* ore factories are built close to the ore, because you want a short path for harvesters
- (negative) they however can only store small abouts of ore 
- (negative) factories are theft (loosing the credits and giving them to the enemy)
* if you build silos the benefits are: 
+ (positive) you can store more ore, 
+ (positive) you can put them in a safer place
+ (positive) you actually have to protect just that one spot istead of all the refineries
- (negative) a bit of power drain, small initial cost

Additional changes:
- (negative) refineries would loose ore (being scattered around if destroyed, so you have to re-harvest OR they could be gone forever), still could have credits stolen (given to the enemy)
- (negative) but could store less ore than now (motivation for building silos)
+ (positive) and silos were immune to theft,
- (negative, but neutral compared to refinaries) but the destruction would mean lost (scattered ore)
- tweaks to silo cost and power consumption

I then actually don't see a negative side to silos, just that the game would become a tiny bit more "economy-management" intensive (but only if you don't spend fast enough).
I feel like this adds to complexity (in a good way; "richness"?) of the game and diferentiating players on skill isn't a bad thing.
The importance of this mechanic could probably still be fine-tunned by refinery and silo properties ("how-much-refineries-store" and "how-much-life-silos-have", silo cost, power consumption) but this would keep silos in game (being actually usefull), which is another positive thing.

PS:  
* Yeah if enemy nukes you silos, then they traded the nuke for your "cash" 
* Yeah paradrops could sneak in, but you had a much better chance of protecting that than all your refineries 
 
I'm not trying to convince anyone that I'm right but  wish to understand why some seem not to really care for the change. :)

**Comment by hacikenks** [comment]
Spies infiltrate war factories, refineries, radars etc. but you suggest that they should not infiltrate silos. Sorry but this sounds a bit strange. If anything spies should be able to infiltrate more buildings.  Also  stored minerals do not generate cash. They often depreciate and lose their value, if anything. Why not make them cheaper instead?

**Comment by ShadowA** [comment]
Didn't read whole discussion but ...

> @Phrohdoh 
> I am OK with removing them from the buildables in MP completely because of all of this.

I actually use silos in MP ^_^ they are useful as they are designed now. 
I don't mind change, but please don't remove them :)

**Comment by MustaphaTR** [comment]
I'm not sure does it fit to OpenRA but i just wanted to say. In my YR mod as Bounty logic added in 0.C, i made the silos prerequisite for bounty income. So no silo=no bounty. For OpenRA maybe silos should incrase bountry income a bit instead of being prerequisite.

**Comment by pi99y** [comment]
I like @MustaphaTR 's idea of increasing bounty income as long as silos also pose a risk = money can be stolen from them. 1 silo could be something like +1% to bounty incoime and capped at 10-20 silos so that you have to build many meaning it's a bit harder to defend them.
Silos animation reflects how much you're floating = indicating how much can be stolen from them.

**Comment by TheRaffy** [comment]
Or silos could be required together with the refinery to build Harvesters at the warfactory.
That would make silos an even better target (People would build more than one, for safety reasons),  and on the other hand it would boost double ref builds.

**Comment by pchote** [comment]
It seems that the discussion here has run its course, and that there are no reasonable solutions that will magically make silos are core part of the gameplay.  Silos are used as part of the campaign, and still serve a purpose for casual players who don't feel a need to optimize their economy.  That is good enough, IMO.
