### ISSUE TITLE
Cannot detect/recognize/load data from C&C:The First Decade DVD

### ISSUE THREAD

**Issue by DomtronVox** [OpenRA/OpenRA#3863]
After starting ORA and selecting the RA or C&C mods, I place the C&C:The First Decade DVD in to my drive. Then I select the load from CD button and immediately receive a "disk not found error." The drive and dvd are functional since I had it installed in wine at one point and I can open the dvd's contents.

I'm guessing that ORA just doesn't support DVD's/The First Decade in which case this is a feature request rather then a bug. Anyway I though an issue should be made.

OS: Ubuntu 12.04 LTS
game version: playtest-20130915 pre-compiled .deb

**Comment by DSUK** [comment]
I am intrested in trying to fix this, though the only .cab extractor i know of is [unshield](https://github.com/twogood/unshield), which I find behaves in quite a peculiar way with TTFD Disk.
I am also not 100% sure if this library will build in windows/mac or not.

**Comment by davegorst** [comment]
Hiya,

Sorry I don't have a PC at the mo, otherwise I'd help. I vaguely remember
making some notes. I think there might need to be some code reorganisation
to deal with different layouts of the filesystem within the .cab. I think
the compression is reasonably standard though, and unshield should extract
it without problems.

Cheers,
Dave

**Comment by DSUK** [comment]
Update: I managed to hack something together that work for C&C however the list of required files in the RA mod isn't consistent the files that are available for RA part of TTFD ( [File List, In groups] (https://gist.github.com/DSUK/e243103217bac918b175) )

the code in available on my fork but it's dirty and hacky and not pull request worthy atm.

**Comment by Mailaender** [comment]
It would be best to implement the file format in C# for OpenRA instead of relying on a platform dependent `libunshield.so`. We already have a parser https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/FileSystem/InstallShieldPackage.cs made for Dune 2000, however the format probably has changed over the years so this may not work without changes.

**Comment by Mailaender** [comment]
There is now a pull request https://github.com/OpenRA/OpenRA/pull/8170 ready for review and testing. Thanks @DSUK!

**Comment by davegorst** [comment]
Please accept my invitation to WorkFlowy


  
  Hi,

Join me and 2 million other people using WorkFlowy to get organized. 

Please accept my invitation (and get us both free space!) using this invite link: https://workflowy.com/invite/24020849.emlx

Thanks,David Gorst
  

  
    
      You are receiving this invitation because David Gorst invited you to WorkFlowy.
    
  
  
    Workflowy · PO Box 40507 · San Francisco, CA 94140
