### ISSUE TITLE
Filter repeated actions

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#3923]
> In AoE, clicking repeatedly when the users were excitedly attacking (clik-lik-lik-lik-lik -- go go go ) was causing huge spikes in the number of commands issued per second -- and if they were pathing a large group of units -- huge spikes in the network demand as well. A simple filter to discard repeat commands at the same location drastically reduced the impact of this behavior.

http://www.gamasutra.com/view/feature/131503/1500_archers_on_a_288_network_.php?page=2 
##

**Comment by abcdefg30** [comment]
https://github.com/OpenRA/OpenRA/pull/11673#issuecomment-619400522 rejected the basic idea here. It is indeed not as easy to do this while issuing orders since some orders might behave different if multiple come through. #19397 offers an idea to solve this on the `ResolveOrder` side of things which should increase usability.
