### ISSUE TITLE
Write a tutorial on creating a basic mod.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#4201]
This should cover creating a new mod.yaml that inherits an existing mod (including, instead of copying the base files).
It should then demostrate how to add a new unit that uses already existing graphics (changing the Image key in Render*), and overriding properties on an existing unit.
##

**Comment by penev92** [comment]
I don't think this is applicable at this point. I have tried creating a mostly hollow dummy mod myself several times over the last few months and it is a total pain.
The best advice we can give modders is "copy one of the existing mods and start removing the stuff you don't need from it", I think. The UI is especially bad here, because it's the reason for most of the crashes when you try to start from scratch or copy a mod and mass delete stuff.

**Comment by Mailaender** [comment]
That sounds like a good plan at first and is what every newbie does, but it will make updates painful especially chrome.yaml stuff will lead to frequent crashes whenever we do UI changes. If you reference those files you don't want to change anyway, you also get the update service for free. It also gives you a simpler file tree to work with.

**Comment by Unit158** [comment]
This should be given new thought now.

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRAModSDK/wiki

**Comment by penev92** [comment]
With the creation of the ModSDK, is this issue still relevant?

**Comment by pchote** [comment]
Fixed by https://github.com/OpenRA/OpenRAModSDK/wiki/Getting-Started.
