### ISSUE TITLE
Act on Instinct (Voiced) does not play.

### ISSUE THREAD

**Issue by dan9550** [OpenRA/OpenRA#4438]
Using mix files taken straight from original game CDs the music player simply just skips to another track when trying to play Act on Instinct (Voiced).
##

**Comment by clemty** [comment]
I extracted aoi.var (the song that does not play) and trouble.var (plays), switched their filenames, and put them back in the .mix file

now 'trouble' plays when I click on 'Act on Instinct (voiced)' in the song list
if I click on 'In trouble (voiced)' it skips to the next song in the list, as before

logs don't show anything unusual, sound.log is empty

conclusions:
- the track name entry for Act on Instinct (voiced) in the list is correctly connected to the aoi.var file in scores.mix
- mix file layout is valid (otherwise openra wouldn't be able to open, the problem seems to be the content of the specific .aud file

I assume the problem is the way openra handles the data found in aoi.var





the problem seems to be the way the song is referenced from within openra:

**Comment by reaperrr** [comment]
most of the .var files seem to be generally of lower sound quality (more muddled, possibly earlier, unoptimized encoder).
aoi.var has an audible 'screech' sound at the start, maybe a bad chunk.
WW's audio engine might simply be more lenient at handling encoding errors (skipping or simply playing bad chunks rather than skipping the entire file).

**Comment by dan9550** [comment]
In my ideal world we would be using OGGs or FLAC files for the music :)

**Comment by Biofreak1987** [comment]
What's the status regarding Act On Instinct (SFX) support?

**Comment by clemty** [comment]
Largely unchanged: the track entry got moved further down (4c461b08af31001accc8b1832667caf53aa2d6df), but it still does not play

**Comment by matjaeck** [comment]
Songs plays for me, so I think this is fixed?

**Comment by abcdefg30** [comment]
It works for me too. If someone can reproduce this issue we can reopen it.
