### ISSUE TITLE
Investigate software voxel renderer

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#4539]
Voxels are tricky to efficiently render in GL, and our current renderer is hacky and relatively slow.

We may be able to win some perf by doing the initial voxel -> texture renderering on the CPU, using voxel.vpl for lighting.  This would give us a regular indexed sprite that we can render using the normal shp shader. 

We would then save the FBO switch each frame plus any batch breakage from switching between the voxel and shp shaders.
##

**Comment by GraionDilach** [comment]
Please do not use the actual voxel.vpl for this task, due to the main reason current voxel renderer being praised by the community is that it does not depend on said file.

The vpl principle sounds good on paper, as being 16/32 practically HSL-based lighting steppings - but the end results look inferior due to that they are forced back to the originally used palette.

A compromise between performance and visuals could be that instead of using the vpl, the engine generates a bumpmap sprite/overlay from the normals along with an indexed sprite from the colors and render that.

**Comment by GraionDilach** [comment]
The voxel renderer in @DCoderLT's cncpp project might help.

**Comment by pchote** [comment]
Superseded by #14674.
