### ISSUE TITLE
Prevent UI sounds from 'overlapping'

### ISSUE THREAD

**Issue by NinovanderMark** [OpenRA/OpenRA#4690]
Currently, if you click on a UI button repeatedly, like when building multiple units, the sample for that action is played as many times as the button is clicked. This is pretty crude and a better way to handle that scenario should be implemented.

My suggestion would be that only 1 of each UI sample may be played at the same time. Don't playback the sample if it's already playing.
##

**Comment by Mailaender** [comment]
We talked about it in IRC some time. What we want is probably a `NotificationManager` trait that queues up the speech and sounds, then only plays a distinct lists. It could also go along with a `NotificationReference` lint test to check for erroneous entries in other traits.

**Comment by deleted-user-1** [comment]
Bump to Next lol.

**Comment by dragunoff** [comment]
I took a stab at fixing this but I stumbled at the question of how to handle cases when a notification overlaps itself? This has been discussed a bit in the thread above but I want to elaborate a bit more.

Currently there are no checks so all notifications play, for example:
```
Unit lost.
Unit lost.
 Unit lost.
  Unit lost.
    Unit lost.
          Unit lost.
```

One way to handle this is to stop the audio that's playing and then start it again:
```
U
 U
  Un
    Unit l
          Unit lost.
```

Another way is to play a new notification only if there's none of the same playing at the moment:
```
Unit lost.
          Unit lost.
```

The above problem also applies to unit voices and it's solved in the first manner (stopping the sound and starting again). But that results in a stutter "A-A-Affirmative", "U-U-Un-Unit lost". That's why I lean more towards the latter solution (playing the audio in full before starting a new one) :thinking: I wonder how other games handle that.

**Comment by NinovanderMark** [comment]
@dragunoff My suggestion would be to have this depend on who initiates the triggering of the sample.

If they player does this directly by ordering a unit, or building something, starting the sample from the start is good auditory feedback that their command is registered. This is how the old C&C games used to do it.

If the trigger is something happening in the game, its function is to aid the player's situational awareness and restarting the sample doesn't add anything. We don't need to know exactly how many units are dying, only that a battle is happening somewhere.
