### ISSUE TITLE
Chat window allows switching to team speak for dead players with no effect

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#4772]
After a player is defeated and is still in the game as a spectator, the chat window still allows switching to team speak mode but what is typed is seen by everyone. This is misleading, there shouldn't be any team speak while dead.

This might be related to dead players being able to pause-spam the game.
##

**Comment by rob-v** [comment]
There are various related issues to this one. According to my test, Spectator can chat with his [Team] - other spectators or [All]. Player can chat with [Team] - allied players or [All]. There is still bug reported in this issue. Defeated player can only chat with all - spectators and players with both options [Team], [All].
The bug is that [Team] is for defeated player in fact [All]. That can be funny and also bad - you think you still chat with your team, though now all see it.

Is there an agreement how to fix this? 
1. disable [Team] option so defeated player can only chat to [All]
2. change [Team] to team of spectators (can be still bad but it is better than [All])
3. ?

**Comment by gdavegdave** [comment]
I think a defeated player should be able to speak to global [All] or to Spectators. He shouldn't be able to speak exclusively to his Team anymore as that could be exploited.

**Comment by kyrreso** [comment]
Is it possible to tag this (future), as this and spec-ping is really wanted by many players?

**Comment by dragunoff** [comment]
IMO it also makes sense to change the input field prefix for spec chat. Right now it says `Team` which can be confusing, especially in the case of defeated players. The UI should make it clear that their message is going out to `Spectators` and not their original team. I know that after sending the message there is a `[Spectators]` prefix but during typing that indication is not there.

**Comment by abcdefg30** [comment]
This was fixed by #15615.
