### ISSUE TITLE
Implement isometric selection box and health bars for structures in isometric mods

### ISSUE THREAD

**Issue by pizzaoverhead** [OpenRA/OpenRA#4783]
Tiberian Sun currently uses the same square selection box for structures that is common to all previous mods. This should be updated to the isometric angled selection area and health bar used in TS and RA2.

![a2cc7cd98d1001e92c94479cb80e7bec55e797fc_188 1](https://f.cloud.github.com/assets/3650108/2320833/097e5cf2-a396-11e3-97e4-ffc3963851ed.jpg)
##

**Comment by Mistranger** [comment]
Done: https://github.com/OpenRA/OpenRA/pull/13426

**Comment by pchote** [comment]
#14482 fixes the biggest blocker for this by decoupling the mouse interaction area from the rendering bounds.  I originally wrote the mouse handling there to support the arbitrary polygons we need for isometric selection boxes, but then swapped them to rectangles to reduce scope and simplify reviewing of the PR.

There are now only two smaller scoped blockers:
* Removing the remaining hardcoded engine references to `Selectable` so that it can be moved into Mods.Common and merged with the `SelectionDecorations` trait.
* Implementing an algorithm for polygon-rectangle hit testing.

Once these are done it will be an easy job to flip the mouse regions back to polygons and implement a new `IsometricSelectable` trait that combines a hexagonal selection area with the 3d box rendering in #13426.

**Comment by pchote** [comment]
I have a working implementation for the points in my comment above, so assigning myself and moving to the Next + 1 milestone. The hard part to solve before it can be PRed is redesigning the selection decoration traits to not hardcode their own positions within an assumed rectangle.

[Video](https://www.youtube.com/watch?v=NCui7if_X-c)

**Comment by deleted-user-1** [comment]
I suppose that the zoom-feature related changes cause the mismatch of the borders of the bars. The best way i can describe it is that the borders of the bars are not in a straight line, but have some kinks in it, and the position of these mismatches change when zooming in or out but never disappear. This is also visible in the video but harder to see due to low resolution. Unfortunately, this makes it look quite unpolished, at least in my eyes. Lack of segments is a dealbreaker for me, but that's a design decision.

Non-edited screenshot with "Battlefield Camera: Far" setting, taken on https://github.com/pchote/OpenRA/commit/299157aa48314b75976ad103e4b83820727fbe84:

![OpenRA-2020-02-29T192711009Z](https://user-images.githubusercontent.com/59416324/75613909-157a0780-5b33-11ea-9f69-740e20a51570.png)

Don't want to be unfair but in my eyes this is not an improvement over what was presented in #13426.

![g](https://cloud.githubusercontent.com/assets/10031125/26720247/eb08bddc-47a0-11e7-8060-3321682d17e5.png)

In any case, it's great to see TS progressing.
