### ISSUE TITLE
Engineers should repair buildings the same way mechanics repair vehicles

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#4870]
Right now engineers can repair buildings in an instant and they disappear with this action. It would be better if they repaired buildings from the outside incrementally. They should not disappear after the repair and the repair should be cost-free like that of the mechanic. And multiple engineers should repair faster.
##

**Comment by tovl** [comment]
I see one thumbs up and no discussion on a not unreasonable suggestion. Why was this closed?

**Comment by phrohdoh** [comment]
@tovl the linked PR's description states:

> Moving forward, I think it is reasonable to WONTFIX the following:
Closes #4875
Closes #4870
Closes #5101
Closes #14261
Closes #12979

**Comment by tovl** [comment]
Yes, I've seen that. Hence the question. I've seen no discussion or justification on this in that PR or elsewhere.

**Comment by PunkPun** [comment]
I think it's for balance and design reasons. I dunno if the engine supports the requested behavior but I would be against implementing it into RA. The repair cursor already repairs incrementaly so this is not a role that needs filling

**Comment by pchote** [comment]
It is not reasonable to invest the time and maintenance overheads to implement every single idea that people come up with, particularly when they are specifically unwanted in the default mods and not actively requested for community mods. The PR above fixed most of the outstanding issues with engineers, so I took the opportunity to clean up a number of other issues that I considered unlikely to ever be implemented.

**Comment by abcdefg30** [comment]
Isn't this already possible be giving the Engineer a setup similar to what Mechanics and Medics have in RA?

**Comment by tovl** [comment]
> particularly when they are specifically unwanted in the default mods

Nobody actually said it was unwanted until I reopened the issue. And some people apparently thought it was a good idea.

It is not decent to just stealth-close issues without any discussion or giving a reason why they are not to be implemented, especially when the only feedback the issue did get was positive or ambivalent. It is also quite presumptuous to assume that just because you don't consider something worth your time, other developers should not consider it worth their time either.

Note that I specifically did not resurrect #12979 because it was already panned (even though actual reasoning would have been nice) and that I am myself ambivalent on this particular issue (#4870).

**Comment by deleted-user-1** [comment]
This issue is requesting this behavior for the default RA mod. It might have been a thing to think about 6 years ago, but RA has long reached 99% feature completeness and changes to fundamental unit roles and behavior need substantial justification. I have never heard a player ask for this and can't see a problem with the way it works now, so doubt there is any benefit in reopening. If this can not be done with conditions or warheads with negative damage, then there should be a new issue outlining the limitation for modders IMO.

**Comment by tovl** [comment]
No, @abcdefg30 is right. This should be doable in the engine already. Closing, since it is quite clear now it is unwanted in the RA mod.
