### ISSUE TITLE
Make approach direction of paratrooper plane controllable

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#4873]
There is no way (or no easy way) of telling from which direction the paratroopers will arrive. Often times the plane flies right towards anti-air defenses and gets shot down. There should be a way to at least determine from which direction the plane approaches the drop site in order to avoid AA and make paratroopers more useful. This could be done by drawing a vector for example.

**Comment by huwpascoe** [comment]
I'm taking on this bounty. Will submit a PR soon

**Comment by huwpascoe** [comment]
Question: The direction of the aircraft is typically randomized. So what exactly is being asked here, an indicator of the direction after the order is sent, or a change in the random behavior?

```
if (randomize)
	dropFacing = Util.QuantizeFacing(self.World.SharedRandom.Next(256), info.QuantizedFacings) * (256 / info.QuantizedFacings);
```

**Comment by UberWaffe** [comment]
A change in the random behavior. The title refers to it being controllable.
Previous discussions I have seen about this was to have it so that you first select the target position, and then select a second point.
The plane will enter the map in a straight line with point 1 and point 2, in such a way that it will first arrive at point 1, start dropping paratroopers while continuing straight towards point 2.

C&C generals particle cannon control is a good idea of what to aim for.

**Comment by pchote** [comment]
We decided that a smoother direction select is to use a click-drag instead of two distinct clicks.  Mouse down like you would normally to select the target point, and then with the mouse held move the cursor in a direction, and you'll get an arrow cursor indicating the direction that the plane should come from (like our new joystick scroll on the rmb, except that doesn't have the cursors implemented yet).

**Comment by penev92** [comment]
Selecting an entry point yourself is just stupid. Just saying...

**Comment by huwpascoe** [comment]
Made a working prototype. PR probably ready in a few days.
![a](https://cloud.githubusercontent.com/assets/1812087/10525400/7f087752-737c-11e5-91d0-6dba85dd0b0c.png)
![b](https://cloud.githubusercontent.com/assets/1812087/10525402/80f8e60a-737c-11e5-936e-1d3ead69cfaa.png)

**Comment by pchote** [comment]
Is that using two separate clicks, or click-drag?  Please see my comment above about click-drag, which makes it suitable for Airstrikes and keeps the interaction model simpler for people who don't care about direction.

**Comment by huwpascoe** [comment]
@pchote yeah that way is implemented

Mouse down, up = random direction
Mouse down, move > deadzone, up = vector from drag origin to target cursor
Mouse down = for powers that rely on quick timing like iron curtain

**Comment by huwpascoe** [comment]
Also the order sends the start and end coords so it could be adapted for sweeping powers too
