### ISSUE TITLE
Ingame map editor : layers [$30]

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#5000]
Could the ingame map editor feature "layers" in order to be able to move several tiles at once without deleting them and redrawing them elsewhere ?

- we could show/hide layers
- move them elsewhere

This could help moving actors faster:
![01](https://cloud.githubusercontent.com/assets/1732773/2566454/70bb10ba-b8c5-11e3-92a3-41381eedb7a0.gif)

**Comment by pchote** [comment]
Full layer support would require map-format changes, and isn't really practical.  Moving tiles is addressed by copy/paste.  Closing as part of a larger editor ticket cleanup.

**Comment by x-a-n-a-x** [comment]
Why would it need map-format changes? The goal of this idea was to be able to move and re-arrange several tiles/actors at once.. during map edition. Of course, all layers would have been merged/flatten right before saving the map.

This issue existed (I use the past since you just closed it) for convenience, user-friendliness.

**Comment by Mailaender** [comment]
Because you need to store all those layers somewhere. The map file format would then become more off a PSD file than a resulting PNG file to compare it to the graphics editor world. That means extra bloat as in complexity (the current map editor already took 1.5 years in the making) and file size which isn't really practically as quick map exchange amd simplified usage is a mayor design goal. This is not meant to be a tool for professionals with a steep learning curve.

**Comment by GraionDilach** [comment]
Besides the above, such a layer is okay as long as you're keeping the TD/RA/D2K terrain. When you go for TS, depth will also prevent you freely moving tiles, rendering your map broken.
