### ISSUE TITLE
Airstrike time delay should be standardized

### ISSUE THREAD

**Issue by psydev** [OpenRA/OpenRA#5057]
I think the amount of time you have to wait between ordering an airstrike and watching the bombs fall should be standardized, instead of depending on map size. On bigger maps, you have to wait a long time. The time depends also on which direction the planes come from, so it's highly variable. Given that players now receive a warning for airstrikes, I think it makes sense to have a standardized time delay (somewhere between 4-8 seconds).

If people don't like the idea of "planes spawning in the middle of the map", perhaps they could be made to look like they just descended from a higher altitude, and now are coming into view.

**Comment by anjew175** [comment]
In my opinion, I think a standardized time like the cargo is what is needed. Currently airstrike is strong and the only way to fix that is to give more times to players and if they can choose the direction for instant arrival it doesn't fix anything, just lets the player know when he can destroy everything. Also works for smaller maps

**Comment by pchote** [comment]
> the only way to fix that is to give more times to players
I disagree.  The much better way to fix this is to make the planes vulnerable to AA.  Choosing the direction is an important balance to stop them from becoming useless again.

**Comment by anjew175** [comment]
Airstrikes are only useless on large maps and when they come from the other side of the map, they are overpowered when they come from the correct direction. 
The only way rockets could hit those things and possibly take it down is if they were slowed down or the old missile bug was re-implemented. If they were slowed down then it would almost be the equivalent of placing a delay so that I don't mind but they may still be OP on the edges of the map. If they aren't slowed then they will still be OP as players just choose the direction that gets the quickest kill.

**Comment by abcdefg30** [comment]
We allow choosing the direction of airstrikes.
