### ISSUE TITLE
Static defenses should reveal their location after firing

### ISSUE THREAD

**Issue by psydev** [OpenRA/OpenRA#5061]
Currently if a turret opens fire on you, but it is under fog, you cannot see its location. I think that it would be better if turrets would become visible after they fire upon you, like in the original. 
##

**Comment by Unit158** [comment]
This could probably use some more discussion, or close.

**Comment by penev92** [comment]
This can definitely use some implementing. I am also told that with the shroud refactoring it is now quite doable (I even see the PR that mentions is just above your comment).

**Comment by GraionDilach** [comment]
This existed as a weapon flag in TS/RA2 - which is why I assume it'll be needed in the long run anyway.

**Comment by StexoO** [comment]
Will not it be too easy to detect and destroy all enemy defenses ? Or simply avoid them ?
Just send a single guy to detect one of them or a curtained APC to detect all of them, then build 3 artilleries / V2s to get rid of all of them ?
I know you all do it in all the RTS where defenses are revealed when they attack you. :smirk:
I don't know if :+1: because the players will build more vehicles / air units and less defenses, so the game will be less static, or if :-1: because we will see less defense, as they will be almost always destroyed by long range vehicles or air units.

**Comment by penev92** [comment]
All the more reason to reveal everything that fires on you, not just buildings.

**Comment by abcdefg30** [comment]
Support for this was added in #12557. `RevealOnFire` is enabled for TS and D2k (#12808), but I don't see this happening for RA and/or TD. (At least not without much discussion, which should happen on the forums.)

**Comment by psydev** [comment]
I can't remember, but I think one of the reasons I suggested this was to help deal with basewalking and being fired upon by newly built structures that you couldn't see.

I don't know where the game meta is right now or if basewalking is still a problem, but I would suggest further discussion on possible implementation of this if basewalking is still an issue.

**Comment by pchote** [comment]
@AoAGeneral: This may have flown under your radar.  How do you think the community would react to the idea of introducing this to TD?

**Comment by AoAGeneral** [comment]
Short discussion in IRC. I think its fine to have it on base defenses only if to be introduced. Having them on units is a good idea but it could very well turn into arty vs arty games or V2 vs V2 in both mods. Also having RevealOnFire with aircraft could be an issue as well since MSAMs or other AA in RA could be very strong without having to spot the unit. (Specially since in RA E3 have shorter ranges.)

Having it on defenses only for TD won't mean to much since once you scout it you scout it anyways and can lob shells on it.

Only concern I would have is would it reveal from black shroud or would it reveal only fog of war?

**Comment by reaperrr** [comment]
The engine doesn't differentiate between shroud and fog for revealing, so it would reveal both and shroud would stay revealed.
