### ISSUE TITLE
CNC grenadiers are only occasionally effective vs infantry

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRA#5081]
I would suggest a buff to the splash range, so that you don't need to worry about missing all the time. Currently, if the grenadiers miss, it is pretty dramatic.

**Comment by pchote** [comment]
There have been a few releases with balance changes since this ticket was created, and no further discussion about this aspect of the balance.

**Comment by Unit158** [comment]
This was actually fixed by a patch that psydev and I made last April.

**Comment by MicroJOo** [comment]
the thing is ... grenadiers are for soviets only ... and soviet allready have enough "anti-infantry" units ... flametroopers , snipers , dogs , shocktroopers ... 

altough it sounds damn reasonable for a grenadier , it would make the balance questionable .... because the grenadier is available without any other prerequisite then barracks ... 

basicly , you would get a unit in 22 seconds after the game started ... for 160$ , in 4 seconds ... faster then a rifleman , excellent against buildings "AND" infantry ... 

i am okay with a grenadier that is only occasionally effective against infantry ...

**Comment by Unit158** [comment]
GDI != soviet

**Comment by MicroJOo** [comment]
whoops ... my bad
