### ISSUE TITLE
High velocity bullets shooting through walls

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#5294]
![](https://cloud.githubusercontent.com/assets/1997864/2947964/6595c7f4-d9fc-11e3-92c4-a718b75aed55.png)

**Comment by UberWaffe** [comment]
In my now-out-of-date branch for line impact projectiles I encountered much the same problem, in that a very fast projectile can travel multiple cells in a single tick.
I solved this by programming a check that checks multiple spots along the path travelled (it worked well at the time, but I am swamped by work and couldn't finish the branch).

However, you can look at https://github.com/UberWaffe/OpenRA/blob/b4242e25daf488d0c0b867e8c674fba908d33ee8/OpenRA.Mods.RA/Effects/LineImpactProjectile.cs#L168 (the Tick() function).

Instead of implementing the impacts at each section, you would only need to do the check on line https://github.com/UberWaffe/OpenRA/blob/b4242e25daf488d0c0b867e8c674fba908d33ee8/OpenRA.Mods.RA/Effects/LineImpactProjectile.cs#L168 that basically checks for obstacles and stops the projectile.

Again, I unfortunately do not have the time to do this myself.
I apologize that I had left so many things half-done.

**Comment by pchote** [comment]
The unit tests introduced with #7430 include an implementation of http://playtechs.blogspot.co.uk/2007/03/raytracing-on-grid.html which can be generalized and used to solve this issue.

**Comment by Rydra** [comment]
@pchote the ray caster was something I was testing in order to implement a future path smoother, but I should put it into its own utility class in another PR.

**Comment by Unit158** [comment]
I'm currently implementing a raycasting solution for d2k's sonic tank, which could be used to solve this problem.

**Comment by Rydra** [comment]
@Unit158 maybe you may find useful the raycasting implementation I made in https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Test/PathfinderTests.cs. It was a proof of concept, but fully working. It returns an enumerations of the cells crossed between two points.

**Comment by pchote** [comment]
:tada:
