### ISSUE TITLE
Remove managed & unmanaged binaries from the tree

### ISSUE THREAD

**Issue by pavlos256** [OpenRA/OpenRA#5485]
I'm talking about the files in [thirdparty](https://github.com/OpenRA/OpenRA/tree/bleed/thirdparty). They're nice for packaging but they have no place in a source tree.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/7479 removes the last Windows binary which was extremely ugly to see in a Linux tarball. Now we only need to get rid of the Mac libraries.

**Comment by pchote** [comment]
The mac SDL binary is custom-compiled with the flags that we need (which are different to a general-purpose build), and so we are unlikely to be able to fetch it from upstream.  The situation will get worse in the future, as we are going to need to follow Xamarin Studio's lead and switch back to a native-code launcher so that we can cleanly handle file and url associations and (hopefully in the future) code signing.

The cleanest solution for our purposes may be to create an external repository that holds known-good binaries of all of our (CIL/Windows/OSX) dependencies, and have the packaging script fetch these before it runs the build.

**Comment by Mailaender** [comment]
We may be able to use https://bintray.com/ for that.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/7617 will remove the last released CLI library from SCM. Not quite sure what to do with Eluant and SDL2-CS which have no proper release management.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/7933 will remove all Mac OS X binaries from the source tree.

**Comment by Mailaender** [comment]
I also managed to fix the rest without much hazzle for developers and adding more transparency in GitHub style by showing off our dependencies with forks and tags. https://github.com/OpenRA/OpenRA/issues/7953
