### ISSUE TITLE
Add support for Ogg Vorbis

### ISSUE THREAD

**Issue by Generalcamo** [OpenRA/OpenRA#5491]
Adding support for Ogg Vorbis would go a long way to increasing the flexibility, ease of modding, and decreasing file size. Adding Ogg Vorbis support will not only reduce file sizes on Music, it will also allow for better quality sounds.

See also:
#5487
#5482

**Comment by Unit158** [comment]
https://github.com/ioctlLR/NVorbis Looks promising. I haven't seen a use case for this yet, however.

**Comment by andrea2312** [comment]
>https://github.com/ioctlLR/NVorbis looks promising.

It's have Microsoft Public License (Ms-PL). Is it acceptable to use?

**Comment by GraionDilach** [comment]
No, the Ms-PL is incompatible with the GPLv3.

**Comment by pchote** [comment]
We should hold off on this until after the sound system has been rewritten to use streaming instead of blobs.  The implementation is going to end up being mostly glue code, and that's going to need to change completely when we move to streaming.

**Comment by GraionDilach** [comment]
Another option is probably to go with Opus instead of Vorbis. https://www.opus-codec.org/

**Comment by karolherbst** [comment]
Is there still a hold on this issue? Because I might be able to work on this if nobody complaints

**Comment by GraionDilach** [comment]
One should not try to add more formats while the audio handling code (to support streaming) is still being rewritten imo.

Feel free taking Vorbis though, I'm still more interested in Opus. Vorbis is so last decade.

**Comment by forcecore** [comment]
Audio streaming arriving "soon"
https://github.com/OpenRA/OpenRA/pull/13521

**Comment by reaperrr** [comment]
> Feel free taking Vorbis though, I'm still more interested in Opus. Vorbis is so last decade.

I don't really mind which one we support, as long as the size/quality/performance mix is good and there's at least one good encoder out there.

That being said, with the mp3 patents having expired, that would probably be the most convenient one for most modders.

**Comment by GraionDilach** [comment]
Nothing comes better than Opus in the size/quality/performance ratio (Opus is the contester of AAC as much as Vorbis was MP3's). I only have implementation problems - asin while the reference decoder/encoder is OpenRA-license compatible, it's in C++ and requires a wrapper somewhere. There are already existing C# wrappers but all of them are license-incompatible, with licenses like MS-PL being used. The C# decoder is less optimal, and updated less regularly, compared to the reference encoder/decoder. The reference decoder's API is frozen since the first release even (only under-the-hood changes which increase encoder quality happens these days, the specification declares that every Opus file must be able to be played through the on-paper specification decoder which is what any versiion of the reference ships). That and I have never edited the dependencies scripts, which is why I haven't really started working on this. (I also lost my Linux testbed a while ago due to switching HDDs).

But yeah, I really should start working on it now with abusing the softfork as a testbed for it.

**Comment by Mailaender** [comment]
The MS-PL doesn't really matter as long as we only use the library and not borrow code from it. I experimented a bit with NVorbis (turns out at least 2 libraries call themselves this), but didn't get far https://github.com/Mailaender/OpenRA/tree/nvorbis as I don't really understand what to do with `float[]` from `ReadSamples`.

**Comment by Unit158** [comment]
I have a working solution for this. It's not elegant - yet.

**Comment by CallumDev** [comment]
Is this still not implemented? I can get something out for vorbis that would be compatible with the current license.

(Also if it's still listed on bountysource does it mean a bounty is still there? There seems to be a lot of older OpenRA issues there)

**Comment by reaperrr** [comment]
> Is this still not implemented? I can get something out for vorbis that would be compatible with the current license.

Unfortunately not, so if you got something out that would be great.

> (Also if it's still listed on bountysource does it mean a bounty is still there? There seems to be a lot of older OpenRA issues there)

We've dropped official support of bountysource (mostly due to the maintenance issues the site ran into at some point), but any bounties still listed there should still be claimable, yes.

**Comment by Unit158** [comment]
It seems like Ogg Opus is becoming more popular in gamedev as of late. @GraionDilach do you think it's worth implementing both Vorbis and Opus support?

**Comment by GraionDilach** [comment]
Opus is still not enough widespread that would-be modders would understand it's gains. Most newbies still think in MP3 vs Vorbis with AAC-derivations coming third.

Opus is great, but if implemented alone, that would require a disclaimer within the ModSDK explaining that it's Vorbis's successor.

**Comment by castilma** [comment]
I would be interested in giving this a shot. I have no experience with C#, but learned java in uni and have some experience with opus and vorbis.
Can you give me some starting pointers, how to approach this?
I think I have to create OpenRA.Mods.Common/FileFormats/VorbisReader.cs and OpenRA.Mods.Common/AudioLoaders/VorbisLoader.cs, right? (btw, what does the loader do, opposed to the reader, which decodes the data?)

**Comment by Mailaender** [comment]
This might not be a good beginner task as you will have to fiddle with OpenRA and libraries that were not designed for game engines which have their own file format loaders. Try looking at:

* https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/AudioLoaders/WavLoader.cs
* https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/FileFormats/WavReader.cs

to get an idea how the interfaces are supposed to be implemented.

**Comment by pchote** [comment]
@reaperrr please make sure to request Bountysource to redeploy your bounty ASAP, or they will take it for themselves.

> If no Solution is accepted within two years after a Bounty is posted, then the Bounty will be withdrawn and the amount posted for the Bounty will be retained by Bountysource. For Bounties posted before June 30, 2018, the Backer may redeploy their Bounty to a new Issue by contacting support@bountysource.com before July 1, 2020. If the Backer does not redeploy their Bounty by the deadline, the Bounty will be withdrawn and the amount posted for the Bounty will be retained by Bountysource.
