### ISSUE TITLE
Toggle notifications dialogs.

### ISSUE THREAD

**Issue by scskwirl** [OpenRA/OpenRA#6354]
For the people who have their volumes down or need accessibility options, any way to toggle text notifications like a unit-ready or construction-complete or base-under-attack?
##

**Comment by dragunoff** [comment]
I gave this a little thought. I think it can be implemented by exposing a setting to the player that works sort of like error reporting levels in some programming environments. For example, in audio settings panel (or in display settings?) add a select box with the following options:

**Show text notifications:**
- **All** (Battlefield control notifications, EVA notifications, etc.)
- **Only non-audible** (show only notifications that don't have an audio cue - e.g. Battlefield control notifications)
- **None** (hide all notifications, that would nicely resolve #16148)

Another way to go about it UI-wise is to present checkboxes with all of the notification types:

**Show text notifications:**
- [x] **Battlefield Control** 
- [ ] **EVA**

To reduce spam identical notifications can be displayed as one notification with a counter:
> EVA: Unit lost. (20)
> EVA: Construction complete.
> Battlefield Control: Selected across map. (2)

We could add another setting to account for cases when audio is not available or muted (see #6400). For example:
- **All (always)**
- **All (if audio not available)**
- **Only non-audible**
- **None**

Or we could leave that to the player to toggle the level of reporting when audio is not available (that would simplify the implementation).

**Comment by dragunoff** [comment]
I have implemented a prototype for this feature. I think that it's better to go with the checkboxes approach - splitting the chat notifications into pools and letting the player decide which ones they want to see. That way we can solve the problem of muting spectator chat (see #5775). Some pools should always be displayed (system, debug, player chat, mission messages). Here are some visual to present the idea:

Define chat pools and add each chat-line to one of them:
```csharp
public enum ChatPool { System, Chat, Spectators, Mission, NonAudible, Audible }
```

Add transcriptions to audible notifications:
```yaml
Notifications:
	AirstrikeReady: airredy1
		Transcription: Air-strike ready.
```

Add the toggle-able chat pools to settings:
![изображение](https://user-images.githubusercontent.com/1355810/72196426-b34d3200-3420-11ea-83e1-2253b9702115.png)

In-game chat widget, combining repeated lines (with a counter) and adding a settings button that opens a panel for quick configuration:
![изображение](https://user-images.githubusercontent.com/1355810/72196517-628a0900-3421-11ea-8497-820059a45aed.png)

**Comment by dragunoff** [comment]
Another prototype with the UI approach from the multiplayer game filter:
![image](https://user-images.githubusercontent.com/1355810/73598005-4f0f2100-453b-11ea-8ce2-c51c6768f340.png)
![image](https://user-images.githubusercontent.com/1355810/73598021-76fe8480-453b-11ea-8c90-4501127d988a.png)

And the settings implemented with flags:
```csharp
	[Flags]
	public enum ChatPoolFilters
	{
		None = 0,
		Feedback = 1,
		Transcriptions = 2
	}
```

I decided to show also the non-toggleable notification pools in the UI panel because otherwise it may be weird that no boxes are checked yet things show up in the chat. 

This is getting closer to being PR ready. There is a problem with the styling of the dropdown, the arrow is hard-coded and can't be changed, this could be resolved as part of  #17612. Also the scrollbar is not necessary, so a solution for #15708 would also be nice.

**Comment by dragunoff** [comment]
I noticed that speech notifications in OpenRA support faction variants (with prefixes). Since these faction variants may sometimes differ in their wording I'm wondering how should we handle the transcriptions then? Add variant support to transcriptions? Or simply have a generic "transcription" for the given notification? 🤔💭

This is the format I'm using now to attach transcriptions to notifications:
```yaml
Notifications:
	AirstrikeReady: airredy1
		Transcription: Airstrike ready.
```

**Comment by pchote** [comment]
IMO we should definitely have a generic string for the notification, which in some cases might be a l lot simpler than what the announcer actually says.

**Comment by dragunoff** [comment]
> 
> 
> IMO we should definitely have a generic string for the notification, which in some cases might be a l lot simpler than what the announcer actually says.

This is what I am leaning towards as well. Variants in wording should not matter as the message is more important.

Another problem is that not all notifications may be worthy of a transcription. I think that things like "Building", "On hold", "Cancelled", "Select target" should not be included as they have instant visual feedback that is the result of direct player action. However some other such events probably should be represented by a chat line - e.g. "Nuclear weapon launched".

Notifications to certainly include:
- Events that don't have any visual feedback (e.g. enemy support powers)
- Events happening off-screen (e.g. unit lost, structure captured)
- Events with visual feedback that is not related to direct player action (e.g. low power, unit ready, construction complete, support power ready)

I have transcribed all TD EVA quotes and will be working with them to put together a pull request.
