### ISSUE TITLE
GLA Tunnel Effect

### ISSUE THREAD

**Issue by scskwirl** [OpenRA/OpenRA#6409]
Ticket #2175 referred to an ability to make a cloaking device. Later in the comment thread, someone mentioned making a structure that works like the GLA tunnel network from C&C Generals.

I haven't seen a specific ticket on this like the comments suggested, so this is to bring the idea up for review.

A structure that can garrison troops and deploy at any other similar structure in the map. If they're all destroyed, the units inside die off. If it's possible to make individual units exit is good; otherwise it can function like APCs and discharge all the units in the network.

**Comment by pchote** [comment]
This is out of scope for our default traits, but could be done easily by a mod.

**Comment by GraionDilach** [comment]
Easily... yeah, that's what you said. I've looked at this a while ago, but it needs a giant c'n'p of the Cargo trait and even then a lot of cases would still need upstream refactoring - like Bounty - because they cannot be wrapped downstream.

**Comment by forcecore** [comment]
Agreed, not possible without modifying mods.common as I tried.
The trouble is that Passenger trait REQUIRES cargo trait.
Certainly, I wouldn't duplicate passenger trait, because it would be quite odd to have two passenger traits.

Then the natural approach the modders would do would be to inherit cargo trait so that passenger trait and all the UnloadCargo stuff will work. Thanks to OOP, this will work, hopefully.

Now I copy pasted CargoInfo trait as SharedCargoInfo, as inheriting it doesn't work. That's because the Create() function in CargoInfo can't be overrridden to allow creation of SharedCargo instance.

I couldn't inherit Cargo for SharedCargo either, as it has .cargo coded in it. .cargo stack is private and many non-overridable functions use .cargo stack. The trouble is, since I am sharing this cargo stack, this is not good... (I put the shared cargo stack as a Player trait.)

This is where I got so far.

I'll resorting to modifying Mods.Common if necessary and perhaps submit a patch.
