### ISSUE TITLE
Wasted iron curtains

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#6560]
I found #5790 because it happens to me almost half the time.
To fix this, is it possible to enlarge the iron curtain effect zone of one cell in all directions and apply the curtain only on the five most centered units inside this zone ?
![sans titre](https://cloud.githubusercontent.com/assets/8930382/4425083/cd0e5256-45a5-11e4-945d-6fe154c56bd6.png)
##

**Comment by sinf** [comment]
I think @StexoO 's idea is great. Iron Curtain is often used in a frontline where artillery shells are hitting all over. Vehicles tend to die, get baited away or lose a lot of HP before they get in proper formation. Moving vehicles prevent the curtain from being used because their cell position is constantly changing, thus increasing curtain radius makes just perfect sense.

However I think it would be even better if curtain (and why not chrono too) had an even larger radius (+2 cells?) and only the 5 units closest to cursor are highlighted with some blinking icon before actually using the superpower.

**Comment by abcdefg30** [comment]
Closing with the same reasoning as https://github.com/OpenRA/OpenRA/issues/5790#issuecomment-68413760. We also have #17064 open now, which is a bit more descriptive about the bug part.
