### ISSUE TITLE
RA - Chrono Enemy tanks into water.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#6937]
Like in Orginal RA2, in our RA mod we should can chrono enemy tanks into water or ships into land and they sinks/explodes.

**Comment by pchote** [comment]
This idea has been discussed multiple times on IRC, and rejected every time.  I think its a shame, but this isn't likely to change.

**Comment by Xunius** [comment]
I didn't get to read all discussions regarding this feature but I still miss it in the old RA game and kind of feel that it is a legit thing to do: if you allow teleporting vehicles to another piece of land then the logic goes for a piece of water too. If deny either one, the other should be denied as well.
To better balance it, here are a few suggestions:
1. increase recharge time.
2. instead of disabling chronoing tanks near radar jams, gap generators seem to make bit more sense (IMO).
3. return husks from water, so the victim gets a chance to revive them. This can be justified by the fact that husks can still be teleported back even if tanks have moved.
4. increase power requirement for the chrono, or create a temporary power down during the 20 sec chrono time. 
5. maybe introducing a "weight limit", for instance ships are too heavy to teleport to land.

I am note sure how difficult to implement these, or to what extent it will help make it more balanced, but still miss this fun feature, and hope it could come back.
