### ISSUE TITLE
Battlefield News not read

### ISSUE THREAD

**Issue by StexoO** [OpenRA/OpenRA#7006]
Despite the fact that the upcoming tournament is announced in the Battlefield News, few people are aware of it. It means that only few people "open" the Battlefield News. Could you show it opened by default ?

**Comment by x-a-n-a-x** [comment]
I like @pchote 's suggestion because I fear that players don't even notice the Battlefield News blinking notification.

For a moment, I thought of displaying a small "popup dialog window" in the middle of the screen with:
"a new stable version has been released, you should update :) "

... but I would be happy if the drop-down menu got opened automatically... 
We would be sure players read messages.
