### ISSUE TITLE
AI harvesters will worse case path find every second when there are no resources

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#7092]
![image](https://cloud.githubusercontent.com/assets/756669/5332699/35b3429c-7e60-11e4-877a-7ed5d852d688.png)

**Comment by reaperrr** [comment]
According to my tests this is THE main showstopper performance issue on larger maps, far worse than the AI base builder and regular pathfinding. Adding to Next Release milestone.

#7658 not only improves FindResources performance massively according to my tests (by a factor of about 20 in some cases, down from 234(!) milliseconds worstcase delay to at most 10 on RA Seaside 2 map), the performance improvement would also allow us to increase the search radius so harvesters a) don't run into this infinite "search resource - find none - try again - find none..." loop that easily, and b) find a new resource field more easily instead of getting stuck.

**Comment by reaperrr** [comment]
Fixed in #8622.
