### ISSUE TITLE
Infantry should return to standing or prone frames between firing

### ISSUE THREAD

**Issue by OmegaBolt** [OpenRA/OpenRA#7131]
In the original TD/RA1/D2k infantry returned to their standing or prone stances between each shot while in OpenRA they freeze on the last fire frame. IMO it'd look a lot better if they returned to their standing/prone frames just like the original games.

It'd fix the issue where infantry stay in their fire frames after shooting but are actually turning around or doing some other action.

It would also fix the following issue in D2k: D2k infantry's last fire frames have muzzle flashes which means they 'freeze mid shot' and it all looks rather silly. The other alternative to fix this would be to loop back to the first fire frame for D2k but I think the above change would be generally better.
##

**Comment by reaperrr** [comment]
Agreed, I'm not that fond of the current approach either.

**Comment by Phrohdoh** [comment]
IIRC this isn't an "approach"/feature, it is a bug (mostly reported in D2k).

**Comment by reaperrr** [comment]
I thought it was originally intentional, because RA/C&C have no muzzle on the last frame so it could be used as standing, aiming frame. I may be wrong, though.
What is definitely a bug, though, is that sometimes the animation gets stuck at the frame before the last, especially when facing east (TS minigunner is a perfect example, reproducable at least 90% of the time for me). This affects RA/TD as well and highlights the problem even more.

**Comment by matjaeck** [comment]
Can't reproduce this in RA, rifle man return to their standing or prone stances between each shot.
