### ISSUE TITLE
Cross-mod texture bogosity

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#7248]
After switching from TD to RA, I found the RA menu background was rendered using the minimap sheet texture instead of the expected artwork.

I'm not sure how to repro this, but I suspect it is a regression from #6830.

**Comment by RoosterDragon** [comment]
This is indeed a regression from #6830.

It you change mods whilst the thread loading the maps is still active, your background image will get corrupted when the thread exits and flushes its buffers.

This is because switching mods will dispose of the MapCache which just goes ahead and disposes stuff the background thread is still using. So the background thread is basically into undefined behaviour land since it's now playing with disposed resources.

To reproduce:
- Open a mod and open either the skirmish or missions tab (anything to kick of the map loader thread by making it load a map).
- Quickly back out to the mods screen - the map loader thread stays alive for five seconds - so be fast.
- Five seconds after the map loaded, the thread dies and your background gets corrupted.
