### ISSUE TITLE
dtrk - tsla bug

### ISSUE THREAD

**Issue by MicroJOo** [OpenRA/OpenRA#7327]
release-20141029
demo-truck is doing no damage on a enemy tesla-coil 
![demo tesla](https://cloud.githubusercontent.com/assets/9139965/5714409/791ac5d0-9ac8-11e4-93cf-e8c575db6fef.png)

cant reproduce 

map is called "The Earth 2064" http://resource.openra.net/maps/1119
replay : https://www.dropbox.com/s/gxo3rpuh6q0k6lb/demo%20tesla%20bug.rep?dl=0
here is a screenshot for the exact time , and position ... on the map 

![openra 2015-01-13 01-17-21-16](https://cloud.githubusercontent.com/assets/9139965/5714500/22f1337c-9aca-11e4-93f0-36685fcf6201.png)

**Comment by StexoO** [comment]
Noticed this too. When my demo truck is shot by a hind, everything around takes damage except the hind.
Like the actor who destroys the demo truck receives no damage from that demo truck (here the Tesla coil) ? Need to check if it's constant and if it happens with any actor.

**Comment by MicroJOo** [comment]
yes , thats right ... i saw this also happening with hinds (sometimes) ... 
no ,  dont think its because the target-actor is destroying the demo by himself ... because his mcv in the pictures did get some damage

**Comment by UberWaffe** [comment]
This is a regression caused by the AffectsParent (https://github.com/OpenRA/OpenRA/blob/0dc65e5cf328f51f80b8f2940ae53119a7fc1afb/OpenRA.Game/GameRules/Warhead.cs#L75) tag I had added to warhead code. I note that the demotruck weapon "mininuke" does not specify this (so it will still be false).

The trait Explodes (https://github.com/OpenRA/OpenRA/blob/0dc65e5cf328f51f80b8f2940ae53119a7fc1afb/OpenRA.Mods.Common/Traits/Explodes.cs#L52) sees the attacker (Tesla Coil, Hind, etc.) as the Parent of the explosion. Therefore it doesn't get damaged.
I apologize that I had never foreseen this interaction.

Easiest fix, Define "AffectsParent: true" in the warheads for the mininuke.

Code fix: change https://github.com/OpenRA/OpenRA/blob/0dc65e5cf328f51f80b8f2940ae53119a7fc1afb/OpenRA.Game/GameRules/Warhead.cs#L75 to compare victim and self, rather than victim and firedBy. Self will have to passed as a reference somehow.

**Comment by StexoO** [comment]
@MicroJOo : the actor as the ingame object. The demo truck (actor) has been destroyed by the Tesla coil (actor), not by the MCV (actor). https://github.com/OpenRA/OpenRA/wiki/Hacking

**Comment by penev92** [comment]
Why is the tesla coil considered the "parent" of the explosion and not the truck? I think that is where the actual problem is.

**Comment by obrakmann** [comment]
@penev92: the patch below would fix that, but I'm not sure if anything relies on the current behaviour, or what the rationale was. This would certainly change the statistics (who killed whom), though.

```diff
diff --git a/OpenRA.Mods.Common/Traits/Explodes.cs b/OpenRA.Mods.Common/Traits/Explodes.cs
index 2703339..7e392cf 100644
--- a/OpenRA.Mods.Common/Traits/Explodes.cs
+++ b/OpenRA.Mods.Common/Traits/Explodes.cs
@@ -52,7 +52,7 @@ public void Killed(Actor self, AttackInfo e)
                                        Sound.Play(weapon.Report.Random(e.Attacker.World.SharedRandom), self.CenterPosition);
 
                                // Use .FromPos since this actor is killed. Cannot use Target.FromActor
-                               weapon.Impact(Target.FromPos(self.CenterPosition), e.Attacker, Enumerable.Empty<int>());
+                               weapon.Impact(Target.FromPos(self.CenterPosition), self, Enumerable.Empty<int>());
                        }
                }
```

**Comment by obrakmann** [comment]
Still exists (again?) in bleed.
