### ISSUE TITLE
D2k rough terrain bonuses

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7328]
Someone recently suggested (I'm thinking @Phrohdoh) that the `rough` terrain should provide armor bonus to infantry. I don't have such detailed knowledge so I want to ask here if this is true for Dune 2000. (If someone can check the game files/some game editor, that would be best).

**Comment by MicroJOo** [comment]
ive tested this quickly in the original 2000 ... theres no difference , so this armor-bonus doesnt exist in the original , but ... 

i dont think it has a hudge impact on the balance , and its more a neat little improvement for the cover-realism .... and since the infantry in the original is really just cannon fodder ... ill give it a 
:+1:

**Comment by Unit158** [comment]
In E:BFD, they got a range bonus, so that's another possibility?
