### ISSUE TITLE
Is the NuGet requirement justified?

### ISSUE THREAD

**Issue by Beep6581** [OpenRA/OpenRA#7386]
In Gentoo, =games-strategy/openra-20150118 requires dev-dotnet/nuget
What is this new addition which justifies having your users install a new package manager (!) which is not in portage, and how does one build without it?
The ebuild should have a USE flag to disable the requirement for NuGet.

**Comment by Hellhake** [comment]
Would it be an option to ship a nuget version with openra?
Since its just one .net binary it shouldn't be problem.

**Comment by pchote** [comment]
Nuget is required to work around conflicting-licensing issues with our StyleCop dependency (which is now an important part of our continuous integration tests).  Other dependencies were handed off to nuget because some people have philosophical issues with including binaries in the version control.  That decision has caused a lot of trouble (some still unresolved), so I expect that we will end up reverting those before we ship the next release.

In any case, those issues don't need to apply here, because the ebuild (which is maintained by @cerebrum) can do whatever it wants with respect to packaging and dependencies.

**Comment by Beep6581** [comment]
I suppose people who use the ebuild do so only to play the game. To participate in development you'd clone and compile it manually. So if the core reason for needing NuGet is not one of playing, then I'd suggest considering dropping it.

It's not the end of the world, there is a working dev-dotnet/nuget ebuild in the dotnet overlay and I did get it to compile once I upgraded dev-lang/mono from 3.2.8 to 3.12.0, but still, that is a hassle and if it's not a requirement for gaming, it would be better to drop it.

**Comment by cerebrum** [comment]
That's what nuget is doing during make phase:
```
make -j5 -l10 cli-dependencies 
cd thirdparty && ./fetch-thirdparty-deps.sh && cd ..
Fetching StyleCop files from nuget
Installing 'StyleCop.MSBuild 4.7.49.0'.
Successfully installed 'StyleCop.MSBuild 4.7.49.0'.
Fetching ICSharpCode.SharpZipLib from nuget
Installing 'SharpZipLib 0.86.0'.
Successfully installed 'SharpZipLib 0.86.0'.
Fetching MaxMind.GeoIP2 from nuget
Attempting to resolve dependency 'MaxMind.Db (? 1.0.0.0)'.
Attempting to resolve dependency 'Newtonsoft.Json (? 6.0.5)'.
Attempting to resolve dependency 'RestSharp (? 105.0.0)'.
Installing 'Newtonsoft.Json 6.0.5'.
Successfully installed 'Newtonsoft.Json 6.0.5'.
Installing 'MaxMind.Db 1.0.0.0'.
Successfully installed 'MaxMind.Db 1.0.0.0'.
Installing 'RestSharp 105.0.0'.
Successfully installed 'RestSharp 105.0.0'.
Installing 'MaxMind.GeoIP2 2.1.0.0'.
Successfully installed 'MaxMind.GeoIP2 2.1.0.0'.
Fetching SharpFont from nuget
Installing 'SharpFont 2.5.0.1'.
Successfully installed 'SharpFont 2.5.0.1'.
Fetching NUnit from nuget
Installing 'NUnit 2.6.4'.
Successfully installed 'NUnit 2.6.4'.
Fetching Mono.Nat from nuget
Installing 'Mono.Nat 1.2.21.0'.
Successfully installed 'Mono.Nat 1.2.21.0'.
```
It installs some C# libs wich we may probably ship by other portage dependencies (we have to figure out those) without nuget? Yup, I should probably make nuget optional USE-flag.

**Comment by Mailaender** [comment]
You can also copy or link to system libraries. https://github.com/OpenRA/OpenRA/blob/bleed/thirdparty/fetch-thirdparty-deps.sh checks if the files exists and only if not triggers nuget to fetch them.

**Comment by Mailaender** [comment]
A new target `make dist` to create a source tarball with bundled dependencies should be an easy way to avoid changes in the thirdparty packaging scripts.

**Comment by cerebrum** [comment]
The problem is that I don't see this packages in neither portage tree nor in dotnet overlay.

**Comment by Mailaender** [comment]
I started packaging some of them at https://build.opensuse.org/project/show/games:openra.

**Comment by LipkeGu** [comment]
some versions of VS have nuget :) so we can check if VS has already installed nuget :)

**Comment by Mailaender** [comment]
I created a bash replacement in https://github.com/OpenRA/OpenRA/pull/8229.

**Comment by Mailaender** [comment]
By the way: you can use system CLI binaries instead if you manually soft-link them: https://build.opensuse.org/package/rdiff/games:openra/development?linkrev=base&rev=40

**Comment by hasufell** [comment]
FYI, the [ebuild from dr overlay](https://github.com/cerebrum/dr/tree/master/games-strategy/openra) (which is linked in your download page) has serious QA issues and will not make it into the gentoo tree. It fetches all third party libs during build-time, which is explicitly not allowed in gentoo.

Packaging OpenRA has become very difficult. because I basically have two options:
* rebundle a tarball myself which already has those 3rd party libs and host it on the gentoo mirrors (time consuming and problematic due to licensing of 3rd party libs)
* reconstruct the whole logic of fetching 3rd party libs in a way that is compliant with our policies (takes a lot of time and is error-prone since some files are unversioned like `GeoLite2-Country.mmdb.gz` and will cause random checksum errors for users)

The best solution would be if OpenRA upstream hosts a tarball which has the raw sources + the 3rd party libs. I don't know whether there was already a bug open for that. Should I open one?


--
As a sidenote: most of the gentoo-specific commands described in the [download page](http://www.openra.net/download/) throw errors. The section also lacks a link to the [official repositories](https://packages.gentoo.org/packages/games-strategy/openra), although the packages are outdated for the above mentioned reasons, however... they don't contain serious QA issues.

**Comment by cerebrum** [comment]
Have you tried the above "new target `make dist` to create a source tarball with bundled dependencies"? Place it on the Gentoo mirrors? I've used upstream cli-dependencies as temporary workaround that just work atm.

Description of Gentoo installation on Forums was working for quite some time. Maybe I should read about those new portage overlays sync system changes and make some changes in installation description and then place it on main page in download section.

**Comment by hasufell** [comment]
> Place it on the Gentoo mirrors?

That's probably not going to happen, since there are too many fishy 3rd party libraries/files, with no or hard to find license information.
