### ISSUE TITLE
TD: airstrike countdown and selected unit health stay in color when the screen is grayed out

### ISSUE THREAD

**Issue by clemty** [OpenRA/OpenRA#7395]
it looks nice, but is that intentional?
![grayout-cropped](https://cloud.githubusercontent.com/assets/10729559/5935510/1472cc66-a6dc-11e4-8bdd-f67bd5833e59.png)

**Comment by obrakmann** [comment]
I don't know about intentional (probably not), but the floating text shown when harvesters unload has the same issue.

**Comment by clemty** [comment]
you're right, it's probably related to #6734

**Comment by pchote** [comment]
This is slightly different to #6734: the cash ticks and lasers don't desaturate because they aren't paletted (and we don't yet define a way to desaturate unpaletted things), while this doesn't desaturate because it uses a palette that explicitly opts out of desaturation.  We probably should fix that.
