### ISSUE TITLE
Add an option to invert the sidebar (UI) position

### ISSUE THREAD

**Issue by xan2622** [OpenRA/OpenRA#7444]
As suggested on IRC, it could be interesting to have an option to invert the sidebar (UI) position from right to left (and maybe also useful for left-handed people ?).

A checkbox (in Options) could let the player invert the UI.
But as @pchote mentioned it, support powers, timers, perf graph... would also have to flip to the right.
##

**Comment by karona75** [comment]
Would it be possible to have the option to move the powers to the middle?

**Comment by x-a-n-a-x** [comment]
I am not sure that most players would like Support Powers to be placed in the middle..

**Comment by karona75** [comment]
It was more of a personal preference. I tend to miss the audio cues and forget to check if powers are available. 

Can it be set as a drop down option?

**Comment by Unit158** [comment]
I seriously doubt any of the team would code a specific GUI for a user without pay. I suggest that you modify the GUI to your liking.

**Comment by karona75** [comment]
Which is why I'm not demanding it out right and building a case for it in IRC. 

If it is something that can be made modifiable I would like to know if it is technically feasible. And it is possible. No one has bothered to do it because no one asked for it. 

At least that's what I've picked up. I'll push it onto to the back burner and have a look at it once I have log collection hooked up nicely.

**Comment by xan2622** [comment]
As convenient as it would be (for left-handed people), it doesn't seem to be a widely requested feature.
