### ISSUE TITLE
Re-order the production icons when Build Everything is enabled

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#7452]
Just a suggestion but I think it could be interesting to re-order the production icons when Build Everything is enabled.

Current "mess" :
![screen shot 02-09-15 at 07 57 pm](https://cloud.githubusercontent.com/assets/1732773/6113486/1536aefe-b098-11e4-992d-bee8c583e4be.PNG)

Re-ordered icons:
![sssssssssss2](https://cloud.githubusercontent.com/assets/1732773/6113496/2115ebb8-b098-11e4-8929-148be8b2f0b2.png)

Maybe to fill the gap, we could add a 1x1 concrete icon?
(the gap doesn't bother me but @penev92 suggested on IRC that there could be a 1x1 concrete..)

This new order of icons would only happen when Build Everything is enabled.
No need to reorder the icons for normal default games.

What do you think?

**Comment by Mailaender** [comment]
I thought about bring the defensive/support queue back now that there are actually enough buildings for it (silo, turrets, walls and concrete) and maybe merging the light and heavy vehicle as well as the aircraft queue (just like the dogs and the kennel in RA).

**Comment by penev92** [comment]
Another simple fix for the building order would be to move the wall before the power plant, so that it fills the empty space.

I like the spamminess of the mod at times, but perhaps merging the vehicles into 1 queue (you still have the starport) might make for a better gameplay. And I can definitely go for a defense tab.

**Comment by x-a-n-a-x** [comment]
@penev92: moving the wall before the powerplant won't solve the problem.. there are 3 walls (one for each faction). The screenshot here just doesn't display the two others.

**Comment by penev92** [comment]
Right now there are 4 walls. However, there should only be 1. If we can fix that, I think we can use that one wall ;)

**Comment by MustaphaTR** [comment]
I did this before but Mailender did not accepted Pull Request. #5855

**Comment by pchote** [comment]
The real problem is that we have 3/4 versions of each building type, when there really ought to be one with 3/4 art variants.  I have a [d2k-raceart](https://github.com/pchote/OpenRA/tree/d2k-raceart) branch that merges everything together, but put it aside when I ran into issues with propagating the race through building placement.  I plan on picking this up again at some point, and fixing that would require less work than adding support for placeholder gaps in the production palette.

**Comment by pchote** [comment]
I rebased and finished the code changes for that branch.  The mod rules need further adapting before a PR can be filed, however.

**Comment by Mailaender** [comment]
If I understand https://github.com/pchote/OpenRA/tree/d2k-raceart correctly you won't get enemy build palette icons after capturing, which is a bit unsatisfying.

**Comment by pchote** [comment]
You do if you make the captured conyard primary.

**Comment by Mailaender** [comment]
Interesting, though a bit confusing.
