### ISSUE TITLE
Combat caused by Lua actor command clears entire queue

### ISSUE THREAD

**Issue by Computerfreaked** [OpenRA/OpenRA#7454]
When doing for example:

```
unit.Hunt()
unit.AttackMove(waypoint7.Location)
unit.AttackMove(waypoint94.Location)
```

Or another example:

```
unit.AttackMove(waypoint7.Location)
unit.Hunt()
```

(where unit is a valid actor)

If the unit gets in a firefight but does not die it goes idle after the fight. It does not complete the action it was doing or any subsequent actions on the queue. It looks like the whole queue is emptied when a single bullet is fired upon the unit or the unit fires itself.
##

**Comment by Bynnar18** [comment]
I've run into this scripting the TD shellmap. It's really annoying. I would fix it myself if I thought I had the experience to.

**Comment by Computerfreaked** [comment]
> So something like this will cause the unit to stop even if it hasn't reached waypoint1:

>     Trigger.OnIdle(unit, function() unit.AttackMove(waypoint1.Location) end)

This is what I thought a solution was and I just tried it. It works :D

**Comment by obrakmann** [comment]
Found the problem. We were only creating an `AttackMoveActivity`, but didn't set the `TargetLocation` in the `AttackMove` trait.

**Comment by Bynnar18** [comment]
>This is what I thought a solution was and I just tried it. It works :D
>
>Nevertheless it is still a workaround if you ask me.

I may of been mistaken, or maybe it just takes some time for it to trigger but I didn't see it work when I tried it.

**Comment by Unit158** [comment]
@obrakmann any progress on this?

**Comment by obrakmann** [comment]
Not really. We can't just set the `TargetLocation` and run the activity, because that causes the `AttackMove` trait do wake up and go off to do its own thing if the unit ever goes idle (and then it would go *back* to the `TargetLocation`, which may be on the other side of the map at that point. We can't unset `TargetLocation` either at the end of the activity, because that would break `AttackMove`. You can't even unset it in the `Cancel` method, because that breaks `AttackMove` as well. And we also can't unset `TargetLocation` in a `CallFunc` or sth. similar, because that might never execute if the activity queue is canceled.

I've tried re-writing activities to allow that sort of thing, but that turned out to be fruitless in the end due to the way that the `Attack` activity in `AttackMoveActivity` is generated (ie. not directly, but three or four method calls deeper into the call chain, where you cannot distinguish between the different use-cases anymore).

So, no, I have no idea how to fix this in a way that isn't hack-ish and which might not work under certain circumstances. `AttackMove`'s `TickIdle` hack is just a giant ugly piece of crap.

**Comment by obrakmann** [comment]
FWIW, I have a WIP branch that should fix this and also includes queueable attack-moves. It still has quite a few bugs that I need to iron out, though.
