### ISSUE TITLE
Dog issues

### ISSUE THREAD

**Issue by pevers** [OpenRA/OpenRA#7506]
I was looking into the dog issues, starting with https://github.com/OpenRA/OpenRA/issues/7077.

I implemented a simple algorithm to check wether the dog has a clear line of sight (meaning no obstructions). This worked but introduced another issue, that is ... the pathplanning is not optimal because the dog will run to the wall, stop and needs to reroute. I think that is not really wanted. So maybe we could introduce a new option that some weapons (such as the DogJaw) can only be fired with no obstructions with the target, modify the path planner to keep this in mind and build in a check on the leap to prevent jumping over blocked tiles. 

Any ideas about this? Other approach? There are also some other bugs with the dogs such as https://github.com/OpenRA/OpenRA/issues/6798 that may could be resolved by a solid approach.

![screenshot from 2015-02-20 01 27 40](https://cloud.githubusercontent.com/assets/3428649/6279303/b1f0da9e-b89f-11e4-9ebd-4036927a8bdf.png)

**Comment by UberWaffe** [comment]
As a possible alternative we can give the dogs a non-leap attack with a melee range that still instant-kills infantry. Then buff the dogs health (and possibly speed?) to compensate.

**Comment by penev92** [comment]
See https://github.com/OpenRA/OpenRA/issues/7498#issuecomment-75014540

**Comment by MicroJOo** [comment]
dogs shouldnt "jump" anyway we just use this "cheap" attack to avoid adding the proper original behaivior ... and that is " dog starts running towards the enemy when in range , and rip him apart ... 
check it out (we dont use that sequences currently)  : 
![dogreissen](https://cloud.githubusercontent.com/assets/9139965/6305427/6eeddce2-b92b-11e4-831f-0feb772bab4a.png)

if you check out the original , you can see the exact behaiviour

**Comment by pevers** [comment]
Ah thanks for clearing this op @MicroJOo. I think that is indeed the way to go.

**Comment by MicroJOo** [comment]
#9171

**Comment by pi99y** [comment]
[14:32:50] <pchote> we now have a bunch of new logic that would make it easier to reimplement dogs
[14:32:55] <pchote> but nobody has chosen to do it yet
[14:33:10] <pchote> like the running attack
[14:33:15] <pchote> instead of the jump

@penev92 please do it, you're our only hope :)

**Comment by pi99y** [comment]
This one in pretty "cool" too:
http://i.imgur.com/8nRan2I.gif

**Comment by pchote** [comment]
Since this has a bounty i'm making it our generic "dogs are broken" ticket.

**Comment by masihaama** [comment]
+1

**Comment by pi99y** [comment]
Hi, this issue was stripped of its "bounty" tag / title while the supposed ~fix #11715  was closed.
Should this be re-tagged in hopes someone gets motivated to do it?
Thanks.

**Comment by abcdefg30** [comment]
@Mailaender had to remove all bounty tags from our issues because of bugs in the bountysource plugin.

**Comment by Mailaender** [comment]
Indeed, the reason was https://github.com/bountysource/core/issues/1062 and the missing auto-updates made this information incorrect when someone added or removed $ for this issue. You can still see the real value at https://www.bountysource.com/issues/8729098-dog-issues

https://github.com/OpenRA/OpenRA/pull/11715 should be easy to polish up to get it merged under the strict @pchote QA review. @GraionDilach promised to do the fine tuning, but probably didn't find the time yet.

**Comment by GraionDilach** [comment]
Yeah, it's on my to-do list, currently I'm adjusting myself to my new job and I'm also waiting for the upgrade-to-condition wave to go down. There isn't much point opening a PR of such level when the queue is so overloaded atm. Also, I want to recheck if I can salvage the old AttackLeap along with that new implementation because the old one is a really primitive implementation of RA2 dog/terror drone behaviour and should be kept there.

**Comment by pi99y** [comment]
Oh so there is a plan for this still, great guys, thanks!

**Comment by ibrokemypie** [comment]
Another issue, when a dog attacks another dog they both begin jumping towards each other, ending in an infinite loop of the two jumping between the positions of both dogs, making sounds the whole time.

**Comment by abcdefg30** [comment]
This was fixed by #15008 (and #16005 and #16007).
