### ISSUE TITLE
Optimize / help out the most advanced lua maps

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#7512]
I really love the advanced lua maps.

Now this: http://resource.openra.net/maps/2269 is my favorite, but It's so hard to make it work caused by crashes and mostly performance.(it runs sooo slow)
Can you help optimize that and other simmilar maps? Or just give some general tips to the authors?
##

**Comment by penev92** [comment]
We can't force tips down their throats. Neither is it our place to mess with their maps.
What we can do is optimize the underlying engine (and that's what we're doing) and answer mappers questions when they ask us.

**Comment by kyrreso** [comment]
I know, but at least this and first versions of the map could really be a nice testcase for the engine.
A static wiki page about lua.perf., or some comments to the authors of the most advanced map would at least help out the players in the long/short run.

**Comment by Mailaender** [comment]
The link http://resource.openra.net/maps/2269 is gone. The author can ask in IRC/forums for help.

**Comment by kyrreso** [comment]
updated maplink

**Comment by GraionDilach** [comment]
I've never seen any proper yaml from that guy even - I consider it a miracle the game doesn't crash on that stuff he makes. It definitely generates a lot of warnings already. (The lint checks tell everything.)

It's not the developers' job to point out what the modder does wrong and I don't think the guy would actually listen at all. (It should be the modder's task to initiate discussions on such things with devs if (s)he wants help, not vice versa.)

Summa summarum: that guy shoulda do a proper mod instead of hijacking RA with all his stuff which even fail the lint checks. OpenRA shouldn't invest time debugging stuff which doesn't adhere quality standards - these lint checks.

**Comment by Mailaender** [comment]
I am not even sure if Lua is the problem or just the "too much stuff at once" in general. #9443 might help.
