### ISSUE TITLE
Units get stuck on bridges [$21]

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#7539]
From time to time a vehicle gets stuck on bridges, it might be after giving a new move order as it is passing over a bridge. I have not been able to get units stuck on longer bridges.
![dy3fcij](https://cloud.githubusercontent.com/assets/7798635/6341942/46dc4d3a-bbd1-11e4-9fca-1821fd88bc5d.png)

Ok so this is how you reproduce this:
1. Move the vehicle south of the bridge.
2. Try to move the vehicle to the cell on the bridge in the picture, it won't go to it directly so move it over the cell then give it a new move order or press "s" (default) as it is in this cell and it gets stuck every time. 
![openra game_2015_02_25_10_33_04_371](https://cloud.githubusercontent.com/assets/7798635/6368125/0043996e-bcda-11e4-8d50-f9b36c4f4433.png)

This happens to infantry as well.

**Comment by pevers** [comment]
Does the vehicle keep being stuck or will it move if you do another move order?

**Comment by abcdefg30** [comment]
It keeps being stuck (I saw this with 3 rifle men somewhen as well).
But I don't have an idea how to reproduce that.
The only thing I know is, that this occurs on repaired bridges.

**Comment by StexoO** [comment]
Maybe related to #6684.
But here the bridge isn't damaged.

**Comment by penev92** [comment]
With @Snurre86's last update on how to reproduce it, this sounds like a tile metadata issue (walkable terrain). Just guessing, though.

**Comment by Snurre86** [comment]
Still happens in release 2015-04-24 in mission "survive 02".

**Comment by pchote** [comment]
Confirmed that this is still an issue on playtest-20151114

**Comment by Snurre86** [comment]
Still happens in Release-20151224

**Comment by fgdzfggsfgsfgsf** [comment]
Confirmed still happens in 20151224.  Also, I think I had 4-5 units stuck on a semi damaged bridge, and I lost all but 1-2 when the bridge was repaired.

**Comment by Codes4Fun** [comment]
This seems to be related to changeset 3fed98fcb10c18a3cccf8193ede0a94fe4273cb1

If I comment out the change to Bridge.cs, the issue stops happening, I also discovered debugging the code that you don't have to completely blow up the bridge to reproduce the bug, you just need to damage it, which then triggers that code and then you can get stuck on it.

Note also another way you can tell the bug is present is the fact that the unit can't move to that specific tile, that is actually part of the bug.

I don't know what the purpose of that code is, with that code disabled, units didn't cross the bridge when it was blown up, and when engineered repaired it, units could pass over it again, so basically works as expected.

Does OpenRa have a mod that dynamically creates bridges? That would be my only guess as to the purpose of that code.

The code itself seems to replace the bridges tiles with neighbor tiles domain values. So it is pulling the rivers domain value over the bridge.

**Comment by Codes4Fun** [comment]
I created a pull request [10728](https://github.com/OpenRA/OpenRA/pull/10728) that fixes this issue.

I created 2 test levels, one to test destroying and rebuilding the bridge, and the other for testing when the bridge is initially destroyed and the bridge is repaired.

[test_maps.zip](https://github.com/OpenRA/OpenRA/files/123878/test_maps.zip)

**Comment by Snurre86** [comment]
Tried it on survival 01 mission and it seems fixed in release 2016-10-19.
