### ISSUE TITLE
A.I. uses SuperPowers with cheat-like precision

### ISSUE THREAD

**Issue by meldrian** [OpenRA/OpenRA#7659]
In mod cnc, all A.I. use their super power weapons super effective, no matter if they are currently able to see the target or did ever discover this part of the map before. 
Got an Army of 25 Soldiers hidden and undiscovered in your base? Say goodbye to'em @ minute 4-7 of gameplay, thx 2 'luckshot' A.I. Airstrike. Same with IonCanon und Nuclear Missile.
Clearly recognizable it is, if you look at the replay and the view of the AI is activated.
Same's also if the a.i. attacks Harvesters with Helis but that's not a big problem...

so,
*\* If it's still in the complete black shroud, structures and soldiers should not be attackable by the a.i.
*\* If it's already discovered once, some randomness in aiming would be great, giving the exact aiming some 'errorness' correction. Example: getting a high random number let the A.I. miss it's main target and instead aim at something a little bit more south, west, north, whatever. A low random number let it hit the exact target it wants to hit.
*\* Units that the A.I. can't not be aware of, because it has no idea where they are, should somehow not be attackable. Instead the front of unit production buildings should be targeted, hoping that some units are still in place right there (like most human player would do).

Tanks for your attention, i hope something like this is usable and applicative somehow.
##

**Comment by epicelite** [comment]
AI needs advantages like this over human players because it has no real intelligence. So it gets small cheats.

**Comment by meldrian** [comment]
Well, how about an alternative A.I. that isn't that 'smart' with super weapons so you don't have to  disabling super powers completely? Someone named Jar Jar Bings or Gobby or Golum, idk.

In addition, imagine someone who's willing to learn the game first before playing against other human players.
Imagine this person being frustrated getting killed by the easiest A.I. out of nowhere game by game by game.
Imagine that this is true and the reason why I made up this issue in the first place.

**Comment by GeertJohan** [comment]
I think @meldrian makes a good point here. Ofcourse the AI uses game information to make decisions because having an AI 'predict' where you will be placing buildings/units the same way humans will is pretty hard. But maybe the AI shouldn't directly go for the best kill, instead go for the second best location to bomb/strike. That way it's less frustrating for new players, but still a challenge to win (it's not fun when it's too easy, right..)

**Comment by UberWaffe** [comment]
Some time ago work was done on making A.I. pick their super-weapon/support powers targets more intelligently. And while the current code make it easy to adjust the yaml to make them pick more poorly, no such effort was made (since no real 'easy' A.I. exists anyway).

@WhomeverMayAttemptToWorkOnThis:
If you only wish to adjust the yaml then you still have options. Here are some possibilities.
You could make an A.I. airstrike itself (or it allies at least) by swapping Ally and Enemy in this:
```
		SupportPowerDecision@Airstrike:
			OrderName: AirstrikePowerInfoOrder
			MinimumAttractiveness: 2000
			Consideration@1:
				Against: Enemy
				Types: Vehicle, Infantry
				Attractiveness: 1
				TargetMetric: Value
				CheckRadius: 2c0
			Consideration@2:
				Against: Ally
				Types: Ground, Water
				Attractiveness: -10
				TargetMetric: Value
				CheckRadius: 2c0
```
to get this:
```
			Consideration@1:
				Against: Ally
				Types: Vehicle, Infantry
				Attractiveness: 1
				TargetMetric: Value
				CheckRadius: 2c0
			Consideration@2:
				Against: Enemy
				Types: Ground, Water
				Attractiveness: -10
				TargetMetric: Value
				CheckRadius: 2c0
```

Or you could, for example, make it use airstrikes less effectively by making it target buildings (which are unlikely to die from a single airstrike), rather than units.
