### ISSUE TITLE
PlayerStatistics update is a performance hog

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#7685]
Even just me without any other AI or player, the occasional ```PlayerStatistics``` update in skirmish takes ~23 ms, causing a short, but noticable lag spike. Appears to be related to render.

**Comment by penev92** [comment]
My money is on [this fellow right here](https://github.com/OpenRA/OpenRA/blob/0dc65e5cf328f51f80b8f2940ae53119a7fc1afb/OpenRA.Mods.Common/Traits/Player/PlayerStatistics.cs#L57) which looks extremely slow.
If I'm right, then we need to switch that with a direct query to get the cells that are visible to the player.
It shouldn't be too hard, too. I'm unfamiliar with the all the visibility stuff, but [this](https://github.com/OpenRA/OpenRA/blob/0dc65e5cf328f51f80b8f2940ae53119a7fc1afb/OpenRA.Game/Traits/World/Shroud.cs#L30) looks like a good place to start (and hopefully finish).

**Comment by Mailaender** [comment]
I think you are right. These are large queries on all actors with multiple trait lookups and we are doing it 4 times per second. A simpler way would be to just make it not update that often.

**Comment by pchote** [comment]
It is the Shroud trait's job to track that kind of state. The stats code needs to use that instead of rolling its own.

**Comment by reaperrr** [comment]
Can't reproduce these massive 23ms lag spikes anymore, maybe it was a specific map, or indirectly fixed by something else.

It still takes ~7-8ms every 10 seconds on my rather fast system, though.

Might be something for @RoosterDragon to look at, my own attempts have just proven that this is still well over my head.

**Comment by RoosterDragon** [comment]
penev is on the right track here, it will be the ```UpdateMapControl``` function slowing things down.

The current function depends on the number of actors, try creating lots of actors and see if the slowdown returns. It takes a while because it has to determine the union of all the actors visibility from scratch every time, which isn't free.

The shroud could help since it's obviously keeping track of this state all the time. You could write a function for it that simply enumerates all the cells in the map and does a count of where ```IsVisibleCore``` on them is true. Divide that by the total cells on the map and I believe you'd have the same calculation. (If you did write this function though, #7686 would be an invalid optimization again.) The speed of this method would be dependant on the map size, instead of the actor count.

Try a large number of actors on a large map and see which works out faster in practise.

Hope that helps. :)

**Comment by penev92** [comment]
Pretty much anything that doesn't have a `Thread.Sleep()` will be faster than this.
Why would it invalidate #7686 though?

**Comment by RoosterDragon** [comment]
#7686 skips the internal bookkeeping the makes ```IsVisibleCore``` return the correct results when shroud & fog is disabled. It can do that because if shroud & fog is disabled then ```IsVisibleCore``` will never be called.

However if we wrote a map control function that works like I described, then we'd need ```IsVisibleCore``` to return correct results even with shroud & fog disabled so that this theoretical map control function would work. Therefore we'd have to undo #7686 if that happened.

**Comment by pchote** [comment]
I don't think the map control statistic is important enough to justify its massive performance overhead.  Lets just remove it.

**Comment by Mailaender** [comment]
I also thought about that. It can make a return once optimized.
