### ISSUE TITLE
Using spy plane triggers "enemy approaching" warning

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#7787]
Using spy plane on enemy base trigers the warning.

In general "enemy approaching" warning is triggered way too often IMO (for example: when you're attacking the enemy). Ideally it should only be triggered by defensive structures - as a warning (but @penev92 reports this is not possible under current implementation).

**Comment by obrakmann** [comment]
Reading the title, I assumed the issue was that an approaching enemy spy plane would trigger the warning, but after reading the yaml rules, I found out that that should already not be the case.

So this is about the spy plane revealing enemy units, which then trigger the warning. With the current implementation, that is indeed not fixable.  The logic would have to be completely turned around.

**Comment by pchote** [comment]
This sounds a bit crap.  I've heard other complaints about this feature, so we may want to consider disabling it until there is time to revisit it properly.

**Comment by obrakmann** [comment]
I tried to address some of the issues with #7799.

**Comment by Mailaender** [comment]
I kinda favor removing it completely in RA. The voice "Enemies Approaching" is also misleading if you are actively scouting the enemy base and you are approaching, not your enemy. So this is also bogus for every revealing unit, not just spy planes.
