### ISSUE TITLE
Map problems

### ISSUE THREAD

**Issue by FIREOFDOOM** [OpenRA/OpenRA#7960]
So I downloaded some maps for openra 20141029 specifically bombardment islands with some added units made by Norman and I download it and eveething is fine. But when I come to play it on the game I can't find it looked everywhere. What happened

**Comment by penev92** [comment]
Are you sure the map is in the correct folder? ( \Documents\OpenRA\maps\<mod>\ ) and are you running release-20141029?
Also it might pay to take a look at \Documents\OpenRA\Logs\ to see if anything broke and got logged.

**Comment by FIREOFDOOM** [comment]
Yes it is in the correct place

**Comment by FIREOFDOOM** [comment]
Same problem with liberation. Of Helsinki

**Comment by Unit158** [comment]
Please post your debug.log

**Comment by obrakmann** [comment]
Here's the exception:
```
Exception of type `System.IO.InvalidDataException`: Unknown binary map format
  at OpenRA.Map.LoadMapTiles () [0x0002b] in /home/oliver/devel/openra/git/OpenRA.Game/Map/Map.cs:401 
  at OpenRA.Map+<Map>c__AnonStorey2.<>m__2 () [0x00006] in /home/oliver/devel/openra/git/OpenRA.Game/Map/Map.cs:254 
  at System.Lazy`1[OpenRA.CellLayer`1[OpenRA.TerrainTile]].InitValue () [0x00000] in <filename unknown>:0 
```
The map has been converted to the new map format already, but the resource site says it's been parsed with release-20141029. Pinging @ihptru.

**Comment by ihptru** [comment]
With the first shot, I could not find any 'Bombardment Islands' with MapFormat: 7   on resource site.
The same is with 'Liberate of Helsinki'

**Comment by obrakmann** [comment]
@ihptru: I'm sorry, I still had another map with format 7 :/

@FIREOFDOOM: I couldn't find that bombardment island map with custom units either, but the map Liberation of Helsinki is a mission and shows up in the Single-Player -> Missions menu, not in the map chooser dialog.  The map still crashes for me since it doesn't correctly set up the custom units' sequences, though.

Can you give us a link to the other map you've downloaded? I suppose it's a similar problem, but it won't hurt to check it out.

**Comment by pchote** [comment]
We have now shipped multiple releases that use the new binary format, so this is no longer a problem.
