### ISSUE TITLE
England faction has wrong flag

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#8024]
The flag for the England faction in Red Alert mod is this: 
![flag](https://cloud.githubusercontent.com/assets/6599106/7333591/3a43279c-eb7e-11e4-92d7-221dc913e2d7.png)

But this flag is wrong. This is the flag of England: http://en.wikipedia.org/wiki/File:Flag_of_England.svg

The flag shown in game is that of United Kingdom: http://en.wikipedia.org/wiki/File:Flag_of_the_United_Kingdom.svg

So either the flag has to change or the name of the faction.

**Comment by MustaphaTR** [comment]
I think name should be United Kingdom and flag should be same.

**Comment by deniz1a** [comment]
Yes I think so too. Because England is not an independent country.

**Comment by penev92** [comment]
>[19:16] <penev> nobody will actually recognize the english flag

**Comment by deniz1a** [comment]
But that's their flag... So either don't use England as faction or use its correct flag.

And about the other point, my logic is actually not consistent with other factions. Ukraine SSR is a faction but that's not an independent country either. So I'm not sure about that but the flag should be corrected I think.

**Comment by Bynnar18** [comment]
I agree with MustaphaTR, just change the country name.

**Comment by lebedkin** [comment]
I agree that technically it is a mistake but we have the same problem with Russia and Ukraina because in USSR they had names Russian SFSR and Ukrainian SSR correspondingly. At the same time, Russian SFSR  - "commonly referred to as Soviet Russia, the Russian Federation, or simply Russia" http://goo.gl/ZWI8MX and Ukrainian SSR - "commonly referred to as Ukraine" http://goo.gl/wAOfWj. So using the same logic, since "United Kingdom of Great Britain and Northern Ireland, commonly known as the United Kingdom (UK) or Britain," http://goo.gl/x2iYwK we can call UK just "Britain" - to save space at UI.

**Comment by abcdefg30** [comment]
Sorry, seems like this is a WONTFIX: #8155

**Comment by RoosterDragon** [comment]
I'd still be in favour of a name change to UK, Britain or United Kingdom, personally.
