### ISSUE TITLE
Remote infantry crushing

### ISSUE THREAD

**Issue by sinf** [OpenRA/OpenRA#8064]
Notice how the engineer passes trough the topmost tiberium tile and dies when the harvester drives on the same tile later. Yes and this affects commandoes too. They can be crushed long after they have entered a building by driving a vehicle over the tile they entered from thus saving said building. No stealth tanks around because spectators see them and it is only 5 mins into the game:
![crush](https://cloud.githubusercontent.com/assets/9487531/7403219/37e539d4-eedc-11e4-8dd6-ad03778173a7.gif)
I just wanted to put this gif here thats all :P
##

**Comment by penev92** [comment]
This would be because they only visually enter the building, but their last known location is just outside it, so the game still thinks they are there. (That would be my wild guess, at least.)
If that if true, this affects entering for capture, sabotage, espionage, demolition (read "engineers, spies, commandos, Tanya").

**Comment by AoAGeneral** [comment]
Its also good to note from that gif that you can see the engineer start to walk back away from the structure after the first one damages it. This is also a known issue where both do not enter the structure.
