### ISSUE TITLE
TakeCover/FraidyCat sequence modifications overridden by WithInfantryBody

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#8075]
If a sequence-modifying infantry render trait is defined on a specific actor, it overrides any sequence modifications done by traits inherited from the ^Infantry default.

Example: On current bleed, TD infantry doesn't go prone visually because TakeCover is inherited from default, while WithInfantryBody is usually defined on the individual infantry actor (because of idle sequences and so on).

This issue blocks moving TakeCover to infantry default in other mods, as it reliably breaks the visual prone sequence modifier (rest of TakeCover trait works fine).

**Comment by reaperrr** [comment]
> [21:45] <+pchote> oh, you're talking about IRenderInfantrySequenceModifier
[21:45] <reaperrr> yeah
[21:46] <+pchote> if you move WithInfantryBody above TakeCover then it won't work, no
[21:46] <+pchote> because it does the lookup in the constructor
[21:46] <+pchote> you can fix that by moving the lookup into INotifyCreated

**Comment by penev92** [comment]
This seems to only solve half of the problem.
I was testing using Minigunners in TD.
Here is some YAML:
>\rules\infantry.yaml:
E1:
	WithInfantryBody:
		StandSequences: stand, stand2

>\sequences\infantry.yaml:
e1:
	stand:
	stand2:
	prone-stand:

Now, when the actor becomes idle, `WithIfantryBody` selects a random sequence from `StandSequences` to use.
Also, when `TakeCover` sets `TakeCover.IsProne` (`TakeCover.IsModifyingSequence`) to `true`, `WithIfantryBody` takes `TakeCover.SequencePrefix` and appends again a random sequence from `StandSequences`. (in our case that gives us either `prone-stand` or `prone-stand2`), then checks if the actor has such a sequence.
If there is such a sequence, great, use that. If not, use the selected sequence **without** the prefix.

This means that if we [enter here](https://github.com/OpenRA/OpenRA/blob/a2c1993561cfda0fd0622257083aaefd5252f0e3/OpenRA.Mods.Common/Traits/Render/WithInfantryBody.cs#L79) with `baseSequence == "stand"` everything is OK - the method will return `prone-stand`.
But if we enter with `baseSequence == "stand2"`, then the method will return `stand2`, so even if the sequence is changed (from `stand` to `stand2`), that doesn't actually matter, because it is not a prone sequence.

**Comment by reaperrr** [comment]
@penev92: I assume you know how exactly to apply the fix @pchote mentioned (I don't), please file a PR (or send me code), I'm working on updating the sequences of each mod to add a ```prone-stand2``` sequence to all infantry that use ```stand2```.
