### ISSUE TITLE
Mechainc can not get into the transport ship/ranger either with or without press alt key

### ISSUE THREAD

**Issue by carlos444** [OpenRA/OpenRA#8126]
release 20150424
tested in bombardment islands map

**Comment by obrakmann** [comment]
Test again. Works for me using force-move (Alt).

**Comment by carlos444** [comment]
really not work in windows/linux version, the Mechainc not move when click him into the ranger.

**Comment by sinf** [comment]
If you're using Linux you should know that many popular window managers hijack your ALT key by default (for moving/resizing windows). For ALT to work in openra you must first release that key with dconf-editor. You can't force-move any units anywhere without doing that. I just tested and can confirm that force-moving mechanics into transports works for me.

**Comment by atlimit8** [comment]
For KDE (assuming the use KWin - the default window manager for KDE):
Go to "System Settings" (under "Settings" in the application launcher menu).
Select "Window Behaviour" (under "Workspace Appearance and Behaviour").
Select "Window Behaviour" along the left.
Select the "Window Actions" tab.
Select "Meta" instead of "Alt" as "Modifier key:" under "Inner Window, Titlebar & Frame".

-- OR (for any use of KWin including under a KDE session) --
Right-click on a window titlebar.
Select "More Actions" -> "Window Manager settings...".
Select "Actions" along the left.
Select the "Window Actions" tab.
Select "Meta" instead of "Alt" as "Modifier key:" under "Inner Window, Titlebar & Frame".


The "Meta" key is that key with a logo between "Ctrl" and "Alt" on most keyboards.

**Comment by carlos444** [comment]
thanks

**Comment by atlimit8** [comment]
If there are any other issues based on the alt key window manger problem, then they should reference this.

**Comment by LavenderMoon** [comment]
@snif "If you're using Linux you should know that many popular window managers hijack your ALT key by default (for moving/resizing windows)."
Why would they do that? Coming from a Windows background, that seems really odd, considering that I've always just moved the titlebar and window edges to move or resize windows, even when using Linux window managers.

**Comment by atlimit8** [comment]
Possibly for border-less windows. It can be useful if an application window border-less such as loading splashes and pseudo-fullscreen windows; although, I can use the `F3` (titlebar context) menu "Move To Screen" option to move pseudo-fullscreen windows to other screens and/or desktops.
