### ISSUE TITLE
Lint rule to check actor upgrades

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#8272]
https://github.com/OpenRA/OpenRA/wiki/Actor-Upgrades can't be checked at compile time. String types of several independent traits have to match. This is error prone as typos can occur and there will be no warning just silent breakage. A rule could add checks against unused `UpgradeTypes` or undefined `Upgrades` and spit out a warning which may catch at least some sloppy yaml mistakes early.

**Comment by Phrohdoh** [comment]
:+1: It is functionality like this that makes an engine great.

**Comment by penev92** [comment]
:+1: to the idea.

**Comment by pchote** [comment]
This is going to be very difficult to implement.  Upgrade sources can be local, from another actor, from weapons, or from lua scripts.

**Comment by penev92** [comment]
I think the point is to check if something can grant that upgrade, not to check if the source and user can meet ingame to actually interact.

**Comment by pchote** [comment]
Indeed, but there are going to be a lot of false positives because many of our upgrade consumers (e.g. EMP, TD cloak crates, Iron Curtain, the RA shellmap invulnerability) rely on outside triggers.

**Comment by pchote** [comment]
That problem could be worked around by having a trait that lets each actor type list the types of externally granted upgrades that it accepts.  You would then need to make a typo in two places for it to pass the linter.

**Comment by penev92** [comment]
OK after a lengthy argument on IRC I guess we can't have this work properly, because we have (very questionable, architecture-wise) upgrade granting from Lua (as seen on the RA shellmap).
There are 3 possible ways IMO:
 - Have a proxy trait from granting upgrades from Lua, that would let us keep track of those uptrades (unlike the current situation).
 - Do the lint check and ignore Lua scripts. This will work for 99% of the maps, and give a few false warnings on the other 1% (not that big of a problem).
 - Do the lint check + a hacky "check" of any Lua scripts inside the map. That would actually work even for that 1%.

**Comment by pchote** [comment]
Lua scripts are only part of the problem.  Pulling all of the possible upgrade sources in the game into one giant list to check against ignoring other metadata (such as warhead target filtering) means that you're going to get false negatives (linter accepting upgrade consumers that can never be triggered) too.

Providing a per-actor list of external source types would also address that.
