### ISSUE TITLE
Some cells are not being overwritten while holding down the left mouse button and dragging

### ISSUE THREAD

**Issue by TiriliPiitPiit** [OpenRA/OpenRA#8306]
In playtest-20150524 when I try to overwrite land tiles with a 2x2 water piece by holding down the left mouse button and dragging the mouse over the screen, some cells are being left out (i.e. they don't turn into water). Even going back with the mouse (before lifting the left mouse button) doesn't make the cell turn. This happens even if I drag the mouse slowly. Starting all over after by lifting the mouse button, holding it down again and dragging works though.
This problem only occurs in the new ingame-editor for me.

Another problem which also appears in the old extern map editor is that some cells are being left out when I move the mouse too fast.

I am on KDE 4.10.5.

**Comment by cjshmyr** [comment]
The dragging works differently from the older editor, it won't place the tile unless all underlying cells are blank when dragging -- except for the initial click. Maybe that behavior could be configurable but I feel the actual problem is there's no quick way to paint an ocean (and to a lesser extent ra interior floors) so maybe a fill area tool gets around this.

**Comment by pchote** [comment]
As @cjshmyr mentioned, this is the expected behaviour.  If you drag the mouse with a 2x2 or larger template it requires all the tiles under the footprint to be of a different template to what you are placing.  If we didn't do that then you would end up with a dragged line of just one edge of the template.
