### ISSUE TITLE
Surrender in multiplayer games when "Abort Mission" is hit.

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRA#8369]
Idea taken from:
http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=16802&start=15#displayed_290379

**Comment by MicroJOo** [comment]
or #3001

**Comment by MicroJOo** [comment]
#3001 is related to this ... but , abandoned player-bases give atleast some sight and buildradius for the remaining players of the team ... and theres a couple of good players that can win games even though they are outnumbered ... so ... better we wait for bots to take over 

im giving this a :-1: because it would destroy "long games" and the hard core of player wouldnt like it
