### ISSUE TITLE
Elite weapon(s) in TS broken

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#8444]
I don't know yet whether this is a yaml or code issue, but in any case elite weapons don't work.

The Nod bike should get the HoverMissile @ elite, but it doesn't.

**Comment by matija-hustic** [comment]
This is a trait construction order issue at its core.

The problem is that when `UpgradeManager.GrantUpgrade` gets called to grand the `eliteweapons` upgrade, the `Armament` traits are not present in the lazy `UpgradeManager.upgrades` dictionary. This is because this dictionary enumerates all constructed traits implementing `IUpgradable` at the time of its first use. And in this particular case, when `^Vehicle.TimedUpgradeBar` gets constructed, it accesses `UpgradeManager.upgrades` thus enumerating only traits that have been constructed up until that moment. And it just so happens that `Armaments` haven't yet been constructed.

If the `IUpgradable` interface is here to stay and this cannot be resolved through `Requires<>`, then a constraint on the use of `UpgradeManager` should be made, forbidding any access to `UpgradeManager.upgrades` during trait construction.

**Comment by matija-hustic** [comment]
If that's OK, I can take care of this in #8496
