### ISSUE TITLE
Deployed tick tanks are treated as regular base structures

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#8521]
They can be repaired, and play the "base under attack" notification when attacked.

**Comment by penev92** [comment]
This will (eventually) be fixed when they start using `DeployToUpgrade` instead of `Transforms`.

**Comment by Mailaender** [comment]
That can also easily repaired by removing the inherited rules.

**Comment by penev92** [comment]
That - yes. The other shortcomings that Transforms has - no. I did test Tick Tanks specifically a while back, when building my argument for using DeployToUpgrade over Transforms, since they (and RA2 GIs) need it the most.
With a tiny amount of micro (for nothing other than deploy/undeploy) they can be so broken... (because transforming forces enemies to switch targets).

**Comment by epicelite** [comment]
For now you could just do repairable=no or something?

**Comment by penev92** [comment]
For now - sure.
