### ISSUE TITLE
Height issue with TS aircraft [$69]

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#8547]
I'll let the screenshot talk:
![height-error-ts](https://cloud.githubusercontent.com/assets/2857877/8293497/01ad8428-1936-11e5-8e4a-68a079c67305.png)

**Comment by reaperrr** [comment]
The  carryall was ordered to land at the side of the mammoth.

**Comment by penev92** [comment]
Aircraft (among a ton of other things) are known to not care about map height. See #7904.

**Comment by pchote** [comment]
Is this fixed now?

**Comment by abcdefg30** [comment]
>  18:15:25 (penev) https://github.com/OpenRA/OpenRA/issues/8547#issuecomment-158766641  I believe the consensus at the time was "don't let abcdefg30 claim the bounty because helicopters are still stupid"
18:15:43 (pchote) penev: is that the ramp thing?
18:15:54 (pchote) because that is a different issue that will
18:16:00 (pchote) that i have a fix in progress for
18:16:17 (pchote) which affects everything using DAT, not specifically aircraft
18:16:57 (penev) pchote: it's helicopters stopping and slowly climbing up/down cliffs
18:17:03 (penev) which is even worse on ramps
18:17:05 (pchote) ah
18:17:09 (penev) but IMO we can close it 
18:17:18 (penev) as they do respect terrain height
18:17:21 (pchote) ramps will be fixed, but cliffs is up to someone else
18:17:28 (GraionDilach) cliffs ain't that bad imo
18:17:36 (pchote) the missile behavior needs to be ported for that
18:17:38 (penev) it's terribad man :X
18:17:48 (penev) anyway
18:17:55 (penev) abcdefg30: close that and claim the bounty, I guess
