### ISSUE TITLE
TD artillery doesn't explode at all anymore

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#8595]
#8303 disabled artillery's vehicle explosion completely, I think we shoul change that to the small unit explosion that all other vehicles use.

**Comment by AoAGeneral** [comment]
What exactly do you mean? Using the arty explosion for other vehicles?

**Comment by reaperrr** [comment]
No, using the explosion of other vehicles for the arty.

**Comment by GraionDilach** [comment]
There's an explosion called UnitExplodeSmall defined in the TD and RA mods which is practically useful for providing visuals alone due to having a small Spread (42 IIRC) He means that instead of just simply spawning the husk, the artillery should explode using this weapon.

This weapon is already used upon many vehicles and husks when they disappear.

**Comment by AoAGeneral** [comment]
Oh I see. That could work. So long as the explosion chain reaction doesn't happen lol

**Comment by GraionDilach** [comment]
@reaperrr, you took care of this already in #8514, I see. Nice.

**Comment by penev92** [comment]
Fixed in #8514, which was just merged.
