### ISSUE TITLE
Allies03a: Imprisoned infantry does not get killed by exploding barrels

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#8722]

**Comment by mistikal** [comment]
For what it is worth, I attempted to reproduce the issue, but mine seem to die as expected. Tested with the medic, dies - tested with the engineer and the infantry, both die.

**Comment by obrakmann** [comment]
Nope, it's really bugged. It was introduced with acc4b307b63ee76c229051143fb28fcbab1a7af4. It seems that disabling `TargetableUnit` is a bad idea (ie. it makes units pretty much invulnerable)

**Comment by abcdefg30** [comment]
Seems like the problem is even bigger:

> 21:21 (+pchote) antares79: don't we cache TargetableUnit etc in a bunch of cases? 
21:21 (+pchote) that won't play nicely with turning them on/off 
21:22 (+antares79) pchote: with 'disable' I meant disabling using upgrades. that would be fine with caching, unless I'm terribly mistaken 
21:22 (+pchote) if you disable one without enabling another then you will have no targeting trait 
21:23 (+pchote) which means nothing can attack it 
21:23 (+antares79) hence the bug 
21:23 (+pchote) yup 
21:23 (+pchote) ...although, unless i'm missing something, I would call it intentional design 
21:23 (GraionDilach) ah yeah, multiple TargetableUnits still doesn't work lol 
21:23 (+antares79) yeah. it's just the wrong use case ;) 
21:24 (+pchote) what is that mission supposed to be doing? 
21:26 (+antares79) there are some infantry units of yours that are held captive by surrounding enemy units. those enemy units must be prevented from shooting at the captives somehow. previously, Cloak was used, since a few days ago it's TargetableUnit 
21:26 (+pchote) just make them not autotargetable 
21:26 (+pchote) via an upgrade 
21:27 (+antares79) yeah. or revert back to cloaking, that worked well. I don't know why it was changed. 
21:28 (+pchote) I think i remember seeing some comments about that being considered a hack 
21:55 (abcdefg30) anyway, i'm for support of multiple targetable unit traits 
21:55 (abcdefg30) we'll need that anyway for the targeting of airborne?
