### ISSUE TITLE
Proposal to refactor TargetType handling

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#8724]
Currently we have like 4-5 traits which handle TargetTypes on actors.
TargetableBuilding returns the cells
TargetableUnit works on units
and multiple subclasses of TargetableUnit, all working around the fact that an actor can have only one Targetable* trait.

I honestly didn't really looked into the code much, but from what I saw, merging TargetableBuilding and TargetableUnit is possible (via moving the Building() check in the latter) and then instead of having TargetableAircraft etc, we could set up their source traits granting an upgrade to enable/disable targeting/affection. (Helicopter granting an upgrade at height 200 for example)

This will be important for the RA2 mod because at there unit-targeting could change on the fly (Temporal weapons made the target only affected by such, an already mindcontrolled unit cannot be remindcontrolled, IronCurtained units weren't attacked by the AI, units in-air (paradropped or flying) couldn't get targeted by strictly ground weapons, etc).

This would also render map scripting easier.

**Comment by pchote** [comment]
There are some good ideas in here, but it will need some more discussion / development before somebody jumps into coding it.

In particular, you need to be careful about the two completely different things that the existing targeting code manages:

1.  The positions that can be targeted on an actor.  Our handling of this is abysmal: we use the range to any targetable position while determining target ranges, but projectiles then go exclusively to the center position.  This causes our weapons to fail completely if their ranges is less than half the footprint size.

2.  Target types, which have an all or nothing effect.

We should keep separate traits for (1), otherwise you are asking for pain around the edge cases: e.g. units can occupy 0, 1, or 2 cells at any given time, and its possible that the actor's center position is in a completely different cell versus buildings which should be attackable at any cell in their footprint.  I'm all for replacing our current mess of subclasses for (2) with some kind of setup that has a single 'manager' trait and some way for other traits to add or remove target types.

**Comment by GraionDilach** [comment]
1. definitely need a fix, TS visceroids were serious melee threats buildings in a base, YR also had Brutes. I can also see why it should keep the sepearate traits.

Maybe decoupling the actual TargetTypes from TargetableUnit/Building into a new properly upgradeable trait would be the way to go. Notsure, I'll definitely brainstorm over this.
