### ISSUE TITLE
AttackMedic and AutoHeal duplicates the logic of AttackFrontal and AutoTarget

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#8763]
Currently we have a duplicate logic for healers. This means that if a unit wants to be a healers/active buffer with a damaging weapon as well, the unit can either resort to force-fire to heal/buff (along with forcing the damaging weapons to not work on allies to make sure it won't get fired along with the bufferweapon) via using the right Attack* or just split the functionality of and use purely `AttackMedic` etc.

This also means that healer/buffers are hardcoded to have "`AttackFrontal`".

What I'd propose that instead of the duplication logic, there would be some kind of a `Benefical` tag on the weapon and `AutoTarget` would look at that - if `Benefical=yes`, allied autotargeting is allowed with that weapon, if no, enemy autotargeting is allowed on that weapon.

#8563 is a case where this becomes a problem.

**Comment by matija-hustic** [comment]
I've worked on this a little locally and got these ideas that I'd like to discuss.
* Right now at most one subclass of `AttackBase` is allowed per actor. Also, exactly one pair of `Cursor` and `OutsideRangeCursor` per `AttackBase` is used. The former is not necessarily a problem, but the latter probably is - different cursors for attack and buff, different cursors for ground attack and air attack for example... I'd suggest moving `Cursor` and `OutsideRangeCursor` to `Armament`.
* Related to this, @GraionDilach, is there any specific reason why you'd want the `Beneficial` on the weapon instead of the `Armament`?
* I imagine then that targeting with the force modifier would in some instances have to discriminate between different available armaments. Right now the force modifier doesn't affect the choice of the armament. It only affects whether or not "a target is targetable". However, an armed medic for example might want to normally heal allied units, but when using the force modifier, shoot them. This would be the case with #8563, a tesla trooper would normally want to powerup a tesla coil, but when force targeting it, he might want to zap it.

**Comment by GraionDilach** [comment]
>Related to this, @GraionDilach, is there any specific reason why you'd want the `Beneficial` on the weapon instead of the `Armament`?
There practically wasn't, it was a draft I didn't give much thought about. Either way if we'd go with `Benefical` - regardless of place - then indeed, force-attack should ignore it.

Moving the cursors to Armament-level sounds odd to me - that same logic could apply to voices (Yuri's Revenge had such for Magnetron, Boris) however I'm not certain how feasible would either be with OpenRA's system.

**Comment by matija-hustic** [comment]
Well, different cursors should probably be handled somewhere. `Armaments` are just the first place to look at after `AttackBase`. Putting the cursors in the `Armaments` is a matter of small changes to the code. It's only a matter of program design and architecture. I've just put it out there so that I could get some hopefully constructive criticism ^^

**Comment by GraionDilach** [comment]
How does that react when a unit has more active armaments with custom cursors? If you can straighten that out, then my concerns are dismissed, but right now, i can't overlook that.

**Comment by GraionDilach** [comment]
On a second thought, the main reason why I suggested `Benefical` was that checking damage wouldn't tell that the actually weapon is aimed at enemies or allies - buffer/debuffer weapons like the tesla charge do not deliver damage - I literally stopped thinking beyond in terms of where should it be placed.

**Comment by matija-hustic** [comment]
Multiple cursors work. I've just equipped the medic with anti-air missiles and a gun for ground units, each of these three having a different cursor. It works as I would expect it (without force fire, only healing icon on damaged units; with force fire, attack cursor on ground units and ground, separate attack cursor on air units)

I personally find the `Beneficial` idea good.

**Comment by GraionDilach** [comment]
My main concern comes from units which can use multiple weapons against the same kind of targets, like the TD Mammoth Tank having both guns and missiles against ground but only missiles against air.

**Comment by matija-hustic** [comment]
What do you propose? Supporting multiple `AttackBase` traits? Creating some kinds of armament groupings?

**Comment by GraionDilach** [comment]
While I would wish for multiple `AttackBase` traits - for having fireported units with classic weapons as well - I am certain that would bring further issues in (I even thought about moving fireports into the equvivalent of `Armament` instead being much more feasible).

What comes into my mind would be some kind of a priority tag  - MousePriority? - and the highest priority weapon would have it's cursor on the target (maybe this too extended for voices?).

But I'm just throwing ideas out to the open, I'm not certain if this could work.

**Comment by matija-hustic** [comment]
Priorities should work fine as a temporary solution. The proper solution should anyway be, as @pchote has commented in IRC, multiple `AttackBases`. But me I'm not gonna be able to take this on right now since I won't have much time in the following month.

**Comment by matija-hustic** [comment]
Should be closed probably..
