### ISSUE TITLE
Game crash Attempted to get trait from destroyed object (crate 1256 (not in world))

### ISSUE THREAD

**Issue by xp65** [OpenRA/OpenRA#8826]
The game crashed with the following exception:
Version: release-20150614

```
Red Alert Mod at Version release-20150614
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (crate 1256 (not in world))
   bij OpenRA.TraitDictionary.CheckDestroyed(Actor actor)
   bij OpenRA.TraitDictionary.Get[T](Actor actor)
   bij OpenRA.Actor.Trait[T]()
   bij OpenRA.Mods.Common.Traits.ParaDrop.IsSuitableCell(Actor actorToDrop, CPos p)
   bij OpenRA.Mods.Common.Traits.ParaDrop.Tick(Actor self)
   bij OpenRA.World.<Tick>m__3(TraitPair`1 x)
   bij OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   bij OpenRA.World.Tick()
   bij OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   bij OpenRA.Game.LogicTick()
   bij OpenRA.Game.Loop()
   bij OpenRA.Game.Run()
   bij OpenRA.Program.Run(String[] args)
   bij OpenRA.Program.Main(String[] args)
```

**Comment by kyrreso** [comment]
Could be the same, this replay will crash your game: https://www.dropbox.com/s/3k218wuhgc1yy7x/OpenRA-2015-07-28T230640Z%20crash.orarep?dl=0

**Comment by kyrreso** [comment]
http://resource.openra.net/maps/3771

**Comment by obrakmann** [comment]
This is a funny one. Crates have a default lifetime of three minutes. Due to the size of the map, the badger aircraft apparently took longer than that to reach the drop location, so the crate died while it was still in the aircraft, and when it was time to drop it, the game crashed.

I guess a reasonable fix would be to only increment the lifetime counter if the crate is actually in the world, which would probably better reflect the intention of the Lifetime property, anyway (ie. the time that the crate should be available for pickup in the game).
