### ISSUE TITLE
LAN discovery

### ISSUE THREAD

**Issue by RobotCaleb** [OpenRA/OpenRA#8906]
I noticed there is no LAN discovery support. LAN parties might enjoy it more if the games could be found.

https://www.reddit.com/r/openra/comments/3ducd2/want_to_play_locally_with_my_father/ct8slv9
##

**Comment by Mailaender** [comment]
@markolson added it in his private https://github.com/markolson/OpenRA/tree/lan The thirdparty dependency is available via https://www.nuget.org/packages/Lidgren.Network/

**Comment by markolson** [comment]
Blast from the past. I'm happy to take another look at OpenRA and get that branch caught up if it's something that could be valuable to merge in.

**Comment by Phrohdoh** [comment]
@markolson It is often requested, please do. :)

**Comment by hoxworth** [comment]
:+1: @markolson Add all the things.

**Comment by spacemunkay** [comment]
:+1: go @markolson!

**Comment by llimllib** [comment]
:performing_arts: @markolson contribute for the good of humanity

**Comment by MicroJOo** [comment]
:+1: @markolson

**Comment by x-a-n-a-x** [comment]
![thumbup](https://cloud.githubusercontent.com/assets/1732773/9120997/e1b29524-3c7f-11e5-843b-3996407ecec6.gif)  @markolson

**Comment by StexoO** [comment]
:+1:

**Comment by rob-v** [comment]
I found 'simple' working library so I could implement LAN discovery. I integrated LAN games with other games, this could be adjusted.

![obrazok](https://cloud.githubusercontent.com/assets/16348750/24216196/a38f3370-0f3b-11e7-8e76-fb0f6f7eba37.png)

**Comment by hoxworth** [comment]
As long as @markolson is involved I'm happy

**Comment by rob-v** [comment]
I didn't use his branch/code, so he is not involved.

**Comment by rob-v** [comment]
I am not sure above the reactions above.. Is this something I could finish using this library https://github.com/rix0rrr/beacon ?

**Comment by pchote** [comment]
@rob-v if you think you have a solid solution for this, then please do file a PR!

I also don't understand what happened in the comment above...

**Comment by markolson** [comment]
I initially made a LAN patch for local play at work, and that's just some old coworkers and I being dumb. If you want to work on this, by all means please do - I tried to get something working again a while back and couldn't.

**Comment by chrisforbes** [comment]
@rob-v Looking forward to your pull request.

**Comment by rob-v** [comment]
Thanks all. Assuming the used library rix0rrr/beacon, which works fine in my tests, is solid. Thanks to its simple interface, also my integration with other MP games is simple, so I hope after a review and update of the integration it will be good solution.
In case of major design concern with used rix0rrr/beacon, I could either try to use Lidgren.Network library used by @markolson or check his branch if it could be finished if he doesn't prefer to finish it by himself, otherwise you can close the PR to let it implement by someone with more network dev experience.
In current implementation you see only Waiting LAN games, not Started.
