### ISSUE TITLE
Playtest AI issues

### ISSUE THREAD

**Issue by xp65** [OpenRA/OpenRA#9008]
Latest Playtest 2015 08 08

First of all congratulations with this update, it makes many things better. Thanks for the hard work!

The problems I came across while testing:

AI makes 18 (some are out of screen) harvesters with only 2 refineries, but not a single unit to defend himself: (his base builiding was destroyed earlier)
![image](https://cloud.githubusercontent.com/assets/6690499/9152840/9b33db74-3e39-11e5-8a7b-90f820f823da.png)

Subs from AI are dropping performance heavily.
The game was very slow, so I started to look for the reason (I first suspected the wall across the map, but it wasn't it). Once I killed all units on land except a few buildings, I started at sea, each boat I destroyed the game got back faster and faster. I have a modern fast computer, SSD hard drive, 16GB Ram, etc so on a slower pc the game wouldn't have been playable at all.

To give an idea: Sub Pen + 6 subs remaining: huge drop in performance, all other units and buildings from that party destroyed. After destroying the sub pen (boats get destroyed with it), performance is back normal. (at the end part of the game, the green player upper right side of the map)

I couldn't wait till the end in the replay to take screenshots at the end, as due to the slow performance it took takes, but see spikes herein performance due to boats:
![image](https://cloud.githubusercontent.com/assets/6690499/9152912/597dd546-3e3d-11e5-8ffa-9e98ef7a904b.png)

Replay: https://drive.google.com/file/d/0BynHp26MoAw-eVpmME5VS0dDQ0E/view?usp=sharing (you can download the file at the top center of that page) and then extract it with an application like 7zip.
The map was: http://resource.openra.net/maps/758/

Thanks again for the great update and thanks for looking into this.

**Comment by Phrohdoh** [comment]
Hey @xp65, thanks for the detailed ticket!
These types of reports make it much easier to begin looking into an issue which means we can resolve it quicker.

Performance is of course quite important so this will definitely need to be resolved before the stable release is out.

**Comment by penev92** [comment]
Nice, I like this report :)
Do you happen to have the `perf.log` from that game, or from watching the replay? My laptop is significantly slower so it might take a while before I can generate my own logs.

**Comment by xp65** [comment]
Thanks guys! I'll let my pc run the replay again later today to make the perf.log.

**Comment by xp65** [comment]
I did some digging and it seems you guys store all the games in the perf.log until closing, thanks to that, I still had the original log file, I cutted out the actual game and here it is: 
https://drive.google.com/file/d/0BynHp26MoAw-emxyWk5Udl9zc3M/view?usp=sharing (download button is center on top of the page)

**Comment by reaperrr** [comment]
The HackyAI lag spikes happen every 30 ticks, which matches `AttackForceInterval`, so it's likely that the AI tries to make squads containing submarines do things they can't do (AttackMove towards land targets).

**Comment by RoosterDragon** [comment]
I ran this replay as max speed with profiling on. The CPU time spent in various interesting areas are:
* 49% in [World.SyncHash ran after processing each order](https://github.com/OpenRA/OpenRA/blob/5720bde43bca138fdd07b2829520e4af1a92eb62/OpenRA.Game/Network/OrderManager.cs#L213). This is the same problem as noted in #8770 - sync hashing for every order is super expensive. @pchote has suggested in IRC that'd we'd be safe enough to sync only one per tick rather than once per order. That would fix this since the per-frame sync only costs 1%.
* 17% in [Move.Tick (for pathfinding)](https://github.com/OpenRA/OpenRA/blob/5720bde43bca138fdd07b2829520e4af1a92eb62/OpenRA.Mods.Common/Activities/Move/Move.cs#L159) - to be expected really as we know pathfinding is expensive.
* 10% in [GroundUnitsAttackState.Tick](https://github.com/OpenRA/OpenRA/blob/5720bde43bca138fdd07b2829520e4af1a92eb62/OpenRA.Mods.Common/AI/States/GroundStates.cs#L144) - in particular finding an enemy to attack when not busy. I suspect this is the problem with the subs - maybe they keep trying to find a target and come up empty causing repeated searches? (Just guessing here.) Does this even find valid nearby targets for subs? - I'm not sure.
* 3% in [TryGetActorFromUInt](https://github.com/OpenRA/OpenRA/blob/5720bde43bca138fdd07b2829520e4af1a92eb62/OpenRA.Game/Network/Order.cs#L120). We can probably eliminate this overhead by allowing lookup of actor by ID so it doesn't have to churn through the whole set of actors.

**Comment by LipkeGu** [comment]
it seems instead earlier than 30 seconds :/
http://i.imgur.com/TNuxk4S.jpg

**Comment by reaperrr** [comment]
> 

it seems instead earlier than 30 seconds :/
http://i.imgur.com/TNuxk4S.jpg
and it doesnt ends :(

This is a different issue, this is the pathfinder. It cannot handle TS' terrain well yet.

**Comment by RoosterDragon** [comment]
We've merged #9022 and #9023 which should address a large amount of the performance problem, and we have #9021 and #3241 which providing specific details on fixing the remaining problems.

**Comment by xp65** [comment]
Thanks guys for the great work, I really appreciate this. Only 12 days have passed and you guys have moved mountains.

**Comment by RoosterDragon** [comment]
Providing the replay and a detailed description of the problem works wonders in helping us solve this sort of thing, so thanks for the awesome report. :)
