### ISSUE TITLE
Hide-map effect does not work in replays

### ISSUE THREAD

**Issue by Townes27** [OpenRA/OpenRA#9063]
The hide-map effect of crates doesn't work in replays, meaning the scouted area merely remains hidden behind fog of war, not newly created shroud as it should.

Here's a replay and a map (provided by Zjordy):
http://s000.tinyupload.com/index.php?file_id=59247814826002024943

**Comment by deniz1a** [comment]
It's because of this line:
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Crates/HideMapCrateAction.cs#L35

Is that check necessary? Why not remove that line? Also, when a player gets this crate, shouldn't it apply to all its allies too? Because otherwise this causes a difference in shroud visibility between allies.

**Comment by Unit158** [comment]
If you didn't have that check, everyone would get affected by the shroud!

**Comment by deniz1a** [comment]
No, it only resets the shroud of the collector's owner. Each player has its own instance of shroud.

**Comment by Unit158** [comment]
@deniz1a Right. Then remove it and see what happens, it may be the correct fix :)
