### ISSUE TITLE
Lint check player palette references

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#9101]
to complete https://github.com/OpenRA/OpenRA/issues/8689.

**Comment by reaperrr** [comment]
I'm not sure whether this approach will work in cases where a single property defines the palette name and a boolean property then defines whether that palette should be treated as player palette.

@pchote's suggestion from #8749 sounds more sensible to me.
`I suggest adding overloads for the palette reference that let you specify as a bool whether or not it is a player palette, or a string that points at the bool field that determines at runtime whether it is a player palette.`

**Comment by Mailaender** [comment]
It will be easier if we used:

```csharp
[PaletteReference] public readonly string Palette = null
[PlayerPaletteReference] public readonly string PlayerPalette = null
```

everywhere (at some places we already do) and using what is != null instead of a boolean switch.

**Comment by pchote** [comment]
That leads to ambiguities when the mod defines both.  A single string and a bool specifying straight / player avoids that.

**Comment by atlimit8** [comment]
What about a new reusable `struct` such as `OpenRA.Primatives.TaggedString<EnumType>` that is loaded from the MiniYaml code:

1. *enumValue*`,`*stringValue*
`player, player`, `fixed, terrain`, `fixed, chrome`

2. Another style is to use *stringValue[*`@`*enumValue]* with the default enum vaule if the `@` is missing:
`player@player`, `terrain`, `chrome`

3. If the `@` is confusing because of its current usage, perhaps *stringValue[*`?`*enumValue]* with the default enum vaule if the `?` is missing:
`player?player`, `terrain`, `chrome`

**Comment by pchote** [comment]
That feels more complicated than it needs to be.  We are already using the pattern i've been asking for for sequences / images.

**Comment by Mailaender** [comment]
You will then need to explain how your new string@string or string?string filetype works in https://github.com/OpenRA/OpenRA/wiki/Traits and I don't see how that will be easier to lint.

```csharp
[PaletteReference("IsPlayerPalette")] public readonly string Palette = null
public readonly string IsPlayerPalette = false
```

will work after some fiddling with the lint rule and the resulting configuration will be understood immediately or at least be more resistant against wrong input.
