### ISSUE TITLE
Changelog has different sets of changes for next release

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#9113]
The changes for next release listed here:
https://github.com/OpenRA/OpenRA/wiki/Changelog
are different from the ones listed here:
https://github.com/OpenRA/OpenRA/wiki/Changelog%20%28bleed%29

**Comment by deniz1a** [comment]
Shouldn't the changelog for bleed say Next+1 or Future instead of Next?

**Comment by penev92** [comment]
They are different because they are for different releases.
For details see https://github.com/OpenRA/OpenRA/wiki/Development-Process
Perhaps someone missed the "+1" this time for bleed.

**Comment by Mailaender** [comment]
[Fixed](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/464a3f9b89fc8b4cdc4c7213cb682ddb716d182e...20ecd4ba39bfd0d31c56d50cbe428a541acb5d4e)

**Comment by pchote** [comment]
That has made the problem worse, IMO.  Most reasonable people should understand from the context that the development branch (and changelog) was a different stream to the main branch (and changelog), and so that there was no conflict between "Next Release" in each.

Changing the development changelog to "Next but one" is still be incorrect (there may be more than one release on the main stream before we switch to the development branch), and confuses terms for people who *do* understand the separation.
