### ISSUE TITLE
Support for wrapping maps

### ISSUE THREAD

**Issue by Aaron-Lloyd** [OpenRA/OpenRA#9137]
So I was playing Materia's Earth map and the thought occurred to me that it'd be really neat if OpenRA allowed for wrappable maps (ie the left side of the map wraps around to the right side or north side wraps to south side). Would allow for some really interesting new map designs and concepts.

**Comment by penev92** [comment]
Interesting idea.
The proper way of doing this will require tricky low-level engine surgery, and I don't see that happaning.
There is, however, a somewhat hacky alternative - the map author can have a Lua script that would teleport units from one edge of the map to the other. This won't be perfect, because the pathfinder will have no clue, but it's the best I can see as viable. You'd want to contact the map author for that.

**Comment by Unit158** [comment]
Because OpenRA wasn't designed with this in mind, it would be tough to do true wrapping. What could be done, however, is the idea of a tile that teleports units. This would be much more feasible imo, and would probablt require less work with the pathfinder.

**Comment by deniz1a** [comment]
For this to be implemented correctly, engine would need to support spherical coordinate system, right?

**Comment by xp65** [comment]
@deniz1a  to simulate a true planet yes, but to make a map just repeat on all edges no. It can be achieved with "almost" purely a change in how things are rendered, it just keeps on repeating all on x and y axis. Mouse clicks and actions are translated to as if it was one map. 

Besides the renderer the biggest change would be pathfinding, so it wouldn't go all the way from one edge to the other edge over the map, but just go straight to the nearest one on the other side of the edge. (left/right  top/bottom).

It would be cool because no one will have an edge of the map as a defence. Your enemies are always on all sides until you have conquered the whole width or height of the map. It would require special maps, but it would certainly create a whole new and very fun dimension to OpenRA.

**Comment by deniz1a** [comment]
I think this would be meaningful only with strategic zoom and much bigger maps. And for that, the engine would have to be 3d. So maybe in the future if C&C Generals and later games are supported then this could be implemented.

**Comment by xp65** [comment]
I don't see why 3d would be needed and it even works on medium sized maps. It doesn't require a spherical implementation, just repeating on all axises.

**Comment by deniz1a** [comment]
Yeah but then what is the map supposed to represent? An asteroid? And without 3d engine, it would not be possible to represent the curvature of the map.

**Comment by xp65** [comment]
Hi Deniz1a, I fear you have a wrong idea about the concept. It doesn't need to represent anything just a repeating map. And there is no need for anything like a 3d or curvature, etc...

All it does is when you move the the right side of the map, where it normally ends in black, the left side of the map just starts again and you can keep on scrolling. 

If a map is 256x256 then 257 would represent 0 again. 258 represent 1, etc. plain and simple.

**Comment by pchote** [comment]
Even a "simple" wrap would be complicated to implement.  If the player has a larger screen resolution than the map then the same actors will need to be rendered multiple times.

**Comment by xp65** [comment]
True it won't be just in or outside the viewport, complicating things and it will probably result in many new errors and visual artifacts. I wouldn't add it high on the list of features. I just agree with Aaron-Lloyd (original poster), the earth map would be a good example to have such a feature.

That said, it's all about people donating time, so instead of playing the game more, I'll install again visual studio soon and take a look at the code to see what I can do. This sounds like something separated enough for me to be able to play with without blocking the development because I have not enough time to be "fast". Is there a means to claim projects at openra? so people are not working on the same thing?

**Comment by penev92** [comment]
You can be "assigned" to the issue, so everyone sees that you are working on it.

**Comment by xp65** [comment]
@penev92 , could you assign me? As I have no rights it seems to assign myself. Thanks

**Comment by penev92** [comment]
Sorry, GitHub won't let me for some reason.

**Comment by GraionDilach** [comment]
@deniz1a Play the original Settlers to see why 3D wouldn't be needed for this feature.

**Comment by xp65** [comment]
@penev92, no prob, best way to claim it is I think that I'll show regular updates and screens of work in progess then :)

**Comment by xp65** [comment]
The terrain is rendered with a vertex buffer, but the position is set at the start of the frame and only vertically the rows are calculate to be rendered the rest is cut with EnableScissor etc... making this is going to be either a lot (as in changing many things) of work or very messy code to maintain.

I decided I'm not going to make it, as I'm too new to this code and it's really complex to make this work right without making things very slow and a mess of the code. I better start with volunteering my time on more achievable tasks :)

**Comment by penev92** [comment]
Good call ;)

**Comment by Phrohdoh** [comment]
Can this be closed?
I don't see map wrapping happening.

**Comment by penev92** [comment]
Yeah, I don't think this will happen as an engine feature.
