### ISSUE TITLE
Add fair use notice for distribution and use of EA assets

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRA#9165]
http://copyright.gov/fair-use/more-info.html

IANAL, but this could potentially allow us to destribute the d2k soundtracks as well.

**Comment by Mailaender** [comment]
http://redalert1.com/ has something like that in the footer in some kind of disclaimer style. However I doubt the "fair use" term from US jurisdiction applies. If you read the legal text:

>  for purposes such as criticism, comment, news reporting, teaching (including multiple copies for classroom use), scholarship, or research, is not an infringement of copyright

That doesn't really fit here.

**Comment by Unit158** [comment]
You're misunderstanding the nuances of the English language, I guess. Fair use was pretty much written for uses like ours. Please read Section 4, I think it will interest you.

**Comment by GraionDilach** [comment]
Problem with "fair use" is that it doesn't exist in most countries' law - I'm certain mine doesbn't acknowledge such for sure.

**Comment by pchote** [comment]
I think this is a good idea.  I see no reason why we shouldn't modify the second paragraph of http://www.openra.net/legal/ to include something like "We believe that this falls under the concept of Fair Use, Fair Dealing, or other related legislation in the countries that our developers and players reside" and then duplicate that paragraph in our ingame credits.

**Comment by Mailaender** [comment]
In Germany the concept is also not known which is also the reason de.wikipedia.org and the international commons.wikimedia.org disallow it. Seeing how minimally it is used on the English Wikipedia, I doubt this counts as citation and Section 4 sounds especially scary, because I guess we and @cncnet have far more players than the http://xwis.net/ platform which still sells keys.

A better precedence is probably the other http://osgameclones.com/ which almost always avoid supplementing the proprietary game files. Actually this makes me wonder if we should shutdown all content mirrors.

**Comment by GraionDilach** [comment]
Content mirrors for the freeware games - TD, RA, TS - are fine. XWIS at our main games doesn't even matter, it's pre-RA2 playerbase died off before/around TFD got released, and CnCNet reached it's current playerbase on it's own.

Section 4 only sounds scary for the abandoned/active games (D2K/RA2), but afaik D2K won't be downloaded via content mirrors - if yes, now that is a problem.

OS Game Clones are again precedents for abandonware projects, not freeware ones.

**Comment by Unit158** [comment]
Actually, d2k becomes quasi-legal to download under section 4, again, IANAL.

**Comment by Mailaender** [comment]
True, that is somehow a point for https://github.com/OpenRA/OpenRA/pull/9162 also in terms of just business logic: "why should they care".

**Comment by GraionDilach** [comment]
It does hurt potential sales. Although this might sound stupid - I'm kinda affected by East-European mentality here, which does not believe in Digital Piracy Is Evil and also personally had some really sad examples of No Export For You to always have a second thought about DPIE - our D2k looks pretty D2k for the casual play-for-fun people who thereby no longer would buy the real thing. That sounds pretty solid as a reason on a court to me.

On the other hand, if there would be a simple way to know that it's out of print, and only 2nd-hand sources are available, then I guess fair use can be applied - the IP owners can't get further profit since they got all the money they could gather from the actual games already.

**Comment by LipkeGu** [comment]
whats the result of the content mirror for music?

**Comment by Mailaender** [comment]
I didn't get a response from EA and explicit permission is very unlikely to happen. All community managers from the time of those games are long fired.

**Comment by Unit158** [comment]
Wait a month or so. Their requests take a while.
