### ISSUE TITLE
AI harvesters don't search far away enough for new resources

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#9232]
https://github.com/Mailaender/OpenRA/commit/2a21c7d1f2f8f10578cb71ce07147886e1dbec55 has the downside that the AI harvesters will start running circles when the next ore patch is too far away. The FindResources has to increase the search range in those cases.

**Comment by RoosterDragon** [comment]
Given that:
- #9144 prevents harvesters sucking up perf searching for unreachable tiles.
- Mailaender@2a21c7d improves performance by saving a whole pathsearch.
- #9140 and #9141 will improve pathfinder perf a bit
- #9222 limits AIs from building too many harvesters

I'd say we could happily triple the search radius without too much worry of performance problems.

In fact, would it be worth removing the limit entirely? It'd be much better to pay one high pathfinder cost to reach far away ore rather than do a moderately costly search that we'll then just have to repeat all the time because it keeps failing.

**Comment by pchote** [comment]
The limit was there primarily for gameplay reasons, not perf.  You don't want your harvesters running to the other side of the map if the local ore field becomes depleted.

**Comment by Mailaender** [comment]
I did some tests and the harvester behavior is still to search for the nearest available resource even without resource radius restrictions. Given the many manual overrides we need to workaround problems of these range checks https://github.com/OpenRA/OpenRA/search?q=SearchFromProcRadius I vote for complete removal.

**Comment by LipkeGu** [comment]
@RoosterDragon says we have to repeat that steps again when maps will be bigger ...

complete removal: :+1:

**Comment by pchote** [comment]
:-1: to removing the limit, which regresses gameplay.  If your harvesters run out of local fields there is no benefit for them to travelling hundreds of cells to find a new field.  If they don't die on the way (very likely if they pick a field near an enemy base) then the time it takes for them to travel there and back would be comparable to the time it would take for the local field to regenerate.

**Comment by penev92** [comment]
- I have always found it retarded when harvesters tried to harvest from the enemy base all the way across the map.
 - If you want them to, you can order them manually, which is still easier than keeping an eye of for them doing it on their own as they please and having to stop them or defend them.
 - The AI has no way of dealing with either the situation where you need to stop them and send them back to base, or the situation where you want to let them do their stuff but you need to protect them.

**Comment by Mailaender** [comment]
You seem to be missing the point. The radius restriction limit was mostly there for performance, not gameplay. The AI would actually do two very large path searches across the whole map to find a new patch no matter if enemies are around before https://github.com/Mailaender/OpenRA/commit/2a21c7d1f2f8f10578cb71ce07147886e1dbec55 so it never adhered to this radius restrictions anyway.

**Comment by LipkeGu** [comment]
AFIN: In some matches the Ai also cant find fields and the harvester is doing cycling loops... in a 3 range radius. so when we have this the AI is going crazy ... without this our harvesters going long travels. 

In fact: Both problems are things what we doesnt want. We could make this upgrade upble WHEN REALLY not other way is found for the Harvesters to find a local field.

**Comment by Mailaender** [comment]
We probably need to differentiate between human controlled and bot owned harvesters again. I will think of something which retains the previous behavior.

**Comment by LipkeGu** [comment]
implement a check which is saying "if there is an enemy building in the area, then dont harvest there" done...

**Comment by RoosterDragon** [comment]
I think Mailaender is on the right lines, if we restore the old behaviour I think that fixes this particular issue with AI harvesters getting in a loop.

That said, the AI could probably benefit from some extra smarts such as taking the enemy location into account when it's deciding what to do with harvesters. (As far as I'm understanding from the code that implements the previous behaviour, the AI just seeks out the next nearest ore and would therefore happily beeline into the enemy base if it happened to be closest)

**Comment by pchote** [comment]
> The radius restriction limit was mostly there for performance, not gameplay.

It was originally introduced (back in #2241, then made configurable #2266) for gameplay reasons.  Performance only became a serious factor much later.

**Comment by Mailaender** [comment]
Performance was a main issue with these improvements from the very beginning although I agree that this radius serves the two purposes in practice. To be fair the harvester resource search also had a check for enemy weapon ranges at that time to prevent it from running into the enemy lines. It was ripped out in https://github.com/OpenRA/OpenRA/pull/6986, because it was expensive and didn't work reliably. There should be a return of the hostile territory checks to fix this problem the originals were always criticized for. Hard-coded range restrictions won't automatically make them smarter.

**Comment by reaperrr** [comment]
Regardless of how we solve the general issue, I think we should increase the default radius a little anyway, because I just came across a shipping map where 24 cells was not even enough to reach the closest ore field.

**Comment by reaperrr** [comment]
Filed #9257 which should help humans and bot-less AIs.

**Comment by UberWaffe** [comment]
Specifically with regards to the AI part, I think the concepts of Points-Of-Interest (POI) could be beneficial here.
A POI would consist of:Center Position, Radius, and Descriptive Tags.
Center Position: Position of the center of the POI.
Radius: Range that defines how 'large' a POI is.
Descriptive Tags: List of predefined tags that can be assigned to a POI, depending on what it is for. (Example: Resource field; Enemy base; Tech structure; Large; Medium; Small; Tiny; etc.)

If an AI can be made capable of dynamically marking POI for itself, then logic could be added to (during the first few minutes of a game) scan the map and slap down some POI for resource fields.

Then instead of making each individual harvester handle scanning for far-away ore patches, a harvester is only concerned with mining out an immediate area near the position.

Ordering harvesters about between resource fields becomes a task of the AI (similar to how a player also would manage his harvesters). If a harvester is idle (cannot find nearby resources by itself), the AI tries to send it to a POI resource field, taking things into account such as harvesters already there, enemy proximity, field size, distance, etc.

**Comment by Mailaender** [comment]
I filed https://github.com/OpenRA/OpenRA/issues/9256 to solve this in the short term which brings back the status quo (AI harvesters are a bit more omniscient) with optimizations (the dual path finder becomes a less frequent path) and cleanups (no more bot exclusive code sitting in the Harvester class).
