### ISSUE TITLE
Fix first sequence frame of animations not showing when Tick is 40 or lower

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#9243]
As mentioned in #7483:

> This is a high-level design flaw rather than a bug (...).
> The problem is that traits like WithMuzzleFlash unconditionally call Animation.Tick from their own tick method, and this gets called once before the first render frame.
> The way to fix that will be to add if (!firstTick) checks, which will require some additional state tracking in some cases.

**Comment by reaperrr** [comment]
@pchote: Could you give an example how exactly a fix would have to look like, or maybe fix one of the affected traits? I wouldn't mind dealing with the rest as far as I can, but the above explanation isn't enough for me to fully grasp what needs to be done here.

**Comment by RoosterDragon** [comment]
If an animation is *always* ticked unconditionally before rendering, a better fix be to start the animations *before* the first frame so that the tick brings them to the first frame.

I believe the would entail setting `frame` initially to `CurrentSequence.Length` as needed inside `Animation.cs`.

You would have to ensure Tick is always called before trying to render though, or the last frame would be displayed before looping around again.

**Comment by Mailaender** [comment]
Can you check if https://github.com/OpenRA/OpenRA/pull/9900 solves it? I don't know how to reproduce this.

**Comment by reaperrr** [comment]
The easiest way to reproduce it is to set `Tick: 40` (or remove `Tick:`) for non-looping, 1-frame sequences (good example: d2k muzzle flashes).

And yes, according to a first preliminary test #9900 seems to solve it.

**Comment by reaperrr** [comment]
@pchote: Closing this as solved by #17851, so you can claim the bounty.
