### ISSUE TITLE
Don't treat trees like regular actors

### ISSUE THREAD

**Issue by Aaron-Lloyd** [OpenRA/OpenRA#9244]
So it's pretty well known that maps with a very large number of trees (or any other type of actor of course) tend to introduce quite a bit of lag to games. But because trees are indestructible and unmoving, is there any way that trees could be treated more like terrain elements than actors in order to avoid the lag that they introduce?

Thanks.

**Comment by penev92** [comment]
Hi. Everything that is physically present in the world (and even some things that aren't) are actors. It's how the engine is set up from the foundations and that won't change.
But do you have any evidence of this, because this is the first time I hear the idea that trees can cause lag?
Trees don't actually do anything other than sit around, so I find that quite odd.

**Comment by Aaron-Lloyd** [comment]
You can try this map here. It lags in singleplayer too quite a bit, but is extremely noticeable in multiplayer from my testing.

http://resource.openra.net/maps/4414

About 4780 actors in total FYI.

**Comment by Aaron-Lloyd** [comment]
Also, if I recall correctly, Materia's had to reduce tree numbers to fix some lag issues on some of his maps.

**Comment by pchote** [comment]
We will at some point implement (visual only - they wont be cleared) forest fires, so they will need to stay as actors.

**Comment by RoosterDragon** [comment]
The sheer number of trees stresses some of the slower parts of the engine:
- Trees are frozen under fog. This means that they all have to be constantly tracked to see if they're within the sight range of the player. Each player has a different view of the map, so this gets slower just by adding more players. 
- The radar needs to constantly track every actor which should be showing up on it.
- The number of actors make our sync checks slow - because there's more stuff to check to make sure it's all in sync.

Some of my immediate musings to improve each of these are:
- For permanent and unchanging features of the map - we should avoid making them freezeable somehow - if they can't possibly change when moving it or out of the sight of the player then we can avoid the checks to see if they're in range.
- There are probably some things we can do to improve the speed of the radar generally.
- If trees weren't freezeable that would make sync checks a bit faster since we wouldn't need to check their frozen state was in sync.

**Comment by LavenderMoon** [comment]
Maybe we should make a class for objects that there are a lot of that don't hugely contribute to the gameplay and thus can have extremely reduced functionality, but can easily be replaced with a proper actor when the needs arises (TerrainOverlay or similar). All you'd need to broadcast about them would be their creation and their destruction. Perhaps we could implement some sort of caching system for the radar that initially generates the overlay for all objects of that class and removes them when they're destroyed or adds them when they're created. Does any of this seem like a workable idea?

**Comment by pchote** [comment]
FrozenUnderFog was removed from trees quite a while ago now, so closing.
