### ISSUE TITLE
Tiered pathing

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#9315]
An alternative (or maybe complementary) solution to #3241.

Divide the map into a coarse-grained grid of cell block nodes and only switch to finer-grained pathing once close enough to the target cell(s).

**Comment by pchote** [comment]
Are you sure this isn't a duplicate?  I've been talking about this a lot over the years, so we should have a ticket.

**Comment by reaperrr** [comment]
It must at least be well-hidden, I only found the group pathing ticket.

**Comment by LavenderMoon** [comment]
Maybe divide the map into polygons (keep a representation for every movement type) and A* through those, caching the two best paths per start-poly/end-poly combo, and noting if moving from one to the other is impossible (for example, if you're trying to send a tank from mainland to an island only accessible by boat, or try to send a ship on land). I've also been considering maintaining a polygonal representation of the map for a different reason: using raytraces to pathfind instead of A*. Of course, that's a bit newer territory than traditional node-based pathfinding algorithms, but from my understanding, it should scale a bit better on larger maps, assuming it isn't constantly running into obstacles. Still haven't put together a testing suite so I can see how workable these ideas are.

**Comment by UberWaffe** [comment]
Should also close #2309 if that is still truly open.

**Comment by pchote** [comment]
I found https://webdocs.cs.ualberta.ca/~mmueller/ps/hpastar.pdf in my bookmarks, which provides a useful review of the area and specific details on one type of implementation.

**Comment by pchote** [comment]
@reaperrr you have a significant bounty on this one too.

**Comment by penev92** [comment]
Implemented in #19591
