### ISSUE TITLE
the ant faction

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/OpenRA#9316]
Hey,
the goal of this issue it to collect information about the ants.
I'm sure you all know the ant easteregg from the original.
I was wondering how much work would it be to create a little ant faction from the assets.
So I made a little research:

As much as I know there are these files in openra:
- ant.shp
- anticon.shp  (Giant Ant)
- antbite.aud
- antdie.aud
- hill01.tem
- lar1.shp
- lar2.shp
- quee.shp

Future more I found these 3 icons while digging in some maps:
- ant1icon.shp (Gigant Ant)
- ant2icon.shp (Fire Ant)
- ant3icon.shp (Warrior Ant)

and some ant information:
http://ra.afraid.org/html/ra/a_csgawt.html

because we only have 1 ant.shp I guess the ants got colored by coding in the original game. Somebody said to me that the fire ants just used the red of soviets.

If you imagine 2 player using an ant faction this simple recoloring might not work. I Suggest the eyes of the ants should be the player color and the rest should give information about the kind of ant. I Don't know if that is possible. and this might also require some new ant.shps.

Anyway here is the big idea:
- Create a mobile construction ant queen by modifying the queen asset that can deploy to an anthill (Maybe unable to undeploy) . Yes that's not easy, and we might need a 3d approache here. Any 3dsmax artist volunteers?
- The queen assest has tiny wings, so she might can fly?
- Create some very basic ant buildings: Anthill (6cell),  SmallAntHill(4cell barraks&refinery), Anthole (1cell powerplant)
- Giant ants should take the roll as harvesters and also as an early attack uni, build able only at the 6cell hill
- Giant ants can unload the ore at the 6cell and 4cell anthill holes
- The ant hole building could be something like an air condition hole and give few power, that you need to build a lot of them. (1cell building). Maybe adding some little building range to it to get them spread out like crazy basewalk.
- The 4cell ant hill can produce fire ants, warriors and queens
- Ants need something to counters air, maybe a fourth flying ant unit that's like a longbow, 
  or only queens can be used as anti air. not yet sure...
- Buildings will need some building in Progress Animations this is where the larvae could get used
- I thought about using larvae as resources or like zerg larvae (but I'm against that)
- I also don't like that the queen used the tesla zap.

Yeah, something like that.

concept of a 4Cell: Ant hill  
![screenshot 2015-09-05 01 33 36](https://cloud.githubusercontent.com/assets/5147014/9806918/b2288510-584b-11e5-955c-c39ca71b6f6c.png)

btw: if you have any other ant stuff. drop it here.
##

**Comment by r34ch** [comment]
Not really a fan of an MP ant faction per se, but if someone made a **quality** mini campaign to play as the ants I would _much_ prefer that.

**1) A new world**
Escape the soviet a-bomb test range as a lone giant ant. Dodge nukes, soviet infantry and tanks. 

The mission name is a reference to a quote in 'Them!';
_"Nobody knows, Robert. When Man entered the atomic age, he opened a door into a new world. What we'll eventually find in that new world, nobody can predict."_
http://www.imdb.com/title/tt0047573/trivia?tab=qt&ref_=tt_trv_qu

**2) Polymorphism** (or Morphology - sounds a little better)
Eat _lots_ of civilians to evolve the ant; scout -> warrior -> queen. Soviets will try to protect the villages at first to slow you down. Then they will simply destroy them with infantry and yaks (much like Soviet mission 1). As you evolve, soviets throw armour at you.

The civilians as 'economy' is reference to the PSX cheat 'Soylent Green' where ore is turned into civilians. This would be an extension of the current 'bounty' system already in place in oRA for killing units - in this case higher income per unit and both hostile and neutral units.
http://uk.ign.com/cheats/games/command-and-conquer-red-alert-retaliation-ps-3785
Mission name a reference to OOP coding and the entry in Wikipedia
https://en.wikipedia.org/wiki/Ant#Polymorphism

**3) God save the Queen**
Unable to find shelter underground, the queen ant has laid larvae above ground in a valley. Some have hatched already. You must fend off soviet ground and later air attacks for 30 minutes. You will need economy to 'produce' more ants from the hills. There is a small village and town nearby. Also a number of soviet bases including an air base. Ants don’t have AA so will have to attack this base or loose. Rivers and bridges give access to this economy (much like ant mission 2). Soviets have access to the scientist which will attack the hills (not ants) and 'gas' them out rendering them unusable.

Mission name is a reference to the fact that the ant missions in the PSX game are located in England on the mission selection map (even though the final ant missions are not located here...)

**3) Retaliation (or CounterStrike)**
Hills have been strategically placed around the map to create forces to pincer the Soviet Base. Gain economy by attacking small villages. Cut off soviet reinforcements by taking out the bridges. Cut off soviet economy by attacking the ore fields and oil derricks. Finally assault the heavily defended soviet base (the one seen in the second last ant mission). Soviets will have access to the chem trooper which is a ranged and more durable version of the scientist. Extremely effective against ants as well as hills.

Mission name is reference to the PSX expansion which rolled Aftermath and Counterstrike into one)

**4) The colony **
Clear out the humans from the heavily defended underground soviet research facility. You get a strike force of ants and reinforcements at different times and access points as you clear them. The first wave soviets will simply throw a meatshield at you (for the lolz). Rifle infantry, dogs, flamers - even scientists. Nuclear reactors which kill human infantry and damage vehicles (oRA damage tiles) will heal ants to add some strategy.

As you continue you see the 'mad experiments' the soviets were developing (a reference to that mission with the chronosphere causing units to have crazy weapons) Chem troopers will exist en mass and the chem tank will see action (TD flame tank firing chem spray). At the end soviets will have modified flame towers to fire chem spray instead of fire. At this point you keep getting loads of reinforcements but soviets will throw _everything_ at you -  Demo trucks, MAD tanks, Mammoths, heavies etc etc.

When you get to the end you will see a large underground room will nothing but gems and a space in the middle. This is a reference to the community ToX maps (tons of gems, tons of units spammed). In the middle of the room is a clearing for the Queen ant to get to to complete the mission - and set up the canon for the original ant missions. 

Reference to the Cylon 'homeworld' in Battlestar Galactica


**Ant units**

Scout
Warrior
Fire
Tesla (dark blue - already fan made somewhere)
Chem (dark green)
Queen

**Comment by TheRaffy** [comment]
Creating the assets would improve these kinda singleplayer missions, too. Very good ideas and referenes btw. But in my opinion I would prefer to have some MP experience. I'm sure there are ways to ensure that they are not disturbing the other factions, or the game experience. 
Due to the limitations of the units & buildings they should not be a threat to the deep metagameplay of the other factions in any way.

**Comment by LavenderMoon** [comment]
This sounds like something more suited for a third-party mod. It would be cool to have a mod with an Ants faction. Maybe the multiplayer could be Ants vs Survivors, where the survivors all have low-level Allied and Soviet tech.

**Comment by TheRaffy** [comment]
Created an anthole with a make animation:
![antholemake](https://cloud.githubusercontent.com/assets/5147014/9864231/af5fb5b6-5b47-11e5-839c-7c539b4888a5.gif)

**Comment by TheRaffy** [comment]
So I made this anthole making animation:
![antholemake-0000](https://cloud.githubusercontent.com/assets/5147014/9893171/3651fc54-5c16-11e5-85da-377ae582a42c.png)
![antholemake-0001](https://cloud.githubusercontent.com/assets/5147014/9893173/36564f8e-5c16-11e5-9aa4-133fbc46385d.png)
![antholemake-0002](https://cloud.githubusercontent.com/assets/5147014/9893172/365573de-5c16-11e5-8a66-cda76bbe02b4.png)
![antholemake-0003](https://cloud.githubusercontent.com/assets/5147014/9893174/3656f0a6-5c16-11e5-8274-3dc1c1e90e03.png)
![antholemake-0004](https://cloud.githubusercontent.com/assets/5147014/9893175/365834ca-5c16-11e5-9a0f-4dfded8d837a.png)
![antholemake-0005](https://cloud.githubusercontent.com/assets/5147014/9893176/365683f0-5c16-11e5-9d0d-d7ccc64eadad.png)
![antholemake-0006](https://cloud.githubusercontent.com/assets/5147014/9893177/366927d0-5c16-11e5-87c7-ede98be182f4.png)
![antholemake-0007](https://cloud.githubusercontent.com/assets/5147014/9893178/3669fcc8-5c16-11e5-8f21-81c8189a74a2.png)

And here's the normal  building with a damanged frame:
![anthole-0001](https://cloud.githubusercontent.com/assets/5147014/9893182/46bcb70a-5c16-11e5-9519-c896134d1c5a.png)
![anthole-0000](https://cloud.githubusercontent.com/assets/5147014/9893183/46bd589a-5c16-11e5-907a-833d5f0d3aca.png)

I imported them into the shp buildiner but when I load a shp at openra it chashes due to index is out of range. I don't know why this happens any idea or expereince in builidng shp files?

**Comment by GraionDilach** [comment]
I seen such happening with SHPs starting with an empty frame, deleting that frame usually solved the problem.

**Comment by Zjordy** [comment]
hey im not sure why, maybe you have a link of the map ? have you set sequences of the ant hill (under sequences) ?

**Comment by TheRaffy** [comment]
zjordy  here is the file: https://www.dropbox.com/s/w5k096mfuwaozzp/antholetest.zip?dl=0

**Comment by KAYVAANSHRIKE** [comment]
Hi TheRaffy, I never saw this page before, but I made a PVP ANT map I named it ANT ALERT!

**Comment by TheRaffy** [comment]
any link? can't find it a the http://resource.openra.net page.

**Comment by KAYVAANSHRIKE** [comment]
I play it on http://cncnet.org/  Red Alert CnCNet 5

**Comment by TheRaffy** [comment]
I downloaded the game and found the normal ant maps but not your mentioned map.
Did you create any new ant assets for your map?
What shp files did you use?

**Comment by dariuszsikorski** [comment]
Hi, here's Ant \o/ from RA. Offtopic, a few years ago i loved to play a game called Swarm Assault, it was about capturing a bases and swarming more ants!

https://www.google.pl/search?q=swarm+assault&espv=2&biw=2133&bih=1232&source=lnms&tbm=isch&sa=X&ved=0CAYQ_AUoAWoVChMI3fPB-o_SyAIVBj8aCh2Mtg9j&dpr=0.9

**Comment by Raymond-cnc** [comment]
Thought i should add this here:

http://resource.openra.net/maps/3998
3v9  map, 3 ant faction and 9 human players..the map isn't completely balanced yet but it should be 3 players to 1 ant player.

Humans start as light squads with engineers. Many buildings to capture.
Ants start with barracks which can build units each having different build speeds.
In the map I modified the ant to be 4 build-able units:
They are distinguished by their size as that was the only thing I could figure out how to change visually.

Queen ant: M.a.d. tank type unit which can heal the other ants
Electric ant: Uses similar attack to teals tank
Flying ant: flies like a heli, shoots flame attacks against infantry and missiles against air units.
Regular ant: uses bite attack, these guys are small and easy to get big quantities of.

**Comment by Mailaender** [comment]
See http://www.moddb.com/mods/over-powered-mod/downloads/over-powered-mod-release-003 Closing here as I don't see this become part of the official distribution.

**Comment by KAYVAANSHRIKE** [comment]
@TheRaffy I just used the RA editor. Let me know if you want to play sometime

Sorry for commenting on closed topic, But I couldn't pm TheRaffy.

**Comment by TheRaffy** [comment]
You can find me frequently at the #openra on freenode.
irc://chat.freenode.net/openra
or as player I use the account name "yellow".
