### ISSUE TITLE
Friend System or Chat System idea.

### ISSUE THREAD

**Issue by Zjordy** [OpenRA/OpenRA#9348]
ok heres an idea,  i don't know how hard it is to make it , but It would be cool if there was something like a Friend System, or a Chatbox in the main multiplayer lobby, so you can see who might be online waiting for a game and maybe talk to them :)

**Comment by pchote** [comment]
You're in luck:  The release-after-next will include a chat box window in the main multiplayer lobby!

![globalchat](https://cloud.githubusercontent.com/assets/167819/9873640/08e717f4-5b99-11e5-874c-191f9f167ace.png)

There's nobody in it right now because very few people run the development version that features this.  The UI will be a bit more polished by the time we release it, too.

Closing as fixed :)

**Comment by Zjordy** [comment]
sweet ! amazing ! haha good job !
