### ISSUE TITLE
Attack Move order doesn't work for Tanya in Allies01 (and probably other missions)

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#9383]
You can issue the attack-move order for a group of actors, but tanya will stay at her original location.  She should at least move to the target location, even though these missions have explicitly disabled auto-targeting.

**Comment by Mailaender** [comment]
Since https://github.com/OpenRA/OpenRA/pull/4464 removing the `-AttackMove` trait should solve it, which is already done in allies-01. https://github.com/OpenRA/OpenRA/pull/11636/files#diff-961e747103f87f110db6c6d41b1e9c0dR32

**Comment by pchote** [comment]
No. That pr significantly predates this ticket, and it remains broken on current bleed.

**Comment by abcdefg30** [comment]
The underlying problem here would be that issuing an `AttackMove` order on actors with out that trait doesn't make them resolve a `Move` order?

I think it would be confusing for players when we "fix" this. If I press `a` and send tanya somewhere, I expect she attack moves. But with this she would just normally move (and possibly die), wouldn't she?

**Comment by pchote** [comment]
It is even more confusing to players (check the ticket history, we have had multiple tickets on it) to have units stay behind when you attack-move a group of units (in this case tanya plus the rest of the starting forces).
