### ISSUE TITLE
Mouse clicks don't work for new release 

### ISSUE THREAD

**Issue by marto1** [OpenRA/OpenRA#9423]
I just changed the release from 2013/05/14 to 2015/09/19 and mouse clicks don't seem to work.
Here is a screen capture of the issue: https://drive.google.com/file/d/0Byqqq9xx8V45RkVnTTU4WXVYN1E/view?usp=sharing
I also built it from source with the latest changes, but there are still no clicks detected. 
The OS is Xubuntu 12.10.

**Comment by pchote** [comment]
At some point between the 2013 and 2015 releases we switched from using SDL 1.2 to the newer SDL 2.0 series.  We haven't seen any similar bug reports, so I suspect that the problem is with the SDL2 packages in your OS.  Unfortunately the 12.10 releases of ubuntu are no longer supported, so you may have to upgrade to a newer OS in order to solve this.

**Comment by marto1** [comment]
Hm..ok I'll try that.
When I run it it says it's using SDL 2.0 tho and I have it installed.

> Platform is Linux
> Using SDL 2 with OpenGL renderer
> Desktop resolution: 1366x768
> Using resolution: 800x600
> Detected OpenGL version: 3.0
> Using OpenAL sound engine
> Using default device
> Available mods:
> 	cnc: Tiberian Dawn (release-20150919)
> 	d2k: Dune 2000 (release-20150919)
> 	modchooser: Mod Chooser (release-20150919)
> 	ra: Red Alert (release-20150919)
> Loading mod: d2k

**Comment by marto1** [comment]
Ok, made a virtualbox with 14.04, it works now. Thank you.
