### ISSUE TITLE
D2k worms are too aggressive

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#9446]
In the original, worms were neither as fast nor as aggressive. If I remember correctly, they also ignored actors on rock.

I think they should move slower, have a lower scan radius and ignore actors on rock.

**Comment by penev92** [comment]
They ignore actors on rock now as well. They are also slow (and the currently ongoing D2k rebalancing will make sure their speed is OK). But yes, they were really retarded in the original.
You can drive over them and they'd ignore you just to go to the other side of the map and do nothing.

**Comment by MustaphaTR** [comment]
In orginal D2K, Worms was tring to reach place to where unit was before re-scan any other target even unit leaves that place. This was making them easy to avoid.

**Comment by UberWaffe** [comment]
I don't the worms are overly aggressive for mid and late games, but I do think that getting harvesters chowed left and right early on is a bit much.
Original D2K they were barely even an annoyance. 
What I would suggest is that worms should start out lazy / slow, but become more aggressive / faster over the course of a few minutes of gameplay. So that after (say 5 minutes?) they are functioning at full seething fury.

**Comment by penev92** [comment]
If we go that way we can just add a start delay to them like we added to `CrateSpawner` and just have no worms before minute 5-6-7-8. That would give people more than enough time to build their economy.

**Comment by pchote** [comment]
Worms are very much not too agressive now.  Can we give them a buff now?

**Comment by WolfGaming** [comment]
it would be fun to make them more aggressive by counting the overall noise on the map. (my 2 cents)

**Comment by penev92** [comment]
I don't think this is an issue any more.
