### ISSUE TITLE
Remove "Hopes Anchor" from Official Maps 

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#9553]
a lot of new players choose this map and have no idea how to play this map ... theres no description anywhere about the actually "rules" on it ... and it looks like a normal map to them ... 

but the "tactical win" in 2 minutes makes this map a easy noob-trap 

we should remove this particular map from the Official Maps

**Comment by obrakmann** [comment]
:-1: I'd hate to see this map removed. It's one of the most visually pleasing maps we ship.

If the problem is that new players aren't aware of what the game mode a map is for, the solution isn't to rip out that game mode, but to make the information more obvious. Could be part of the lobby re-write, that's currently happening.

**Comment by MicroJOo** [comment]
this issue isnt about the visually appearance of the map ... its about a gameplay-problem ...
its a really old map , and the rules on it doesnt make it enjoyable at all .. with a  2-minute time-limit for the tactical win ... and we have to deal with all sorts of problems .. the lack of naval balance for example ... 

you could instead of "ripping" it out ... just move it to "custom maps" and let people download it from our ressource center ... 

and in your specific case , @obrakmann ... because the map is oh such a visually firework of beautifulness ... could just remove the rules and make it a conquest map

**Comment by Micr0Bit** [comment]
#9553

**Comment by Micr0Bit** [comment]
closing this again , i asked for removing/changing ... nobody seem to be interested
