### ISSUE TITLE
Ore trucks in refinery and hijackers

### ISSUE THREAD

**Issue by Szunti** [OpenRA/OpenRA#9560]
What are these hijackers doing?

I know they are slow, can be crushed much more easily than normal inf, but the first one was there, wasn't it?

![openra_hijackers](https://cloud.githubusercontent.com/assets/1443881/10316437/8858e3d8-6c5f-11e5-902b-9d6608e0a1c1.gif)
##

**Comment by MicroJOo** [comment]
theres actually a smiliar problem with the spy ... when he is trying to enter a building ... sometimes he just bounces back ... although he should have access ... 

@Mailaender : this is probably a bug

**Comment by Mailaender** [comment]
This seems to be multiple things. The ore truck bug is probably a duplicate of https://github.com/OpenRA/OpenRA/issues/9197. The hijacker not entering correctly is another one and crushable hijackers is a balancing decision we should rethink as well, because both the evading and the crushing make hijacking impossible and glitchy.

**Comment by Szunti** [comment]
#15661 probably fixed this too.
