### ISSUE TITLE
Make maps with creep.active to act like a normal bot

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#9570]
It's boring to play against passive creep, and too advanced to make Lua stuff
This would let mappers build a lot of cool maps, and give units/buildings to the AI to make it hard to play against them.

Examples:
*AI with only nukes, and you have to move quickly and have multiple bases
*AI with only sea, but start with a lot of units
*AI start with many units and mcv
*fight between AI's and then winner vs player
etc..

The issues is also that many servers do not allow bots.. This way we can still play with bots and humans there...

**Comment by pchote** [comment]
I see no point in allowing servers to disable bots if we then also add an option for maps to ignore servers ignoring bots.  That is silly.

I personally think we should instead remove the disable bots server command - this is a legacy hack added back in the days before RA had a skirmish option, specifically to prevent people from hogging the (only) two or three dedicated servers with 1vbot games.  There is no reason to keep it in modern versions of OpenRA.

**Comment by penev92** [comment]
There are plenty of servers these days, and anyone can play skirmish without a server, so that might be a good idea.

**Comment by MicroJOo** [comment]
@pchote , @penev92 : i am not sure about his ... 

theres still times , where we dont have enough dedicated servers around ... and its just really annoying when noobs use the dedicated servers to play "singleplayer against bots" ... "instead" of  just playing actually in singleplayer and not on our servers ...

and some people spend money on the dedicated servers ... so you dont want them to occupie a server  and play against 10 bots ... kicks every other player 

our hetzner servers in the past  "always" disabled bots ... and these days the more popular "baxxster" servers also disable them ... for a good reason

**Comment by pchote** [comment]
> you dont want anyone to occupie a server and play against 10 bots ... kicks every other player 

Are people still actually doing this in recent (newer than three years ago) versions of OpenRA?

**Comment by MicroJOo** [comment]
yes , the "new" players

**Comment by obrakmann** [comment]
Perhaps it would sense to turn the no bots flag into a 'no single player' flag, which would, if set on the server, prevent starting the game if there is just one human player in the lobby.

**Comment by pchote** [comment]
Sounds good to me.  I don't think its fair to discriminate against people who want to comp-stomp with their friends.

**Comment by MicroJOo** [comment]
im fine with that

**Comment by StexoO** [comment]
< offtopic / new issue needed ? >
Maybe the new players just click on Multiplayer to play a multiplayer game and they don't see the Direct IP button ? And maybe opening ports is a bit "hard" or can't be done in some places ?
So OpenRA could have in the main menu something like Online multiplayer, LAN multiplayer and Direct IP buttons, or submenus or anything else (flashing with multiple colors to be seen in the first place :P).
The Direct IP window could also show (after asking openra.net or any other website) what are the current LAN and Web IPs of this OpenRA client.
It's annoying to be kicked by new players looking for local games on public servers but it's also annoying for a new player to be kicked from the first server he connects to in order to play his first OpenRA game of his life. :P "meh I'll uninstall OpenRA"
The OpenRA installer could also ask the player to open ports (don't know if it's already the case, Direct IP shows 1234 in the port textbox) so the players can instantly and easily play together in a LAN game or a Direct IP game.
OpenRA could also include some sort of 'Search LAN servers' feature so wherever you are (home, campus, airport, stadium, Moon, ...) you can find a local server and play very easily without blocking public servers and without knowing anything about IPs, ports and things like that.
< /offtopic / new issue needed ? >

@kyrreso 
> *AI with only nukes, and you have to move quickly and have multiple bases
> *AI with only sea, but start with a lot of units
> *AI start with many units and mcv

That would be awesome to have a Customize AI button with checkboxes like Don't build buildings, Only naval units, Expand base everywhere, Allow multiple superweapons, Agressiveness [Turtle, Normal, Rush], Unlimited money and so on, so no need to create (and maintain) AIs like Nuke AI, MCV AI, Wire fence AI, ...

**Comment by pchote** [comment]
> The OpenRA installer could also ask the player to open ports (don't know if it's already the case, Direct IP shows 1234 in the port textbox) so the players can instantly and easily play together in a LAN game or a Direct IP game.

The game will already do this if you have a supported UPNP enabled router.

> OpenRA could also include some sort of 'Search LAN servers' feature

This already has a ticket: #8906

**Comment by GraionDilach** [comment]
The problem is that the UPNP issue reported last week maybe crashes the host if it tries to use UPNP.

**Comment by pchote** [comment]
Yeah, I carefully chose my words when I said "a supported UPNP enabled router".  Our UPNP library is a piece of shit, but it works well for things that don't crash or otherwise confuse it.

**Comment by MicroJOo** [comment]
btw. i almost forgot ... we might need the option "disable bots" for "ranked servers" ...

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/10670 added the option to disallow single-player games, but not multi-player vs. AI battles.

**Comment by kyrreso** [comment]
Can this be opened? The main meaning of the issues is to set AI-players in the game, not creeps(dumb AI)..
Or make creep.active...

**Comment by abcdefg30** [comment]
We have #10589 open for that, I think.

**Comment by kyrreso** [comment]
That is only for missions as I read it....

**Comment by Narg6** [comment]
Yeah, allowing HackyAI in custom missions would be a great thing !!!

**Comment by abcdefg30** [comment]
#10916 added basic support for this.
