### ISSUE TITLE
Missile behaviour regression

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#9645]
![screen shot 2015-10-16 at 08 13 27](https://cloud.githubusercontent.com/assets/167819/10535835/117773e8-73de-11e5-979d-e6ae5d7a6aec.png)

Missiles from the TD SAM site will no longer hit aircraft outside more than ~75% of its nominal max range.  I'm not sure whether this is caused by an effective decrease in the missile speed (which will have even wider balance implications), a specific regression to the lifetime check, or some other factor.

I expect this will affect other missile types from the other mods too.

**Comment by matija-hustic** [comment]
It's en edge case for the launch angle & speed determination logic - since the missile is spawned at height zero and the lookahead gives zero as maximum height at zero distance ahead, the missile thinks it is at the edge of a cliff. This is an invalid condition in and of itself because it should explode the missile straight away, but the logic tries to handle it by setting the launch speed to minimum and launch angle to a maximum. Setting the speed to  minimum however makes the missile explode before it reaches the heli.

There's a new PR in the pipes that'll have the logic a lot cleaner and simpler which should avoid things lilke this.

Right now there's a simple fix of not considering the missile launched with zero height and cliff distance zero ahead as actually having a cliff in front of it. Another one would be setting the launch height of the SAM missile to at least 1 (since with the new logic any missile that finds itself with height equal to zero at any moment, obviously apart from the instant it is launched, should explode). But I'll file a PR with the first fix and then see about the best solution in the follow up PR to #8717.

**Comment by pchote** [comment]
Note that this situation (zero launch height and zero cliff height) is the default for all of our shipping mods, since they don't use height. The missile code *must* treat it properly, and not as an edge case to be managed.

**Comment by matija-hustic** [comment]
Hm... Well the CnC rocket soldier, mobile SAM, recon bike all launch from nonzero heights...

But OK, I'll keep in mind that zero launch heights should be considered valid, too.

**Comment by GraionDilach** [comment]
Could it be the firing offset itself which gives the others a height offset? In that case the fix might be to reset that on the SAM since it's a popup turret afterall.

**Comment by penev92** [comment]
Yes, but someone might want to fire missiles from the ground (from underground?), so that still shouldn't be invalod. That said, you can always put an offset of 1 and still have it look like it's being fired from underground.

**Comment by matija-hustic** [comment]
@GraionDilach, these actors (rocket soldier, mobile SAM, recon bike) all have their `position.Z == 0`. I was, as you said, in fact referring to the firing offset (under the `Armament` trait as far as I can see) when talking about the launch height. SAM has the firing offset zero while most others don't.

I think I'll just revert the impact condition to missile's height being strictly negative and to let it survive zero height.

**Comment by r34ch** [comment]
Perhaps related; on bleed in RA, RS and Mig rockets travel a few pixels before detonating.

**Comment by reaperrr** [comment]
Fixed by #9646.
