### ISSUE TITLE
d2k aircraft speeds are far too slow.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#9680]
I suspect the values defined in the original d2k were before the acceleration bonuses were applied.  As they are in OpenRA it feels like carryalls are actually slower than letting harvesters drive themselves, and the starport deliveries slow to the point that I first though somebody had broken the production traits.

**Comment by reaperrr** [comment]
> I suspect the values defined in the original d2k were before the acceleration bonuses were applied.

I don't think so. Aircraft in D2k were not particularly fast. It *could* be that our aircraft-specific conversion formula is at fault (for D2k it's effectively original speed [ / 64] * 7, whereas the formula for ground units gives original speed [ / 64] * 10.67), but I don't know how much of a difference there is between our aircraft speed and our ground unit speed. I assume there's a reason why the formulas differ like that.

>  As they are in OpenRA it feels like carryalls are actually slower than letting harvesters drive themselves

That applied to the original as well, at least for shorter distances. It was actually worse, because they were slower at picking up and dropping them. Carryalls were only really beneficial over longer distances (when the pick/drop overhead had less of an effect) or when the direct path was blocked by cliffs or other obstacles (D2k pathfinding was more performant, but also dumber than ours). And for partial protection from worms and enemies.

> and the starport deliveries slow to the point that I first though somebody had broken the production traits.

The real problem here is that they should fly in from the closest map border cell, like they did in the original. The TD-style approach works poorly, especially on large maps.


Anyway, filed #9702.

**Comment by pchote** [comment]
Fixed by #9702.
