### ISSUE TITLE
Chrono vortex

### ISSUE THREAD

**Issue by Dasha-98** [OpenRA/OpenRA#9778]
Hi there,

In know this issue has been discussed and closed :
https://github.com/OpenRA/OpenRA/issues/6615#issuecomment-151457459

But I juste want to add an element.

From what I read, the thing preventing the implementation of this Vortex is the complexity of the rendering.

However, as I stated it, the PS1 version of the Vortex is far more simpler. It appears as a kind of black cloud throwing Tesla thunders. Maybe because It was tough to render on the PS1 ?

If it can help, I'd do a capture of this to show you.

Also for the PS1, the Vortex used to disappear after a random time. And not always attack units.

For the PC version it seems It always attack and never disappears.

Both PS1 and PC version may appear randomnly around the map after chronoshift use.

As far as I remember PS1 version is less powerful.

So maybe the vortex feature can be created based on the PS1 version instead of the PC version ?

Regards.

**Comment by MicroJOo** [comment]
why do you need to open another ticket for that ? when the first one got closed ?

**Comment by j2k15** [comment]
Hi,

Here're some images from the PSX Red Alert Retaliation game showing a Vortex.

I saw that some utilities exist to extract files from RA PSX games. As I've the game, I can also help to extract any required file if needed.

![capture d ecran 2015-10-27 a 19 31 16](https://cloud.githubusercontent.com/assets/15321563/10768646/750adb5e-7ce2-11e5-9ebc-54d2f22d4315.png)
![capture d ecran 2015-10-27 a 19 31 21](https://cloud.githubusercontent.com/assets/15321563/10768645/7509b22e-7ce2-11e5-9da3-01908154d5e9.png)
![capture d ecran 2015-10-27 a 19 31 33](https://cloud.githubusercontent.com/assets/15321563/10768647/750d1360-7ce2-11e5-8118-fcde58a868ec.png)


.

**Comment by huwpascoe** [comment]
The full vortex effect could be done relatively easily with a fragment shader if the world were rendered to a framebuffer

**Comment by pchote** [comment]
> The full vortex effect could be done relatively easily with a fragment shader if the world were rendered to a framebuffer

This is the long-term plan, indeed.  That also fixes a bunch of issues with other effects (desaturate / nuke, global lighting)

**Comment by j2k15** [comment]
After some testing on the PS1 game, I confirm that :

The Vortex does not always attack units. Even the one touching it.
The Vortex can disappear.
The Vortex is less powerful than the PC version.

**Comment by j2k15** [comment]
Hi,

Since in OpenRA Chronoshift has been updated, I thought about what could be the requirements for the Chrono Vortex.

Here're adaptations I have in mind compared to the original Vortex.

1) Loading time is lower than in original game, odds to have a Vortex appearing shall be reduced accordingly.
2) Several units can be Chronoshifted. We could use this parameter to calculate Vortex life time. E.g. if 3 units are chronoshited, Vortex would disappear after 3 min, or after having killed / destroyed 3 units / buildings.

Of course some general behaviour of a Vortex can still apply like :
- It spawns at a random location ;
- It slowly and randomly moves ;
- Only 1 Vortex at the same moment on the map (or more crazy :if a 2nd has to appear when 1 is already in game, both are vanished instantly).
- ...

For Chronotank,

- The Chronoshift weapon has smaller range and a lower loading time. Lower loading time could lead to a lower chance to have a Vortex.
- As of duration here above maximum duration would be 1 min. or 1 kill.
- As Chronoshift from Chronotank has a lower range, we could make it less powerful : e.g. cannot attack structures...

I really think it could be a nice stuff to adapt the Vortex to the new rules introduced by OpenRA.

**Comment by j2k15** [comment]
About first point, by loading time I mean Chronosphere loading time...

**Comment by r34ch** [comment]
If it is implemented in MP I think it shouldn't attack anything. RNG damage like that flat out sucks imho.

But I guess that's fairly boring.

If it does do 'something' it would be far more interesting to have it permanently chronoshift any vehicle it comes across to a random point on the map (reusing the chronocrate logic from SS if/when implemented) up to a low maximum (1~3 units) before it dissipates - if it doesn't dissipate before then. 

Apart from making slightly more sense from an in-universe pov, there is a fairly good chance you can simply move the unit back. At worst, you get a laugh seeing an ore truck stuck on an island or on top of a ridge.

This ability is already somewhat hinted at the very bottom of http://cnc.wikia.com/wiki/Chrono_vortex#In-game

The RNG issue with that is of course demo trucks and infantry in transports but you could allow those units to be transported ok from a vortex. This is turn would be a nod to in-universe canon where by the next world war, such issues have been ironed out by the new chronosphere.

http://cnc.wikia.com/wiki/Chronosphere_(Red_Alert_2)#In-game
http://cnc.wikia.com/wiki/Demolition_truck_(Red_Alert_2)#Usage

The implied link would be that scientists studied chrono vortexes after the RA1 world war and how demo trucks and transports with passengers weren't affected.

Might lead to some interesting games of people deliberately driving such units (inc MCVs) into a vortex.

**Comment by MicroJOo** [comment]
i think blancing that thing would be the smallest problem

**Comment by huwpascoe** [comment]
I think it would be neat for the vortex to always appear when units are both chronoshifted and ion curtained at the same time. It would be an interesting predictable side effect strategy wise and make some sort of sense in that you're messing with two unstable phenomena that were never intended to be combined.

* On chronshifting units, these units would have an extra flag along with their return to origin countdown.
* If any of these units are curtained any point before returning (should probably add the deployed conyard to that check too) then the flag is set.
* When the chrono-return happens, if the flag is set then spawn a vortex at the point of origin.

**Comment by 3Lucian** [comment]
what about if the vortex appeared at the location where the units we're chronoshifted from - almost like the physics of chronoshifting has a direct effect on the physical space the units are shifted from, and only lasted as long as the chronoshift. its behavior could be that it does damage to anything in the general area it was chronoshifted from, maybe 8 cell radius, but was unlikely to take out anything with more health than a powerplant. infantry should be killed(sucked into it), as should planes and helis, tanks should live if they have more armor than a flak or a ranger. However, germany's one should maybe do more damage or move faster, or have a larger range, because of the larger chrono shift.

this would have an interesting effect on the strategy of chronoshifting, it would mean when surrounded by the enemy, chronoshifting your unit away would be advantageous, as the vortex would damage your enemy, but when chronoshifting from your own base, you'd have to be careful not to damage your own stuff.

Re-chronoing already chrono'd units would create another vortex. and would mean that an attempted nuke snipe with chrono'd units close to the silo may be chrono'd away, but the vortex has the possibility of damaging the target anyway.

**Comment by KOYK** [comment]
the reason the original red alert had the chrono vortex was to balance the nuke like ability the allied players had. how many times have you seen entire bases popup from no ware behind your base OR inside your base? the answer is countless,not to mention Germany that can teleport an entire army, and what about using chrono to teleport soviet mad tanks in team games? ohh no sir this is game breaking.we need something to counter this. like the original after this X comulatve number a chrono is used by a player,bring the vortex and wreak havoc to that player. add some sound hints to grow in volume and make aware the player that hes close to bring the vortex to his face ehm base i mean. make the vortex to "attack move" to the last known position of the chronosphere  building and fade the vortex away after it reach its destination.

**Comment by pchote** [comment]
Python snippets used to create the animation in #15300:

```python
import numpy as np
from PIL import Image

open_frames = [
    'lut/C9E6E9AF', # HOLE0000.LUT
    'lut/CBE6E9AF', # HOLE0001.LUT
    'lut/CDE6E9AF', # HOLE0002.LUT
    'lut/CFE6E9AF', # HOLE0003.LUT
    'lut/D1E6E9AF', # HOLE0004.LUT
    'lut/D3E6E9AF', # HOLE0005.LUT
    'lut/D5E6E9AF', # HOLE0006.LUT
    'lut/D7E6E9AF', # HOLE0007.LUT
    'lut/D9E6E9AF', # HOLE0008.LUT
    'lut/DBE6E9AF', # HOLE0009.LUT
    'lut/C9E8E9AF', # HOLE0010.LUT
    'lut/CBE8E9AF', # HOLE0011.LUT
    'lut/CDE8E9AF', # HOLE0012.LUT
    'lut/CFE8E9AF', # HOLE0013.LUT
    'lut/D1E8E9AF', # HOLE0014.LUT
    'lut/D3E8E9AF', # HOLE0015.LUT
]

loop_frames = [
    'lut/D5E8E9AF', # HOLE0016.LUT
    'lut/D7E8E9AF', # HOLE0017.LUT
    'lut/D9E8E9AF', # HOLE0018.LUT
    'lut/DBE8E9AF', # HOLE0019.LUT
    'lut/C9EAE9AF', # HOLE0020.LUT
    'lut/CBEAE9AF', # HOLE0021.LUT
    'lut/CDEAE9AF', # HOLE0022.LUT
    'lut/CFEAE9AF', # HOLE0023.LUT
    'lut/D1EAE9AF', # HOLE0024.LUT
    'lut/D3EAE9AF', # HOLE0025.LUT
    'lut/D5EAE9AF', # HOLE0026.LUT
    'lut/D7EAE9AF', # HOLE0027.LUT
    'lut/D9EAE9AF', # HOLE0028.LUT
    'lut/DBEAE9AF', # HOLE0029.LUT
    'lut/C9ECE9AF', # HOLE0030.LUT
    'lut/CBECE9AF', # HOLE0031.LUT
]

close_frames = [
    'lut/CDECE9AF', # HOLE0032.LUT
    'lut/CFECE9AF', # HOLE0033.LUT
    'lut/D1ECE9AF', # HOLE0034.LUT
    'lut/D3ECE9AF', # HOLE0035.LUT
    'lut/D5ECE9AF', # HOLE0036.LUT
    'lut/D7ECE9AF', # HOLE0037.LUT
    'lut/D9ECE9AF', # HOLE0038.LUT
    'lut/DBECE9AF', # HOLE0039.LUT
    'lut/C9EEE9AF', # HOLE0040.LUT
    'lut/CBEEE9AF', # HOLE0041.LUT
    'lut/CDEEE9AF', # HOLE0042.LUT
    'lut/CFEEE9AF', # HOLE0043.LUT
    'lut/D1EEE9AF', # HOLE0044.LUT
    'lut/D3EEE9AF', # HOLE0045.LUT
    'lut/D5EEE9AF', # HOLE0046.LUT
    'lut/D7EEE9AF', # HOLE0047.LUT
]

states = ["fact-0000.png", "fact-0026.png"]
frame = 0

lut_filenames = open_frames + loop_frames + loop_frames + loop_frames + close_frames
total = len(lut_filenames)

for s in states:
    input_image = Image.open(s)
    vtx = np.fromfile('TEMP_VTX.PAL', dtype='uint8').reshape((16, 256))
    pal = im.getpalette()
    input_array = np.array(input_image)

    for f in lut_filenames:
        i = frame % total
        dx = int(4 + 4 * i / total * np.sin(2 * np.pi * 2 * i / total))
        dy = int(4 + 4 * i / total * np.cos(2 * np.pi * 2 * i / total))

        output_array = np.copy(input_array)
        lut = np.fromfile(f, dtype='int8').reshape((64, 64, 3))
        for y in range(64):
            for x in range(64):
                i = lut[y, x, 0]
                j = lut[y, x, 1]
                output_array[y+dy, x+dx] = vtx[lut[y, x, 2], input_array[j+dy, i+dx]]
        output_image = Image.fromarray(output_array)
        output_image.putpalette(pal)
        output_image.save('factvtx {:04d}.png'.format(frame))
        frame += 1
```
The HOLEXXXX.LUT files are in local.mix, but aren't included in the global mix database so xcc mixer doesn't know their proper names.  The TEMP_VTX.PAL is generated at runtime by the original game - start a game and then copy it from the game dir.

**Comment by temprasphere** [comment]
Has anything further happened on this feature

**Comment by Dasha-98** [comment]
> Has anything further happened on this feature

No, as far as I know.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/assets/167819/395c2416-d79a-49c1-b135-58bcd125f9b8



https://github.com/pchote/OpenRA/commits/chrono-vortex-renderer

**Comment by Dasha-98** [comment]
I can see the animation has been created, but I guess it's still need to be considered for an addition in the rules, right ?
