### ISSUE TITLE
Mark Tanya as uncrushable?

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#9792]
I can't tell ya how many times I've had my Tanya crushed by a goddamn ore tuck while trying to go place C4 on a refinery. Lets just say she is smart enough to avoid bring crushed, okay? I mean why the hell are shock troopers uncrushable what makes them so special?

Would also be nice if she was made temporarily invulnerable to FRIENDLY fire when placing C4. A lot of "lol killed ur tanya accidentally XDDD" happening in team matches. Especially bad with shock troopers for some reason.
##

**Comment by GraionDilach** [comment]
What is a Tonya?

**Comment by pchote** [comment]
>  I mean why the hell are shock troopers uncrushable what makes them so special?

Shock troopers are crushable.  There's nothing special about them.

**Comment by r34ch** [comment]
I think this is the same underlying issue as has been brought up before; that infantry entering buildings actually stay in a cell outside of the building although the animation depicts otherwise?

**Comment by penev92** [comment]
That one is a bug that has its own ticket. This here is about balancing and doesn't seem to be a widely accepted suggestion.

**Comment by epicelite** [comment]
No I mean Tanya when going to C4 a refinery will often just run straight into a ore truck like a dumb fuck.

**Comment by penev92** [comment]
There is this new thing called "micromanagement", I hear it's quite useful when a player applies it to their units.

**Comment by Phrohdoh** [comment]
I've never witnessed
>A lot of "lol killed ur tonya accidentally XDDD" happening in team matches.

Do you have an example replay or gif, etc?

I don't think it would be proper to give friendly-fire invulnerability across the board even temporarily.
Imagine your ally nukes the refinery as you are trying to C4 it.

**Comment by r34ch** [comment]
I know someone was working on stopping allied units attacking a building that is getting captured. I don't know if that logic could be extended to buildings getting infiltrated/C4'd, but that would be a cleaner way around temporary invulnerability.

I'm not adverse to buffing tanya's evade capabilities, I have plenty of replays of tanyas getting squished by accident trying to enter a building.

The hijacker got an evasion buff, perhaps Tanya could get a buff in this regard as well rather than simply being made uncrushable. I also wouldn't mind reducing the prone chance either since that seriously hampers micro (crawling about for two cells is infuriating)
