### ISSUE TITLE
Attacking an invulnerable unit should display an animation/play a sound

### ISSUE THREAD

**Issue by scshunt** [OpenRA/OpenRA#9815]
In RA2, attacking an iron curtained unit displays an animation/plays a sound to indicate that it is invulnerable.

**Comment by atlimit8** [comment]
If this is for RA2, this is in the wrong repository.

**Comment by GraionDilach** [comment]
I'd say it fits, `CreateEffectWarhead` has no support for `TargetTypes`.

**Comment by pchote** [comment]
@atlimit8: this is a request for an engine/common mod code feature, so this is the right repo for it.

**Comment by MustaphaTR** [comment]
I think we should add it for RA mod too. I'm not sure about is orginal RA really has that anim (possibly no) a glow like in PS version for this work should be good.

**Comment by atlimit8** [comment]
While your feature request is valid, it would be appreciated if it was phrased to explain what is requested for OpenRA and then why.
For example:
> Add `TargetTypes` support to `CreateEffectWarhead`
>
> In RA2, attacking an iron curtained unit displays an animation/plays a sound to indicate that it is invulnerable.

That would make the conditions for closing this issue clear since the desired RA2 feature would require additional rules for ra2 mod after the requested feature is merged which is out of scope here (this issue should be closed when the engine supports it, not when it is added to ra2).

**Comment by Phrohdoh** [comment]
I feel the title covers the first part of your requirement, and the description the second part.
This has no tie to RA2 (and the issue tracking there) other than the example given in the description.
