### ISSUE TITLE
Death Hand does almost no damage

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#9823]
##

**Comment by reaperrr** [comment]
It can kill a full-health wind trap which makes it at least as strong as in the original (where it was inaccurate on top of that).

**Comment by MicroJOo** [comment]
@reaperrr is right
https://youtu.be/dmflM70vtZI?t=5m22s

and i think its too early to talk about changing superweapons in d2000 ...

**Comment by KamenStrike** [comment]
I've played at least a couple dozen games against the AI as Harkonnen and Nod. Here's my observations:

1. I was surprised and disappointed at first because the Nod Nuke can destroy a Construction Yard yet the Death Hand cannot.
2. In my games against the AI I gravitate towards towards using the Death hand to destroy the AI's un-concreted turrets, which it can wipe out in a ~3-tile radius.
3. If I can predict or misdirect the trajectory of an enemy army, it will kill all units in ~3 tile radius. This is pretty effective against the AI, probably wouldn't work very well on a player.
4. The Death Hand's cooldown is about 5:00. It takes ~15 seconds from activation to impact.
5. The Atreides Air Strike is easier to get (slightly lower cost, requires no power, available earlier in the tech tree), has the same cooldown, takes considerably less time between activation and impact, and seems roughly as effective for damaging buildings (can definitely destroy a power plant and deal extra collateral). It seems less effective against units.
6. The Atreides get about 6 Fremen from the Palace in the time it takes to launch the Death Hand. I'm personally convinced that this slow trickle of Fremen isn't as useful as the air strike/nuke.
7. The Ordos palace provides about 3 Saboteurs in that time, which are harder to compare than the Air Strike, because they need to be successfully slipped past enemy lines. Assuming one of these three saboteurs per time frame can destroy a high value building, I'd say it seems to be roughly equivalent. 

To me, it seems like the Air Strike is more accessible and would be almost equally useful in human vs human matches. Saboteurs are hard to pin down because they can be stopped. My current perspective is that we should look into making the Death hand less accurate (as in the original) but distinctly more destructive than the Air Strike (which benefits believability and offsets the inaccuracy).

It would be best to take more time to observe game recordings between human beings before making any decisions, however.

**Comment by pchote** [comment]
Is this still an issue on `release-20191117`? If yes, do we want to try and fix this ASAP for the pending hotfix?

**Comment by PunkPun** [comment]
Is this still relevant?

**Comment by abcdefg30** [comment]
The Death Hand is still very weak, but I think we can defer that to when/if D2k gets a balance overhaul.
