### ISSUE TITLE
Camo Pillboxes dont cloak.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#9849]
Found out in a 1V1 game, other player said he could totally see them so it wasn't just me. Tested in a solo game, same results. Doubt this is intentional.
In playtest 20151031

**Comment by obrakmann** [comment]
Can't reproduce.  I can imagine this happening though when you place the pillbox directly next to an enemy unit which then manages to escape. The pillbox then won't cloak again until the unit is destroyed. That bug is very likely the same that causes #6185.

Anyway, please describe the circumstances under which this happened in more detail or provide a replay. Thanks!

**Comment by penev92** [comment]
I can't reproduce either.
