### ISSUE TITLE
Suggestion: Support powers in RA should pause on low power

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#9964]
Currently the soviet Spy plane and para support powers continue charging on low power. Although low power doesn't make sense to 'pause' them, if #9962 is addressed, it is only fair in terms of balance.
##

**Comment by pi99y** [comment]
I would suggest for players to be unable to use/deploy those powers but they should still charge - since the delay is not directly power related just the "call in" is (communication).

**Comment by penev92** [comment]
That makes more sense actually.

**Comment by r34ch** [comment]
In that case perhaps the support icon can 'pause' when ready when you have low power. That would probably be less confusing from a UI perspective to players.

**Comment by GraionDilach** [comment]
Paused only when ready sounds confusing to me from a gameplay POV. It makes no sense that the charging doesn't pause but only the launch does.

**Comment by pi99y** [comment]
I think the logic behind "delay" can be found in the "time to get the paratroopers/planes ready for the flight" not to somehow to produce them with power. The communication of where to drop/spy is power related.

I also like how this, along with instant pause on GPS #9962, would diversify the techy allied with the more "robust" soviet forces.

**Comment by penev92** [comment]
To clarify - we're talking about calling in paradrops here. It doesn't make sense for the player's power state to affect the airplane preparation, but if you don't have power, then your radar is definitely offline, so you can't call in the airstrike. That makes sense to me.

**Comment by GraionDilach** [comment]
That's a lore justification which IMO cannot be applied to such an extent towards gameplay. If the countdown does not halt immediately when low power then nothing will imply the player that "oh this support power actually do need power, but only when ready" and will confuse the player when it notices that. It's inconsistent with itself.

**Comment by pi99y** [comment]
Good point @GraionDilach about the indicators. I still feel that it should be solved by the UI and that the logic is sound. A small "crossed circle" icon (like the one if you want to move outside of the map) in the corner of the power's icon should indicate it's not usable.

**Comment by GraionDilach** [comment]
Regardless how prominent you empathize it, this is a pulling-your-midfinger-into-the-player's-face approach because still nothing will imply of a charging-under-low-power support power that it will not work under low power. The UI cannot solve that.

**Comment by pchote** [comment]
I agree with the point @GraionDilach is trying to make.  From a gameplay perspective we should keep power to all-or-nothing to avoid unnecessary confusion.

**Comment by pi99y** [comment]
I mostly want this "addition" so that it emphasises differences in the two opposing sides (and how they play), not for lore's sake. 

The "analog-clock-like-mask" over icon effect indicates charging, while "black-overlay" indicates being powered down = not working. Both allready exist. Is this really the UI message that wouldn't get across?

As I said I do agree clarity is important.
I guess it's just a matter of which thing is a priority.

**Comment by UberWaffe** [comment]
Has slower charging rate on low power been considered? Or is that an overly complicated approach?

**Comment by GraionDilach** [comment]
@pi99y The black-overlay is the first frame of the analog-clock-like-mask. I'd associate instantly blacked-when-charged support powers as autofirer SPs, which does not require the player for activation - Zero Hour Supply Drop Zone and Reinforcement Pads, and their equivalents employed in RA2 mods - while your idea has no equivalent in any of the C&Cs I recall. Pretty certain the majority of the players will also expect that or think they lost the opportunity of using that SP.

**Comment by pi99y** [comment]
So if the paratroopers power is allready charged (ready) and you loose power after it charged you could still use it while on low power? To me that's more confusing than the UI addition for "can't use" would bring.

**Comment by GraionDilach** [comment]
Look, I don't care what makes sense to you if it's _against the conventions of the entire franchise this game runs on_. If you want to pause the support power, then pause it entirely, not just after it became charged. A pause-only-when-charged solution is __not a solution__ and __will confuse players__ in the long run. Please stop arguing for such.

I won't argue about the actual effect this would bring to the RA mod balance so I don't mind if it gets paused or not in the long run. I'm not that much into RA to understand what's balanced and what isn't. What I know is that pause-only-when-charged does not make sense in gameplay terms.

**Comment by pi99y** [comment]
I'm sorry that you see this as arguing or being directed against you - because it's not.
And many of your points are important and valid to me. I just want a conversation that comes to the best solution where all aspect have been considered.

For example, "paused when allready charged" is not a new concept to openRA.

Nuke from the latest playtest:
![hold](https://cloud.githubusercontent.com/assets/10639257/11092918/3c132008-8887-11e5-97cc-349417d548d9.jpg)

I'll shut up now :)

**Comment by SoScared** [comment]
"The communication of where to drop/spy is power related."

Lt. Dan begs to differ:)
![dan](https://cloud.githubusercontent.com/assets/2715583/11218380/079bc12c-8d55-11e5-97bd-aa0463f19846.png)

**Comment by klaas1** [comment]
To me this 

1) does not make sense: your airfield doesn't power down, why should your paradrop?
2) does not improve the game: airdrops are fun, and sometimes you are stuck on low power, but you can still airdrop, which at least gives you some things to do.
3) doesn't do much balance wise: airdrops are rarely game-changing, and I'd argue that we should be looking in buffing the Soviets a bit instead of giving Allies an even bigger advantage.

**Comment by GraionDilach** [comment]
The Allied GPS is also a support power - although unlisted in the original post.

**Comment by r34ch** [comment]
@klaas1 as linked in the OP, this is a balance proposal if the spy satalite ever gets fixed/balanced.

**Comment by klaas1** [comment]
@r34ch I understand. I fully agree GPS should be offline at low power, since the building is also powered down. 

I do not think this would throw off the balance though, maybe it will restore some balance late game, where it becomes hard to play against anyone with GPS up and running. This also (maybe even more so) counts for other Allied players.

I just don't think powering down the paradrop does much balance wise, nor the fact that you can't powerdown your airfield. 

Maybe you should have the option to power down your tech center? Although you should not have acces to the tech units either when the power is down, same counts for Soviets and the radar dome IMO.

**Comment by pchote** [comment]
The game balance has changed a lot since this was filed, so closing as no longer valid.
