### ISSUE TITLE
Upgrade for fake buildings to become the real one

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#9991]
Inspired by http://cnc.wikia.com/wiki/Fake_buildings_(Generals)#Abilities to give them more purpose.

**Comment by MicroJOo** [comment]
:-1: unless we rename the mod to "Red Generals"

**Comment by pchote** [comment]
How would these upgrades work in RA?  Generals had per-actor queues and per-actor UI to display the upgrade buttons.

**Comment by GrayHatter** [comment]
This leads me to a question, how hard would it be to auto sell a building when you try to place another over it?

E.g. if I'm cramped for space I'd like to replace a basic power, with an advanced plant. So instead of grabbing the sell tool, clicking, moving the recovered civilians, then placing the plant. Could I ctrl + click the advanced plant over the basic, and have it auto sell? maybe for a bit more because I'm not getting the extra cannon fodder?

**Comment by Mailaender** [comment]
> How would these upgrades work in RA? Generals had per-actor queues and per-actor UI to display the upgrade buttons.

Hmm, I think you are right. Fake building upgrades would essentially just be used to drastically speed up building production which would get France per actor queues through the backdoor.
